### ISSUE TITLE
what is the frequency of tof camera?

### ISSUE THREAD

**Issue by TxT1212** [microsoft/Azure-Kinect-Sensor-SDK#1000]
**Describe the bug**

and what‘s the modulated signal frequency? I wanna know whether it will Interfere with other tof camera or I can use azure kinect with another tof device with two frequency: 75MHz, 100Mz

**Comment by wes-b** [comment]
What do you mean by modulated signal frequency? The sensor uses a 850nm laser and there is some additional information here: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/868#issuecomment-552621616.

**Comment by TxT1212** [comment]
> What do you mean by modulated signal frequency? The sensor uses a 850nm laser and there is some additional information here: [#868 (comment)](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/868#issuecomment-552621616).

Thank you for this information! Truly appreciate it.
 Kinect v2 work in 3 modulation signal frequencies，as far as I know. Please correct me if I am wrong. so what about azure kinect?

**Comment by wes-b** [comment]
Azure Kinect does not use modulation frequencies at or near 75 MHz or 100 MHz.  We unfortunately cannot make claims about the degree of interference experienced by an external party product as we have no insight into the exact hardware and algorithm implementation. Multiple Azure Kinects can be connected and configured to avoid interference with each other using the sync in/out ports.
