### ISSUE TITLE
K4A Recorder - Audio

### ISSUE THREAD

**Issue by rfilkov** [microsoft/Azure-Kinect-Sensor-SDK#1002]
**Describe the bug**

Currently the Azure Kinect recorder doesn't include audio track in the mkv-file. I suppose this is a feature missed in the initial design. It is very difficult (and not really needed) all interested users to save their own audio files, when they make a recording. Moreover to save them synchronously to the streams from the other cameras. That's why I file this one as a bug rather than feature request.

As far as I see, you are currently working on K4A-recorder updates. Please consider including an optional audio track, as well. It will be much better if you do it once, instead of all interested developers to reinvent the wheel over and over again.

**To Reproduce**

Make a recording with the k4arecorder. Then play the recording in any video player. There is no audio track to play.

**Expected behavior**

Optionally, save audio from the microphone as audio track, synchronous to the other saved camera streams.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: Windows 1909
 - SDK Version:  1.3.0
 - Firmware version:  1.6.102

**Additional context**

**Comment by wes-b** [comment]
Please see #927
