### ISSUE TITLE
Driver issues with Kinect Azure

### ISSUE THREAD

**Issue by DivyanshK86** [microsoft/Azure-Kinect-Sensor-SDK#1005]
- My Azure kinect is connected to USB 3.0 port.
- The light at the back is stable white.
- Windows camera app works fine.

I am having these driver issues:
 
![image](https://user-images.githubusercontent.com/40302532/71306066-f9a30880-2401-11ea-9555-d3e43c7954f1.png)

what I have tried so far:
- clicking on update driver from device manager.
- installing the latest windows updates.
- disconnected and reconnected the device.
- system reboot.

but the problem still remains.

I have installed the Azure kinect viewer v1.3.0 but it does not find the device:

![image](https://user-images.githubusercontent.com/40302532/71306092-2d7e2e00-2402-11ea-9352-16bc6c1994ab.png)

**Comment by wes-b** [comment]
In device manager, what USB host controller are you connected to?

**Comment by jelmerS2** [comment]
Strange, at my installation the Azure Kinect is installed succesfully and it shows up in the Azure Kinect Viewer. 

But when I try to start the videofeed, the program quits without warning. 
The same behaviour with another program that uses the new Kinect. Exit without any error.

**Comment by wes-b** [comment]
Are there any issues reported in Event Viewer https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/853#issuecomment-567119412?

If not can you repro the issue with k4aviewer and share the log?

**Comment by Chris45215** [comment]
I've seen this happen when the camera is connected to the wrong USB port, or one that isn't a compatible host controller. The cameras are very picky about the port type they are connected to - and some computers have a USB 3.1 or USB 3.2 port which actually isn't compatible. ASRock's ITX Ryzen motherboards, for example, include a special extra USB 3.1 port (separate from all the USB 3.0 and 2.0 ports), and that port has its own dedicated host controller - but it is not compatible with the camera. All the other USB 3.0 ports on the motherboard are compatible with the camera, so it's just a matter of attaching to the correct port.

**Comment by wes-b** [comment]
@jelmerS2 Let us know if you are still working through this.
