### ISSUE TITLE
Utilizing AMD GPU's for bodytracking computation

### ISSUE THREAD

**Issue by cmdrogogov** [microsoft/Azure-Kinect-Sensor-SDK#1016]
Hi,

It is possible to run body tracking via HIP on AMD's ROCM stack?  Or is this heavily restricted to Nvidia only?

**Comment by qm13** [comment]
Please see customer voice:
https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/38129473-body-tracking-without-cudnn
If you do not think this covers your enhancement request please open a new customer voice.
