### ISSUE TITLE
Does Azure Kinect have recording capability now

### ISSUE THREAD

**Issue by 1216704928** [microsoft/Azure-Kinect-Sensor-SDK#1021]
Does Azure Kinect have recording capability now?Hopefully the videos recorded by Azure Kinect will have sound.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tesych** [comment]
@1216704928 thank you for your question! Azure Kinect Sensor SDK includes video recording capabilities. To include audio, please submit your idea to our [customer voice]{https://feedback.azure.com/forums/920053}, so other users can vote for your idea.

**Comment by rfilkov** [comment]
There is already a similar idea there: https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/38424175-no-microphone-access-available-in-api-recorder-k4 

Please upvote it and share it to other interested users, as well.
