### ISSUE TITLE
Kinect/SDK Android Support  

### ISSUE THREAD

**Issue by allenstecat** [microsoft/Azure-Kinect-Sensor-SDK#1022]
Has any thought been given to adding support for Android to the Kinect device? There are several devices and solutions that would be able to leverage Azure Kinect if enabled.

**Comment by tesych** [comment]
@allenstecat thank you for your idea! Please submit your idea to our [customer voice](https://feedback.azure.com/forums/920053), so other users can vote for your idea.

**Comment by Thaina** [comment]
> @allenstecat thank you for your idea! Please submit your idea to our [customer voice](https://feedback.azure.com/forums/920053), so other users can vote for your idea.

That web cannot be access anymore
