### ISSUE TITLE
Is there any API to combined images for two Azure Kinects?

### ISSUE THREAD

**Issue by Piler-Tam** [microsoft/Azure-Kinect-Sensor-SDK#1023]
The FOI of one Azure Kinect is not enough for me, so I am trying to use two azure kinects. However, some parts of the images of two device may duplicate, Is there any API to combined images for two Azure Kinects?

**Comment by qm13** [comment]
The Sensor SDK does not include an API to merge multiple depth images or point clouds. The Green Screen sample shows how to use multiple Azure Kinect devices.
