### ISSUE TITLE
Two proposals for performance enhancement of body tracking

### ISSUE THREAD

**Issue by QuiqueMartinez** [microsoft/Azure-Kinect-Sensor-SDK#1028]
1) Specify the maximum of skeletons to be extracted after segmentation. Could be the user nearest to the sensor or to a given point.
2) Specify the bounding box  (or the max z-distance) where the depth points have to be got from.

**Comment by qm13** [comment]
Could you please post these to the customer feedback channel https://feedback.azure.com/forums/920053-azure-kinect-dk
