### ISSUE TITLE
how to reduce depth noise at human hair part ?

### ISSUE THREAD

**Issue by carlhuang070** [microsoft/Azure-Kinect-Sensor-SDK#1032]
And now , we found every depth camera may be have noise issue at human hair part.

So we want to know whether Kinect DK SDK have api which can increase the power of IR emiting to reduce the hair noise ?

**Comment by tesych** [comment]
@carlhuang070 , can you share more details about what you see including the details about human hair (color for example)?

**Comment by rabbitdaxi** [comment]
@carlhuang070 may be try use NFOV modes see whether it helps (or try to have the camera move closer to the hair). The noise is a function of signal, therefore, for some material which is IR absorbing could reduce the signal returned back dramatically and further increasing the noise.
