### ISSUE TITLE
blue distortion in RGB images

### ISSUE THREAD

**Issue by ekolve** [microsoft/Azure-Kinect-Sensor-SDK#1045]
Attached are two images taken from the Azure Kinect while pointed at some window blinds.  In the first image there is an area in the image in the upper right (about 150x150 in size) that has a blue streak.  If I rotate the camera just a few degrees to the left, the distortion disappears (as seen in the second image).  Is this the result of the protective glass that sits directly in front of the lens? Or is there something in the SDK causing this?

![azure-blue-image](https://user-images.githubusercontent.com/326692/73096875-b9b8c080-3e9a-11ea-8af9-e2e81dbacc44.png)
![azure-no-blue-image](https://user-images.githubusercontent.com/326692/73096883-bf160b00-3e9a-11ea-8b56-c06295bab7ae.png)

**Comment by ETowleMS** [comment]
There is likely a stray reflection from somewhere in the room which is causing the lens flare. There is nothing in our Sensor SDK which should contribute to this problem.
