### ISSUE TITLE
suggestion: start using squash commits

### ISSUE THREAD

**Issue by slimsag** [microsoft/Azure-Kinect-Sensor-SDK#1048]
Today, it is very difficult to look at the SDK's Git history due to the large number of low-effort commit messages and tiny commits. For example, on this page 16 "Update Contributing" commits were merged: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/commits/develop?after=f21aac905c4e8d416ae3dc4055f673d12a3ebaa7+34

I suggest enforcing that all PR commits be squashed before merge ([GitHub docs](https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests)) which is something that larger projects often do in order to keep Git history relatively clean.

**Comment by tesych** [comment]
@slimsag, thank you for pointing out. So far it was our policy so we can preserve all of the history, but we also agree with your point of view. We will make the change and enforce the squash commits.
