### ISSUE TITLE
No Depth Camera and Limited IR Camera Streaming

### ISSUE THREAD

**Issue by danielleamya** [microsoft/Azure-Kinect-Sensor-SDK#1050]
Hi,

I am having an issue with getting the depth camera to work in the stream example. I have not edited the original code in any way. Upon running the example, I can clearly see the RGB camera capture clearly. However I can barely see the IR camera feed (does not appear the same way it does in the Azure Kinect Viewer application, and cannot see the depth camera at all.

To reproduce, navigate to the example-streams folder, and run the example-streams VS solution. Expected is that the live feed would look identical to the live feed from the Azure Kinect Viewer application, but this is not the case.

OF vs Azure Kinect Viewer:
<img width="1451" alt="Screenshot 2020-01-29 11 38 35" src="https://user-images.githubusercontent.com/14864541/73376880-244b7100-428c-11ea-94c6-1bcbb4db8a7f.png">
<img width="1451" alt="Screenshot 2020-01-29 11 39 00" src="https://user-images.githubusercontent.com/14864541/73376890-29102500-428c-11ea-8b4c-a38d19433b67.png">

Running:
Windows 10, of_v0.11.0, Visual Studio 2019

**Comment by wes-b** [comment]
What is the depth mode you are using? It seems like passive IR rather than one of our active IR modes. Also passive IR does not produce a depth image. Try NFOV unbinned like you are using in the K4aViewer.
