### ISSUE TITLE
Device removed / inserted Api 

### ISSUE THREAD

**Issue by neilDGD** [microsoft/Azure-Kinect-Sensor-SDK#1054]
Hi,

We need to detect when k4a devices are removed and inserted, as there seems to be no API calls for doing so I tried to make a low priority / frequency status thread to enumerate connected sensors but it turns out the only way you can get the sensor IDs to compare with already cached sensors is by calling device::open(), obviously this would not work as a ::close() would be required before re-opening for comparison. Am I missing something in the API where this is possible? It is pretty standard behaviour to detect these events. Is there something in the pipeline to support this?

Many thanks,

Neil

**Comment by wes-b** [comment]
#175 is tracking this. I agree that it is something we need to add. To my surprise this has not been requested very much and has remained a low priority.
