### ISSUE TITLE
Suggest to fix API Reference

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#1056]
**Is your feature request related to a problem? Please describe.**

Currently, API Reference has the following problems.

* Currently, C# Wrapper API is treated as Data Structures.
  I think it should be treated as one language such as C, and C++.
  ![2020-02-03_11h00_58](https://user-images.githubusercontent.com/816705/73620563-e8dae900-4675-11ea-8236-c78f0cd97783.png)

* Azure Kinect Body Tracking SDK doesn't have API Reference for C# Wrapper.
  It has already been implemented from 0.9.5. I think it should be documented.
  ![2020-02-03_10h49_18](https://user-images.githubusercontent.com/816705/73620564-eb3d4300-4675-11ea-8c04-09f299246e50.png)

**Describe the solution you'd like**

Add and Fix the API reference of C # wrapper appropriately.

**Describe alternatives you've considered**

**Additional context**

**Comment by tesych** [comment]
@UnaNancyOwen thank you for the suggestion. We already have the issue opened for this #616. Closing as duplicate.

**Comment by UnaNancyOwen** [comment]
@tesych Thanks, Don't forget to add C# wrapper API reference to Azure Kinect Body Tracking SDK document!
