### ISSUE TITLE
Rolling-shutter effect

### ISSUE THREAD

**Issue by zoltantorok** [microsoft/Azure-Kinect-Sensor-SDK#1062]
I need to correct for the rolling-shutter effect of the color camera.
Can you tell me what is the row readout time? What type of camera is in the Kinect for Azure?

Thanks

**Comment by hardyzhuang** [comment]
the color sensor is OV12A10, https://www.ovt.com/sensors/OV12A10

**Comment by tesych** [comment]
Closing this issue due to the inactivity.  Will be happy to reopen when more details are provided.
