### ISSUE TITLE
Body index map is excluding legs when knee is elevated

### ISSUE THREAD

**Issue by cavisions** [microsoft/Azure-Kinect-Sensor-SDK#1075]
**Describe the bug**

When knee is elevated the whole leg disappears from body index map. The problem is observed regardless of conditions like clothes I wear, lighting conditions, ect.

**To Reproduce**

This problem can be observed in the viewer application delivered with the body tracking SDK.

**Expected behavior**

**Screenshots**

![a](https://user-images.githubusercontent.com/15303035/74438358-463b1b00-4e6a-11ea-850e-997fb4368a18.jpg)
![b](https://user-images.githubusercontent.com/15303035/74438361-4804de80-4e6a-11ea-9d38-27447d5c5bc5.jpg)

**Desktop (please complete the following information):**
 - OS with Version: 1903
 - SDK Version:  1.3.0
-  Body Tracking SDK Version: 1.0
 - Firmware version:  1.6

**Comment by qm13** [comment]
Tracking as part of #949
