### ISSUE TITLE
Documentation about the calibration in json format

### ISSUE THREAD

**Issue by etiennedub** [microsoft/Azure-Kinect-Sensor-SDK#1076]
Hi,
I had some problem with the default calibration, so I calibrate it myself and I i obtained better result.
But I would like to be able to set the new parameters in the json format supported by the SDK.
I can retrive the json with the `k4a_device_get_raw_calibration` method and load the calibration with `k4a_calibration_get_from_raw` but I don't understand the format.
I don't understand the part with the intrinsics cx, cy, fx, and fy. I tought they were normalize by the resolution size but it doesn't work all the time.

Is there some documentation about those or could you explain how do you get those values ?

Thank you !

EDIT : I found the source code where a transformation is apply on the intrinsics parameters. ([transformation_get_mode_specific_camera_calibration](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/95f1d95f1f335b57a350a80a3a62e98e1ee4258d/src/transformation/mode_specific_calibration.c)). I was able to calculate the coresponding parameters with this but I would still be interested by some documentation if there is some. Otherwise you can close this issue

**Comment by Zoltan3057** [comment]
Hi,
I am confused about the exact meaning of Rotation in the result json file.
Is it R_iw or R_wi.
In other words, does the rotation matrix transform world point to imu coordinate or the other way round.

```
"InertialSensors": [ ...
"Rt": {
                    "Rotation": [
                        -0.0023570656776428223,
                        0.11232874542474747,
                        -0.9936683177947998,
                        -0.9999814033508301,
                        -0.005854570306837559,
                        0.0017102138372138143,
                        -0.005625395104289055,
                        0.9936538338661194,
                        0.11234045773744583
                    ],
                    "Translation": [
                        -0.05079573020339012,
                        0.003704430302605033,
                        0.001192310475744307
                    ]
                },
```
