### ISSUE TITLE
K4aviewer : core dumped

### ISSUE THREAD

**Issue by Pavankv92** [microsoft/Azure-Kinect-Sensor-SDK#1079]
Hi, I have error when I try to launch k4aviewer 

error : Segmentation fault (core dumped)
-----------------------------------------------------------
output file when I launch the ros driver for azure is below.

SUMMARY
========

PARAMETERS
 * /azure_kinect_ros_driver/body_tracking_enabled: False
 * /azure_kinect_ros_driver/body_tracking_smoothing_factor: 0.0
 * /azure_kinect_ros_driver/color_enabled: True
 * /azure_kinect_ros_driver/color_format: bgra
 * /azure_kinect_ros_driver/color_resolution: 1536P
 * /azure_kinect_ros_driver/depth_enabled: True
 * /azure_kinect_ros_driver/depth_mode: WFOV_UNBINNED
 * /azure_kinect_ros_driver/fps: 15
 * /azure_kinect_ros_driver/imu_rate_target: 0
 * /azure_kinect_ros_driver/ir_mono8_scaling_factor: 1.0
 * /azure_kinect_ros_driver/point_cloud: True
 * /azure_kinect_ros_driver/point_cloud_in_depth_frame: False
 * /azure_kinect_ros_driver/recording_file: 
 * /azure_kinect_ros_driver/recording_loop_enabled: False
 * /azure_kinect_ros_driver/rescale_ir_to_mono8: False
 * /azure_kinect_ros_driver/rgb_point_cloud: True
 * /azure_kinect_ros_driver/sensor_sn: 
 * /azure_kinect_ros_driver/tf_prefix: 
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    azure_kinect_ros_driver (azure_kinect_ros_driver/node)
    joint_state_publisher_azure (joint_state_publisher/joint_state_publisher)
    robot_state_publisher_azure (robot_state_publisher/state_publisher)

ROS_MASTER_URI=http://localhost:11311

process[joint_state_publisher_azure-1]: started with pid [29568]
process[robot_state_publisher_azure-2]: started with pid [29569]
process[azure_kinect_ros_driver-3]: started with pid [29570]
[ WARN] [1581951372.891065940]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
[ INFO] [1581951373.004918358]: K4A Parameters:
[ INFO] [1581951373.005387666]: sensor_sn - std::string : 
[ INFO] [1581951373.005404353]: depth_enabled - bool : 1
[ INFO] [1581951373.005419870]: depth_mode - std::string : WFOV_UNBINNED
[ INFO] [1581951373.005439186]: color_enabled - bool : 1
[ INFO] [1581951373.005457178]: color_format - std::string : bgra
[ INFO] [1581951373.005475190]: color_resolution - std::string : 1536P
[ INFO] [1581951373.005503903]: fps - int : 15
[ INFO] [1581951373.005525254]: point_cloud - bool : 1
[ INFO] [1581951373.005545151]: rgb_point_cloud - bool : 1
[ INFO] [1581951373.005566291]: point_cloud_in_depth_frame - bool : 0
[ INFO] [1581951373.005582868]: tf_prefix - std::string : 
[ INFO] [1581951373.005602113]: recording_file - std::string : 
[ INFO] [1581951373.005619396]: recording_loop_enabled - bool : 0
[ INFO] [1581951373.005638242]: body_tracking_enabled - bool : 0
[ INFO] [1581951373.005671535]: body_tracking_smoothing_factor - float : 0
[ INFO] [1581951373.005688881]: imu_rate_target - int : 0
[ INFO] [1581951373.005708131]: rescale_ir_to_mono8 - bool : 0
[ INFO] [1581951373.005727459]: ir_mono8_scaling_factor - float : 1
[ INFO] [1581951373.009676714]: Found 1 sensors
[ INFO] [1581951373.009709994]: No serial number provided: picking first sensor
[ INFO] [1581951373.211264129]: K4A[0] : 000328192012
[ INFO] [1581951373.261679246]: K4A Serial Number: 000328192012
[ INFO] [1581951373.267142793]: RGB Version: 1.6.102
[ INFO] [1581951373.267175221]: Depth Version: 1.6.75
[ INFO] [1581951373.267187172]: Audio Version: 1.6.14
[ INFO] [1581951373.267201245]: Depth Sensor Version: 6109.7.0
[ INFO] [1581951373.341772237]: Setting RGB Camera Format: bgra
[ INFO] [1581951373.341816031]: Setting RGB Camera Resolution: 1536P
[ INFO] [1581951373.341831759]: Setting Depth Camera Mode: WFOV_UNBINNED
[ INFO] [1581951373.341852299]: Setting Camera FPS: 15
[ INFO] [1581951373.341878185]: Using default IMU rate. Setting to maximum: 1600 Hz.
[ INFO] [1581951373.341899835]: Setting Target IMU rate to 1600 (desired: 1600)
[2020-02-17 15:56:14.168] [error] [t=29610] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/tewrapper/tewrapper.c (61): transform_engine_start_helper(). Transform engine create and initialize failed with error code: 204.
[2020-02-17 15:56:14.168] [error] [t=29610] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/tewrapper/tewrapper.c (68): teresult == K4A_DEPTH_ENGINE_RESULT_SUCCEEDED returned failure in transform_engine_start_helper()
[2020-02-17 15:56:14.168] [error] [t=29610] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/tewrapper/tewrapper.c (86): transform_engine_start_helper(tewrapper) returned failure in transform_engine_thread()
[2020-02-17 15:56:14.168] [error] [t=29570] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/tewrapper/tewrapper.c (313): tewrapper_create(). Transform Engine thread failed to start
[2020-02-17 15:56:14.168] [error] [t=29570] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/transformation/transformation.c (637): transformation_context->tewrapper != NULL returned failure in transformation_create()
[ INFO] [1581951374.169702275]: K4A Calibration Blob:
[ INFO] [1581951374.169748664]: 	 Depth:
[ INFO] [1581951374.169772472]: 		 Extrinsics:
[ INFO] [1581951374.169814398]: 			 Translation: 0, 0, 0
[ INFO] [1581951374.169850821]: 			 Rotation[0]: 1, 0, 0
[ INFO] [1581951374.169870066]: 			 Rotation[1]: 0, 1, 0
[ INFO] [1581951374.169920629]: 			 Rotation[2]: 0, 0, 1
[ INFO] [1581951374.169952258]: 		 Resolution:
[ INFO] [1581951374.169975639]: 			 Width: 1024
[ INFO] [1581951374.169999394]: 			 Height: 1024
[ INFO] [1581951374.170025981]: 		 Intrinsics:
[ INFO] [1581951374.170051831]: 			 Model Type: 4
[ INFO] [1581951374.170074263]: 			 Parameter Count: 14
[ INFO] [1581951374.170099948]: 			 cx: 510.937
[ INFO] [1581951374.170121069]: 			 cy: 510.552
[ INFO] [1581951374.170143886]: 			 fx: 505.46
[ INFO] [1581951374.170163970]: 			 fy: 505.506
[ INFO] [1581951374.170178244]: 			 k1: 0.492722
[ INFO] [1581951374.170193465]: 			 k2: -0.0134234
[ INFO] [1581951374.170206069]: 			 k3: -0.00166395
[ INFO] [1581951374.170223267]: 			 k4: 0.833643
[ INFO] [1581951374.170235563]: 			 k5: 0.0782976
[ INFO] [1581951374.170252500]: 			 k6: -0.00946048
[ INFO] [1581951374.170264489]: 			 codx: 0
[ INFO] [1581951374.170280289]: 			 cody: 0
[ INFO] [1581951374.170295255]: 			 p2: 8.77614e-05
[ INFO] [1581951374.170311171]: 			 p1: -0.000207289
[ INFO] [1581951374.170329264]: 			 metric_radius: 0
[ INFO] [1581951374.170347290]: 	 Color:
[ INFO] [1581951374.170374511]: 		 Extrinsics:
[ INFO] [1581951374.170407037]: 			 Translation: -31.9686, -2.27377, 3.94809
[ INFO] [1581951374.170436668]: 			 Rotation[0]: 0.999999, -0.000933465, -0.00143222
[ INFO] [1581951374.170467079]: 			 Rotation[1]: 0.00105493, 0.996182, 0.087296
[ INFO] [1581951374.170491233]: 			 Rotation[2]: 0.00134526, -0.0872974, 0.996181
[ INFO] [1581951374.170512750]: 		 Resolution:
[ INFO] [1581951374.170537163]: 			 Width: 2048
[ INFO] [1581951374.170564490]: 			 Height: 1536
[ INFO] [1581951374.170588374]: 		 Intrinsics:
[ INFO] [1581951374.170613809]: 			 Model Type: 4
[ INFO] [1581951374.170637963]: 			 Parameter Count: 14
[ INFO] [1581951374.170663831]: 			 cx: 1022.58
[ INFO] [1581951374.170687792]: 			 cy: 775.268
[ INFO] [1581951374.170712215]: 			 fx: 971.997
[ INFO] [1581951374.170740140]: 			 fy: 971.906
[ INFO] [1581951374.170760150]: 			 k1: 0.781141
[ INFO] [1581951374.170777143]: 			 k2: -3.04307
[ INFO] [1581951374.170793536]: 			 k3: 1.7224
[ INFO] [1581951374.170807729]: 			 k4: 0.656092
[ INFO] [1581951374.170825197]: 			 k5: -2.86714
[ INFO] [1581951374.170838394]: 			 k6: 1.64986
[ INFO] [1581951374.170856266]: 			 codx: 0
[ INFO] [1581951374.170869904]: 			 cody: 0
[ INFO] [1581951374.170888470]: 			 p2: -2.35504e-05
[ INFO] [1581951374.170904275]: 			 p1: 0.000614642
[ INFO] [1581951374.170923084]: 			 metric_radius: 0
[ INFO] [1581951374.170937966]: 	 IMU (Depth to Color):
[ INFO] [1581951374.170953752]: 		 Extrinsics:
[ INFO] [1581951374.170968316]: 			 Translation: -31.9686, -2.27377, 3.94809
[ INFO] [1581951374.171001537]: 			 Rotation[0]: 0.999999, -0.000933465, -0.00143222
[ INFO] [1581951374.171035502]: 			 Rotation[1]: 0.00105493, 0.996182, 0.087296
[ INFO] [1581951374.171069509]: 			 Rotation[2]: 0.00134526, -0.0872974, 0.996181
[ INFO] [1581951374.171086414]: 	 IMU (Depth to IMU):
[ INFO] [1581951374.171107949]: 		 Extrinsics:
[ INFO] [1581951374.171126223]: 			 Translation: -50.9833, 3.36116, 1.47934
[ INFO] [1581951374.171152569]: 			 Rotation[0]: 5.00064e-05, 0.105701, -0.994398
[ INFO] [1581951374.171186440]: 			 Rotation[1]: -0.999989, -0.00461923, -0.000541294
[ INFO] [1581951374.171216676]: 			 Rotation[2]: -0.00465056, 0.994387, 0.105699
[ INFO] [1581951374.171234080]: 	 IMU (IMU to Depth):
[ INFO] [1581951374.171252593]: 		 Extrinsics:
[ INFO] [1581951374.171268040]: 			 Translation: 3.37055, 3.93346, -50.8522
[ INFO] [1581951374.171288616]: 			 Rotation[0]: 5.00064e-05, -0.999989, -0.00465056
[ INFO] [1581951374.171314079]: 			 Rotation[1]: 0.105701, -0.00461923, 0.994387
[ INFO] [1581951374.171338292]: 			 Rotation[2]: -0.994398, -0.000541294, 0.105699
[ INFO] [1581951374.171356248]: 	 IMU (Color to IMU):
[ INFO] [1581951374.171371958]: 		 Extrinsics:
[ INFO] [1581951374.171396466]: 			 Translation: -46.9498, -28.614, 3.49653
[ INFO] [1581951374.171416273]: 			 Rotation[0]: 0.00137554, 0.0184903, -0.999828
[ INFO] [1581951374.171435780]: 			 Rotation[1]: -0.999983, -0.00570376, -0.00148123
[ INFO] [1581951374.171455264]: 			 Rotation[2]: -0.00573017, 0.999813, 0.0184822
[ INFO] [1581951374.171472166]: 	 IMU (IMU to Color):
[ INFO] [1581951374.171489552]: 		 Extrinsics:
[ INFO] [1581951374.171512884]: 			 Translation: -28.5289, -2.79097, -47.0488
[ INFO] [1581951374.171534393]: 			 Rotation[0]: 0.00137554, -0.999983, -0.00573017
[ INFO] [1581951374.171554518]: 			 Rotation[1]: 0.0184903, -0.00570376, 0.999813
[ INFO] [1581951374.171576166]: 			 Rotation[2]: -0.999828, -0.00148123, 0.0184822
[ INFO] [1581951374.171659647]: STARTING CAMERAS
[azure_kinect_ros_driver-3] process has died [pid 29570, exit code -11, cmd /home/Vishwanath/catkin_ws/devel/lib/azure_kinect_ros_driver/node __name:=azure_kinect_ros_driver __log:=/home/Vishwanath/.ros/log/98ac35c8-5193-11ea-9d58-1866da36604f/azure_kinect_ros_driver-3.log].
log file: /home/Vishwanath/.ros/log/98ac35c8-5193-11ea-9d58-1866da36604f/azure_kinect_ros_driver-3*.log

----------------------------------------------------------------------------------------------
system config 
ubuntu 18.04, OpenGL version string: 4.6.0 NVIDIA 440.33.01
-------------------------------------------------------------------------------------------------

I have used azure in the same system few days ago and everything was fine. but now i get this error.
any help is appreciated.

Thanks
Pavan

**Comment by wes-b** [comment]
Hello @Pavankv92, please in the future use our bug template to answer basic questions to about issue being opened (for most it helps reduce back and forth about the issue). For example what are the steps for reproducing. As just running the viewer on my Linux PC won't reproduce this issue.

Any chance you are trying to use the machine remotely?

**Comment by zapaishchykova** [comment]
hey @wes-b, why is it a problem to use a machine remotely? I have the same error with Jetson Nano headless mode and Azure Kinekts, and this error occurs completely randomly
