### ISSUE TITLE
Crash body tracker

### ISSUE THREAD

**Issue by Zafoue** [microsoft/Azure-Kinect-Sensor-SDK#1092]
When I launch the body tracker after 2 minutes the application crashes and stops working. We want to confirm that this is not a driver problem I tested the body tracker in cpu mode and the no problem
 - OS with Version: <! win 10 v 1809 -->
 - SDK Version:  <! V 1.3 -->
-Body track version 1.00
 - Firmware version:  < !AzureKinectDK_Fw_1.6.102075014 -->

**Comment by wes-b** [comment]
#1091
