### ISSUE TITLE
Publish SDK 1.4.0

### ISSUE THREAD

**Issue by tesych** [microsoft/Azure-Kinect-Sensor-SDK#1093]
1.4.0 version is coming soon!

**MSI Link:** [[here](https://download.microsoft.com/download/4/5/a/45aa3917-45bf-4f24-b934-5cff74df73e1/Azure%20Kinect%20SDK%201.4.0.exe)]
**Nuget Link:** [[1.4.0](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0)] [~~[1.4.0-beta.0](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0-beta.0)~~]  [~~[1.4.0-alpha.4](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.4)~~] *This Nuget contains binaries for Windows [AMD64] & Ubunutu [AMD64 & ARM64]*
**Deb package link:** [[AMD64](http://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/)] [[ARM64](http://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/libk/)]
**Firmware:** [[1.6.108079014](https://download.microsoft.com/download/4/5/a/45aa3917-45bf-4f24-b934-5cff74df73e1/Firmware/AzureKinectDK_Fw_1.6.108079014.bin)]
Summary of changes [are here](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CHANGELOG.md#v140-alpha-quality)

Updates - 3/5/2020:
* 1.4.0-alpha.4 Nuget Package is available. It contains new alpha firmware 1.6.108079014 see #530 for the latest on firmware.
* Linking issue https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1118 Neon instructions needed (3/9/2020).

Updates - 3/3/2020:
*  1.4.0-alpha.3 Nuget package is available and it contains ARM64 binaries for Ubuntu 18.04 and has been tested on Jetson Nano.
*  Alpha Firmware 1.6.107078014 is provided in this package, however it is not recommended for Linux platforms #1098.

**Comment by tkircher** [comment]
Where can we find the depth library for ARM?

**Comment by tesych** [comment]
@tkircher all the information is coming in the next few days. I know everyone is very excited about this release :)

**Comment by tkircher** [comment]
Definitely excited. Got a Jetson Nano specifically for this.

**Comment by airfield20** [comment]
Following for arm information

**Comment by ergodaveh** [comment]
Where would I find a Windows Installer for this release?

**Comment by wes-b** [comment]
This issue is still a TODO, title updated to reflect that.

**Comment by wes-b** [comment]
Updated description and added Nuget Link

**Comment by UnaNancyOwen** [comment]
How is ARM64 support on Azure Kinect Body Tracking SDK going?

**Comment by tesych** [comment]
@UnaNancyOwen , ARM support for Body Tracking SDK is in progress and coming soon. I will update with more details.

**Comment by tkircher** [comment]
Incidentally, after upgrading to AzureKinectDK_Fw_1.6.107078014.bin, from the nuget 1.4.0 release, the Kinect stopped responding. Factory reset did not work, and the LED is blinking white.

**Comment by tkircher** [comment]
Incidentally, confirmed that k4aviewer works on the Jetson Nano (arm64).

**Comment by wes-b** [comment]
Description updated, [1.4.0-alpha.3](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.3) replaced with 
[1.4.0-alpha.4](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.4)

**Comment by UnaNancyOwen** [comment]
Please consider merge these pull requests (#822, #1097) before to release v1.4.0.
It provide all SDK APIs in C# wrapper by adding missing functions.

**Comment by SladeLu** [comment]
> Where can we find the depth library for ARM?

same question

**Comment by tkircher** [comment]
The ARM depth library is in the NuGet package, under linux/lib/native/arm64/

The link is here:

https://www.nuget.org/api/v2/package/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.4

and the file is actually just a zip file. So rename it from .nuget to .zip and unzip it.

**Comment by SladeLu** [comment]
> The ARM depth library is in the NuGet package, under linux/lib/native/arm64/
> 
> The link is here:
> 
> https://www.nuget.org/api/v2/package/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.4
> 
> and the file is actually just a zip file. So rename it from .nuget to .zip and unzip it.

Thanks, I know where to find the libdepthengine2.0 file now, but still don't know where to place it under arm64 architecture to run k4aviewer sucessfully.

**Comment by tkircher** [comment]
You almost certainly want to put it in /lib/aarch64-linux-gnu/

**Comment by valdivj** [comment]
How did you get 1.4.0-alpha.4 to install on jetson nano.
I have nuget installed put it doesn't want to pull the package?
Any ETA on the .deb package

nano@nano-desktop:~$ nuget
NuGet Version: 2.8.7.0

**Comment by SladeLu** [comment]
> You almost certainly want to put it in /lib/aarch64-linux-gnu/

THANKS! My jetson nano works well!

**Comment by valdivj** [comment]
got it had to do this:
alias nuget="mono /usr/local/bin/nuget.exe"

**Comment by valdivj** [comment]
Got the Kinect for Azure running on the Jetson Nano. :)
Anybody have any ideas on making the Kinect for Azure run with Gstreamer.
I want to use the Kinect for Azure with Deepstream.

I have already done this with the Kinect V2
https://youtu.be/MiVizFsyMRU 

I know the Kinect V2 & the Kinect for Azure are different but it shouldnt be impossible.

**Comment by valdivj** [comment]
If anybody is interested here is a video of the Kinect for Azure running on the Jetson Nano
https://youtu.be/NpavmEy9zJU

**Comment by eric-schleicher** [comment]
@valdivj what is the (full) command line argument you used.   I'm new to nuget as well.  the syntax isn't intuitive.  also did you have to update the firmware on the K4A?

**Comment by valdivj** [comment]
Had to install mono first
Then ran this:$ alias nuget="mono /usr/local/bin/nuget.exe"
Then this:$ nuget install Microsoft.Azure.Kinect.Sensor -Version 1.4.0-alpha.4
You might want to try this :https://github.com/microsoft/Azure-Kinect-Sensor-SDK
They just added arm support 3 days ago.

**Comment by iscsrl** [comment]
Is it possible to use it on RaspberryPi 4? Any tips on how can I perform the installation?

**Comment by tkircher** [comment]
> Is it possible to use it on RaspberryPi 4? Any tips on how can I perform the installation?

The short answer is no.

**Comment by SladeLu** [comment]
BTW，does anyone try applying Azure SDK ROS package on JETSON Nano? I failed during compling the ROS azure package. Maybe need to modify cmakelist.txt to adapt the arm64 version sdk?

**Comment by wes-b** [comment]
Beta Released today

**Comment by tesych** [comment]
@UnaNancyOwen we will include #1097 but not #822 since we need more time to review.

**Comment by UnaNancyOwen** [comment]
@tesych Thanks! Why is #822 stagnant? It seems that reviews have been paused for several months.

**Comment by tesych** [comment]
@UnaNancyOwen we run into few technical issues, that we are working through and will release as soon as possible.

**Comment by UnaNancyOwen** [comment]
@tesych I see. I'm looking forward to provide it in v1.4.x (or v1.5.0). Thanks, :)

**Comment by valdivj** [comment]
Here is a link to github repo with instructions to get Azure for Kinect to run on nano
https://github.com/valdivj/Azure-for-Kinect-Jetson-nano

**Comment by eric-schleicher** [comment]
As @valdivj mentions, this is the biggest event since the release of the camera.  many thanks!

**Comment by nonlinear1** [comment]
Good news, But I just have Nvidia Xavier, Could the SDK with ARM support can be applicable to Nvidia Xavier? if not, could you give the Nvidia Xavier arm support.

**Comment by wes-b** [comment]
> Good news, But I just have Nvidia Xavier, Could the SDK with ARM support can be applicable to Nvidia Xavier? if not, could you give the Nvidia Xavier arm support?

Sorry @nonlinear, we don't have any Xavier's to test against. I am thinking it should work though.

**Comment by richardeakin** [comment]
> @UnaNancyOwen , ARM support for Body Tracking SDK is in progress and coming soon. I will update with more details.

Any updates on this? We'd like to test on an NVidia Jetson TX2.

**Comment by eric-schleicher** [comment]
@nonlinear1 it absolutely works on the jetson nano, so you really shouldn't any issue on the xavier

**Comment by valdivj** [comment]
This a little off topic but if  you are going to use the Jetson Nano and the Kinect for Azure here is a link to a video that shows you how you can easily make a portable Battery power supply to run the pair.
https://youtu.be/WuC0PN5PuYA

**Comment by SladeLu** [comment]
Does someone build this new SDK and successfully complie AZURE_ROS_PKG on arm64(jetson nano). Wondering some instructions using this ARM64 SDK on AZURE_ROS_PKG.  Seems the manully compling file structure cannot fit the AZURE_ROS_PKG required provided by microsoft.  Or it will have some updates on AZURE_ROS_PKG ?

**Comment by nonlinear1** [comment]
Just now, I try to compile the Azure Kinect SDK for ARM in Xavier. But I failed. I first download  1.4.0-alpha.4 from https://www.nuget.org/api/v2/package/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.4. Then I copy the /linux/lib/native/arm64/release/libdepthengine.so.2.0 from 1.4.0-alpha.4 to "usr/lib" in Xavier. After that, I download the Azure Kinect SDK from https://github.com/microsoft/Azure-Kinect-Sensor-SDK. Is something wrong? Could someone know? Thanks a lot. the following is  a snapshot of error.
![1680809713](https://user-images.githubusercontent.com/19766939/77288052-f4f83400-6d11-11ea-87de-de205bf776c0.jpg)

**Comment by wes-b** [comment]
@nonlinear1, you are close. [This](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/scripts/docker/setup-ubuntu.sh) docker file script manages the dependencies that ARM64 builds need. You should be able to use this to get your dependencies installed. This script is for cross compiling ARM64 on AMD64, so don't run the script directly on ARM64 or you will end up with AMD64 binaries.

**Comment by nonlinear1** [comment]
Thank you webs-b I have succeed in compiling the Azure Kinect SDK in Xavier. OS: ubuntu 18.04. This is the snap shot:
![1702722019](https://user-images.githubusercontent.com/19766939/77397430-8fbf4400-6de0-11ea-9586-3c63b1d84b10.jpg)

**Comment by TheRunningHorse** [comment]
I tried to compling the SDK in Xavier too, but I failed.Is there are something wrong?

FAILED: tests/Transformation/CMakeFiles/transformation_ut.dir/transformation.cpp.o 
/usr/bin/c++   -I../extern/azure_c_shared/src/inc -I../extern/azure_c_shared/src/pal/linux -isystem ../extern/googletest/src/googletest/include -isystem ../extern/googletest/src/googletest -I../src/../include -Isrc/sdk/include -I../extern/spdlog/src/include -I../tests/UnitTests/utcommon/inc -isystem ../extern/googletest/src/googlemock/include -isystem ../extern/googletest/src/googlemock -I../include -O2 -g -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wno-missing-field-initializers -Werror -pthread -std=gnu++11 -MD -MT tests/Transformation/CMakeFiles/transformation_ut.dir/transformation.cpp.o -MF tests/Transformation/CMakeFiles/transformation_ut.dir/transformation.cpp.o.d -o tests/Transformation/CMakeFiles/transformation_ut.dir/transformation.cpp.o -c ../tests/Transformation/transformation.cpp
../tests/Transformation/transformation.cpp: In member function ‘virtual void transformation_ut_transformation_depth_image_to_point_cloud_Test::TestBody()’:
../tests/Transformation/transformation.cpp:403:43: error: call of overloaded ‘abs(double)’ is ambiguous
     if (std::abs(check_sum - reference_val) > 0.001)
                                           ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5352,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from ../extern/googletest/src/googletest/include/gtest/gtest.h:56,
                 from ../tests/UnitTests/utcommon/inc/utcommon.h:7,
                 from ../tests/Transformation/transformation.cpp:4:
/usr/include/stdlib.h:837:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^
In file included from /usr/include/c++/5/ext/string_conversions.h:41:0,
                 from /usr/include/c++/5/bits/basic_string.h:5352,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from ../extern/googletest/src/googletest/include/gtest/gtest.h:56,
                 from ../tests/UnitTests/utcommon/inc/utcommon.h:7,
                 from ../tests/Transformation/transformation.cpp:4:
/usr/include/c++/5/cstdlib:166:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^
/usr/include/c++/5/cstdlib:174:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^
/usr/include/c++/5/cstdlib:179:3: note: candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^

**Comment by UnaNancyOwen** [comment]
Azure Kinect worked on Jetson Nano! 👍 
I'm look forward to more optimization in the future.
![Screenshot from 2020-03-24 22-17-32](https://user-images.githubusercontent.com/816705/77435253-6c6ab800-6e25-11ea-93eb-30f4d91bd1b7.png)

**Comment by UnaNancyOwen** [comment]
Has the Azure Kinect Body Tracking SDK with ARM64 supported been released?
Do we still have to wait a while for that? Thanks,

**Comment by TheRunningHorse** [comment]
I have another error now!
FAILED: tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o 
/usr/bin/g++   -I../tools/k4aviewer -Isrc/sdk/include -I../include -Isrc/record/sdk/include -I../extern/imgui/src -I../extern/imgui/src/examples -I../extern/imgui/src/examples/libs/gl3w -I../extern/imgui/src/examples/libs/glfw/include -I../extern/libjpeg-turbo/src -I../extern/libusb/src/libusb -I../extern/libyuv/src -I../extern/libyuv/src/include -I../extern/glfw/src/include -O2 -g -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wno-missing-field-initializers -Werror -idirafter/usr/include/soundio -std=gnu++11 -MD -MT tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o -MF tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o.d -o tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o -c ../tools/k4aviewer/k4apointcloudwindow.cpp
../tools/k4aviewer/k4apointcloudwindow.cpp: In member function ‘virtual void k4aviewer::K4APointCloudWindow::Show(k4aviewer::K4AWindowPlacementInfo)’:
../tools/k4aviewer/k4apointcloudwindow.cpp:95:12: error: ‘SeparatorEx’ is not a member of ‘ImGui’
     ImGui::SeparatorEx(ImGuiSeparatorFlags_Vertical);
            ^~~~~~~~~~~
../tools/k4aviewer/k4apointcloudwindow.cpp:95:12: note: suggested alternative: ‘Separator’
     ImGui::SeparatorEx(ImGuiSeparatorFlags_Vertical);
            ^~~~~~~~~~~
            Separator
[13/21] Building CXX object tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4awindowset.cpp.o

**Comment by wes-b** [comment]
> I have another error now!
> FAILED: tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o
> /usr/bin/g++ -I../tools/k4aviewer -Isrc/sdk/include -I../include -Isrc/record/sdk/include -I../extern/imgui/src -I../extern/imgui/src/examples -I../extern/imgui/src/examples/libs/gl3w -I../extern/imgui/src/examples/libs/glfw/include -I../extern/libjpeg-turbo/src -I../extern/libusb/src/libusb -I../extern/libyuv/src -I../extern/libyuv/src/include -I../extern/glfw/src/include -O2 -g -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wno-missing-field-initializers -Werror -idirafter/usr/include/soundio -std=gnu++11 -MD -MT tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o -MF tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o.d -o tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4apointcloudwindow.cpp.o -c ../tools/k4aviewer/k4apointcloudwindow.cpp
> ../tools/k4aviewer/k4apointcloudwindow.cpp: In member function ‘virtual void k4aviewer::K4APointCloudWindow::Show(k4aviewer::K4AWindowPlacementInfo)’:
> ../tools/k4aviewer/k4apointcloudwindow.cpp:95:12: error: ‘SeparatorEx’ is not a member of ‘ImGui’
> ImGui::SeparatorEx(ImGuiSeparatorFlags_Vertical);
> ^~~~~~~~~~~
> ../tools/k4aviewer/k4apointcloudwindow.cpp:95:12: note: suggested alternative: ‘Separator’
> ImGui::SeparatorEx(ImGuiSeparatorFlags_Vertical);
> ^~~~~~~~~~~
> Separator
> [13/21] Building CXX object tools/k4aviewer/CMakeFiles/k4aviewer.dir/k4awindowset.cpp.o

Please open a new bug and share steps to reproduce how you got to this build error. My guess is that you are working from the ZIP file download, which we do not support. You need to clode the repo so that submodules get populated and built.

**Comment by UnaNancyOwen** [comment]
@tesych @wes-b Please update download link in Microsoft Docs. It's still v1.3.0.
https://docs.microsoft.com/en-us/azure/Kinect-dk/sensor-sdk-download#windows-download-link

**Comment by wes-b** [comment]
> @tesych @wes-b Please update download link in Microsoft Docs. It's still v1.3.0.
> https://docs.microsoft.com/en-us/azure/Kinect-dk/sensor-sdk-download#windows-download-link

Thank you! I have submitted a PR.

**Comment by valdivj** [comment]
If anybody is interested here is a video of the Kinect for Azure  running Nvida Deepstream using the Jetson Nano.
https://youtu.be/Pew5plgRKps

**Comment by tkircher** [comment]
@valdivj using the drill body and battery is a great idea. This is mine:

![side_view](https://user-images.githubusercontent.com/19326823/78513543-ede11500-7758-11ea-86ca-e4d454995b3a.jpeg)
![front_view](https://user-images.githubusercontent.com/19326823/78513545-f2a5c900-7758-11ea-8087-d9cf49d14a6c.jpeg)

**Comment by valdivj** [comment]
@tkircher  Looks Clean!
All it needs is a label with your Brand on it. : )

**Comment by dadaofeng** [comment]
This version (1.4.0) does not support body tracking sdk on Ubuntu 18.04.
Is there any way to deal with this?

**Comment by wes-b** [comment]
> This version (1.4.0) does not support body tracking sdk on Ubuntu 18.04.
> Is there any way to deal with this?

Body Tracking team is also adding ARM support. A new version of BT is comming that will work with 1.4.0.

**Comment by vnt1537** [comment]
> Thank you webs-b. I have succeeded in compiling the Azure Kinect SDK in Xavier. OS: ubuntu 18.04. This is the snap shot:
> ![1702722019](https://user-images.githubusercontent.com/19766939/77397563-d2811c00-6de0-11ea-8aec-dbd1f0551e11.jpg)

Hello, can you send some link to some instruction where I can install this successfully for Nvidia Xavier!! It would be really helpfully :) Thank you.

**Comment by wes-b** [comment]
>Hello, can you send some link to some instruction where I can install this successfully for Nvidia Xavier!! It would be really helpfully :) Thank you.

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#debian-package

**Comment by wes-b** [comment]
Locking thread to encourage the creation of new issues
