### ISSUE TITLE
Green Screen Error: Timedout waiting for synchronized captures

### ISSUE THREAD

**Issue by SaraHackett13** [microsoft/Azure-Kinect-Sensor-SDK#1101]
I am able to compile and run the green_screen example. I am wanting to calibrate two cameras. I used the provided checkerboard image and made sure it was visible to both cameras. I am using the following arguments: green_screen 2 9 6 22

I get an error that says "ERROR: Timedout waiting for synchronized captures"

How can I fix this? 

Here are screenshots of my command line:
![cmd_snapshot](https://user-images.githubusercontent.com/49536808/75921400-aba97880-5e26-11ea-9a42-f6524cf67bf8.PNG)
![cmd_error](https://user-images.githubusercontent.com/49536808/75921440-bb28c180-5e26-11ea-862e-783341d72d54.PNG)

**Comment by wes-b** [comment]
What firmware version are you using?

**Comment by SaraHackett13** [comment]
@wes-b I am using Azure Kinect SDk v1.3.0

**Comment by wes-b** [comment]
That is the SDK version, I believe you need to update the firmware on each device. 

```AzureKinectFirmwareTool.exe -q``` will report the version.

Review #530 for the issues with given firmware.

**Comment by SaraHackett13** [comment]
I ran `AzureKinectFirmwareTool.exe -q` and got the following output for all three of my cameras. 

![firmware](https://user-images.githubusercontent.com/49536808/76024404-ac0e4600-5ef0-11ea-816e-d3e1eb10eff0.PNG)

**Comment by SaraHackett13** [comment]
I tried to update my firmware using 
```
AzureKinectFirmwareTool.exe -u firmware\AzureKinectDK_Fw_1.6.102075014.bin
```

The output was `SUCCESS: The firmware was already up-to-date.`

[This page](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md) shows that firmware 1.6.102075014 is the latest. 

How do I install firmware version 1.6.104075014?

**Comment by wes-b** [comment]
Download this Alpha package [1.4.0-alpha.4](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.4) and use the firmware there, we are about to promote it to beta quality.

**Comment by SaraHackett13** [comment]
I was able to get the Green Screen example working. 
Initially, I had three cameras powered on, connected to the host PC, and synced with 3.5mm cables. I disconnected the third camera. Then ran `green_screen 2 9 6 22`  again with success. I did _not_ need to update my firmware. 

Thanks for the help.

**Comment by wes-b** [comment]
Good new, thanks for the update.
