### ISSUE TITLE
Installment issue

### ISSUE THREAD

**Issue by byzhou** [microsoft/Azure-Kinect-Sensor-SDK#1109]
Please run you ci in a blank ubuntu 14.04/16.04/18.04 whatever you guys are supporting. I fixed a bunch package dependency issues before I can 

```
cmake .. ; make 
```

**Comment by qm13** [comment]
Apologies. Just saw this. Not enough info to make actionable. Please follow bug template next time so the bug is seen in triage. Feel free to reopen with more info if it is still an issue.
