### ISSUE TITLE
Offset in Skeletons from Azure Kinect and Kinect v2

### ISSUE THREAD

**Issue by justamad** [microsoft/Azure-Kinect-Sensor-SDK#1113]
Hello, 

for my use case, I want to register the Skeletons from Azure Kinect to the Skeletons coming from Kinect v2. In the calibration process, I'm using an 8x5 50mm checkerboard and identify three corner points using OpenCV, and for each Kinect, using the mapper functions to go from 2D (x,y) color pixel location to 3D (x,y,z) camera space (see image 1,2)

![azure](https://user-images.githubusercontent.com/61836442/76141669-cbc77a80-6066-11ea-8348-43b8762ce8ee.png)

![kinect](https://user-images.githubusercontent.com/61836442/76141670-cc601100-6066-11ea-8257-96314f51a244.png)
  
After moving the checkerboard 4-6 times and capture new calibration images for both cameras, I'm using SVD to get a rotation and translation between the two camera locations. The mean squared error of the rotated points is usually less than 1cm. However, when applying the resulting rotation+translation onto the skeletons, I receive an offset in the y-axis, when x and z-axis are looking good, as shown in the image.

![Skeleton](https://user-images.githubusercontent.com/61836442/76141716-498b8600-6067-11ea-96d6-426cf1e83175.png)
 
System Setup Azure:
OS: Windows 10
GPU: Nvidia RTX 2060
RAM: 16GB
Azure Kinect SDK: 1.3.0
Body Tracking: 1.0.0

Kinect v2:
OS: Windows 10
Library: PyKinect2 (Python) (with Kinect Studio)

**Comment by davidkitman** [comment]
Could this be related to the tilt of the depth camera on the Kinect Azure vs its RGB camera?
"The depth camera is tilted 6 degrees downwards of the color camera"
Are you transforming for that?
https://docs.microsoft.com/en-us/azure/kinect-dk/coordinate-systems

**Comment by justamad** [comment]
Hi davidkitman,

thanks for your advice! I manually corrected for it by applying a rotation matrix of 6 degrees around the x-axis and now the result is looking much better, see the image below. 

![fix_cal](https://user-images.githubusercontent.com/61836442/76211918-91e1aa00-6207-11ea-8916-20d2345e4da7.png)

**Comment by changikjun** [comment]
How did you offset the data Azure to v2?
Can I get the Sequence..?

**Comment by justamad** [comment]
For the initial rotation+translation matrix between the checkerboards please check out the following links for description and the Python code:

http://nghiaho.com/?page_id=671
https://github.com/nghiaho12/rigid_transform_3D

After applying the rot+trans matrix, I corrected for the depth camera tilt by multiplying an Euler-Rotation matrix around the x-axis by 6 degrees to all joints over all frames, as shown below:

```python
import numpy as np

def create_rotation_matrix_x(angle=6):
    angle = angle * np.pi / 180
    rot_x = np.matrix([[1, 0, 0],
                       [0, np.cos(angle), -np.sin(angle)],
                       [0, np.sin(angle), np.cos(angle)]])
    return rot_x
```

**Comment by changikjun** [comment]
Thanks for your advice!
But actually, I'm use c++..
And I have more question!
If I get data of Azure, (instrinsic, extrinsic, etc,,,)
How Can Do I insert in V2 code...??
