### ISSUE TITLE
Check to see if joint exists

### ISSUE THREAD

**Issue by eshirima** [microsoft/Azure-Kinect-Sensor-SDK#1114]
**Is your feature request related to a problem? Please describe.**
At the moment, their is no conscience way for checking to see if a particular joint was successfully detected. Looking at the available options from the [API](https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/1.x.x/structk4abt__joint__t.html#aed7bb9ef0a5ec3afa766b5ab3e20e048), one can use the `confidence` flag but it does not guarantee existence.

**Describe the solution you'd like**
Maybe consider adding a boolean flag, `exists` to the `k4abt_joint_t `struct.

**Describe alternatives you've considered**
At the moment, iterating through `position `and `orientation` to make sure they are empty seems to be the way forward.

**Additional context**
This will be extremely useful especially when working in scenarios where specific joints are visible and/or needed. A quick flag would truly help rather than iterating through two different properties.

**Comment by qm13** [comment]
Confidence level K4ABT_JOINT_CONFIDENCE_LOW is set if the DNN does not return a position for the joint. A joint is still estimated by the human model fitting component of the pipeline. The DNN is also not perfect. It can miss joints that are clearly visible to a human. It can also see joints that are clearly not visible to a human.
