### ISSUE TITLE
[ARM NEON] Transformation API's needs to be optimizes in Neon

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#1118]
**Describe the bug**
ARM64 builds are currently doing transformation calculations on the CPU.

**Comment by tkircher** [comment]
Most of the SSE functions in transformation_depth_to_xyz_sse() can already be found here:

https://github.com/DLTcollab/sse2neon

**Comment by wes-b** [comment]
Wonderful!
