### ISSUE TITLE
Consistent shut down for all 3 Azure Kinect DK 

### ISSUE THREAD

**Issue by datajoker1** [microsoft/Azure-Kinect-Sensor-SDK#1120]
![image](https://user-images.githubusercontent.com/1762209/76285516-eefa6000-62da-11ea-8fdf-e38d5f87f36e.png)

We have bought 3 Azure Kinect DK and when we were using them, there were several times when all had frequent shut downs. We could not find the problem for this matter, therefore we hope you guys could help us. 

Thank you.

**Comment by tesych** [comment]
@datajoker1 , can please follow the bug template and provide more information around your scenario. Otherwise, it would be hard for us to help.

**Comment by wes-b** [comment]
It looks like you are not be receiving any depth frames.

Does K4aViewer work as expected?
