### ISSUE TITLE
Depth is not sync with color camera

### ISSUE THREAD

**Issue by etiennedub** [microsoft/Azure-Kinect-Sensor-SDK#1121]
**Describe the bug**
It seems that the depth is out of sync with the color camera by one frame.
I did some experiment with a led on a Arduino and the IR camera of the kinect set to passive.
The Arduino led is sync with the sync pulse send by the kinect.

**To Reproduce**
1. Turn on a led until the 5th pulse of the sync signal with a arduino.
2. Start the Kinect in master mode with the depth set to passive IR and set `synchronized_images_only` to true . Set the exposition to 16670us so the IR should start the exposition at 7.535ms after the pulse (16.67ms / 2 - 1.6ms / 2 = 7.535ms).
3. Start fetching the IR and color frame and save the few first frames.

**Expected behavior**
The led should be visible in the same number of color frames and IR frames.

**Screenshots**
Arduino timming (top sync pulse and bottom led):
![screenshot](https://user-images.githubusercontent.com/14828908/76322653-09701180-62ba-11ea-9f3e-53f3b92d45fd.png)

![screenshot](https://user-images.githubusercontent.com/14828908/76322131-628b7580-62b9-11ea-9c81-4418dd52e0a1.png)
Red = led off
Green = led on
(Zoom the screenshot to see the led)

**Desktop (please complete the following information):**
OS with Version: Arch Linux x86_64 Linux 5.4.15-arch1-1
SDK Version: 1.3.0
Firmware version: 1.6.102 and 1.6.104

**Comment by wes-b** [comment]
Not sure what is up with your setup. Here is a way you can test it yourself:

1. Put a chess board pattern in the view of the camera - center it top to bottom in the camera's view (you want to measure around center of capture). K4aViewer or PC Camera app will help get this aligned.
1. Use the recorder tool to record ~10s
   * `k4arecorder.exe -l 10 -c 720p -d NFOV_UNBINNED --imu off -e 16000 c:\output.mkv`
   * save it to an SSD driver to ensure you don't have disk write errors.
1. While recording move your hand several times, up and down, in front of the chessboard. Do this rapidly.
1. After recording, open mkv file in K4aViewer.
1. Use the stepping commands to find an image where your hand is over of the chess board. The expected results are below. There will be some motion blur, but the blur seen from the depth camera and the color camera should align. Also ensure the timestamps from the two images indicate you have the expected alignment.
NOTE: We use a fixed exposure for this to ensure the exposure is not changing; a change in exposure will result in a misalignment between the two.
![image](https://user-images.githubusercontent.com/11180453/76577308-1dff0600-6482-11ea-9e72-d7aede47959e.png)
![image](https://user-images.githubusercontent.com/11180453/76577356-40911f00-6482-11ea-8bec-40581e32ed4c.png)
