### ISSUE TITLE
same k4a_image_format_t format() function works fine for depth image, get error for color image 

### ISSUE THREAD

**Issue by k123jack** [microsoft/Azure-Kinect-Sensor-SDK#1133]
This piece of code, works fine for k4a_capture_get_depth_image(),  but change it to k4a_capture_get_color_image() will get the error below. 

//------------------------Code : 
#pragma comment(lib, "k4a.lib")
#include <k4a/k4a.h>
#include <opencv2/opencv.hpp>
// #include <opencv2/highgui.hpp>
// #include <opencv2/highgui/highgui.hpp>
using namespace cv;

#include <stdio.h>
#include <stdlib.h>

int main()
{
    uint32_t count = k4a_device_get_installed_count();
    if (count == 0)
    {
        printf("No k4a devices attached!\n");
        return 1;
    }

    // Open the first plugged in Kinect device
    k4a_device_t device = NULL;
    if (K4A_FAILED(k4a_device_open(K4A_DEVICE_DEFAULT, &device)))
    {
        printf("Failed to open k4a device!\n");
        return 1;
    }

    // Get the size of the serial number
    size_t serial_size = 0;
    k4a_device_get_serialnum(device, NULL, &serial_size);

    // Allocate memory for the serial, then acquire it
    char *serial = (char*)(malloc(serial_size));
    k4a_device_get_serialnum(device, serial, &serial_size);
    printf("Opened device: %s\n", serial);
    free(serial);

    // Configure a stream of 4096x3072 BRGA color data at 15 frames per second
    k4a_device_configuration_t config = K4A_DEVICE_CONFIG_INIT_DISABLE_ALL;
    config.camera_fps       = K4A_FRAMES_PER_SECOND_15;
    config.color_format     = K4A_IMAGE_FORMAT_COLOR_BGRA32;
    config.color_resolution = K4A_COLOR_RESOLUTION_720P;
    config.depth_mode = K4A_DEPTH_MODE_NFOV_UNBINNED;
    // Start the camera with the given configuration
    if (K4A_FAILED(k4a_device_start_cameras(device, &config)))
    {
        printf("Failed to start cameras!\n");
        k4a_device_close(device);
        return 1;
    }
    std::cout<< "started camera" <<std::endl;
    k4a_capture_t capture = NULL;
    k4a_wait_result_t result = k4a_device_get_capture(device, &capture, K4A_WAIT_INFINITE );
    k4a_image_t color_image = k4a_capture_get_color_image(capture);
    if (color_image != NULL)
    {
        printf("color image got\n");
    }

    k4a_image_format_t format = k4a_image_get_format(color_image);
    int rows = k4a_image_get_height_pixels(color_image);
    std::cout<< rows <<std::endl;
    int cols = k4a_image_get_width_pixels(color_image);
    int stride = k4a_image_get_stride_bytes(color_image);
    uint8_t* buffer = k4a_image_get_buffer(color_image);
    cv::Mat colorMat(rows , cols, CV_8UC4, (void*)buffer, cv::Mat::AUTO_STEP);
    cv::imshow("Image", colorMat);
    cv::waitKey(0);

    k4a_capture_release(capture);
    // Camera capture and application specific code would go here
    // Shut down the camera when finished with application logic
    k4a_device_stop_cameras(device);
    k4a_device_close(device);

    return 0;
}

//-------------------------
error : 

![image](https://user-images.githubusercontent.com/32082877/76926882-d44e6980-6920-11ea-9796-55a333479848.png)

Thanks.

**Comment by wes-b** [comment]
You must NULL check the return of k4a_capture_get_<type>_image when [synchronized_images_only](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/structk4a__device__configuration__t_a8208974f05d89fc1362c6a0900bdef4d.html#a8208974f05d89fc1362c6a0900bdef4d) is false / not used.
