### ISSUE TITLE
Wrong link to dockerfile in building.md

### ISSUE THREAD

**Issue by roelofvandijk** [microsoft/Azure-Kinect-Sensor-SDK#1140]
**In this file:**
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md

**The link to the dockerfile is:**
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/scripts/Dockerfile

**It should be:**
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/scripts/docker/Dockerfile

**Comment by roelofvandijk** [comment]
This certainly is not a bug, maybe you could add a issue category for these minor things?

**Comment by wes-b** [comment]
Its a bug, thanks for pointing it out. We will get it fixed soon

**Comment by wes-b** [comment]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/commit/4e92a4c346485685561942d7b649c3f0263a0163
