### ISSUE TITLE
transformation_example not outputting .ply files

### ISSUE THREAD

**Issue by philianeles** [microsoft/Azure-Kinect-Sensor-SDK#1142]
**Describe the bug**
I am running the transformation_example on Visual Studio 16 2019 however  `returnCode` is always returning zero and no .ply files seems to be produced.

**To Reproduce**
1. Build the Azure-Kinect-Sensor-SDK using `cmake -G "Visual Studio 16 2019"`
2. Click on 'K4A.sln'
3. Scroll down to 'transformation_example' and run
4. See error: image below in screenshot

**Expected behavior**
.ply files produced

**Screenshots**
![image](https://user-images.githubusercontent.com/11179066/77208968-5bf0cf80-6afd-11ea-933e-35ab9e6858f8.png)

**Desktop**
 - OS with Version: Windows 10 10.0.17134 
 - SDK Version: 1.3.0
 - Firmware version: 1.6.102075014 

**Additional context**
Maybe I am forgetting to specify some paths?

**Comment by UnaNancyOwen** [comment]
It's not a bug.
The example requires command arguments to be passed at runtime.
That console shows you how to use it.
If you want to capture from AKDK device, set it up as follows.
(Please create the output directory in advance.)
```
capture C:\output
```
Please see this page how to pass command arguments on Visual Studio.
https://docs.microsoft.com/en-us/cpp/build/reference/debugging-prop-pages?view=vs-2019#command-arguments

**Comment by philianeles** [comment]
ok great thank you!
