### ISSUE TITLE
transformation_example | "k4a::k4a" 

### ISSUE THREAD

**Issue by alitokur** [microsoft/Azure-Kinect-Sensor-SDK#1155]
I have a problem in building "transformation_example". I am using cmake to build but it can't find target  libraries.

Error Lines : 

-  Target "transformation_example" links to target "k4a::k4a" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

- Target "transformation_example" links to target "k4a::k4arecord" but the target was not found.  Perhaps a find_package() call is missing for an  IMPORTED target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it

- Target "transformation_example" links to target "libjpeg-turbo::libjpeg-turbo" but the target was not found.  Perhaps a  find_package() call is missing for an IMPORTED target, or an ALIAS target is missing? This warning is for project developers.  Use -Wno-dev to suppress it.

After this steps, I still opened the solution window.
 ![nf 1](https://user-images.githubusercontent.com/20575896/78120257-468b7780-7412-11ea-892f-57d103702e92.png) 
As you can see, header files are missing. After using nugget, and adding turbojpeh include.dir, then i think, have no problem with them. 

![nf2](https://user-images.githubusercontent.com/20575896/78120742-2314fc80-7413-11ea-9e23-fe49c32f8a49.png)

And now, when i try to build, i see the following error:
![error](https://user-images.githubusercontent.com/20575896/78122216-1d201b00-7415-11ea-9031-26c43904da71.png)

edit: additional dependencies: 
![linker](https://user-images.githubusercontent.com/20575896/78127202-69228e00-741c-11ea-819e-0c6cc4b20ecd.png)

I'm sorry, not familiar with visual studio. What should I do?

 - OS : Windows 10 
 - SDK Version:  1.4.0 
 - Current Firmware Versions:
  RGB camera firmware:      1.6.98
  Depth camera firmware:    1.6.70
  Depth config file:        6109.7

**Comment by tkircher** [comment]
On Linux, in order to get some of these examples to build, I had to manually edit the link.txt files to change -lk4a::k4a to -lk4a, etc. because k4a::k4a is of course not the name of any library. Going to try to track down the source of the issue sometime.

**Comment by alitokur** [comment]
thank u @tkircher , i'm not sure, but when I added ` #pragma comment(lib, "k4a.lib")` , the problem has been fixed.
