### ISSUE TITLE
GLSL error with Open Source drivers

### ISSUE THREAD

**Issue by hrsFire** [microsoft/Azure-Kinect-Sensor-SDK#1157]
**Describe the bug**
It isn't possible to start the k4abt_simple_3d_viewer in CPU mode with the Open Source drivers even when the driver supports OpenGL 4.4 or higher.

**To Reproduce**
1. In a terminal start the example "k4abt_simple_3d_viewer CPU"
2. The following error occurs:
"Shader Error: 0:2(38): error: `gl_FragColor' undeclared
0:2(38): error: value of type vec4 cannot be assigned to variable of type error"

**Expected behavior**
The app should start.

**Logs**
ubuntu@device:~$ k4abt_simple_3d_viewer CPU
Shader Error: 0:2(38): error: `gl_FragColor' undeclared
0:2(38): error: value of type vec4 cannot be assigned to variable of type error

ubuntu@device:~$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RAVEN (DRM 3.33.0, 5.3.0-42-generic, LLVM 9.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.0-devel (git-8970b78 2020-03-29 bionic-oibaf-ppa)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.0-devel (git-8970b78 2020-03-29 bionic-oibaf-ppa)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.0-devel (git-8970b78 2020-03-29 bionic-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04 Bionic Beaver x64
 - SDK Version:  libk4a1.3, libk4abt1.0
 - Firmware version:
Current Firmware Versions:
  RGB camera firmware:      1.6.102
  Depth camera firmware:    1.6.75
  Depth config file:        6109.7
  Audio firmware:           1.6.14
  Build Config:             Production
  Certificate Type:         Microsoft

**Additional context**
I've opened a [pull request](https://github.com/microsoft/Azure-Kinect-Samples/pull/47) to fix the issue.

**Comment by yijiew** [comment]
@hrsFire Thanks for creating the pull request to fix the problem! I have merged the pull request.
