### ISSUE TITLE
Conflicting Azure Kinect Specifications

### ISSUE THREAD

**Issue by hofst** [microsoft/Azure-Kinect-Sensor-SDK#1160]
Not sure if this is a bug, but you enlist the Kinect Azure as having an OmniVision OV12A10 CMOS with 30Hz across all resolutions. However, OmniVision lists this sensor with up to 90Hz at 1080p (see https://www.ovt.com/sensors/OV12A10). Those statements are in conflict, which one is correct?

**Comment by wes-b** [comment]
Azure Kinect only supports 30FPS.
