### ISSUE TITLE
K4arecorder cannot switch color mode

### ISSUE THREAD

**Issue by SladeLu** [microsoft/Azure-Kinect-Sensor-SDK#1161]
SDK version: 1.4.0
Hardware:  Jestson nano
Ubuntu version: 18.04

K4aviewer works normally. 
But when i used commands line to record  images, it works normally if only running `k4arecorder output.mkv`  but shows up lots of errors with controlling color mode by `k4arecorder output.mkv`. Pls help. Thanks.
![image](https://user-images.githubusercontent.com/17822960/78562252-a5565400-784b-11ea-9fbf-734f35d08292.png)
![image](https://user-images.githubusercontent.com/17822960/78562331-c0c15f00-784b-11ea-9df1-3285e973f6be.png)

**Comment by wes-b** [comment]
Can you try #485? I know this is not a multi camera scenario, but the error below indicates you might be memory limited, which is a change we do by default on our test devices

> libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12
