### ISSUE TITLE
Kinect 4 Azure API calls from Python or Pre-Recorded Videos

### ISSUE THREAD

**Issue by GMZRD71** [microsoft/Azure-Kinect-Sensor-SDK#1162]
I’m a graduate electrical and computer engineering student at the University of Texas at San Antonio.  We have seven Kinect 4 azure SDK’s in our lab.  We are enhancing the current applications from the Kinect 4 azure SDK cameras we have in our lab.   While tracking the body positions of people with the kinects, I would like to combine these positional data with other information from the video/audio either in real time or in post-processing.   I have two questions: (1) Is there a way to call the body tracker API for the cameras from Python in real-time or in post-processing either in windows [preferably] or in ubuntu?  (2) Can I use the Kinect API body tracker with videos previously recorded with our kinect 4 azure cameras?

**Comment by qm13** [comment]
@GMZRD71 there is currently no official Python wrapper from Microsoft. However @etiennedub has started a project to develop a Python 3 wrapper https://github.com/etiennedub/pyk4a. You can also up vote the customer feedback requesting an official Python wrapper https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/37675798-python-support
