### ISSUE TITLE
Body tracking value error is too great

### ISSUE THREAD

**Issue by devLupin** [microsoft/Azure-Kinect-Sensor-SDK#1167]
--My information--
OS : Win 10
Language : C++/C#
Sensor : Azure Kinect DK
SDK version : Latest

This is part of main.cpp of simple_cpp_sample. I made some modifications.

```cpp
void print_body_information(k4abt_body_t body)
{
    std::cout << "Body ID: " << body.id << std::endl;
    for (int i = 0; i < (int)K4ABT_JOINT_COUNT; i++)
    {
        k4a_float3_t position = body.skeleton.joints[i].position;
        k4a_quaternion_t orientation = body.skeleton.joints[i].orientation;
        k4abt_joint_confidence_level_t confidence_level = body.skeleton.joints[i].confidence_level;

        if (confidence_level >= K4ABT_JOINT_CONFIDENCE_MEDIUM) {
            printf("Joint[%d]: Position[mm] ( %f, %f, %f ); \n",
                i, position.v[0], position.v[1], position.v[2];
        }
    }
}
```

I stood always in the same position.
Let's say that the current loop is JOINT SPINE NAVAL.

```
output example)

(1)st : 1, 1, 1
(2)nd : 1, 1, 2                  // The error of 1 is acceptable.

(n)th : 70, 30, 90            // This result is example. The maximum error I had was around 70.
```

Not always a difference of 70.

**I stood in the same position.**
Since it is a program, I can understand the error +-5 degree.
**How should we predict this anomalous error?**

Do all sensors have this error?
The sensor itself I purchased may be defective.

If the sensor itself is a problem, I can simply replace or A/S the sensor. 
However, if this error is present on all sensors, it becomes a big problem.

Provide a solution.

**Comment by yijiew** [comment]
Hi @devLupin , thanks for running the experiment. Is this issue easy to repro? If so, could you send us a mkv recording (maybe using k4aviewer or directly using the k4arecord APIs ) so that we can repro and analyze the result on our side?
