### ISSUE TITLE
Mistakes in documentation of k4a_transformation_depth_image_to_color_camera_custom()

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#1170]
**Describe the bug**

I think the part of documentation in <code>k4a_transformation_depth_image_to_color_camera_custom()</code> seems to be incorrect.
It say "use_linear_interpolation to false ...", but <code>use_linear_interpolation</code> option does not exist. I think it's probably a description of old API that's under development.

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/85f9b9217f3e808b6f687e228be695483af34613/include/k4a/k4a.h#L2139-L2140

**Expected behavior**

You should rewrite the description to be more in line with the current API. 
Currently, It is controlled by the <code>interpolation_type</code> option.

**Desktop (please complete the following information):**

 - SDK Version:  1.4.0 and develop/HEAD

**Comment by wes-b** [comment]
Thank you - fixed it with this change: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/commit/e287f73b03578914f19135cea881fc929a610cad.
