### ISSUE TITLE
Issue with Joints -- 26 points returned

### ISSUE THREAD

**Issue by aanexplus** [microsoft/Azure-Kinect-Sensor-SDK#1210]
**Describe the bug**

When I run the code for body tracking, I got 26 joints instead of 32 joints. Everything seems fine when I was recording the data because I used window3d. I do not know how to interpret the 26 joints because I do not know which belong to which. Why am I getting 26 positions instead of 32? Below is my code for recording the joint position: 

                    if (body.skeleton.joints[joint].confidence_level &gt;= K4ABT_JOINT_CONFIDENCE_LOW) {
                        const k4a_float3_t& jointPosition = body.skeleton.joints[joint].position;
                        const k4a_quaternion_t& jointOrientation = body.skeleton.joints[joint].orientation;

                        jointPosition.
                        
                        file__ &lt;&lt; k4abt_frame_get_device_timestamp_usec(bodyFrame) &lt;&lt; "\t" &lt;&lt; jointPosition.xyz.x &lt;&lt; "\t" &lt;&lt; jointPosition.xyz.y &lt;&lt; "\t" &lt;&lt; jointPosition.xyz.z &lt;&lt; "\t";
                        file2__ &lt;&lt; k4abt_frame_get_device_timestamp_usec(bodyFrame) &lt;&lt; "\t" &lt;&lt; jointOrientation.wxyz.w &lt;&lt; "\t" &lt;&lt; jointOrientation.wxyz.x &lt;&lt; "\t" &lt;&lt; jointOrientation.wxyz.y &lt;&lt; jointOrientation.wxyz.z &lt;&lt; "\t";

                        file_rec__ &lt;&lt; jointPosition.xyz.x &lt;&lt; "\t" &lt;&lt; jointPosition.xyz.y &lt;&lt; "\t" &lt;&lt; jointPosition.xyz.z;
                        file2_rec__ &lt;&lt; jointOrientation.wxyz.w &lt;&lt; "\t" &lt;&lt; jointOrientation.wxyz.x &lt;&lt; "\t" &lt;&lt; jointOrientation.wxyz.y &lt;&lt; jointOrientation.wxyz.z ;

                        window3d.AddJoint(
                        jointPosition,
                        jointOrientation,
                        body.skeleton.joints[joint].confidence_level &gt;= K4ABT_JOINT_CONFIDENCE_MEDIUM ? color: lowConfidenceColor
                        );

---
#### Document Details

**To Reproduce**
Please use the code snippet above to reproduce

**Expected behavior**

I should get a 32 key point as shown in the documentation but I got only 26.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by qm13** [comment]
The joint positions are documented [here](https://docs.microsoft.com/en-us/azure/Kinect-dk/body-joints). My suspicion is you are not seeing the hand joints.
