### ISSUE TITLE
Better Player Index quality and performance

### ISSUE THREAD

**Issue by jBachalo** [microsoft/Azure-Kinect-Sensor-SDK#1211]
With the v2 sensor it was a simple matter to use the Player Index image to pull a mask for background replacement type effects.
Now with the Azure Kinect this isn't possible for 2 reasons

1- Huge amounts of latency between the Player Index and RGB video
2- Poor quality of the silhouette generated in Player Index.

Can we please bring back the player index used in the v2 sensor?

**Comment by qm13** [comment]
Duplicate issue.
The body tracking performance is being tracked with issue #514 
The poor instance segmentation is being tracked with issue #949
