### ISSUE TITLE
Azure Devices generate pink and black frames in the slave mode with external master device. 

### ISSUE THREAD

**Issue by hagorms** [microsoft/Azure-Kinect-Sensor-SDK#1227]
How to replicate: 

**Describe the bug**

**To Reproduce**
1) Connect device to external signal generator.
2) Set external signal generator frequency to 5 , 15, or 30. 
3) Start Azure recording in slave mode.
4) Start signal generator.
5) After recording is finished convert mkv to frames with ffmpeg.

Some of the converted frames will be pink or black.
If 2 kinects were connected to Master device, pink frames are not synchronized. 
This issue was tested with 2 different kinects.
This issue was tested with --rate 5, 15, 30 

**Expected behavior**
No black or pink frames are recorded. 

**Desktop**
 - OS with Version: Windows 10. 
 - SDK Version: 1.4.0
 - Firmware version : AzureKinectDK_Fw_1.6.108079014 
**Additional context**
![A0S_A1S_IM_15FPS_5M_3_A1S-0010](https://user-images.githubusercontent.com/12120066/82770088-86317700-9e37-11ea-8e9b-75dfe32db3c5.jpg)
![A0S_A1S_IM_15FPS_5M_3_A1S-0009](https://user-images.githubusercontent.com/12120066/82770107-921d3900-9e37-11ea-8d11-6ff13172b389.jpg)

**Comment by qm13** [comment]
How does the .mkv file look in the k4aviewer?

**Comment by hagorms** [comment]
Dear qm13,
mkv files have some small black blinks in the k4aviewer. 
Do you mind have a look on the file?

**Comment by wes-b** [comment]
Can you share a screen shot of K4AViewer and the black blinks you are referring to? We do expect a version of this to float across the depth camera, but it is not usually an entire frame.

**Comment by hagorms** [comment]
Here are screenshots: 
![image](https://user-images.githubusercontent.com/12120066/83989383-8442da00-a946-11ea-813b-1fe5832b00c8.png)
![image](https://user-images.githubusercontent.com/12120066/83989406-96247d00-a946-11ea-9099-2d693015e952.png)
![image](https://user-images.githubusercontent.com/12120066/83989412-9de42180-a946-11ea-8c0f-9ae5cbb372ae.png)

**Comment by wes-b** [comment]
Does this only reproduce with the external generator? Can you reproduce this with the Azure Kinect as the master?

**Comment by hagorms** [comment]
It reproduces with external generator. If one of Kinect is a master, it might happen for one or two frames. After that it stays stable

**Comment by wes-b** [comment]
The sync pulse width will cause this. Using a signal generator, you are very likely outside the tolerance of how long the pulse should be active. We are not convinced yet that we want to fully document what the tolerance of this pulse needs to be to avoid this condition. But if you can record and emulate sync pulse generated by a master device for the color mode and resolution you will be using, then you should not have a problem going forward.

@markhog who also has questions in this area

**Comment by tostercx** [comment]
Have a _very_ similar issue except the frames are red and black, not pink. Seems to be related to ambient temperatures getting lower, not sure why.

The signal is generated by the master device in my case, no external trigger. Black/red frames only on slaves.
