### ISSUE TITLE
Body tracking sdk in Rsapberry Pi4

### ISSUE THREAD

**Issue by Michael-robo13** [microsoft/Azure-Kinect-Sensor-SDK#1232]
I have a question about the body tracking sdk. Can it be used in raspberry pi 4? I want to obtain the skeleton data in system of raspberry pi4 + ros + azure kinect. Looking forward to your reply.

**Comment by qm13** [comment]
@Michael-robo13 Neither the Sensor SDK nor the Body Tracking SDK currently work with Raspberry Pi. We have released the Sensor SDK on the NVIDIA Jetson range of products and are working on a version of the Body Tracking SDK targeting the Xavier variants. Longer term we are also looking at other hardware acceleration options.

**Comment by AswinkarthikeyenAK** [comment]
Hi @qm13 ,
is the body tracking sdk released for Jetson Nano? If could share some info on that it would be really great 

Thanks

**Comment by qm13** [comment]
It will not be available on the Jetson Nano. We are working to make it available on the Jetson Xavier variants.

**Comment by Azzedine-Touazi** [comment]
Please what about Jetson TX2. When are you expecting the body tracking SDK will be released for Jetson (TX2)? Thanks in advance.

**Comment by qm13** [comment]
We will not prevent the Body Tracking SDK being used on a TX2. What frame rate you can achieve is unknown.

**Comment by Azzedine-Touazi** [comment]
@qm13  Thanks again!

**Comment by AswinkarthikeyenAK** [comment]
@qm13,
Any updates on when we might get the SDK Jetson Xavier variants? 
Thank you

**Comment by Azzedine-Touazi** [comment]
@qm13,  
Please any update about body tracking SDK for Jetson.  

Thanks in advance.

**Comment by Michael-robo13** [comment]
Sorry, I didn`t use the body tracking SDK for Jetson. I changed my plan.
________________________________
发件人: Azzedine Touazi <notifications@github.com>
发送时间: 2020年11月30日 21:24
收件人: microsoft/Azure-Kinect-Sensor-SDK <Azure-Kinect-Sensor-SDK@noreply.github.com>
抄送: 刘灏 <18hliu@stu.edu.cn>; Mention <mention@noreply.github.com>
主题: Re: [microsoft/Azure-Kinect-Sensor-SDK] Body tracking sdk in Rsapberry Pi4 (#1232)


@qm13<https://github.com/qm13>,
Please any update about body tracking SDK for Jetson.

Thanks in advance.

―

**Comment by Azzedine-Touazi** [comment]
Hi @qm13

Any update relative to this issue? If not, are there other AI devices which support Azure body tracking SDK? 

Cheers.

**Comment by andrey-tsb** [comment]
Also looking forward for Kinect Azure support on embedded platforms like Rpi4 (not sure about Azure body tracking SDK development roadmap). Currently there are other solutions for body tracking on Raspberry Pi4, but only with other sensors.
