### ISSUE TITLE
I use dockerfile(in path scripts/docker) to build an image, and get the opengl with version 3.1, why?

### ISSUE THREAD

**Issue by zdegrh** [microsoft/Azure-Kinect-Sensor-SDK#1233]
Describe the problem:
I am thinking about using k4a in docker, then I build the image with dockerfile as following:
#START
ARG UBUNTU_VERSION=18.04
#Use the official ubuntu:18.04 image as the parent image
FROM ubuntu:${UBUNTU_VERSION}

#Set the working directory to /app
WORKDIR /root

ARG ARCH=amd64

ADD setup-ubuntu.sh /root
ADD sources.list /root

#Tell Ubuntu non-interactive install
ARG DEBIAN_FRONTEND=noninteractive

RUN chmod +x ./setup-ubuntu.sh
RUN ./setup-ubuntu.sh ${ARCH}

#somthing about ssh and vnc
RUN apt-get install -y ca-certificates
RUN update-ca-certificates
RUN apt-get update \
	&& apt-get install -y supervisor \
		openssh-server vim \
		xfce4 xfce4-goodies \
		x11vnc xvfb \
		firefox \
		git \
		pwgen
#dockerfile end

and then run k4aviewer, it says 
"Error: OpenGL 4.4 context creation failed. You could try updating your graphics drivers."
then run "glxinfo | grep OpenGL", get
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 9.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 19.2.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
now, how to upgrade OpenGL version to 4.4 or higher?
or, how can i get an image with opengl4.4 or higher?
thanks.

and, with image “schultetwin1/akbuilder:0.0.3”, how can i run k4aviewer?
thanks.

**Comment by wes-b** [comment]
Docker is currently targeted as a build & automation tool. IIRC our issue around running remotely will prevent you from being able to run K4aViewer or other tools. We need an active user session.
