### ISSUE TITLE
Sucessful Application built, Failed to "Start camera"?

### ISSUE THREAD

**Issue by Se7en7th** [microsoft/Azure-Kinect-Sensor-SDK#1236]
Hi Devs,
I'm a College student researching on Azure Kinect's capabilities, I have followed the "Quickstart: Build your first Azure Kinect application" guide and have successfully coded the code on a blank .cpp app with no visible errors in the error list or in the output log.

Upon compiling the solution, I am to expect a window to pop up showing a stream of the view of the Kinect camera that is plugged into the computer?

Currently, what I have on the output window is a blank screen, am I supposed to code a .xaml grid for the stream?
<img width="932" alt="blank window error" src="https://user-images.githubusercontent.com/65853237/83539046-26b72380-a529-11ea-99df-fe1603c0d082.png">

**Comment by wes-b** [comment]
That tutorial is just expected to start and stop the camera's. It doesn't look into UI components to show the images.  Take a look at our [green screen example](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/examples/green_screen/README.md), it pops up a window.
