### ISSUE TITLE
Azure Kinect Body tracking SDK crashes on opening

### ISSUE THREAD

**Issue by hpsinghjk** [microsoft/Azure-Kinect-Sensor-SDK#1242]
![IMG_1266](https://user-images.githubusercontent.com/66403083/83716089-d6be8680-a626-11ea-9a32-9c165d715c7c.jpg)
![IMG_1266](https://user-images.githubusercontent.com/66403083/83716106-e2aa4880-a626-11ea-8901-dbf57616cf49.jpg)

**Describe the bug**
Azure Kinect Body tracking SDK crashes on opening

**To Reproduce**
 build 18362.836
 - SDK Version:  <!-- 1.0.1
 -

**Comment by hpsinghjk** [comment]
Hello, I wanted to perform body tracking for shoulder movement. The Azure kinect viewer opens up on the computer and I can see the depth camera information but the kinect body tracking does not open and crashes as soon as I click on it. I have tried uninstall and reinstall but it is showing a different icon compared to the viewer as can be seen in the picture above. Please advise what other information would you require.

**Comment by lisajamhoury** [comment]
@hpsinghjk Did you solve this issue? Having the same problem and cannot find a solution.

**Comment by lisajamhoury** [comment]
We fixed this with the firmware update. https://docs.microsoft.com/en-us/azure/kinect-dk/update-device-firmware
