### ISSUE TITLE
Missing camera performance evaluation result 

### ISSUE THREAD

**Issue by mkarlan** [microsoft/Azure-Kinect-Sensor-SDK#1246]
**Describe the bug**
I can see different metrics explained for evaluating the camera's performance on the [official documentation](https://docs.microsoft.com/en-us/azure/kinect-dk/depth-camera) page. But the result for the same for the different working ranges has not been published.

**Describe the solution you'd like**
Some publicly accessible (and citeable) metrics indicating how accurate the camera is.

**Comment by wes-b** [comment]
I think you are after this: https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification

**Comment by mkarlan** [comment]
No, I am looking for metrics results such as z accuracy, repeatability, plane fit RMSE, Peak Signal to Noise Ratio (PSNR)

**Comment by wes-b** [comment]
Z accuracy is in the link I shared: https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification#depth-camera-supported-operating-modes.
