### ISSUE TITLE
how to set the stride_bytes argument in the k4a_image_create() for the mjpg 

### ISSUE THREAD

**Issue by GitZinger** [microsoft/Azure-Kinect-Sensor-SDK#1247]
**Describe the bug**

I tried to put 0 or 1 as the stride_bytes in there but got the error with "mjpg does not have a constant stride"? 
what should I do? 
please help me here! thank you so much!

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version:  1700
 - SDK Version:   1.2.0
 - Firmware version:  

**Additional context**

**Comment by qm13** [comment]
There is no stride for mjpg. What issue are you encountering?

**Comment by GitZinger** [comment]
then
1. I mean how can I declare a handler variable from the k4a_image_create()  to  hold a mjpg color image? should I put 0 or 1 in there as the 3rd argument?
2.  then how to save the mjpg image into file? 
thanks @qm13

**Comment by wes-b** [comment]
Use k4a_image_create_from_buffer() and set the stride to 0.

**Comment by GitZinger** [comment]
@wes-b 
that is why i got this issue:
I tried to put 0 or 1 as the stride_bytes in there but got the error with "mjpg does not have a constant stride"?

**Comment by wes-b** [comment]
I expect you would get this error from k4a_image_create(), but not k4a_image_create_from_buffer(). Also you are on an old SDK version so please update and retest with k4a_image_create_from_buffer().
