### ISSUE TITLE
Release libk4abt compatible with libk4a1.4

### ISSUE THREAD

**Issue by d-walsh** [microsoft/Azure-Kinect-Sensor-SDK#1248]
**Describe the bug**

The current release of libk4abt (`libk4abt1.0`) is only compatible with `libk4a1.3`. I want to use the Body Tracking SDK with `libk4a1.4` so I believe we need a new release that supports this. It's clear to see here that the latest libk4abt release is `1.0`: https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/

**To Reproduce**

`sudo apt install libk4a1.4-dev` forces `libk4abt1.0-dev` to be uninstalled.

**Expected behavior**

Be able to install a version of `libk4abt` compatible with `libk4a1.4`.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by aistyler** [comment]
@d-walsh @qm13 

any update?

**Comment by JBYoshi** [comment]
I'm having trouble with this as well. I'm experiencing problems with #1187 on libk4a1.3, which should be fixed in libk4a1.4. However, I also need access to body tracking, so I can't currently update to the newer version until a compatible body tracking SDK is released.

**Comment by tlind** [comment]
Same issue here! Any update?

**Comment by qm13** [comment]
Fixed

**Comment by remmel** [comment]
`sudo apt install libk4abt1.1-dev`
