### ISSUE TITLE
Color Camera Fails on Startup for Linux ARM

### ISSUE THREAD

**Issue by madelinegannon** [microsoft/Azure-Kinect-Sensor-SDK#1249]
**Describe the bug**

`DecodeMJPEGtoBGRA32(). MJPEG decode failed: -1` error when running `k4aviewer` and color camera is enabled on Jetson Xavier NX.

**To Reproduce**

1. Running `k4aviewer` on NVIDIA Jetson Xavier NX
2. Select Device and Start using default settings
3. "Cameras failed: Failed to get capture from device!" will pop up.
4. Stop and restart: same error after a few seconds.
5. See errors below

> No errors occur when disabling color camera (uncheck Enable Color Camera) and restarting

> Same issue for BGRA MJPG NV12 and YUY2 formats, and 30, 15, 5 FPS

**Expected behavior**

Able to use color camera feed

**Logs**

Output from `k4aviewer`:
```
[ error    ] : DecodeMJPEGtoBGRA32(). MJPEG decode failed: -1
[ warning  ] : capturesync_add_capture(). Capture Error Detected, Color 
[ error    ] : capturesync_get_capture(device->capturesync, capture_handle, timeout_in_ms) returned failure in k4a_device_get_capture()
[ warning  ] : color_capture_available(). A streaming color transfer failed
```
Output from terminal:
```
[2020-06-10 13:52:43.473] [error] [t=11626] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/color/uvc_camerareader.cpp (1300): DecodeMJPEGtoBGRA32(). MJPEG decode failed: -1
[2020-06-10 13:52:43.473] [error] [t=11627] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/sdk/k4a.c (269): capturesync_get_capture(device->capturesync, capture_handle, timeout_in_ms) returned failure in k4a_device_get_capture()
```

**Desktop (please complete the following information):**
 - Hardware: NVIDIA Jetson Xavier NX, ARMv8 Processor, NVIDIA Tegra Xavier GPU, 64bit
 - OS with Version:  Ubuntu 18.04 
 - SDK Version:   1.4
 - Firmware version:   Current Firmware Versions:
   - RGB camera firmware:      1.6.108
   - Depth camera firmware:    1.6.79
   - Depth config file:        6109.7
   - Audio firmware:           1.6.14

**Additional context**

- Seems like a similar issue to #926 (no solution was posted). Any thoughts @wes-b ?
- I also increased my USBFS memory to 1000 in case of this is a LIBUSB issue.

**Comment by wes-b** [comment]
PR #1194 has a fix for this. While we work on releasing 1.4.1 with this fix, you can access our Beta build here with the [nuget package](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.1-beta.0). Just download, rename to zip and unpack. It has Win64, and libs for AMD64 & ARM64 on Ubuntu.
