### ISSUE TITLE
Visual Studio Projects don't load after adding Body Tracking SDK via NuGet

### ISSUE THREAD

**Issue by redfood** [microsoft/Azure-Kinect-Sensor-SDK#1250]
**Describe the bug**

(I'm not sure if this is the correct place to report this problem since I think it is with that NuGet package).

I am using Visual Studio 2019.  If I create a project and add the body tracking SDK via NuGet.  I can compile and run my program file.  If I close and then reopen the project the solution looks empty and it says "unloaded".

**To Reproduce**
1. Open Visual Studio 2019
2. Add the body tracking SDK via NuGet
2. Create a command line c program that uses the body tracking SDK.
3. Quit VS
4. Reopen the "solution"

**Expected behavior**
The solution would open.

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS with Version: 10.0.18363 
 - SDK Version:  v1.0.1
 - Firmware version:    
RGB camera firmware:      1.6.108
  Depth camera firmware:    1.6.79

**Additional context**
I am able to get the project to load if I edit the `.vcxproj` file and delete the following lines:
```
<None Include="..\packages\Microsoft.Azure.Kinect.BodyTracking.1.0.1\content\dnn_model_2_0.onnx">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
```
(I found this because sometimes VS would give an error about trying to include `dnn_model_2_0.onnx` twice.

**Comment by qm13** [comment]
Fixed
