### ISSUE TITLE
What is the associated audio device name for a given kinect?

### ISSUE THREAD

**Issue by pajama** [microsoft/Azure-Kinect-Sensor-SDK#1252]
I'm recording from 3 kinects simultaneously. I would like to auto-merge my audio recordings to the correct device mkv files afterwards. How do I determine which audio source is associated with which camera?

I'm recording the audio with a libsoundio wrapper for Unity. I'm just recording streams for any devices that contain "Azure Kinect Microphone Array". Is there a better way to identify the kinect microphones? 

Thanks so much!

**Comment by qm13** [comment]
The k4aviewer illustrates how to do this for both Windows and Linux.
