### ISSUE TITLE
Secondary color image in the reference frame of primary color image?

### ISSUE THREAD

**Issue by SeanStephensenAIRM** [microsoft/Azure-Kinect-Sensor-SDK#1255]
I'm using a stereo camera pair and code that is roughly based on the greenscreen example. I've been able to write out the secondary camera's depth image transformed into the perspective of the primary color camera using:

`successful = k4a_transformation_depth_image_to_color_camera(k4a_transformation_t seconday_depth_to_main_color, k4a_image_t secondary_depth_image, k4a_image_t transformed_image);`

shown here is the primary depth image in the primary color reference, the untransformed secondary depth image (secondary color reference), and the transformed secondary depth image (primary color reference frame):

![show1](https://user-images.githubusercontent.com/60408933/84825476-1736e080-afe7-11ea-9114-a2bcbb5c0029.JPG)

![show2](https://user-images.githubusercontent.com/60408933/84825489-1c942b00-afe7-11ea-88a1-ec4a977b663b.JPG)

![show3](https://user-images.githubusercontent.com/60408933/84825502-2027b200-afe7-11ea-8274-70131ba05dfa.JPG)

I'd like to get a similar result to the last image, but where the secondary color image is shown in the primary color's reference, but the only k4a functions seem to be depth--> color or color--> depth. Is there any way to accomplish this with k4a functions? or would this OpenCV territory?

**Comment by qm13** [comment]
When you refer to stereo cameras do you mean two Azure Kinect cameras? The greenscreen samples demonstrates calibrating two Azure Kinect cameras and then transforming the depth image from one of the cameras to the other camera.

**Comment by SeanStephensenAIRM** [comment]
@qm13 that's correct, we have a stereo pair of kinects. I'd like to view the RGB images from the 2 kinects in a common reference frame using the calibration obtained from the chessboard calibration
