### ISSUE TITLE
Kinect doesn't work after operating for a period of time

### ISSUE THREAD

**Issue by qwe953751** [microsoft/Azure-Kinect-Sensor-SDK#1265]
The Kinect Viewer is work normally.
I embedded kinect on my other development system using Miscrosoft.Azure.Kinect.Sensor kit Ver1.2

My pc equipment:
CPU: I7
OS: Windows10, x64

I encountered a problem, and the following error occurred occasionally after I operated for a period of time. As attached:
![1](https://user-images.githubusercontent.com/17944469/86467543-239d9600-bd68-11ea-8d42-5cae05463044.png)
![2](https://user-images.githubusercontent.com/17944469/86467550-25fff000-bd68-11ea-8614-eff493c4453e.png)

I want to know how to solve this problem.
Now, i update Miscrosoft.Azure.Kinect.Sensor kit to version 1.4.  If it still occurred, i will update to here.

**Comment by wes-b** [comment]
For some reason the depth camera is not working. It might be because of your USB controller.

**Comment by qm13** [comment]
Please use the issue template next time.
Is your Azure Kinect on the latest firmware? How long does it run before failing? What USB controller is being used? What host platform? Can you provide repro steps? Can you share logs?
