### ISSUE TITLE
I want proof of safety inspection from Kinect DK.

### ISSUE THREAD

**Issue by devLupin** [microsoft/Azure-Kinect-Sensor-SDK#1269]
I couldn't find any documentation on the Kinect DK safety inspection on the official website.

'github' knows that it should only post questions for development.
But, I can't find it anywhere, so I ask a question here.

I want a certificate stating that the sensor is harmless to human body from electromagnetic waves, etc.
It looks like they have been certified by looking at the marks imprinted on the sensor, so I request the relevant documents.

**Comment by qm13** [comment]
Updated Support documentation to include link to EU certification.
