### ISSUE TITLE
Depth Distortion Issue

### ISSUE THREAD

**Issue by mxf8bv** [microsoft/Azure-Kinect-Sensor-SDK#1272]
There is a strong distortion of depth information for flat surfaces that are not parallel to the sensor plane **only if an additional surface is below the object**. See images below. 

Minimal setting:
Condition 1: matte brown cardboard box, surface towards camera is approx 5cmx20cm, distance to camera approx. 1m, angle approx 45 degrees (picture 1 below: side view of point cloud with undistorted front of box)
Condition 2: same but with an additional matte brown cardboard sheet below the box (picture 2 below: same view; flat box front appears concave)

Depth representation in condition 1 is fine. In condition 2, the box surface towards the camera appears strongly concave (approx. 5cm?).

The same effect occurs for different objects on different surfaces (e.g. a table), when the camera is pointing down at around 45 degrees. The central part of a cylinder, for example, appears to be only only 75% of its top and bottom width.

Questions:
1. what is the reason for this effect?
2. can the effect be reduced by different settings?

![box_depth_noSurface](https://user-images.githubusercontent.com/14327148/86779778-395ad600-c05c-11ea-83fa-03e538d24645.jpg)
![box_depth_withSurface](https://user-images.githubusercontent.com/14327148/86779802-411a7a80-c05c-11ea-8d3e-bcdbee1eaddd.jpg)

Thanks,
   Mathias

**Comment by qm13** [comment]
@mxf8bv could you please also attach color images of the two setups taken with the AK color camera.

**Comment by mxf8bv** [comment]
Sure. I attach views of the box frontal to the camera, one time hanging over the table ("noSurface") and once on the table ("withSurface").  
![RGB_withSurface](https://user-images.githubusercontent.com/14327148/87135009-c2ab1c00-c299-11ea-988b-af5e215ab3b3.png)
![Depth_noSurface](https://user-images.githubusercontent.com/14327148/87135013-c3dc4900-c299-11ea-9ede-84bd0e1bf6bd.png)
![Depth_withSurface](https://user-images.githubusercontent.com/14327148/87135014-c3dc4900-c299-11ea-8c7b-3fd2aef45b26.png)
![Pointcloud_sideview_noSurface](https://user-images.githubusercontent.com/14327148/87135015-c474df80-c299-11ea-9667-65d5f9367916.png)
![Pointcloud_sideview_withSurface](https://user-images.githubusercontent.com/14327148/87135017-c474df80-c299-11ea-8b14-e06df2c654b0.png)
![RGB_noSurface](https://user-images.githubusercontent.com/14327148/87135019-c50d7600-c299-11ea-8bda-51f687a4144b.png)





I blurred out parts of our lab in the images.
BTW it's the AK original cardboard box.

**Comment by qm13** [comment]
@mxf8bv this looks like an example of severe multi-path. Try placing the box on a surface with low IR reflectivity.
