### ISSUE TITLE
request doc for range of possible IR levels from the IR camera

### ISSUE THREAD

**Issue by diablodale** [microsoft/Azure-Kinect-Sensor-SDK#1285]
I request the range of possible valid values for a uint16 pixel in an image that comes from the active IR camera. I have not seen clear information on that. Two issues write it is "dynamic" and the sample code for viewer.exe hardcodes values. However, all of those are to make the image pretty -- not to declare what is the possible range.

What is this range? And lets document that range in in the API docs.

### Investigation

I did casual testing. Using the active IR and finding the max value in every frame of the IR camera images in a stream of them. As my hand approached the sensor, the max value increased until ~13500 and then immediately jumped to 65535. This jump to 65535 coincides with my hand being "too close" to the sensor and it being logically clipped.

In those experiments and the world of ^2, I might think the range of possible values is 0->16383. However, I was not able to ever get values above ~13500. Perhaps there is an exponential intensity ramp as my hand approaches the physical distance minimum and those last ~2800 values are difficult to achieve. However, that is only a guess.

I would expect the firmware (or depthengine) team to know how they map data from the sensor hardware into the uint16 values. And therefore would also know the range of values it can be. What is this range?

### Related info

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/490
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/733
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/95f1d95f1f335b57a350a80a3a62e98e1ee4258d/examples/viewer/opengl/k4astaticimageproperties.h#L88

**Comment by qm13** [comment]
There is no simple explanation to this as pixel saturation can vary by camera mode and environmental conditions. You should see valid values from 0 up to some number around 13500. The 65535 value indicates that the pixel was saturated.
