### ISSUE TITLE
Example project doesn't compile in a separate solution. 

### ISSUE THREAD

**Issue by hagorms** [microsoft/Azure-Kinect-Sensor-SDK#1288]
Dear developers, 
I tried to put the playback_external_sync example to a separate windows solution.
After I linked k4a.lib and k4arecord.lib I still have many link errors. 
I tried to link loger and other libraries so i reduced the number of link errors from 40 to 22. 
You can see attached screenshot with all linker errors.
Did I build release 1.4.x branch incorrectly? 
Do I need to specify some special flags in cmake? 

How to reproduce: 
Create a new solution on visual studio 2019 in windows 10. Put code from playback_external_sync example there, 
include "include" folder, 
link k4a.lib and k4a.record.lib. 
I can provide cmake archive if you need it. 
Best regards, 
Safroshkin Matvey 

![image](https://user-images.githubusercontent.com/12120066/87807070-1a2c2780-c858-11ea-9fc1-bdc633af95aa.png)

**Comment by qm13** [comment]
Have you setup the project correctly? What kind of project did you use? There are a bunch on none K4A issues.
