### ISSUE TITLE
Outdoor Kinect Usage

### ISSUE THREAD

**Issue by HungrySkeleton** [microsoft/Azure-Kinect-Sensor-SDK#1290]
Hello 

I was planning on using the kinect for outdoor usage are there any microsoft products or enclosures I can use to cool down the sensor I have looked at the specs of the kinect itself and it appears the operating range is around 10-25 degrees celsius.

**Comment by qm13** [comment]
We are not aware of any commercially available enclosures. Azure Kinect DK is not designed to work outdoors. You may experience IR interference from the sun.
