### ISSUE TITLE
[Firmware / Hardware] Some Kinect devices don't initialise via USB-C -> C 

### ISSUE THREAD

**Issue by 37** [microsoft/Azure-Kinect-Sensor-SDK#1294]
Hi, I think I've got a fun one for you. Sorry about the ticket length. 

I have identified an issue whereby some Azure Kinect devices will not attempt initialise when plugged in via USB-C to a machine that I have proven to work with other Azure Kinect devices. So far, I have found this issue presents in about 12 of 122 Kinect devices tested. 

The machines I'm using are Lattepanda Delta 432 units running Ubuntu 18.04. Unless I mention otherwise I am connecting and powering Kinects via USB-C on the host machine. 

The issue: 
If I plug a problematic Kinect into one of my Lattepanda boards sometimes no Kinect status light appears (totally blank; same behaviour as when you solely power via the DC-barrel jack without a USB) and no Microsoft devices appear in `lsusb`. 

```
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 8087:0aaa Intel Corp. 
Bus 001 Device 006: ID 2341:8036 Arduino SA Leonardo (CDC ACM, HID)
Bus 001 Device 005: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 004: ID 04e2:1410 Exar Corp. XR21V1410 USB-UART IC
Bus 001 Device 003: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 002: ID 1a2c:0e24 China Resource Semico Co., Ltd 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
I get the same output with no Kinect plugged in. 

Further, `dmesg -w` remains completely silent and it's as if no device is connected at all. I'll refer to this Kinect, and ones that demonstrate the same behaviour as 'problem Kinects'. 

Where this gets interesting is that with this exact same machine, I can plug in a different Kinect with the same usb and it will function perfectly. `lsusb` will show 5 devices, and I can use the sensor. 

Additionally, some machines work with *any* kinect, and 'problem Kinects' will always work with a laptop.  

I have spent today trying to debug this on 9 kinect devices, testing with 4 machines. 2 of the machines selected work with any Kinect, and two don't. *All 4 machines are the same Lattepanda model and have the same Intel usb host controller*. 

## Test machine information: 

Machine name | kernel
-- | --
Machine 1 | Linux blk1-c 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
Machine 2 | Linux blk1-h 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
Machine 3 | Linux hfm1-3 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
Machine 4 | Linux hfm1-4 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux | 

Note: I have no issue using any other usb-C device with these boards. I formatted and reflashed machine 4 and machine 1 to the latest kernel and saw no changes. 

## Test Kinect information: 

Kinect | RGB firmware | Depth firmware | Audio firmware | Build
-- | -- | -- | -- | --
A | 1.6.102 | 1.6.75 | 1.6.14 | Release
B | 1.6.102 | 1.6.75 | 1.6.14 | Release
C | 1.6.102 | 1.6.75 | 1.6.14 | Release
D | 1.6.102 | 1.6.75 | 1.6.14 | Release
E | 1.6.102 | 1.6.75 | 1.6.14 | Release
F | 1.6.102 | 1.6.75 | 1.6.14 | Release
G | 1.6.102 | 1.6.75 | 1.6.14 | Release
H | 1.6.102 | 1.6.75 | 1.6.14 | Release
I | 1.6.102 | 1.6.75 | 1.6.14 | Releas

## Testing standard usb-c. 
Plugging each kinect device into each host machine via usb-c for both power & data. Expected behaviour is the host machine showing 5 Microsoft devices from `lsusb | grep Microsoft`. 

Lattepanda | Kinect A | Kinect B | Kinect C | Kinect D | Kinect E | Kinect F | Kinect G | Kinect H | Kinect I
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Machine 1 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5
Machine 2 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5
Machine 3 | 5 | 0 | 0 | 0 | 0 | 0 | 5 | 5 | 5
Machine 4 | 5 | 0 | 0 | 0 | 0 | 0 | 5 | 5 | 5

Above: These numbers can be replicated and remain the same even if the usb is left in, machine rebooted, booted first then plugged in, etc. I've tried also endless USB combinations. 

## Testing  Direct DC power + USBC data 
Plugging each kinect device into each machine via usb-c for both power & data. Expected behaviour is a solid white status light on the Kinect.

Lattepanda | Kinect A | Kinect B | Kinect C | Kinect D | Kinect E | Kinect F | Kinect G | Kinect H | Kinect I
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Machine 1 | solid white | solid white | solid white | solid white | solid white | solid white | solid white | solid white | solid white
Machine 2 | solid white | solid white | solid white | solid white | solid white | solid white | solid white | solid white | solid white
Machine 3 | solid white | None | None | None | None | None | solid white | solid white | solid white
Machine 4 | solid white | None | None | None | None | None | solid white | solid white | solid white

Above: status light colours on the connected Kinect device. 

## Testing no DC power + USBA data cable
Just plugging each kinect into the host machine via USB-A > C. Expected behaviour is a flashing amber status light on Kinect.

Lattepanda | Kinect A | Kinect B | Kinect C | Kinect D | Kinect E | Kinect F | Kinect G | Kinect H | Kinect I
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Machine 1 | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber
Machine 2 | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber
Machine 3 | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber
Machine 4 | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber | Flasing amber

## Testing DC barrel jack cable + USB-A to C
Plugging each Kinect into a host machine via both USB-A power and USB-A > C data. Expected behaviour is the host machine showing 5 Microsoft devices from `lsusb | grep Microsoft`. 

Lattepanda | Kinect A | Kinect B | Kinect C | Kinect D | Kinect E | Kinect F | Kinect G | Kinect H | Kinect I
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Machine 1 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5
Machine 2 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5
Machine 3 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5
Machine 4 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5 | 5

Above: All Kinect devices work with all machines when powered and connected over two dedicated USB-A cables. This is a fine workaround for testing though unfortunately I need to use the machine's USB-C to run the Kinect for my application. I also need to use these Lattepanda boards.

It now appears to me that the problem lays within the USB-C on either Kinect or host machine. 

## Testing updating Kinect firmware 

I updated `Kinect B` a known 'problem' unit to the latest firmware (`AzureKinectDK_Fw_1.6.110079014` from #1206) and saw no change to sensor initialisation. 

Lattepanda | Kinect B (no change) | Kinect B (updated firmware) 
-- | -- | --
Machine 1 | 5 | 5
Machine 2 | 5 | 5
Machine 3 | 0 | 0
Machine 4 | 0 | 0

## Testing factory reset

I followed the instructions on factory resetting a Kinect found [here](https://docs.microsoft.com/en-us/azure/kinect-dk/reset-azure-kinect-dk) however it never seemed to work. I see recieve no amber light at step 7, and have tried this in a number of devices. 
> After about 3 seconds, the power indicator light changes to amber. After the light changes, release the reset button.

Any advice on what I might be doing wrong? 

## dmesg logs on tolerant machine with both normal and problem Kinects
I tried comparing the output from `dmesg -w` for Kinect A (normal) and Kinect B (problematic) on `machine 1`, which initialises all Kinects. 

Logs from plugging in Kinect A (normal): 
```
$ dmesg -w
[ 2182.959121] usb 2-6: new SuperSpeed Gen 1 USB device number 11 using xhci_hcd
[ 2182.982035] usb 2-6: New USB device found, idVendor=045e, idProduct=097a, bcdDevice= 1.27
[ 2182.982037] usb 2-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2182.982039] usb 2-6: Product: 4-Port USB 3.0 Hub
[ 2182.982041] usb 2-6: Manufacturer: Generic
[ 2182.982042] usb 2-6: SerialNumber: 000106794412
[ 2182.984355] hub 2-6:1.0: USB hub found
[ 2182.984746] hub 2-6:1.0: 2 ports detected
[ 2183.059004] usb 1-7.1: new high-speed USB device number 12 using xhci_hcd
[ 2183.083083] usb 1-7.1: New USB device found, idVendor=045e, idProduct=097b, bcdDevice= 1.27
[ 2183.083085] usb 1-7.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2183.083087] usb 1-7.1: Product: 4-Port USB 2.0 Hub
[ 2183.083088] usb 1-7.1: Manufacturer: Generic
[ 2183.083089] usb 1-7.1: SerialNumber: 000106794412
[ 2183.083857] hub 1-7.1:1.0: USB hub found
[ 2183.084074] hub 1-7.1:1.0: 4 ports detected
[ 2183.275066] usb 2-6.2: new SuperSpeed Gen 1 USB device number 12 using xhci_hcd
[ 2183.295770] usb 2-6.2: New USB device found, idVendor=045e, idProduct=097c, bcdDevice= 1.00
[ 2183.295772] usb 2-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2183.295774] usb 2-6.2: Product: Azure Kinect Depth Camera
[ 2183.295775] usb 2-6.2: Manufacturer: Microsoft
[ 2183.295777] usb 2-6.2: SerialNumber: 000106794412
[ 2183.379007] usb 1-7.1.3: new high-speed USB device number 13 using xhci_hcd
[ 2183.399743] usb 1-7.1.3: New USB device found, idVendor=045e, idProduct=097e, bcdDevice= 1.06
[ 2183.399745] usb 1-7.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2183.399746] usb 1-7.1.3: Product: Azure Kinect Microphone Array
[ 2183.399748] usb 1-7.1.3: Manufacturer: Microsoft Corporation.
[ 2183.399749] usb 1-7.1.3: SerialNumber: 000106794412
[ 2183.402911] hid-generic 0003:045E:097E.0005: hiddev0,hidraw1: USB HID v1.11 Device [Microsoft Corporation. Azure Kinect Microphone Array] on usb-0000:00:15.0-7.1.3/input2
[ 2183.559073] usb 2-6.1: new SuperSpeed Gen 1 USB device number 13 using xhci_hcd
[ 2183.583500] usb 2-6.1: Isoc endpoint with wBytesPerInterval of 1024 in config 1 interface 1 altsetting 4 ep 129: setting to 944
[ 2183.583888] usb 2-6.1: New USB device found, idVendor=045e, idProduct=097d, bcdDevice= 0.0c
[ 2183.583890] usb 2-6.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2183.583891] usb 2-6.1: Product: Azure Kinect 4K Camera
[ 2183.583893] usb 2-6.1: Manufacturer: Microsoft
[ 2183.583894] usb 2-6.1: SerialNumber: 000106794412
[ 2183.586282] uvcvideo: Found UVC 1.00 device Azure Kinect 4K Camera (045e:097d)
[ 2183.586407] uvcvideo: Failed to query (GET_INFO) UVC control 3 on unit 1: -32 (exp. 1).
[ 2183.588273] uvcvideo: Failed to set UVC probe control : -32 (exp. 26).
[ 2183.591507] uvcvideo 2-6.1:1.0: Entity type for entity Extension 2 was not initialized!
[ 2183.591510] uvcvideo 2-6.1:1.0: Entity type for entity Extension 6 was not initialized!
[ 2183.591512] uvcvideo 2-6.1:1.0: Entity type for entity Extension 5 was not initialized!
[ 2183.591513] uvcvideo 2-6.1:1.0: Entity type for entity Processing 3 was not initialized!
[ 2183.591515] uvcvideo 2-6.1:1.0: Entity type for entity Camera 1 was not initialized!
[ 2183.591603] input: Azure Kinect 4K Camera as /devices/pci0000:00/0000:00:15.0/usb2/2-6/2-6.1/2-6.1:1.0/input/input18

```

Logs from plugging in Kinect B (problematic): 

```
$ dmesg -w
[ 1820.323106] usb 2-6: new SuperSpeed Gen 1 USB device number 8 using xhci_hcd
[ 1820.345997] usb 2-6: New USB device found, idVendor=045e, idProduct=097a, bcdDevice= 1.27
[ 1820.345999] usb 2-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1820.346000] usb 2-6: Product: 4-Port USB 3.0 Hub
[ 1820.346002] usb 2-6: Manufacturer: Generic
[ 1820.346003] usb 2-6: SerialNumber: 000426201212
[ 1820.348241] hub 2-6:1.0: USB hub found
[ 1820.348625] hub 2-6:1.0: 2 ports detected
[ 1820.422995] usb 1-7.1: new high-speed USB device number 10 using xhci_hcd
[ 1820.446660] usb 1-7.1: New USB device found, idVendor=045e, idProduct=097b, bcdDevice= 1.27
[ 1820.446662] usb 1-7.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1820.446663] usb 1-7.1: Product: 4-Port USB 2.0 Hub
[ 1820.446665] usb 1-7.1: Manufacturer: Generic
[ 1820.446666] usb 1-7.1: SerialNumber: 000426201212
[ 1820.447569] hub 1-7.1:1.0: USB hub found
[ 1820.447782] hub 1-7.1:1.0: 4 ports detected
[ 1820.734997] usb 1-7.1.3: new high-speed USB device number 11 using xhci_hcd
[ 1820.755820] usb 1-7.1.3: New USB device found, idVendor=045e, idProduct=097e, bcdDevice= 1.06
[ 1820.755822] usb 1-7.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1820.755824] usb 1-7.1.3: Product: Azure Kinect Microphone Array
[ 1820.755825] usb 1-7.1.3: Manufacturer: Microsoft Corporation.
[ 1820.755827] usb 1-7.1.3: SerialNumber: 000426201212
[ 1820.759171] hid-generic 0003:045E:097E.0004: hiddev0,hidraw1: USB HID v1.11 Device [Microsoft Corporation. Azure Kinect Microphone Array] on usb-0000:00:15.0-7.1.3/input2
[ 1820.847067] usb 2-6.2: new SuperSpeed Gen 1 USB device number 9 using xhci_hcd
[ 1820.867723] usb 2-6.2: New USB device found, idVendor=045e, idProduct=097c, bcdDevice= 1.00
[ 1820.867725] usb 2-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1820.867727] usb 2-6.2: Product: Azure Kinect Depth Camera
[ 1820.867729] usb 2-6.2: Manufacturer: Microsoft
[ 1820.867730] usb 2-6.2: SerialNumber: 000426201212
[ 1821.111055] usb 2-6.1: new SuperSpeed Gen 1 USB device number 10 using xhci_hcd
[ 1821.131495] usb 2-6.1: Isoc endpoint with wBytesPerInterval of 1024 in config 1 interface 1 altsetting 4 ep 129: setting to 944
[ 1821.131864] usb 2-6.1: New USB device found, idVendor=045e, idProduct=097d, bcdDevice= 0.0c
[ 1821.131865] usb 2-6.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1821.131867] usb 2-6.1: Product: Azure Kinect 4K Camera
[ 1821.131869] usb 2-6.1: Manufacturer: Microsoft
[ 1821.131870] usb 2-6.1: SerialNumber: 000426201212
[ 1821.134129] uvcvideo: Found UVC 1.00 device Azure Kinect 4K Camera (045e:097d)
[ 1821.134257] uvcvideo: Failed to query (GET_INFO) UVC control 3 on unit 1: -32 (exp. 1).
[ 1821.136083] uvcvideo: Failed to set UVC probe control : -32 (exp. 26).
[ 1821.139374] uvcvideo 2-6.1:1.0: Entity type for entity Extension 2 was not initialized!
[ 1821.139376] uvcvideo 2-6.1:1.0: Entity type for entity Extension 6 was not initialized!
[ 1821.139377] uvcvideo 2-6.1:1.0: Entity type for entity Extension 5 was not initialized!
[ 1821.139379] uvcvideo 2-6.1:1.0: Entity type for entity Processing 3 was not initialized!
[ 1821.139380] uvcvideo 2-6.1:1.0: Entity type for entity Camera 1 was not initialized!
[ 1821.139469] input: Azure Kinect 4K Camera as /devices/pci0000:00/0000:00:15.0/usb2/2-6/2-6.1/2-6.1:1.0/input/input17

```

These outputs read almost identically, with the only deviation being the order of device initialisation. 
I was expecting some difference or warning from the problematic Kinect, but it starts as normal. 

## dmesg logs on picky machine with both normal and problem Kinects

Logs from plugging in Kinect A (normal): 
```
$ dmesg -w
[ 2272.606958] usb 1-7.1: new high-speed USB device number 22 using xhci_hcd
[ 2272.710682] usb 1-7.1: New USB device found, idVendor=045e, idProduct=097b, bcdDevice= 1.27
[ 2272.710685] usb 1-7.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2272.710688] usb 1-7.1: Product: 4-Port USB 2.0 Hub
[ 2272.710690] usb 1-7.1: Manufacturer: Generic
[ 2272.710691] usb 1-7.1: SerialNumber: 000106794412
[ 2272.711608] hub 1-7.1:1.0: USB hub found
[ 2272.711828] hub 1-7.1:1.0: 4 ports detected
[ 2272.835083] usb 2-6: new SuperSpeed Gen 1 USB device number 24 using xhci_hcd
[ 2272.857960] usb 2-6: New USB device found, idVendor=045e, idProduct=097a, bcdDevice= 1.27
[ 2272.857963] usb 2-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2272.857965] usb 2-6: Product: 4-Port USB 3.0 Hub
[ 2272.857967] usb 2-6: Manufacturer: Generic
[ 2272.857969] usb 2-6: SerialNumber: 000106794412
[ 2272.860180] hub 2-6:1.0: USB hub found
[ 2272.860416] hub 2-6:1.0: 2 ports detected
[ 2272.998962] usb 1-7.1.3: new high-speed USB device number 23 using xhci_hcd
[ 2273.103637] usb 1-7.1.3: New USB device found, idVendor=045e, idProduct=097e, bcdDevice= 1.06
[ 2273.103639] usb 1-7.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2273.103641] usb 1-7.1.3: Product: Azure Kinect Microphone Array
[ 2273.103643] usb 1-7.1.3: Manufacturer: Microsoft Corporation.
[ 2273.103645] usb 1-7.1.3: SerialNumber: 000106794412
[ 2273.107601] hid-generic 0003:045E:097E.000B: hiddev0,hidraw2: USB HID v1.11 Device [Microsoft Corporation. Azure Kinect Microphone Array] on usb-0000:00:15.0-7.1.3/input2
[ 2273.183034] usb 2-6.2: new SuperSpeed Gen 1 USB device number 25 using xhci_hcd
[ 2273.203788] usb 2-6.2: New USB device found, idVendor=045e, idProduct=097c, bcdDevice= 1.00
[ 2273.203790] usb 2-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2273.203793] usb 2-6.2: Product: Azure Kinect Depth Camera
[ 2273.203795] usb 2-6.2: Manufacturer: Microsoft
[ 2273.203796] usb 2-6.2: SerialNumber: 000106794412
[ 2273.427018] usb 2-6.1: new SuperSpeed Gen 1 USB device number 26 using xhci_hcd
[ 2273.447439] usb 2-6.1: Isoc endpoint with wBytesPerInterval of 1024 in config 1 interface 1 altsetting 4 ep 129: setting to 944
[ 2273.447770] usb 2-6.1: New USB device found, idVendor=045e, idProduct=097d, bcdDevice= 0.0c
[ 2273.447772] usb 2-6.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2273.447774] usb 2-6.1: Product: Azure Kinect 4K Camera
[ 2273.447776] usb 2-6.1: Manufacturer: Microsoft
[ 2273.447777] usb 2-6.1: SerialNumber: 000106794412
[ 2273.450275] uvcvideo: Found UVC 1.00 device Azure Kinect 4K Camera (045e:097d)
[ 2273.450515] uvcvideo: Failed to query (GET_INFO) UVC control 3 on unit 1: -32 (exp. 1).
[ 2273.452331] uvcvideo: Failed to set UVC probe control : -32 (exp. 26).
[ 2273.455652] uvcvideo 2-6.1:1.0: Entity type for entity Extension 2 was not initialized!
[ 2273.455655] uvcvideo 2-6.1:1.0: Entity type for entity Extension 6 was not initialized!
[ 2273.455657] uvcvideo 2-6.1:1.0: Entity type for entity Extension 5 was not initialized!
[ 2273.455659] uvcvideo 2-6.1:1.0: Entity type for entity Processing 3 was not initialized!
[ 2273.455661] uvcvideo 2-6.1:1.0: Entity type for entity Camera 1 was not initialized!
[ 2273.455776] input: Azure Kinect 4K Camera as /devices/pci0000:00/0000:00:15.0/usb2/2-6/2-6.1/2-6.1:1.0/input/input25

```
Logs from plugging in Kinect B (problematic): 
```
dmesg -w
... nothing happens when device is plugged in

sudo tail -n 0 -f /var/log/syslog
... nothing happens when device is plugged in

... :shrug:

```

Expected output: some kind of error message when plugging in Kinect B. 

Given that both `lsusb` and `dmesg -w` will output nothing when a problem Kinect (ie. B) is plugged in, it's as if the device was never plugged in and simply doesn't exist.

I suspected this problem could possibly be induced by some cooked BIOS settings, ie. xhci, usb, or pci settings; and that could explain why some machines work and other don't (ie. different BIOS settings between Machines). However, I updated the bios to the same version on all boards and still experienced the same thing. 

I feel like the issue might be based in how the two devices are negotiating a host/client relationship when plugged in - ie. there's some trickery around poor resistor tolerances stacking-up within the Lattepanda USB-C port or within the Kinect's internal USB 3.0 hub. Or both, so the Kinects are just refusing to communicate with the host machine.

If the problem was solely within the Lattepanda usb-c port I assume that other Kinects or usb-c devices wouldn't work with that port, or if it was a driver issue I'd get _some_ kind of error through syslog. 

I don't know why Kinect B would work with (lattepanda#2) but not (lattepanda#3), or why (lattepanda#3) will work with Kinect A but not Kinect B. Meanwhile (lattepanda#2) works with all Kinects, and (Kinect A) works with all lattepandas. :white_flag: :shrug:  

Any help or advice on what to try next would be greatly appreciated!

**Comment by 37** [comment]
Hey @qm13 if you want me to post you some of the hardware that I've found issues with let me know. Happy to do so if it'll help in debugging :surfer:

**Comment by qm13** [comment]
Handling offline
