### ISSUE TITLE
Kinect Operating Outside of Temperature Range

### ISSUE THREAD

**Issue by HungrySkeleton** [microsoft/Azure-Kinect-Sensor-SDK#1297]
Hello Kinect Team,

I wanted a follow up with what happens when a kinect is operating outside of its temperature range. I am planning to use the kinect in an indoor environment where it is relatively hot I was wondering what kind of effects does temperature have on our RGB,IR,Depth and other readings is there a risk of damage if it operates slightly hot outside of it's prescribed range. Or will it be okay to operate the kinect in that hot environment as long as I can provide it the necessary cooling to keep it in the 10-25C range. 

Is it possible for you guys to suggest an ideal operating temperature so we can develop a script that will try to automate our temperature monitoring and keep the device in those ideal conditions.

**Comment by qm13** [comment]
@HungrySkeleton Azure Kinect is a developer kit. Microsoft has not run extended reliability tests on the device outside the published range. You are ok so long as you keep the device within the published temperature range. Some developers have performed controlled tests to correlate the loaded (dictated by your use case (eg. NFOV unbinned at 30 fps + RGB 1080p at 30 fps + IMU) steady state internal temperature with a 25 degC external temperature and designed systems to keep the internal temperature below that maximum loaded steady state.
