### ISSUE TITLE
Too many IMU samples are captured

### ISSUE THREAD

**Issue by darglein** [microsoft/Azure-Kinect-Sensor-SDK#1300]
Hello,
I'm currently trying to make use of the IMU data when I realized that there are too many IMU samples captured. I have set the camera to 30FPS 720p and read all IMU samples until the timestamp of the image is reached. In average it records around 56 samples for every frame, which corresponds to and IMU frequency of 56*30 = 1680Hz. This seems a bit much as the spec states an IMU frequency of 200Hz.

The code is as following:
```
    // Init
    k4a_device_configuration_t config = K4A_DEVICE_CONFIG_INIT_DISABLE_ALL;
    config.color_format               = K4A_IMAGE_FORMAT_COLOR_BGRA32;
    config.color_resolution           = K4A_COLOR_RESOLUTION_720P;
    config.depth_mode                 = K4A_DEPTH_MODE_NFOV_2X2BINNED;
    config.camera_fps                 = K4A_FRAMES_PER_SECOND_30;
    config.synchronized_images_only   = true;

    device.start_cameras(&config);
    device.start_imu();
    calibration = device.get_calibration(config.depth_mode, config.color_resolution);
```
 ```
   // Capture (called in a loop)
   k4a::capture capture;


    if (!device.get_capture(&capture, std::chrono::milliseconds(1000)))
    {
        std::cout << "Capture Timeout" << std::endl;
        return false;
    }


    k4a::image k4a_color = capture.get_color_image();
    k4a::image k4a_depth = capture.get_depth_image();

    double t_color = k4a_color.get_device_timestamp().count() / (1000.0 * 1000.0);
    //    double t_depth = k4a_depth.get_device_timestamp().count() / (1000.0 * 1000.0);

    data.timeStamp = t_color;


    std::vector<Imu::Data> imu_data;
    while (true)
    {
        k4a_imu_sample_t imu_sample;
        // if (device.get_imu_sample(&imu_sample, std::chrono::milliseconds(0)))
        if (device.get_imu_sample(&imu_sample, std::chrono::milliseconds(K4A_WAIT_INFINITE)))
        {
            Imu::Data sample;
            sample.timestamp = imu_sample.gyro_timestamp_usec / (1000.0 * 1000);


            sample.acceleration =
                Vec3(imu_sample.acc_sample.xyz.x, imu_sample.acc_sample.xyz.y, imu_sample.acc_sample.xyz.z);

            sample.omega =
                Vec3(imu_sample.gyro_sample.xyz.x, imu_sample.gyro_sample.xyz.y, imu_sample.gyro_sample.xyz.z);

            //            std::cout << sample << std::endl;
            imu_data.push_back(sample);

            if (sample.timestamp >= t_color)
            {
                break;
            }
        }
        else
        {
            break;
        }
    }
    std::cout << "imu data size: " << imu_data.size() << " Imu frequency: " << imu_data.size() * 30 << std::endl;

```
The individual IMU samples seem correct, as they contain valid values with timestamps, which also indicates a too large frequency. Example timestamps:

> color t 2.40183 imu t 2.36927
> color t 2.40183 imu t 2.36985
> color t 2.40183 imu t 2.37046
> color t 2.40183 imu t 2.37104
> color t 2.40183 imu t 2.37164
> color t 2.40183 imu t 2.37223
> color t 2.40183 imu t 2.37282
> color t 2.40183 imu t 2.37342
> color t 2.40183 imu t 2.37401
> color t 2.40183 imu t 2.37461
> color t 2.40183 imu t 2.3752
> color t 2.40183 imu t 2.3758
> color t 2.40183 imu t 2.37639
> color t 2.40183 imu t 2.37699
> color t 2.40183 imu t 2.37758
> color t 2.40183 imu t 2.37817
> color t 2.40183 imu t 2.37877
> color t 2.40183 imu t 2.37935
> color t 2.40183 imu t 2.37995
> color t 2.40183 imu t 2.38054
> color t 2.40183 imu t 2.38114
> color t 2.40183 imu t 2.38173
> color t 2.40183 imu t 2.38232
> color t 2.40183 imu t 2.38292
> color t 2.40183 imu t 2.38351
> color t 2.40183 imu t 2.38411
> color t 2.40183 imu t 2.3847
> color t 2.40183 imu t 2.3853
> color t 2.40183 imu t 2.38589
> color t 2.40183 imu t 2.38649
> color t 2.40183 imu t 2.38708
> color t 2.40183 imu t 2.38767
> color t 2.40183 imu t 2.38827
> color t 2.40183 imu t 2.38885
> color t 2.40183 imu t 2.38945
> color t 2.40183 imu t 2.39004
> color t 2.40183 imu t 2.39064
> color t 2.40183 imu t 2.39123
> color t 2.40183 imu t 2.39182
> color t 2.40183 imu t 2.39242
> color t 2.40183 imu t 2.39301
> color t 2.40183 imu t 2.39361
> color t 2.40183 imu t 2.3942
> color t 2.40183 imu t 2.3948
> color t 2.40183 imu t 2.39539
> color t 2.40183 imu t 2.39599
> color t 2.40183 imu t 2.39658
> color t 2.40183 imu t 2.39718
> color t 2.40183 imu t 2.39777
> color t 2.40183 imu t 2.39836
> color t 2.40183 imu t 2.39895
> color t 2.40183 imu t 2.39954
> color t 2.40183 imu t 2.40014
> color t 2.40183 imu t 2.40073
> color t 2.40183 imu t 2.40133
> color t 2.40183 imu t 2.40192
> imu data size: 56 Imu frequency: 1680
> color t 2.43518 imu t 2.40251
> color t 2.43518 imu t 2.40311
> color t 2.43518 imu t 2.4037
> color t 2.43518 imu t 2.4043
> color t 2.43518 imu t 2.40489
> color t 2.43518 imu t 2.40549
> color t 2.43518 imu t 2.40608
> color t 2.43518 imu t 2.40668
> color t 2.43518 imu t 2.40727
> color t 2.43518 imu t 2.40786
> color t 2.43518 imu t 2.40846
> color t 2.43518 imu t 2.40904
> color t 2.43518 imu t 2.40964
> color t 2.43518 imu t 2.41023
> color t 2.43518 imu t 2.41083
> color t 2.43518 imu t 2.41142
> color t 2.43518 imu t 2.41201
> color t 2.43518 imu t 2.41261
> color t 2.43518 imu t 2.4132
> color t 2.43518 imu t 2.4138
> color t 2.43518 imu t 2.41439
> color t 2.43518 imu t 2.41499
> color t 2.43518 imu t 2.41558
> color t 2.43518 imu t 2.41618
> color t 2.43518 imu t 2.41677
> color t 2.43518 imu t 2.41737
> color t 2.43518 imu t 2.41796
> color t 2.43518 imu t 2.41854
> color t 2.43518 imu t 2.41914
> color t 2.43518 imu t 2.41973
> color t 2.43518 imu t 2.42033
> color t 2.43518 imu t 2.42092
> color t 2.43518 imu t 2.42151
> color t 2.43518 imu t 2.42211
> color t 2.43518 imu t 2.4227
> color t 2.43518 imu t 2.4233
> color t 2.43518 imu t 2.42389
> color t 2.43518 imu t 2.42449
> color t 2.43518 imu t 2.42508
> color t 2.43518 imu t 2.42568
> color t 2.43518 imu t 2.42627
> color t 2.43518 imu t 2.42687
> color t 2.43518 imu t 2.42746
> color t 2.43518 imu t 2.42804
> color t 2.43518 imu t 2.42864
> color t 2.43518 imu t 2.42923
> color t 2.43518 imu t 2.42983
> color t 2.43518 imu t 2.43042
> color t 2.43518 imu t 2.43102
> color t 2.43518 imu t 2.43161
> color t 2.43518 imu t 2.43221
> color t 2.43518 imu t 2.4328
> color t 2.43518 imu t 2.43339
> color t 2.43518 imu t 2.43399
> color t 2.43518 imu t 2.43458
> color t 2.43518 imu t 2.43518
> imu data size: 56 Imu frequency: 1680

**Desktop:**
 - OS with Version: Ubuntu 20.04
 - SDK Version:  1.41
 - Firmware version:  rgb 1.6.110

**Comment by qm13** [comment]
@darglein your data is correct. The actual IMU read rate is 1666 kHz. The samples are batched and passed to the host compute at 200 Hz.
