### ISSUE TITLE
Depth Errors on Semi-Translucent Objects

### ISSUE THREAD

**Issue by thane** [microsoft/Azure-Kinect-Sensor-SDK#1305]
**Description**
I'm trying to find the height of stacks of lab wellplates.  These plates are made of clear poly-polypropylene plastic and are covered with a semi-translucent silicone mat:
![2D](https://user-images.githubusercontent.com/1294039/89221661-42768e80-d599-11ea-82c2-3df81498f4f5.png)
However, the stacks of plates look sunken into the ground in the depth image:
![Bad](https://user-images.githubusercontent.com/1294039/89221686-502c1400-d599-11ea-9cb1-81afe6c414b9.png)
When I cover each of the stacks with an index card, the depth image looks as expected: 
![Good](https://user-images.githubusercontent.com/1294039/89221691-54583180-d599-11ea-8bc2-9fdf6cf98252.png)
Do you have any tips for improving the depth camera performance in this case?  The depth image looks great when looking at other objects, so I was surprised about how poorly it worked on the wellplate.  I submitted a report to the Microsoft's support line and was asked to post here.  

After some further reading, it looks like silicone is relatively transparent to IR.  I assume that is what's causing this, but wanted to see if anyone had any further ideas.

**Desktop (please complete the following information):**
 - OS with Version: Windows 18362
 - SDK Version:  
 - Current Firmware Versions:
  RGB camera firmware:      1.6.110
  Depth camera firmware:    1.6.79
  Depth config file:        6109.7
  Audio firmware:           1.6.14

**Comment by qm13** [comment]
@thane what you are seeing is a combination of multipath and subsurface scattering. This is a limitation of current ToF depth technology.
