### ISSUE TITLE
OpenGL Shading Language Version Error

### ISSUE THREAD

**Issue by 0707yiliu** [microsoft/Azure-Kinect-Sensor-SDK#1307]
**Describe the bug**

I can start-up Azure Kinect Viewer. But when I run simple_3D_bady_tracker, it prints a error:
Shader Error: 0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

I get my OpenGL SL version as follow, is it meaning that  my GLSL version is higher than its request??
**Screenshots**

![Screenshot from 2020-08-04 20-49-58](https://user-images.githubusercontent.com/28921533/89365068-73c09d00-d706-11ea-9f15-0d740c918275.png)

**Desktop (please complete the following information):**
 - OS with Version:  Ubuntu 18.04
 - SDK Version:   Azure-Kinect-Sensor-SDK 1.3.0 Body.exe from `sudo apt install libk4abt1.0-dev`

**Comment by qm13** [comment]
Make sure you have the latest NVIDIA driver installed for you graphics card. It should also install the supported version of OpenGL.

**Comment by angelicaCruz** [comment]
I am running to the same error but I am running the body tracker on CPU only mode. Is there a way to solve it?
