### ISSUE TITLE
1 Kinect Azure works other does not, get: "failed to start device"

### ISSUE THREAD

**Issue by GrahamDClark** [microsoft/Azure-Kinect-Sensor-SDK#1310]
Both Kinect Azures worked until recently.
1 works fine.
In Azure Kinect Viewer, the other in Azure Kinect Viewer sometimes doesn't show up in list of devices at all, or says "Failed to start device, you must close and reopen the device".
After doing that and Refreshing Devices, nothing shows up (except the other camera if plugged in).

On Windows PC. 
Azure Kinect Viewer firmware is up to date.

Tried on second PC, with Azure Kinect Viewer, same message, so it's likely a hardware issue.
Microphone data shows up in Azure Kinect Viewer, no imagery.
The other Kinect Azure works fine on both PCs.

hard reset the kinect azure, same issues

Here is the log from when it does show up in the device list (but no image):

[ error    ] : usb_cmd_io(). Command(00000022) sequence ended in failure, TransactionId 55555555 == 0000000A Response size 0x00000010 == 0x00000010 Packet status 0x55555555 == 0x00000000 Packet type 0x55555555 == 0x0a6fe000
[ error    ] : usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, p_data, data_size, NULL, 0, bytes_read, &cmd_status) returned failure in usb_cmd_read()
[ error    ] : usb_cmd_read( depthmcu->usb_cmd, DEV_CMD_NV_DATA_GET, (uint8_t *)&nv_tag, sizeof(nv_tag), calibration, cal_size, bytes_read) returned failure in depthmcu_get_cal()
[ error    ] : depthmcu_get_cal(depth->depthmcu, depth->calibration_memory, DEPTH_CALIBRATION_DATA_SIZE, &depth->calibration_memory_size) returned failure in depth_start()
[ error    ] : usb_cmd_io(). Command(000000F2) sequence ended in failure, TransactionId 55555555 == 0000000B Response size 0x00000010 == 0x00000010 Packet status 0x55555555 == 0x00000000 Packet type 0x55555555 == 0x0a6fe000
[ error    ] : usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, NULL, 0, p_data, data_size, NULL, cmd_status) returned failure in usb_cmd_write_with_status()
[ error    ] : usb_cmd_write_with_status(depthmcu->usb_cmd, DEV_CMD_DEPTH_STREAM_STOP, NULL, 0, NULL, 0, &cmd_status) returned failure in depthmcu_depth_stop_streaming()
[ error    ] : usb_cmd_io(). Command(0000000A) sequence ended in failure, TransactionId 55555555 == 0000000C Response size 0x00000010 == 0x00000010 Packet status 0x55555555 == 0x00000000 Packet type 0x55555555 == 0x0a6fe000
[ error    ] : usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, NULL, 0, p_data, data_size, NULL, cmd_status) returned failure in usb_cmd_write_with_status()
[ error    ] : usb_cmd_write_with_status(depthmcu->usb_cmd, DEV_CMD_DEPTH_STOP, NULL, 0, NULL, 0, &cmd_status) returned failure in depthmcu_depth_stop_streaming()
[ error    ] : depth_start(device->depth, config) returned failure in k4a_device_start_cameras()
[ error    ] : usb_cmd_io(). Command(00000115) sequence ended in failure, TransactionId 00000000 == 00000000 Response size 0x0000000C == 0x00000010 Packet status 0x00000000 == 0x00000000 Packet type 0x0a6fe000 == 0x0a6fe000
[ error    ] : usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, p_data, data_size, NULL, 0, bytes_read, &cmd_status) returned failure in usb_cmd_read()
[ error    ] : usb_cmd_read(depthmcu->usb_cmd, DEV_CMD_DEPTH_READ_PRODUCT_SN, NULL, 0, (uint8_t *)temp_serial_number, sizeof(temp_serial_number) - 1 , &bytes_read) returned failure in depthmcu_get_serialnum()
[ error    ] : depthmcu_get_serialnum(device->depthmcu, serial_number, &serial_number_size) != K4A_BUFFER_RESULT_SUCCEEDED returned failure in k4a_device_open()
[ error    ] : usb_cmd_io(). Command(00000115) sequence ended in failure, TransactionId 00000000 == 00000000 Response size 0x0000000C == 0x00000010 Packet status 0x00000000 == 0x00000000 Packet type 0x0a6fe000 == 0x0a6fe000
[ error    ] : usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, p_data, data_size, NULL, 0, bytes_read, &cmd_status) returned failure in usb_cmd_read()
[ error    ] : usb_cmd_read(depthmcu->usb_cmd, DEV_CMD_DEPTH_READ_PRODUCT_SN, NULL, 0, (uint8_t *)temp_serial_number, sizeof(temp_serial_number) - 1 , &bytes_read) returned failure in depthmcu_get_serialnum()
[ error    ] : depthmcu_get_serialnum(device->depthmcu, serial_number, &serial_number_size) != K4A_BUFFER_RESULT_SUCCEEDED returned failure in k4a_device_open()
 
What should I do, seems like hardware failure? I have no idea how to send it back as microsoft website offers no contact for that I can easily find. Is there a contact for that?
Thank you

**Comment by qm13** [comment]
@GrahamDClark you can find Azure Kinect support info here https://docs.microsoft.com/en-us/azure/kinect-dk/support

You need to complete this form https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=f77b1b95-721e-43a0-2db8-b01e81a3f813

**Comment by GrahamDClark** [comment]
Thank you!
