### ISSUE TITLE
Body tracking in target region

### ISSUE THREAD

**Issue by Vaasu143** [microsoft/Azure-Kinect-Sensor-SDK#1311]
Hello experts,

First of all, this is not a bug. I am trying to find body tracking in the defined region of whole area. Unfortunately don't know where can I find the co-ordinates to define the target region in the whole sensor region. Is there any setting to be done in K4a library to define this.

**Comment by qm13** [comment]
You can find info on body tracking coordinates here https://docs.microsoft.com/en-us/azure/Kinect-dk/body-joints
You can find info on the camera coordinate system here https://docs.microsoft.com/en-us/azure/Kinect-dk/coordinate-systems
