### ISSUE TITLE
IR Laser glare/reflection

### ISSUE THREAD

**Issue by kramakr4** [microsoft/Azure-Kinect-Sensor-SDK#1314]
Hi,

I am trying to place the Kinect in a box made of quartz. Fused silica (quartz) is known to be transparent to IR radiation in the range at which Kinect's IR Laser operates. However, when I use the NFOV or WFOV modes I see a reflection of the IR radiation on the quartz surface. However, this does not happen in Passive IR mode. So, I assume this is the laser light being reflected. Any way to get around this?
![With_Quartz](https://user-images.githubusercontent.com/69551017/89959618-b6481500-dbf1-11ea-9437-1f9690f6452b.JPG)
![Without_Quartz](https://user-images.githubusercontent.com/69551017/89959622-b8aa6f00-dbf1-11ea-9269-548cd5d52bc5.JPG)

**Comment by qm13** [comment]
You are likely seeing reflection between the camera window and quartz. We recommend not putting any window in front of the Azure Kinect window.
