### ISSUE TITLE
opencv-kinfu-samples must enable OPENCV_ENABLE_NONFREE

### ISSUE THREAD

**Issue by qm13** [microsoft/Azure-Kinect-Sensor-SDK#1315]
[Moved from user feedback site]

Can I use the opencv-kinfu-samples including dependencies in a commercial product?

**Comment by qm13** [comment]
MIT license. Yes, you are free to use the sample code in a commercial product.

**Comment by UnaNancyOwen** [comment]
@qm13 What do you think about the patent of Kinect Fusion?
https://docs.opencv.org/4.4.0/d8/d1f/classcv_1_1kinfu_1_1KinFu.html#details
```
Note that the KinectFusion algorithm was patented and its use may be restricted by the list of patents mentioned in README.md file in this module directory.
```
