### ISSUE TITLE
Kinect Azure device with Jetson Nano - error [libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12]

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [microsoft/Azure-Kinect-Sensor-SDK#1316]
**Describe the bug**

I am trying to use Kinect Azure with Jetson Nano device. I am able to start the k4aviewer and can visualize the output of the camera, but in the meantime I get the following error `libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12
` 
**Expected behavior**

Run the k4aviewer while it is connected to Kinect Azure device.

`~/Azure-Kinect-Sensor-SDK$ ./build/bin/k4aviewer`
`libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12`
`libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12`
`libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12`
`libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12`

Kindly let me know if you need more information. Thanks

**Comment by qm13** [comment]
See bug #485 

You need to increase the value of `usbfs_memory_mb`
