### ISSUE TITLE
synchronized capturing with 3 devices

### ISSUE THREAD

**Issue by f-pfeiffer** [microsoft/Azure-Kinect-Sensor-SDK#1323]
Hi,

I'm looking for a solution to capture synchronized videos/images with 3 Azure Kinect Sensors.
The green screen example (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/green_screen) includes synchronization and calibration of two devices. Is there also any similar solution for 3 devices?

**Comment by qm13** [comment]
It should be pretty simple to extend the 2 camera implementation in green screen sample to three cameras.
