### ISSUE TITLE
Any c# specific documentation available?

### ISSUE THREAD

**Issue by nicobeek** [microsoft/Azure-Kinect-Sensor-SDK#1325]
While browsing through the functions at https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/index.html
I noticed the k4a_device_get_color_control_capabilities() function listed under C. In the C# assembly I can only find a Device.GetColorControl and Device.SetColorControl. Are there any other functions not available in C#, and is there a C# specific documentation available? The link only has C and C++ documentation.

Thanks!
Nico

**Comment by qm13** [comment]
You can find the C# documentation [here](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/namespace_microsoft_1_1_azure_1_1_kinect_1_1_sensor.html)

**Comment by rcffc** [comment]
@qm13 Thanks, it was quite hard to find.

**Comment by qm13** [comment]
Added links in troubleshooting section of the documentation.
