### ISSUE TITLE
Body tracking inaccurate for some people's back

### ISSUE THREAD

**Issue by Piler-Tam** [microsoft/Azure-Kinect-Sensor-SDK#1330]
I am developing a rock climbing game with Azure Kinect.

I notice that some people are well tracked and some are not. They body keep flipping and it looks like it cannot determine whether the person is front facing/not facing to the camera. I just wonder why it happens.

Is it matter with the height of the person? or the clothes?

**Comment by qm13** [comment]
@Piler-Tam could you post some examples where you are seeing flipping.
