### ISSUE TITLE
Add pulseaudio as dependency on Ubuntu

### ISSUE THREAD

**Issue by 12101111** [microsoft/Azure-Kinect-Sensor-SDK#1337]
**Describe the bug**

I installed `k4a-tools` on a Ubuntu 18.04 arm64 device which pulseaudio is not installed at first.

`k4aviewer` try to connect to pulseaudio then crash.

**To Reproduce**

1. Uninstall `pulseaudio`
2. install `k4a-tools`
3. run `k4aviewer`

```
han@agx ~> k4aviewer
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

fish: 'k4aviewer' terminated by signal SIGSEGV (Address boundary error)

```

**Expected behavior**

Add pulseaudio as dependency to install it automatically

**Desktop (please complete the following information):**
 - OS with Version: 18.04.5 LTS arm64
 - SDK Version: 1.4.1
 - Firmware version:  

**Additional context**

**Comment by qm13** [comment]
The Sensor SDK has a dependency on libsoundio. I quick grep on the code does not find any dependency on pulseaudio.
