### ISSUE TITLE
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    307733 type:Color

### ISSUE THREAD

**Issue by siraj-haid** [microsoft/Azure-Kinect-Sensor-SDK#1350]
**Describe the bug**
When the WFOV(wide field of view) depth configuration is used, the Azure kinect is failing in Kinect viewer. We tried to update the firmware but it did not work. Everytime after opening the kinect viewer for couple of seconds we receive the following errors in the viewer when crashing:

**To Reproduce:**
1. Open the Kinect viewer
2. Select WFOV as depth configuration
3. start the viewer
4. The error will appear

**Expected behavior**
The Kinect viewer will crash with the error above in the log.
**Logs**
<[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    307733 type:Color
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    374388 type:Color
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    441066 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    507733 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    574411 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    641077 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    707722 type:Color
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    774400 type:Color
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    841055 type:Color
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    907733 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    974388 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:   1041066 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:   1107733 type:Color
[ warning  ] : usb_cmd_libusb_cb(). USB timeout on streaming endpoint for depth
[ error    ] : replace_sample(). capturesync_drop, releasing capture early due to full queue TS:   1174411 type:Color
[ error    ] : cmd_status == CMD_STATUS_PASS returned failure in depthmcu_depth_stop_streaming()
[ error    ] : depthmcu_depth_stop_streaming(). ERROR: cmd_status=0x00000063
[ error    ] : cmd_status == CMD_STATUS_PASS returned failure in depthmcu_depth_stop_streaming()
[ error    ] : depthmcu_depth_stop_streaming(). ERROR: cmd_status=0x00000063
 -->

**Desktop (please complete the following information):**
 - OS with Version: Windows 10
 - SDK Version: 1.4.0
 - Firmware version: RGB camera: 1.6.102
                                Depth camera: 1.6.75

**Comment by qm13** [comment]
Please try flashing the device on a different port or different computer. Suspect you have a USB controller issue.

**Comment by siraj-haid** [comment]
I tried to flash the device. Then I replaced the USB cable with one we use for our second Kinect camera and it gave the same error  

Also i tried the camera on 3 different computers and still the same error.

Do you have another suggestions?

Thank you.

**Comment by qm13** [comment]
@siraj-haid Can you please try to reset the device to factory defaults and then attempt to flash the device. You can find the instructions [here](https://docs.microsoft.com/en-us/azure/Kinect-dk/reset-azure-kinect-dk)

**Comment by siraj-haid** [comment]
@qm13  I changed the power cable of the Kinect camera and for now the camera stopped crashing. Thank you for your help.

**Comment by guss2149** [comment]
Hello,  I am currently getting these same errors when I use an alternate power source. Our application require a much longer cable than the original one but we've only had success (no errors) when we run a 110V extension cord and use the original power supply and original power cable. Does anyone know of any other way to power the cameras? Our attempted (with no success) setup is using [this cable](https://www.ebay.com/itm/172817859383?_trkparms=ispr%3D1&amdata=enc%3AAQAFAAAAkFCyoA%2BXzDlXqBnbcJoXJfz9lpLxQ048xN3i2kJF0g3LhrYejm5Ob%2FKGbzm6uifaGmcXAJfsvpYOtMRubeXEhM78InKa4IPck8jtn10%2FazMga1CcPfDnP7Foeu3c3071tXqICL5u2k8U70anGcRnDoGledkru4VkzsTW7zO8Q1p9GcfMEfMyHxzjeSoxO%2BgtgA%3D%3D&chn=ps&norover=1&mkevt=1&mkrid=711-117182-37290-0&mkcid=2&itemid=172817859383&targetid=1262376588856&device=c&mktype=pla&googleloc=9021515&poi=&campaignid=12874531651&mkgroupid=123924950842&rlsatarget=pla-1262376588856&abcId=9300535&merchantid=108712654&gclid=EAIaIQobChMIw8X87Oni8AIVC26GCh2usA_5EAQYAiABEgI2xfD_BwE) and with a 3 conductor cable (only using 2 wires) soldered to the leads connected to [this power supply](https://www.deltapsu.com/en/products/din-rail-power-supply/DRS-5V50W1AZ). We have had no success. Has anyone had any success with any alternate power supply solution?

**Comment by kalisina** [comment]
Hi @siraj-haid 
I'm currently running into the same issue, which power cable are you using now? 
You're not using the one provided in the box anymore? 

Hi @qm13, I've factory reseted the device manually, what do you mean by flashing it? 

Hi @guss2149, have you fixed the issue on your side?

**Comment by qm13** [comment]
@arkader https://docs.microsoft.com/en-us/azure/kinect-dk/update-device-firmware
