### ISSUE TITLE
How to avoid RGB camera feed from becoming dark post calibration using green screen example?

### ISSUE THREAD

**Issue by srinivas-varadharajan** [microsoft/Azure-Kinect-Sensor-SDK#1352]
Hey Guys,

I'm trying to run the green screen example.
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/green_screen

Post running the example, the rgb camera feed becomes too dark.
The camera feed becomes alright if I unplug the cameras and connect again.

Any suggestion on how to calibrate it correctly would be helpful.

Thanks

**Comment by qm13** [comment]
Some things to consider:

- Please make sure you are on the latest firmware.
- Also what command are you using in green_screen as this can control the color exposure?
- Please include pre and post green screen color camera images?
- What are the lighting conditions of the environment?
