### ISSUE TITLE
Body tracking while sitting

### ISSUE THREAD

**Issue by devLupin** [microsoft/Azure-Kinect-Sensor-SDK#1353]
Please refer to the picture below.
![image](https://user-images.githubusercontent.com/33558083/93182439-a6819a80-f774-11ea-88f4-1f19b8c08f85.png)

I think that general body tracking tracks the entire body and refers only to the necessary data.

My situation is to extract upper body data when sitting.
Can you see only the upper body and recognize that it is a human body and extract data without recognizing the whole body?

**Comment by qm13** [comment]
Use the confidence level to exclude joints not reported by the DNN (generally joints not observed in the image).
