### ISSUE TITLE
Body tracking not working from Unity on Windows 2004

### ISSUE THREAD

**Issue by DanielEliasib** [microsoft/Azure-Kinect-Sensor-SDK#1367]
**Describe the bug**

I'v being fighting with this bug for several day. I have a Unity project that uses the C# wrapper. One day it randomly started to crash all the time and after creating a fresh one and debugging I was able to find that the problem came from: `Microsoft.Azure.Kinect.BodyTracking.Tracker.Create();`. In the fresh Unity project it would log **K4A_RESULT_FAILED**.

Then I realised the problem started after windows made me update to 2004, I reverted the update and now the same code works as expected. 

It's a tricky bug because running the body tracking example that comes with the sdk works fine, so this may be something related to Unity as well, but only this was failing. Also is worth noting that using a version of my code without the body tracking worked fine.

**To Reproduce**
I can't reproduce it anymore because I reverted my windows installation to 1903 and never created a step by step process because I was just trying to fix it. Maybe on the weekend I'll try with my home PC.

But If I were to give a list of steps It'd be:

1.- Create a Unity 2019.3 or 2019.4 project,
2.- Create a script that calls `Tracker tracker = Tracker.Create(device.GetCalibration(), new TrackerConfiguration() { ProcessingMode = TrackerProcessingMode.Gpu, SensorOrientation = SensorOrientation.Default });`, using the body tracking sdk.

You'll need to add the relevant dll for this.

I'll update this section if I get to reproduce it this weekend. 

**Expected behavior**
Tracker.Create(); is expected to initialized body tracking. 

**Logs**
Don't have logs, and can't reproduce anymore because I changed Windows versions. 

**Desktop (please complete the following information):**
 - OS with Version: Windows 2004
 - SDK Version:  1.0.1
 - Firmware version:  1.6.75

**Additional context**
Maybe it's one of those isolated case of weird bugs that happen when windows updates.

**Comment by benMOOVENCY** [comment]
Hello @DanielEliasib  you could look these issues 
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/932. https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1147

there is maybe a pb with the onxruntime.dll

**Comment by henryo12** [comment]
I was experiencing the same issue. My project runs as expected inside the Unity Editor, but when I build the code, the exe fails on the Tracker.Create(). I copied onnxruntime.dll and dnn_model_2_0.onnx next to the exe and everything worked.

**Comment by DanielEliasib** [comment]
Hi, I haven't been able to test this solution, this weekend I unpaused the updates to try this out but it seems that now Windows Update can't find the 2004 update that was causing problems, or any newer updates. I guess I have to wait until the October update is pushed to my device.

**Comment by DanielEliasib** [comment]
I can confirm that the solution listed above seems to work, I'm on build 20241.1005 and I can run the body tracking with no issue.
