### ISSUE TITLE
ROS support

### ISSUE THREAD

**Issue by joylital** [microsoft/Azure-Kinect-Sensor-SDK#137]
Support for ROS with Azure Kinect DK

**Comment by skalldri** [comment]
This work is going well, and is getting close to the point where we can have an initial release.

**Comment by Brent-A** [comment]
This work is underway in [Azure-Kinect-ROS-Driver](https://github.com/microsoft/Azure-Kinect-ROS-Driver) (which is currently private). It will eventually be shipped as a consumer of the Azure Kinect Sensor SDK.

**Comment by zjudmd1015** [comment]
Has it released yet?

**Comment by skalldri** [comment]
Hi @zjudmd1015 , 

The ROS driver repo has just been made public. You can find it here: https://github.com/microsoft/Azure_Kinect_ROS_Driver

Please go try it out and let me know if you run into any issues!

Cheers,
Stuart

**Comment by skalldri** [comment]
The ROS driver repo is now public. All future ROS-specific work will be tracked in the Issues for that repo. Closing out this issue.
