### ISSUE TITLE
(HIP_LEFT,HIP_RIGHT)'s orientations are actually (KNEE_LEFT,KNEE_RIGHT)'s

### ISSUE THREAD

**Issue by knat** [microsoft/Azure-Kinect-Sensor-SDK#1372]
```C++
k4abt_skeleton_t skeleton = ...;
k4a_quaternion_t const& hipLeftQ = skeleton.joints[K4ABT_JOINT_HIP_LEFT].orientation;
k4a_quaternion_t const& hipRightQ = skeleton.joints[K4ABT_JOINT_HIP_RIGHT].orientation;
```
They are orientations of bones marked with red:
![0](https://user-images.githubusercontent.com/10220052/95011059-9a487900-0660-11eb-9e91-65f65d6f0728.png)
![1](https://user-images.githubusercontent.com/10220052/95022315-1ff01700-06a9-11eb-8b12-5a57198aa99b.png)
The same confusing applies to CLAVICLE_LEFT and CLAVICLE_RIGHT.
As far as I know,  bones marked with green have no orientations(or have fixed orientations):
![2](https://user-images.githubusercontent.com/10220052/95020744-853f0a80-069f-11eb-900f-b123f6ba1555.png)

**Comment by qm13** [comment]
We are confused as to what you are asking? Are you asking why the hip orientation is the same as the knee orientation?

**Comment by knat** [comment]
Hi,
```C++
k4a_quaternion_t const& SPINE_NAVAL_Q = skeleton.joints[K4ABT_JOINT_SPINE_NAVAL].orientation;
```
`SPINE_NAVAL_Q` is the orientation of the bone that points to SPINE_NAVAL joint:
![1](https://user-images.githubusercontent.com/10220052/95116400-8e040f00-0779-11eb-9133-aa7424d89cf0.png)

```C++
k4a_quaternion_t const& HIP_LEFT_Q = skeleton.joints[K4ABT_JOINT_HIP_LEFT].orientation;
```
Is `HIP_LEFT_Q` the orientation of the bone that points to HIP_LEFT joint? No, it's the orientation of the bone that points to KNEE_LEFT joint.

It's not a bug, but very confusing. It takes me hours to figure it out.
