### ISSUE TITLE
OpenCV issue

### ISSUE THREAD

**Issue by Henrilux** [microsoft/Azure-Kinect-Sensor-SDK#1381]
Hi,

I'm trying to deploy this SDK in China but having network issue due to "the firewall".

I **installed OpenCV supplied and the powershell script failed to function.**

Is there a way I could manually config OpenCV2, k4a, and re-route lib folder?

attached screenshot for reference

![issue](https://user-images.githubusercontent.com/43144582/95702055-d0e44c00-0c7d-11eb-960d-ef223191411a.png)

**Comment by qm13** [comment]
Please redirect your question to an OpenCV forum.
