### ISSUE TITLE
Device timestamp slower than reality

### ISSUE THREAD

**Issue by initialneil** [microsoft/Azure-Kinect-Sensor-SDK#1384]
**Describe the bug**
Use Azure Kinect to capture celephone's stopwatch and record device timestamp at the same time. The device timestamp is slower than captured stopwatch image. See the sample and table below:
![image](https://user-images.githubusercontent.com/4156648/96208567-6c3c3080-0fa0-11eb-991f-36c378b06e86.png)
![image](https://user-images.githubusercontent.com/4156648/96209870-3cdaf300-0fa3-11eb-880e-425b53c2ef70.png)

- The Azure Kinect's device timestamp is a lot slower. After around 16 minutes, it's 373 milliseconds less.
- I tested 2 Azure Kinect devices and they produced very similar results.
- I was working on a system with both Azure Kinect devices and some other factory cameras. The factory camera I used showed very accurate timestamp againt stopwatch(around 5ms difference for 30minutes). 
- Because Azure Kinect's timestamp is drifting, I cannot properly synchronize the 2 kind of devices based on timestamp.

**To Reproduce**
- Shoot a celephone's stopwatch and record the device timestamp at the same.
- Wait a while and shoot again, e.g. 10 minutes, 1 hour, etc.
- 720p, 30fps, exposure 10ms

**Expected behavior**
Azure Kinect timestamp runs accurate agaiant reality.

**Desktop (please complete the following information):**
 - OS with Version: Windows 1909
 - SDK Version:  1.4.1
 - Firmware version:  one with 1.6.98, another one 1.6.110

**Comment by qm13** [comment]
@initialneil the Azure Kinect DK timer will drift (as does any time). You will need to compensate for this drift on your host compute (which presumably has a more accurate timer or NTP support).
