### ISSUE TITLE
I want to know whether the kinectDK has models to provided

### ISSUE THREAD

**Issue by VegetableWithChicken** [microsoft/Azure-Kinect-Sensor-SDK#1388]
The model of the official coordinate system is marked. Is there a corresponding model to be provided for the convenience of art colleagues to build models
[here ](https://docs.microsoft.com/zh-cn/azure/kinect-dk/body-joints)

**Comment by qm13** [comment]
@UEBoy2019 could you provide us more info on this request?

**Comment by VegetableWithChicken** [comment]
> @UEBoy2019 could you provide us more info on this request?

I’m making a dress-up demo, and I hope to have a matching model so that I can make clothes
