### ISSUE TITLE
Kinect Azure Body Tracking Coordinate Mapping

### ISSUE THREAD

**Issue by starlee94** [microsoft/Azure-Kinect-Sensor-SDK#1389]
Hi guys, I am currently in the progress of converting my Microsoft Kinect V2 project to an Azure Kinect project and I encountered a problem with Mapping joint position to Color and Depth space. MY project was written in C#, there weren't much documentation for Body Tracking SDK in C#, the code I am having issue are as below:

![Capture](https://user-images.githubusercontent.com/20609628/96617114-1991aa00-12fb-11eb-87fe-4fa19cf47c37.JPG)

is there any alternative to achieve this?

**Comment by RoseFlunder** [comment]
Hi,
to convert a 3D position (like from body tracking) to one of the 2D coordinate systems you can use these functions:

https://docs.microsoft.com/en-us/azure/kinect-dk/use-calibration-functions

You can also find the C# API reference on the website for corresponding C# functions.

**Comment by starlee94** [comment]
@RoseFlunder Thank you for directing me to the right direction! I have found the solution.
