### ISSUE TITLE
AMD x570 compatibility

### ISSUE THREAD

**Issue by madhan001** [microsoft/Azure-Kinect-Sensor-SDK#1390]
Is the Azure kinect compatible with the AMD x570 (MSI x570 Tomahawk) chipset's USB 3.1 controller? I don't see any information regarding compatibility with AMD chipsets but only Intel ones.

**Comment by RoseFlunder** [comment]
I have tested the azure kinect briefly on a Windows PC with a MSI X570 Carbon Wifi Mainboard and AMD Ryzen 3700X.
The k4a viewer worked without issues.
Haven't done any longtime testing though.

**Comment by madhan001** [comment]
> I have tested the azure kinect briefly on a Windows PC with a MSI X570 Carbon Wifi Mainboard and AMD Ryzen 3700X.
> The k4a viewer worked without issues.
> Haven't done any longtime testing though.

Was it tested with the back panel port ? Linux or windows ?

**Comment by RoseFlunder** [comment]
Yes, the device was connected via the backpanel usb ports and the pc was running with windows 10.

**Comment by madhan001** [comment]
> Yes, the device was connected via the backpanel usb ports and the pc was running with windows 10.

Thanks for answering my questions
