### ISSUE TITLE
Having problems with azure kinect on unity.

### ISSUE THREAD

**Issue by syuenminleong** [microsoft/Azure-Kinect-Sensor-SDK#1391]
I currently facing some problems when using Azure Kinect on Unity and I want to ask for advice. Below I have share my google drive link, inside the file got one video I recorded the problem I am facing right now and a zipped file with my source code. The video you can see that I am trying to grab the object on the right, but the object in the middle is grabbed, and the detection of my hand is also very inaccurate (like my palm is released, AK detect result shows grip). My scene is place at here: TEST\Assets\AzureKinectExamples\KinectDemos\InteractionDemo\KinectInteractionDemo1

The above are the problems I currently faced, I hoped that you can understand what I want to express about. Thank you.

[https://drive.google.com/drive/folders/1iicneUbwrbFDT102xabz7_oAegpQUieu?usp=sharing](url)

**Comment by anantley** [comment]
Hi @syuenminleong  

I could see your video but I couldn't reach your code.  From the video it looks like the skeletal hand tracking is too noisy for your purposes.  Sometimes this can be mitigated by not facing the Azure Kinect directly. With a 45 degree angle you can get the hand extension more reliably.
