### ISSUE TITLE
Unity | Can't display color or depth image in the Body Tracking example

### ISSUE THREAD

**Issue by karolsenami** [microsoft/Azure-Kinect-Sensor-SDK#1397]
**Description**

I am trying to create a script to display Depth and Color images on a `RawImage` object.
I added to the `DeviceConfiguration` : `ColorResolution.R720p, ImageFormat.ColorBGRA32`
Then assigned it to the `currentFrameData` by modifying `BackgroundData` and `SkeletalTrackingProvider`.
But I'm having trouble on retrieving the bytes in a good format. I can't find any help online, and I hope someone here knows how to deal with it. Also I don't understand the "// Repack data and store image data" code.

I tried multiple workaround but nothing seems to work.
Any help would be appreciated

**Comment by anantley** [comment]
Hi I have a visualizer working with this configuration:
`device.StartCameras(new DeviceConfiguration()
                    {

                        CameraFPS = FPS.FPS15,
                        DepthMode = DepthMode.NFOV_2x2Binned,
                        WiredSyncMode = WiredSyncMode.Standalone,
                        ColorResolution = ColorResolution.R1080p,
                        ColorFormat = ImageFormat.ColorBGRA32,
                        SynchronizedImagesOnly = false,
                    });`

Can you send a link to where you apply the capture to the raw image object?
