### ISSUE TITLE
Linux libdepthengine.so.2.0

### ISSUE THREAD

**Issue by nrpr161293** [microsoft/Azure-Kinect-Sensor-SDK#1403]
**Describe the bug**
My team is trying to run the k4aviewer on linux machine and the depth info of the kinect isn't working, other info like RGB is working perfectly. I think the error is related with the libdepthengine.so.2.0 but we already put the file in the build/bin folder and still for some reason we cannot read it. Can you please help us?

**To Reproduce**
1. open the k4aviewer on terminal
2. select "enable depth camera"

**Expected behavior**
It should work with depth info.

**Logs**

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/71510928/97323757-08035180-1869-11eb-8f04-2c6c65ef864f.png)

**Desktop (please complete the following information):**
 - OS with Version: Linux 18.04
 - SDK Version:  1.4.1
 - Firmware version:  
![Screenshot from 2020-10-27 15-33-05](https://user-images.githubusercontent.com/71510928/97324850-39305180-186a-11eb-8006-be4f56dec98f.png)

**Comment by RoseFlunder** [comment]
Did you compile the sdk yourself?
Usually you don't need to copy any files when installing the sdk and k4aviewer via apt from the MS package repository.

**Comment by nrpr161293** [comment]
Yes we compile using this instructions https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md, but doesn't generate any libdepthengine.so.2.0 on the build/bin folder, for that reason we copy the lib to the folder.

**Comment by zliuchen** [comment]
I have similar issue on Windows. I built from cmake, and the depthengine dll is not part of the project's build.lib folder. Therefore, I copied the depth engine dll from the msi installer, but it didn't help. Still complained about missing depth engine

**Comment by qm13** [comment]
> Yes we compile using this instructions https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md, but doesn't generate any libdepthengine.so.2.0 on the build/bin folder, for that reason we copy the lib to the folder.

The depth engine is provided as a binary only.

**Comment by qm13** [comment]
Did you install the [Debian package](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#debian-package) or build the SDK from scratch? If you built from scratch please try installing the Debian package and run k4aviewer.

If it does continue to fail please provide us with the complete error message (it is cut off in the screen shot).

**Comment by nrpr161293** [comment]
Hi @qm13 thank you for your feedback regarding to the depthengine. Indeed is a binary and for that reason it cannot be included on the sdk. For that reason I copy it and paste it on the build/bin folder, I don't know if this should be the correct one?
Regarding to the installation, we try both, first using the debian package and then build from scratch, in both ways we can open the k4aviewer and the RGB image works perfectly but when we try to see the depth info the following errors appear. Maybe I'm putting the libdepthengine.so.2.0 in the wrong folder.

![Screenshot from 2020-10-29 16-04-11](https://user-images.githubusercontent.com/71510928/97600008-83e3d200-1a00-11eb-8450-826631b7d262.png)

**Comment by qm13** [comment]
What happens when you use the pre-built k4aviewer tool in the package?

**Comment by jiapei-nexera** [comment]
I'm now having exactly the same problem.... Where can we download that **libdepthengine.so.2** ?
