### ISSUE TITLE
depth engine dll

### ISSUE THREAD

**Issue by zliuchen** [microsoft/Azure-Kinect-Sensor-SDK#1405]
Hi There,
    I downloaded the MSI, and installed the SDK binaries.

    In addition, I cloned the git repo, and cmake/VS studio. I tried to debug through example "fastpointcloud"; however, during run-time it complained about "no depth engine".
     As I checked, there is the depthengine_2_0.dll in the same folder as k4a.dll. 

      I tried to run the release version, the same error.

can anyone tell me what I am missing? Thanks.

**Comment by qm13** [comment]
Do you have depthengine_2_0.dll in your path? If you run the k4aviewer tool from the install directory does it work?
