### ISSUE TITLE
MKV recording sample file for Body Tracking

### ISSUE THREAD

**Issue by rejnok93** [microsoft/Azure-Kinect-Sensor-SDK#1411]
Is it possible to have at least 1 very simple short MKV recording sample with a person or static figurine, that can be used with Azure Kinect Body Tracking SDK (eg. "offline_processor" example)?
The official "Office Sample Recordings" will not output any body tracking data, that will help our project team decide to start developing (new medical diagnostic device) on top of the Azure Kinect DK.
For example Intel RealSense provide many sample recordings for download, also with humans in view, to test their Body Tracking SDK.

_Originally posted by @wes-b in https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/339#issuecomment-502757624_

**Comment by adammpolak** [comment]
Any movement on this?

**Comment by chiwa737** [comment]
I love to have this as well

**Comment by qm13** [comment]
Darn. Meant to update this issue many moons ago. Here is a link to a sample video

https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/sample_recordings

**Comment by adammpolak** [comment]
Thank you!
