### ISSUE TITLE
How to set or configure the depth camera exposure including the IR images ?

### ISSUE THREAD

**Issue by GitZinger** [microsoft/Azure-Kinect-Sensor-SDK#1421]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

currently the ir/depth camera cannot be set with the exposure.
**Describe alternatives you've considered**

**Additional context**

**Comment by qm13** [comment]
This is not possible. Changing the exposure time means changing the integration time and impacts the depth camera calibration.
