### ISSUE TITLE
Azure Kinect Body Tracking SDK is not work well with RTX3080

### ISSUE THREAD

**Issue by VegetableWithChicken** [microsoft/Azure-Kinect-Sensor-SDK#1423]
windows 10,x64
i7-9700KF 
32GB
NIVIDA GeForce RTX3080

run the Azure Kinect Body Tracking SDK ,but k4abt_simple_3d_viewer.exe    do not work
but the SDK is work well

**Comment by L4Z3RC47** [comment]
related issue #1125

**Comment by VegetableWithChicken** [comment]
Who can tell me, has this problem been solved and what needs to be updated. I updated to cudn10.1, but it has no effect. 
Do I need to move the CUDN   DLL library to bianary replacement of body tracking file ？？

**Comment by qm13** [comment]
Issue appears to be with CUDA compatibility. Tracking in #1125.
