### ISSUE TITLE
Is it possible to body tracking from k4aviewer's result?

### ISSUE THREAD

**Issue by gdosu** [microsoft/Azure-Kinect-Sensor-SDK#1429]
Hello. I'm totally new on here, so my expression can be ambiguous.

I have Ubuntu 18.04 on ARM64 and I run Azure Kinect Viewer(k4aviewer) successfully just a moment ago.

And unfortunately Azure Kinect Body Tracking Viewer seems not support ARM64 yet.

Then is it possible to send k4aviewer's result to other PC and process body tracking from there?

Actually I was trying usb extender originally, but it also has problem from opening color camera device.

**Comment by RoseFlunder** [comment]
It is possible but not with the k4aviewer.
If you dont need realtime results, you could make a recording with the k4arecorder command line tool which creates a mkv file.
This file can be processed on another pc for body tracking results, altough the simple viewer will not work, you have to compile sth else for it like the offline processor sample which exports the body tracking information per frame from a mkv file to a json file.

For realtime results you would need to develop your own applications with the SDKs.
You can create a application on the ARM pc that sends the k4a captures + device calibration over the network to your x86 PC and the x86 PC would need an application receiving the captures, feed the Body tracker with it and then display the ab results or save them or whatever you need.
Thats of course work that needs to be done by person that has C/C++ knowledge.
