### ISSUE TITLE
Master Slave Kinect triggering not functioning

### ISSUE THREAD

**Issue by jsaisagar** [microsoft/Azure-Kinect-Sensor-SDK#1432]
Dear team,

I have two kinects which I am connecting in master/slave architecture. It was working for sometime and then suddenly the synching is not happening. 
Slave is not able to receive master signal at all. 

I am getting the following error:
 validate_configuration(). Failure to detect presence of sync out cable with wired sync mode K4A_WIRED_SYNC_MODE_MASTER.

May I know how to resolve this issue? Does factory reset help?

Thanks,
Sai

**Comment by qm13** [comment]
Some thoughts on debugging the situation:
1. Can you swap out the master camera?
2. Can you swap out the sync cable
3. Can you scope the sync cable to see if the pulse is being transmitted.
