### ISSUE TITLE
Is it okay not to turn off the Kinnect power?

### ISSUE THREAD

**Issue by solra96** [microsoft/Azure-Kinect-Sensor-SDK#1433]
Kinect flashes white when the PC is turned off when connected normally.
In other words, the Kinect sensor is turned on even if the PC is turned off.
Is it okay not to turn off the Kinect even when I'm not using it?
Is it okay to turn off the power of Kinect once a week?
If not, would it be appropriate to turn off the Kinect power once every few days?

The PC and The Kinect will be shut down after using it from 9 to 18 every day.

**Comment by qm13** [comment]
The Azure Kinect will remain powered if either the USB-C port continues to provide power (5.9 Watts) or if the device is powered by the supplied power brick. You can leave it powered on. It will be in an idle states (not capturing images).
