### ISSUE TITLE
Depth image of a specific distance

### ISSUE THREAD

**Issue by xiaoguitoucode** [microsoft/Azure-Kinect-Sensor-SDK#1434]
hi, I am new to Azure Kinect, and I want to get a depth image of a specific distance (0.5m-1m), how do I do it, or where do I start? Thanks!

**Comment by qm13** [comment]
The pixel depth value is the distance of that pixel in mm from camera.

https://docs.microsoft.com/en-us/azure/kinect-dk/coordinate-systems#3d-coordinate-systems

**Comment by xiaoguitoucode** [comment]
The format of the depth value is K4A_IMAGE_FORMAT_DEPTH16 ,Does it mean the longest distance is 65.536m?
Is there any code for reference？
