### ISSUE TITLE
Build fails when using ｍake instead of Ninja

### ISSUE THREAD

**Issue by Xiaoxuan1-Yu** [microsoft/Azure-Kinect-Sensor-SDK#1436]
release/1.2.x
Used regular CMake build generator (instead of Ninja).
Ubuntu 16.04.
GCC 6.

Build fails with the following error：
~/Azure-Kinect-Sensor-SDK/build$ make 
Scanning dependencies of target validateclangformat
[  0%] Validating format of /home/xxx/Azure-Kinect-Sensor-SDK/src/allocator/allocator.c
Traceback (most recent call last):
  File "/home/xxx/Azure-Kinect-Sensor-SDK/cmake/ValidateFormat.py", line 108, in <module>
    main(sys.argv[1:])
  File "/home/xxx/Azure-Kinect-Sensor-SDK/cmake/ValidateFormat.py", line 42, in main
    proc = subprocess.Popen([args.clangformat] + ['-output-replacements-xml', file], stdout=subprocess.PIPE, encoding="utf-8")
TypeError: __init__() got an unexpected keyword argument 'encoding'
CMakeFiles/validateclangformat.dir/build.make:329: recipe for target 'src/allocator/allocator.c.clang-validate-result' failed
make[2]: *** [src/allocator/allocator.c.clang-validate-result] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/validateclangformat.dir/all' failed
make[1]: *** [CMakeFiles/validateclangformat.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by HlibKazakov2000** [comment]
[Currently, the only supported distribution is Ubuntu 18.04](https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download#:~:text=Currently%2C%20the%20only%20supported%20distribution%20is%20Ubuntu%2018.04)
Update GCC to version 8.4
And check Python for updates
