### ISSUE TITLE
Latency Question

### ISSUE THREAD

**Issue by DirkKramer** [microsoft/Azure-Kinect-Sensor-SDK#1446]
Hello,

As issue #816 states, there is some latency between capturing the image and releasing the capture to the program.

Questions:

- How accurate are the latency measurements in the tables provided by Wes-b.
<img width="318" alt="latency" src="https://user-images.githubusercontent.com/46933603/102460424-3f130980-4047-11eb-949a-46785b563a35.PNG">

for example if we use 1280x720 with BGRA32, the table says that we can ecnouter a latency of roughly 68ms. But what is the error on this measurement. can it also be 80ms or 50ms sometimes?

-How can i measure this latency programatically, in our case preferably in c#.

**Comment by qm13** [comment]
These are rough numbers. The number will vary by content.
