### ISSUE TITLE
QUESTION: Which method is used to determine the distance.

### ISSUE THREAD

**Issue by Me817** [microsoft/Azure-Kinect-Sensor-SDK#1458]
Hello,

in the [documentation](https://docs.microsoft.com/en-us/azure/kinect-dk/depth-camera) for the Microsoft Azure Kinect I read that the depth camera uses the time of flight method to measure the distances in the scene. But in another [article](https://www.researchgate.net/publication/323818253_IMpixel_65nm_BSI_320MHz_demodulated_TOF_Image_sensor_with_3mm_global_shutter_pixels_and_analog_binning/download) I read thet the TOF camera uses the Phase shifting or Phase Coherence method to determine the distances in the scene. So my question is: Does the Azure Kinect use both method to avoid ambiguity in the distance values if the movements was bigger than the have of the phase? Or does it only use one of the methods? If the second is the case: Which method is used?

Thank you in advance.

**Comment by qm13** [comment]
Depth Sensor in Azure Kinect DK uses Indirect Time of Flight Technique. Read this paper for additional information https://ieeexplore.ieee.org/document/8310200
