### ISSUE TITLE
Sample unity body tracking app missing meta files

### ISSUE THREAD

**Issue by Utkarsh-Bajpai** [microsoft/Azure-Kinect-Sensor-SDK#1461]
When tried to open the PuppetMaster scene in Sample Unity Body Tracking Application, there are missing prefab errors. This is because of missing meta files for the prefabs Female adult and jasper. Meta files are also missing for other files such as all files in the model directory, and a few .cs files.

Could you please add the required meta files.

![image](https://user-images.githubusercontent.com/21344935/103526044-3f642f00-4ea6-11eb-9e90-1379611d9086.png)

**Comment by anantley** [comment]
Hi I fixed the problem in .gitignore and will push the fix today

**Comment by janwww** [comment]
Hi, I had the same problem and everything seems to work now in your project from your pull request, thanks!

I was wondering if the missing script on the `Kinect4AzureTracker` object in the `PuppetMaster` scene is still relevant (see image).
I couldn't find any scripts with missing `.meta` files and everything seems to work, so I guess it's not important?
![image](https://user-images.githubusercontent.com/43852173/104955656-c77c2580-59ca-11eb-8ce7-4edb96e8b44f.png)

**Comment by anantley** [comment]
Hi @janwww,
The missing script is just leftover cruft. You can delete it.
