### ISSUE TITLE
Question about green_screen code

### ISSUE THREAD

**Issue by logic03** [microsoft/Azure-Kinect-Sensor-SDK#1462]
Can the program in Azure-Kinect-Sensor-SDK / examples / green _ screen / MultiDeviceCapturer.h capture only one image ? If have _ synced _ images are set to true after the synchronization is successful, then it will exit the cycle of capturing images. Am I right？

**Comment by qm13** [comment]
Yes, I believe so. However the header file is large and it isn’t clear exactly where “after the synchronization is successful” happens.
