### ISSUE TITLE
Question about MAX_ALLOWABLE_TIME_OFFSET_ERROR_FOR_IMAGE_TIMESTAMP

### ISSUE THREAD

**Issue by logic03** [microsoft/Azure-Kinect-Sensor-SDK#1466]
请问在进行双相机的深度图像同步的时候，Azure-Kinect-Sensor-SDK / examples / green _ screen / MultiDeviceCapturer.h的MAX_ALLOWABLE_TIME_OFFSET_ERROR_FOR_IMAGE_TIMESTAMP也是设置为100us吗？因为我看到https://blog.csdn.net/qq_43707919/article/details/109347961这个博客里面有个人说当同步RGB图像的时候这个值设置为100us，当同步深度图像的时候这个值设置为260us。但是我觉得不管同步RGB图像还是深度图像，这个值都应该被设置为100us，请问我说的对吗？
————————————————————————————————————————
In the depth of the dual camera image synchronization, Azure-Kinect-Sensor-SDK / examples / green _ screen / MultiDeviceCapturer.h MAX_ALLOWABLE_TIME_OFFSET_ERROR_FOR_IMAGE_TIMESTAMP is also set to 100 us? Because I saw someone on this blog saying that the value is set to 100μs when synchronizing RGB images and 260μs when synchronizing depth images.(https://blog.csdn.net/qq_43707919/article/details/109347961) However, I think this value should be set to 100μs for both RGB and depth images. Am I right?

**Comment by qm13** [comment]
You are correct. The RGB camera does not need to be offset from the depth camera. The offsetting (delay) between 2 depth cameras is to prevent them from interfering with each other as they both emit IR light to generate the depth image.
