### ISSUE TITLE
How can I tell if a PC with a USB C port is capable of supplying sufficient power to an Azure Kinect

### ISSUE THREAD

**Issue by DrMaxP** [microsoft/Azure-Kinect-Sensor-SDK#1468]
I have the option of buying a small PC that has a single USB C port. How would I know if it is capable of powering an Azure Kinect with a suitable USB C to USB C cable? (i.e. a single cable solution). What spec/info should I be looking for?

**Comment by DrMaxP** [comment]
This PC cannot be expanded to add more ports.

**Comment by qm13** [comment]
Consult the PC manual or ask the vendor. If the USB-C port is labeled as USB3.1 Gen 1 or 2 then it will be capable of self powering Azure Kinect. Azure Kinect at full power draw requires 6.9W of power. Gen 1 and 2 ports have a minimum power capability of 7.5W.
