### ISSUE TITLE
Body Tracking not working on AMD CPU's / Motherboard's?

### ISSUE THREAD

**Issue by Shureshure** [microsoft/Azure-Kinect-Sensor-SDK#1481]
Hi
Unfortunately i switched from Intel to an AMD Ryzen 9 5900X
Now the Problem:

The Azure Kinect Viewer works flawlessly, but the Body Tracking Viewer it does not work.
I get into the program, but for some reason the 3D Visualization Window opens only after five or ten Minutes.
The Camera transmits the Image, but the skeleton is completely missing (only a red point can be seen).

There are problems with AMD CPU's / Motherboard's? are there any solutions?

Many thanks for the answer

**Comment by RoseFlunder** [comment]
I don't think so.
I use a Ryzen 3700X (Zen 2) on a X570 Chipset with an NVidia 1080 and everything works

There is a known issue regarding the new Nvidia 3000 Series if you also have a new GPU by chance?
At the moment we can't use any Nvidia 3000 Series (Ampere GPU) with the current body tracking sdk version

**Comment by qm13** [comment]
@Shureshure does your new AMD computer have an NVIDIA GPU? Is so what NVIDIA GPU does it use?

**Comment by Shureshure** [comment]
Thank you for the fast answer
Yes i have a rtx 3090. I was so fixated on amd that I did not get the idea that it could be due to the graphics card.
Now I see that I'm not the only one who has problems with it.
The problem doesn't seem to have been solved. Is there any news about a patch?

**Comment by qm13** [comment]
Ok. We are working on an update that provides support for the NVIDIA 3xxx range of GPU cards. We are planning to get it out (barring issues) by mid February.

**Comment by asergaz** [comment]
Related thread in Microsoft Q&A: https://docs.microsoft.com/en-us/answers/questions/238927/index.html

**Comment by UnaNancyOwen** [comment]
@qm13 How is the update release going? I'm looking forward to it! Thanks, 😄

**Comment by zirkeltraining** [comment]
Same here, we're anxiously hoping for the fix, otherwise we need to return that expensive new Machine….

**Comment by Shureshure** [comment]
@qm13 mid February 2022? or 2023?  How long it will take? it would be nice to know how the situation is.

**Comment by telhabilal-arbisoft** [comment]
Do we have any updates regarding the 30 series update release?

**Comment by guobenyu1976** [comment]
@qm13 i also want to know the date update. if it could be release this week, we could wait for it. otherwise we need to borrow/buy another 20 series computer to let the project go on.

**Comment by sgrafbus** [comment]
@qm13 and responsible MS folks: Can we please get an update on the status or your latest plans to support the NVIDIA 3xxx range of GPU cards for the Azure Kinect body tracking? We have a core development project relying on the use of the feature in combination with the 3xxx GPU performance, so would appreciate a transparent update on what we can expect by when, please. Thank you!

**Comment by RoseFlunder** [comment]
@sgrafbus in this issue is the latest update:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1519#issuecomment-790861711

So hopefully this week.

**Comment by zirkeltraining** [comment]
we're still waiting and would be very happy about an update on this issue.

**Comment by YongsunLee** [comment]
Is this problem solved?
If not, I would like to know the official answer when it will be resolved.

**Comment by qm13** [comment]
Added ONNX DirectML execution environment support (default environment). Now possible to run on AMD and Intel GPUs on Windows. Performance is dependent on the GPU.

**Comment by vertex798** [comment]
> Added ONNX DirectML execution environment support (default environment). Now possible to run on AMD and Intel GPUs on Windows. Performance is dependent on the GPU.

AMD Rizen 5900, RTX 3090.
What steps should I take to use this feature?

**Comment by ZodiacWind** [comment]
> > Added ONNX DirectML execution environment support (default environment). Now possible to run on AMD and Intel GPUs on Windows. Performance is dependent on the GPU.
> 
> AMD Rizen 5900, RTX 3090. What steps should I take to use this feature?

Same question. I cannot make it with Razen 5950X and RTX 3080Ti. Could anybody provide some guidelines?

**Comment by MarioTed** [comment]
> > > Added ONNX DirectML execution environment support (default environment). Now possible to run on AMD and Intel GPUs on Windows. Performance is dependent on the GPU.
> > 
> > 
> > AMD Rizen 5900, RTX 3090. What steps should I take to use this feature?
> 
> Same question. I cannot make it with Razen 5950X and RTX 3080Ti. Could anybody provide some guidelines?

Same question. Idk to how to do it.

**Comment by tinywolf3** [comment]
3060, 3070, 3080, same here. please fix it.
