### ISSUE TITLE
How to convert between OpenCV Mat and k4a::image?

### ISSUE THREAD

**Issue by WestbrookZero** [microsoft/Azure-Kinect-Sensor-SDK#1482]

**Comment by diablodale** [comment]
cv::Mat and k4a::image both provide access to the raw buffers, images, sizes, and pixel format (e.g. bytes/pixel). You can use this information to copy data to/from each image type. You can also use this information to "wrap" the raw data without copying it. You have the choice of copy or wrap.

The greenscreen example has some code from which you can learn https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/master/examples/green_screen/main.cpp

**Comment by ChristopherRemde** [comment]
If you have a k4a_image  _colorImage_ , you can convert the k4a_image to an OpenCV Mat with this code: 

	`cv::Mat cImg = cv::Mat(k4a_image_get_height_pixels(colorImage), k4a_image_get_width_pixels(colorImage), CV_8UC4, k4a_image_get_buffer(colorImage));`

Convert this OpenCV Mat back into a k4a_image _newk4aImage_:

```
	k4a_image_create(K4A_IMAGE_FORMAT_COLOR_BGRA32, cImg.cols, cImg.rows, cImg.cols * 4 * (int)sizeof(uint8_t), &newk4aImage);
	memcpy(k4a_image_get_buffer(newk4aImage), &cImg.ptr<cv::Vec4b>(0)[0], cImg.rows * cImg.cols * sizeof(cv::Vec4b));
```

You can see this file for more context:

https://github.com/MarekKowalski/LiveScan3D/blob/AzureKinect/src/LiveScanClient/azureKinectCapture.cpp#L160

Edit: Don't use this code, see https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1482#issuecomment-763596308 for a safer example

**Comment by diablodale** [comment]
@ChristopherRemde examples have several errors in them. Important when exchanging raw image data between different SDK/systems to declare the `step` or `stride`. It is not guaranteed for both systems (cv and k4a) to use the same stride. As fact, k4a aligns row strides to 32-byte boundaries and cv uses 64-byte boundaries. Therefore, add the step/stride parameter to both of his examples.

The color image from a k4a sensor can be many formats. https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___enumerations_gabd9688eb20d5cb878fd22d36de882ddb.html#gabd9688eb20d5cb878fd22d36de882ddb
The byte size and step/stride are different for them all. So you can not always assume it is 4 bytes with CV_8UC4. You will need to consult the documentation for k4a SDK and cv for the color image for you choose. The NV12 and YUY2 are usually more difficult for beginners, so I recommend you choose BGRA to begin.

It is also not safe to use memcpy() as he did. It is not guaranteed for the complete byte size of an image buffer to be the (rows * col * pixelsize). Image buffers are not guaranteed to be continuous/contiguous. The image buffer you are given can have different step/strides and may put additional unused bytes at the end of each row. I isolated data corruptions bugs in the k4a SDK itself where Microsoft didn't follow these rules.

Always stride and step. No exceptions when exchanging images between foreign systems. Even if you look at the internals of the SDKs, they can change change their alignment defaults at any time or the SDK can have differnet stride rules when you compile for different platforms (32-bit, 64-bit, Windows, Linux, Mac, etc.)

In all the no-copy examples, remember to manage the lifetime of the original source image. You must keep it alive while you are using the wrapped image. If you don't, then when you access the wrapped image, it will try to access deallocated memory and your app will probably crash.

Here is a corrected wrap (no copy) example
```c++
cv::Mat wrappedk4aimage {
  yourk4aimage.get_height_pixels(),
  yourk4aimage.get_width_pixels(),
  CV_8UC4, // calculate this with a function or hard code it if you guarantee it will never change
  yourk4aimage.get_buffer(),
  (size_t)yourk4aimage.get_stride_bytes()
};
```

His 2nd example is a copy which is different than his first example (no copy). Here is a corrected copy example.

```c++
auto yourk4aimage = k4a::image::create(
  K4A_IMAGE_FORMAT_COLOR_BGRA32, // again calculate with function or hard code
  cvimage.cols,
  cvimage.rows,
  (int)cvimage.step
);

// using memcpy like this is somewhat inflexible/dangerous; I use it only for quick example
memcpy(
  yourk4aimage.get_buffer(),
  cvimage.data,
  cvimage.step * cvimage.rows
);
```

And here is a (no copy) wrap of a cv image with a k4 image.

```c++
k4a::image::create_from_buffer(
  K4A_IMAGE_FORMAT_COLOR_BGRA32, // again calculate with function or hard code
  cvimage.cols,
  cvimage.rows,
  (int)cvimage.step,
  cvimage.data,
  cvimage.step * cvimage.rows,
  nullptr,
  nullptr
);
```

**Comment by ChristopherRemde** [comment]
@diablodale Thank your for your very detailled explanation! I learned quite a few new things, and will try to correct the code! And yes I forgot to include a notice that this is only code for one specific format.

**Comment by WestbrookZero** [comment]
My main code is as follows:
```
k4a::calibration kinectCalibration = _device.get_calibration(config.depth_mode, config.color_resolution);
k4a::transformation imageTransformation(kinectCalibration);
k4a::image depthImage = dataCaptured.get_depth_image();
positionImage = k4a::image::create(K4A_IMAGE_FORMAT_CUSTOM, positionWidth, positionHeight,positionWidth*6);
const Position* mPosition = reinterpret_cast<Position*>(positionImage.get_buffer());
imageTransformation.depth_image_to_point_cloud(depthImage, K4A_CALIBRATION_TYPE_DEPTH, &positionImage);
size_t depthPixelNum = depthWidth * depthHeight;	
pcl::PointCloud<pcl::PointXYZRGB> pointCloud.reset(new pcl::PointCloud<pcl::PointXYZRGB>(depthWidth, depthHeight));
auto& points = pointCloud->points;				
for(size_t i = 0; i < depthPixelNum; ++i)
{
	auto& point = points[i];
	{
		const Position& pos = mPosition[i];
		point.x = 0.001f * static_cast<float>(pos.mX);
		point.y = 0.001f * static_cast<float>(pos.mY);
		point.z = 0.001f * static_cast<float>(pos.mZ);
	}
}
cv::Mat combinedRgbMat.create(depthHeight, depthWidth, CV_8UC3);
for (std::uint32_t j = 0; j < pointCloud->width; j++)
{
	for (std::uint32_t i = 0; i < pointCloud->height; i++)
	{	
		combinedRgbMat.at<cv::Vec3b>(i, j) = cv::Vec3b((*pointCloud)(j, i).b, (*pointCloud)(j, i).g,  (*pointCloud)(j, i).r);
	}
}
```
when i use OpenCV  image "combinedRgbMat"  to detect person to get 2D (x,y)coordinates , How to convert OpenCV 2D (x,y) coordinates to X and Y coordinates of point cloud ?

**Comment by diablodale** [comment]
I recommend you read https://docs.microsoft.com/en-us/azure/kinect-dk/use-image-transformation and reference the examples. You are raising a different off-topic question.
