### ISSUE TITLE
Two camera calibration orientation (green screen example)

### ISSUE THREAD

**Issue by tostercx** [microsoft/Azure-Kinect-Sensor-SDK#1486]
**Describe the bug**

I'm not sure if this is a bug or not, but perhaps someone can clarify. I need to calibrate two cameras that may not be in the same orientation. In the green screen two camera calibration there's a long paragraph about why the orientation is assumed to always be down and that the algorithm behind it isn't supposed to be able to tell which side is which if the image is flipped by 180 degrees.

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/61951daac782234f4f28322c0904ba1c4702d0ba/examples/green_screen/main.cpp#L395-L418

However while looking for a solution some comments about how OpenCV works suggested that using a non-symmetrical chessboard image solves the problem (can't find source atm). And the chessboard image that comes with the example isn't symmetrical! (One side starts with black squares in the corners and the other one with white ones.)

After disabling the lines responsible for flipping the detected corner coordinates and testing for while surprisingly it works perfectly in any orientation as far as I can tell.

I expected that the example's author simply made a mistake by flipping the coordinates (in which case this would be a bug) but looking trough OpenCV's docs I can't seem to find anything related to this problem. I started looking trough the source but it's a bit too over my head to be honest. So I still don't know for sure if OpenCV checks the colors of the nearby squares to detect the orientation or if my results are a fluke. Or perhaps the detection is there and the example's author had tested this with an older version of OpenCV or a symmetrical chessboard image? The code and comments seem to be well thought out so I'm not sure.

**To Reproduce**

* Set up two cameras, one flipped upside down
* Run the example
* ---> orientation is not detected correctly 
* Disable the following lines:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/61951daac782234f4f28322c0904ba1c4702d0ba/examples/green_screen/main.cpp#L420-L425
* recompile, run the example
* ---> as far as I can tell the orientation seems to be detected perfectly

**Expected behavior**

If OpenCV is built to correctly detect the orientation with non-symmetrical images, these lines should be removed and the example would work even with an upside-down camera. Or perhaps I'm missing some vital information.

**Screenshots**

Current behavior (corners detected in wrong orientation):
![image](https://user-images.githubusercontent.com/4965387/105487032-2508be80-5cb8-11eb-9831-bf30d2348b54.png)

Flipping disabled (corners detected correctly):
![image](https://user-images.githubusercontent.com/4965387/105486767-baf01980-5cb7-11eb-8618-6a3ad9515798.png)

_edit_

And here's an example with the same patch (flipping points disabled) with a symmetrical image (last column covered, starts and ends with a black square) --> corners not detected correctly. The algorithm does seem to take their color into consideration.
![image](https://user-images.githubusercontent.com/4965387/105496703-82a40780-5cc6-11eb-85cc-0d0d635d88c4.png)

**Comment by qm13** [comment]
@tostercx please also look at https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1420.

There may be other bugs in the sample code. You are welcome to submit fixes.
