### ISSUE TITLE
Laptop Recommendations for Running 3 Sensors

### ISSUE THREAD

**Issue by DudeWithEmoTiger** [microsoft/Azure-Kinect-Sensor-SDK#1493]
Is it possible to run body tracking sdks with 3 sensors on a fairly high performance gaming laptop?

Would something like Asus Rog Strix and Zephyrus configs equipped with NVIDIA 2070 and above as well as 8 gb of VRAM work? 

They generally contain 3 USB3 Ports so connecting the cameras hopefully shouldn’t be an issue. 

I am looking for a portable solution because I may need to use the sensors in multiple locations. I also don’t want to break the bank by buying multiple host computers.

I have searched across this thread for specific recommendations in the laptop space but haven’t found that many. I know the solution utilized by DepthKit provides a baseline, but I am still unsure if gaming laptops with enough ports potentially solve the bandwidth issue mentioned by developers.

So, yeah, any help or advice would be appreciated!

**Comment by diablodale** [comment]
I doubt you will be successful with the current Body Tracking SDK v1.0.1.
I have a new XMG laptop with RTX 2070 Super max-p 8gb at 115w.
A single Kinect Azure sensor running body tracking consumes ~70% of the RTX GPU and delivers 30fps.
