### ISSUE TITLE
Question about external parameters for depth

### ISSUE THREAD

**Issue by logic03** [microsoft/Azure-Kinect-Sensor-SDK#1500]
我在实验的时候，k4a_calibration_t获得的深度图的内参是正确的，但是得到的深度图外参一直都是固定的数值如下：
rotation	{1.00000000, 0.000000000, 0.000000000, 0.000000000, 1.00000000, 0.000000000, 0.000000000, 1.00000000}
translation{0.000000000, 0.000000000, 0.000000000}
请问是为什么呢？我应该如何获得一个摄像机的深度图外参呢？
________________________________________________________________________________________________________

When I was doing the experiment, the internal parameters of the depth map obtained by k4a_calibration_t were correct, but the external parameters of the depth map obtained were always fixed as follows:
rotation	{1.00000000, 0.000000000, 0.000000000, 0.000000000, 1.00000000, 0.000000000, 0.000000000, 1.00000000}
translation{0.000000000, 0.000000000, 0.000000000}
May I ask why?How do I get external parameters for a camera depth map?

**Comment by jaygullapalli** [comment]
Could you provide the sequence of function calls (or code snippet) that you use when you get this information? It will provide a better insight for us into the issue.
