### ISSUE TITLE
Azure Kinect point density

### ISSUE THREAD

**Issue by arudomanenko** [microsoft/Azure-Kinect-Sensor-SDK#1505]
Hi! Thank you for great API for kinect) 
Unfortunately, I have a question about hardware of device, because I didn't find it in datasheet
How much is density of device is? If I have a square object 400mm x 400mm x 10 mm, how many point I will have in point cloud, based on kinect capture?
Sorry, if a question is little bit irrelevant to repo

**Comment by qm13** [comment]
The Azure Kinect camera resolution is 1024 x 1024 with a 120deg FOV. This means the angular resolution is ~8.5 pixels per degree. How many degrees of FOV is covered by the square object depends on the distance the camera is from the object. You can use simple trigonometry to calculate the angle based on the distance.
