### ISSUE TITLE
can't compile C:2039 error cinttypes.h

### ISSUE THREAD

**Issue by drhalftone** [microsoft/Azure-Kinect-Sensor-SDK#1507]
Never had a problem compiling my code before using Qt with VS2017; however, I now have brand new Windows laptop with VS 2019 Community and Qt 5.12.2 and now pops up an error I have never seen before:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(23): error C2039: 'imaxdiv_t': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(23): error C2873: 'imaxdiv_t': symbol cannot be used in a using-declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(25): error C2039: 'imaxabs': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(25): error C2873: 'imaxabs': symbol cannot be used in a using-declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(26): error C2039: 'imaxdiv': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(26): error C2873: 'imaxdiv': symbol cannot be used in a using-declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(27): error C2039: 'strtoimax': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(27): error C2873: 'strtoimax': symbol cannot be used in a using-declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(28): error C2039: 'strtoumax': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(28): error C2873: 'strtoumax': symbol cannot be used in a using-declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(29): error C2039: 'wcstoimax': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(29): error C2873: 'wcstoimax': symbol cannot be used in a using-declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(30): error C2039: 'wcstoumax': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\cinttypes(30): error C2873: 'wcstoumax': symbol cannot be used in a using-declaration

**Comment by drhalftone** [comment]
I was able to fix the issue by commenting out all references to the cinttypes.h header, which brings up the obvious question why are the references there in the first place?

**Comment by drhalftone** [comment]
What is the solution?

**Comment by qm13** [comment]
@drhalftone How is this related to Azure Kinect?

**Comment by drhalftone** [comment]
They are your header files (k4a/*.h) that are causing the problem.  I deleted the "#include <cinttypes>” calls and then everything compiles fine.  



On Feb 16, 2021, at 2:56 PM, qm13 <notifications@github.com> wrote:


@drhalftone <https://github.com/drhalftone> How is this related to Azure Kinect?

**Comment by qm13** [comment]
@drhalftone From your comments you imply that this project - using QT and Azure Kinect - used to compile ok on VS2017 but after upgrading to VS2019 no longer compiles? What happens when you compile a Azure Kinect sample (that does not use QT)?

**Comment by DISAPPEARED13** [comment]
it's weird that I have to commenting the reference to solve the problem, but it does work. Might be the complier version is the problem. But why?
