### ISSUE TITLE
order of coefficients in raw calibration intrinsics

### ISSUE THREAD

**Issue by seigeweapon** [microsoft/Azure-Kinect-Sensor-SDK#1518]
hi, This is a question, not a bug report.

In the raw calibration json, I can get 14 parameters, as below:
`{
        "CalibrationInformation": {
                "Cameras": [{
                        "Intrinsics": {
                                "ModelParameterCount": 14,
                                "ModelParameters": [0.49079370498657227, 0.503465473651886, 0.49270063638687134, 0.49279910326004028, 0.92184948921203613, 0.50040090084075928, 0.028360467404127121, 1.2584241628646851, 0.75181210041046143, 0.14418977499008179, 0, 0, 2.7718663204723271E-6, -3.0782209705648711E-6], ...`

I wonder if the order of parameters is the same of k4a_calibration_intrinsic_parameters_t? Just to make sure I didn't make wrong assumption. Thanks.

typedef union
{
    /** individual parameter or array representation of intrinsic model. */
    struct _param
    {
        float cx;            /**< Principal point in image, x */
        float cy;            /**< Principal point in image, y */
        float fx;            /**< Focal length x */
        float fy;            /**< Focal length y */
        float k1;            /**< k1 radial distortion coefficient */
        float k2;            /**< k2 radial distortion coefficient */
        float k3;            /**< k3 radial distortion coefficient */
        float k4;            /**< k4 radial distortion coefficient */
        float k5;            /**< k5 radial distortion coefficient */
        float k6;            /**< k6 radial distortion coefficient */
        float codx;          /**< Center of distortion in Z=1 plane, x (only used for Rational6KT) */
        float cody;          /**< Center of distortion in Z=1 plane, y (only used for Rational6KT) */
        float p2;            /**< Tangential distortion coefficient 2 */
        float p1;            /**< Tangential distortion coefficient 1 */
        float metric_radius; /**< Metric radius */
    } param;                 /**< Individual parameter representation of intrinsic model */
    float v[15];             /**< Array representation of intrinsic model parameters */
} k4a_calibration_intrinsic_parameters_t;

**Comment by qm13** [comment]
Yes the order of parameters is the same as k4a_calibration_intrinsic_parameters_t. A few extra points:
Few extra notes 

1. codx=cody=0
2. Both principal points and focal length are normalized wrt image width and height
3. metric_radius is irrelevant.
