### ISSUE TITLE
Body Tracker mid-February 2021 update delayed?

### ISSUE THREAD

**Issue by Brekel** [microsoft/Azure-Kinect-Sensor-SDK#1519]
There have been mentions of a Body Tracker SDK update being right around the corner, scheduled for mid February 2021, bringing NVidia 3000 support (and hopefully other improvements).

Is there any word on the delay and/or a new estimate?
Numerous people are eagerly awaiting it so even a beta would help tremendously.

**Comment by qm13** [comment]
Sorry for the delay. Adding RTX 30xx support threw up some unexpected issues. We plan to build the final release candidate Friday and publish the release early next week.

**Comment by Brekel** [comment]
That's great to hear, thanks for sharing that info!

**Comment by jaymimc** [comment]
> Sorry for the delay. Adding RTX 30xx support threw up some unexpected issues. We plan to build the final release candidate Friday and publish the release early next week.

Has the RTX 3xxxx support update been published now then?

**Comment by Jeremboo** [comment]
And will it be accompanied by support for other graphics cards? I'm waiting for some information about the AMD GPUs support :)

**Comment by Blargstomp404** [comment]
> 
> 
> Sorry for the delay. Adding RTX 30xx support threw up some unexpected issues. We plan to build the final release candidate Friday and publish the release early next week.

New with Azure Kinect, is there a link to try out the rc for rtx 3xxx cards?

**Comment by Brekel** [comment]
Looks like the new MSI installer just hit the website :)
https://docs.microsoft.com/en-us/azure/Kinect-dk/body-sdk-download

**Comment by AswinkarthikeyenAK** [comment]
Hi Guys, 
Has anyone tested the NVidia 30xx series for body tracking in Ubuntu 18.04 by any chance? It will be really helpful to know this information.

Thanks
