### ISSUE TITLE
Open source BT SDK

### ISSUE THREAD

**Issue by rfilkov** [microsoft/Azure-Kinect-Sensor-SDK#1521]
Please consider again open-sourcing the Body Tracking SDK, unless there is something really secretive and proprietary in it. This may help workaround the major issues, because many users would try to improve it in many directions. It may ease and help the team at the same time. The blockers with the NVidia and other GPUs could have been solved months ago, if the source was open.

**Comment by qm13** [comment]
There are no plans to open source the Body Tracking SDK. The DNN model is inferenced using ONNX Runtime which is open-sourced.

**Comment by rfilkov** [comment]
OK. Thank you for the sincere response! It was expected.
Unfortunately, the body tracking ruined this otherwise great sensor.
