### ISSUE TITLE
Azure Kinect Camera Update to highest specification 

### ISSUE THREAD

**Issue by hayeonp95** [microsoft/Azure-Kinect-Sensor-SDK#1523]
Hi, 

It has been 10months since the azure kinect camera has updated, so I was wondering when would you do update to the highest specification? 

I'm currently using azure kinect and developing fitness training at home and what concerns me is its discontinuation as no updates has been done for 10 months. 

Thank you!

**Comment by dimitrijevic** [comment]
Think you should read [this](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1496) 

I’d like to know if those future devices are going to be able to sync with the AKDK also, or should I purchase as many of those as I can now, given that my project’s goal was to use multiple Kinect devices in the end...

I’m guessing the new devices will have a lesser price point given LG announced mass production of their camera modules based on MS IP two days ago...

**Comment by Brekel** [comment]
@dimitrijevic do you have a link to LG's announcement? Sounds interesting!

> I’m guessing the new devices will have a lesser price point given LG announced mass production of their camera modules based on MS IP two days ago...

**Comment by dimitrijevic** [comment]
> @dimitrijevic do you have a link to LG's announcement? Sounds interesting!
> 
> > I’m guessing the new devices will have a lesser price point given LG announced mass production of their camera modules based on MS IP two days ago...

@Brekel Sure here it is: http://www.lginnotek.com/en/itk_news/lg-innotek-joins-hands-with-microsoft-to-proliferate-cloud-connected-3d-sensing-camera/

I’d love to see a plethora of new devices out there if they can sync with each other, though I’m not sure how will they be unifying access to those on multiple platforms and if they do, could we expect them all to use the Windows.Media.Capture namespace for C# windows apps for the upcoming commercial SDK?

Or if they can’t sync is there going to be an AKDK fire sale in EU? :)
