### ISSUE TITLE
How to get Exposure Time and White Balance while in AutoMode

### ISSUE THREAD

**Issue by KnoxBorquez** [microsoft/Azure-Kinect-Sensor-SDK#1525]
Hi everyone

I need to save the Device configuration used while in AutoMode, so I can match color/brightness/etc with a future frame, but GetColorControl() gives me the set value while in Manual mode.

Any way of getting the value the device is using while in AutoMode ?

**Comment by qm13** [comment]
You should use `k4a_image_get_exposure_usec()` to get the exposure settings.
