### ISSUE TITLE
Body tracking SDK version 1.1.0 CUDA bug

### ISSUE THREAD

**Issue by Deok-Won-Lee** [microsoft/Azure-Kinect-Sensor-SDK#1537]
Hi, I'm using Kinect Azure and the body tracking sdk.
when i excuted the "k4abt_simple_3d_viewer" there is warnning messages like below.
I think the message means that the body tracker is not using GPU. 
And it seems like there is some link error btw tracking sdk and cuda lib.

![Screenshot from 2021-03-22 19-22-27](https://user-images.githubusercontent.com/79687158/111975442-f5edbc80-8b43-11eb-8c1a-2272d202e137.png)

My environment is
Sensor sdk : 1.4
Body tracking sdk : 1.1
Cuda version : 11.1
cudnn version : 8.0.5
OS : Ubuntu 18.04

Help!
Thanks

**Comment by qm13** [comment]
This is expected. ONNX Runtime now warns when a model instructions cannot be executed on GPU. The DirectML execution environment drops back to CPU. The CUDA execution environment drops back to CPU. The TensorRT execution environment drops back to CUDA and then CPU.

The model is still running on GPU with the exception of the Shape__40 node.

**Comment by qm13** [comment]
Fixed
