### ISSUE TITLE
model_path for body tracking model seems to not be taken in account

### ISSUE THREAD

**Issue by Moovency** [microsoft/Azure-Kinect-Sensor-SDK#1539]
Hi, i'm trying to use the light model in our visual studio project.

I assign the value "dnn_model_2_0_lite_op11.onnx" to the model_path variable the body tracking config, but when I execute I have an error looking for the previous model "dnn_model_2_0.onnx"

![image](https://user-images.githubusercontent.com/74403053/112304800-32353000-8c9e-11eb-9d81-d2b0e650633d.png)

I display the model_path after assigning itand the value is correct
![image](https://user-images.githubusercontent.com/74403053/112305407-f2227d00-8c9e-11eb-82fc-4d1c55cff6d7.png)

Could you help me please ?

**Comment by vladalx** [comment]
It looks like the model_path received by the TrackerHost::Create is null or empty. Please make sure that the k4abt_tracker_configuration_t instance referenced by the GetConfigBodyTracker is the same one that is used in the CreateBodyTracker function.

**Comment by Moovency** [comment]
Thank you for your quick response.
When I check the value in the create function I obtain that:
![image](https://user-images.githubusercontent.com/74403053/112310861-55171280-8ca5-11eb-85e5-4aab19e5c157.png)

**Comment by vladalx** [comment]
Are you sure you are using the right k4abt.dll from the 1.1.0 version ?

**Comment by Moovency** [comment]
That was the problem, I was launching my program in a folder containing files from a previous version generation and they were taken instead of the  version.

Thank you for your help my problem is solved.
