### ISSUE TITLE
Body tracking performance is too low in C# winform.

### ISSUE THREAD

**Issue by ykk271** [microsoft/Azure-Kinect-Sensor-SDK#1547]
I made a simple example to save RGB video and skeleton data. but FPS is too low. When capturing, CPU and GPU use is only 20% and 10% respectively. How to improve FPS or GPU usage rate? The FPS is calculated between 15 and 10.

**Setup**
- Sensor SDK 1.4.1
- Body tracking SDK 1.0.1
- CPU: AMG Ryzen 7 3700X
- GPU: RTX2060

**Comment by qm13** [comment]
Can you share the simple example?

**Comment by ykk271** [comment]
Thank you for your response.

My code here. 
===============================================
using System;
using System.Drawing;
using System.Windows.Forms;
using Microsoft.Azure.Kinect.Sensor;
using Microsoft.Azure.Kinect.BodyTracking;
using Image = Microsoft.Azure.Kinect.Sensor.Image;
using PixelFormat = System.Drawing.Imaging.PixelFormat;
using System.Buffers;
using System.Threading;

namespace Gait_Kinect
{
    public partial class Form1 : Form
    {
        Device Kinect;
        Tracker bodyTracker;
        Calibration calib;
        Skeleton skl;

        Bitmap ColorBitmap;
        bool Loop = true;

        Thread t;
        Thread t2;

        public Form1()
        {
            InitializeComponent();
            InitKinect();

            t = new Thread(new ThreadStart(KinectLoop));
            t.Start();

            t2 = new Thread(new ThreadStart(KinectLoop2));
            t2.Start();
        }

        private void KinectLoop()
        {
            while (Loop)
            {
                unsafe
                {
                    Image colorImage = Kinect.GetCapture().Color;
                    using (MemoryHandle pin = colorImage.Memory.Pin())
                    {
                        ColorBitmap = new Bitmap(
                             colorImage.WidthPixels,
                             colorImage.HeightPixels,
                             colorImage.StrideBytes,
                           PixelFormat.Format32bppArgb,
                             (IntPtr)pin.Pointer);
                    }
                }
                PictureBox_RGB.Image = ColorBitmap;
            }
        }

        private void KinectLoop2()
        {
            while (Loop)
            {   
                bodyTracker.EnqueueCapture(Kinect.GetCapture());
                Frame frame = bodyTracker.PopResult();
                if (frame != null)
                {
                    uint bodyNum = frame.NumberOfBodies;
                    if (bodyNum > 0)
                    {
                        skl = frame.GetBodySkeleton(0);
                    }
                }
                frame.Dispose();
            }
        }

        private void InitKinect()
        {
            Kinect = Device.Open(0);

            Kinect.StartCameras(new DeviceConfiguration
            {
                ColorFormat = ImageFormat.ColorBGRA32,
                ColorResolution = ColorResolution.R1536p,
                DepthMode = DepthMode.NFOV_2x2Binned,
                SynchronizedImagesOnly = true,
                CameraFPS = FPS.FPS30,
            });

            calib = Kinect.GetCalibration();
            bodyTracker = Tracker.Create(calib, new TrackerConfiguration
            {
                ProcessingMode = TrackerProcessingMode.Gpu,
                SensorOrientation = SensorOrientation.Default,
                GpuDeviceId = 1
            });
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            Loop = false;
            Kinect.StopCameras();
            t.Abort();
            t2.Abort();
        }
    }
}

**Comment by ykk271** [comment]
Thanks for your response.
my code is here.

```csharp
using System;
using System.Drawing;
using System.Windows.Forms;

using Microsoft.Azure.Kinect.Sensor;
using Microsoft.Azure.Kinect.BodyTracking;

using Image = Microsoft.Azure.Kinect.Sensor.Image;
using PixelFormat = System.Drawing.Imaging.PixelFormat;
using System.Buffers;
using System.Threading;

namespace Gait_Kinect
{
    public partial class Form1 : Form
    {
        Device Kinect;
        Tracker bodyTracker;
        Calibration calib;
        Skeleton skl;

        Bitmap ColorBitmap;
        bool Loop = true;

        Thread t;
        Thread t2;

        public Form1()
        {
            InitializeComponent();
            InitKinect();

            t = new Thread(new ThreadStart(KinectLoop));
            t.Start();

            t2 = new Thread(new ThreadStart(KinectLoop2));
            t2.Start();
        }

        private void KinectLoop()
        {
            while (Loop)
            {
                unsafe
                {
                    Image colorImage = Kinect.GetCapture().Color;
                    using (MemoryHandle pin = colorImage.Memory.Pin())
                    {
                        ColorBitmap = new Bitmap(
                             colorImage.WidthPixels,
                             colorImage.HeightPixels,
                             colorImage.StrideBytes,
                           PixelFormat.Format32bppArgb,
                             (IntPtr)pin.Pointer);
                    }
                }
                PictureBox_RGB.Image = ColorBitmap;
            }
        }

        private void KinectLoop2()
        {
            while (Loop)
            {   
                bodyTracker.EnqueueCapture(Kinect.GetCapture());
                Frame frame = bodyTracker.PopResult();
                if (frame != null)
                {
                    uint bodyNum = frame.NumberOfBodies;
                    if (bodyNum > 0)
                    {
                        skl = frame.GetBodySkeleton(0);
                    }
                }
                frame.Dispose();
            }
        }

        private void InitKinect()
        {
            Kinect = Device.Open(0);

            Kinect.StartCameras(new DeviceConfiguration
            {
                ColorFormat = ImageFormat.ColorBGRA32,
                ColorResolution = ColorResolution.R1536p,
                DepthMode = DepthMode.NFOV_2x2Binned,
                SynchronizedImagesOnly = true,
                CameraFPS = FPS.FPS30,
            });

            calib = Kinect.GetCalibration();
            bodyTracker = Tracker.Create(calib, new TrackerConfiguration
            {
                ProcessingMode = TrackerProcessingMode.Gpu,
                SensorOrientation = SensorOrientation.Default,
                GpuDeviceId = 1
            });
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            Loop = false;
            Kinect.StopCameras();
            t.Abort();
            t2.Abort();
        }
    }
}

```

**Comment by YJ-L-2017** [comment]
I have the same problem,CPU and GPU use is only 50% and 20% respectively,The FPS is calculated between 15 and 30.
Setup

Sensor SDK 1.4.1
Body tracking SDK 1.0.1
CPU: i9 9880
GPU: RTX1650

**Comment by fkavache** [comment]
Hi @YJ-L-2017,

Could you please provide a simple example project to reproduce this issue?

**Comment by Thaina** [comment]
~~In unity also slow, around 100 ms per `tracker.EnqueueCapture`. And so the latency are very obvious. Unlike `Azure Kinect Body Tracking Viewer` 3D visualization app that was very fast~~

~~Is it because I use `TrackerProcessingMode.Cuda` ?~~

It seem there was many problem altogether unrelated to this. The latency in build exe actually came from the reason I have not enough dll in my build folder to allow me to use GPU. And unity editor just have its own latency when run in editor so sorry for unnecessary digging this old thread
