### ISSUE TITLE
Body Tracking C# Wrapper on Linux (or Alternative)

### ISSUE THREAD

**Issue by leskodan** [microsoft/Azure-Kinect-Sensor-SDK#1553]
This may be just as much a question as it is a feature request.

**Is your feature request related to a problem? Please describe.**

I have run into the same error outlined in #1304 in which the C# wrapper (specifically creating a tracker) is not supported on Linux. 

**Describe the solution you'd like**

First off, I'd like to add my vote for this feature as I feel that there would be tremendous value in the ability to build with the C# wrapper in .NET Core on Linux.

**Describe alternatives you've considered**

Here is where my question comes in. I am wondering if building a .NET Core application in a docker container would be a potentially viable option for working around this issue? I've seen some issues with accepting the EULA when building a docker container specifically with body tracking, so I have steered away from this so far. That said, I am curious if anyone has gotten this to work. If so, it would be great to document this somewhere as it is great for folks looking to use the C# Wrapper.

**Comment by qm13** [comment]
Added in v1.1.2
