### ISSUE TITLE
k4abt_simple_3d_viewer source?

### ISSUE THREAD

**Issue by fractalfantasy** [microsoft/Azure-Kinect-Sensor-SDK#1562]
We’re having trouble getting Body Tracking SDK (1.1.0) running with its new environment variables. Getting no errors / exceptions / crashes, it just doesn't seem to start. (gyp recompilation is succeeding, and CPU mode works).

Would be helpful if you updated the samples repository so that we can have a look at the k4abt_simple_3d_viewer source.

**Comment by qm13** [comment]
The environment variables are read by ONNX Runtime (DLL). There is no changes needed to the samples.

What operating system are you using? What environment variables are you using?

**Comment by mikkamikka** [comment]
@qm13 We are using Windows 10 (v.1909)
Environment variables we've set at Windows system user level:
```
ORT_TENSORRT_ENGINE_CACHE_ENABLE=1
ORT_TENSORRT_CACHE_PATH="C:\Temp"
```
Are there any special 'ONNX Runtime environment variables' we should've set somewhere else??

Tracker configuration set to default:
`k4abt_tracker_configuration_t tracker_config = K4ABT_TRACKER_CONFIG_DEFAULT;`
I guess those Tensor related env. variables make no sense since we are using default processing mode K4ABT_TRACKER_PROCESSING_MODE_GPU_DIRECTML
(https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/1.1.x/k4abttypes_8h_source.html)

Another question is: 
Should we have CUDA 11.1+ and CuDNN v.8+ runtime installed system-wide to run body tracking v1.1.0 ?

**Comment by qm13** [comment]
I am confused. Are you attempting to use CUDA, DirectML, or TensorRT?

All the necessary NVIDIA files are included in the .msi install. They do not need to be system wide. You can drop them into your project folder. You need the correct NVIDIA driver for your card. See troubleshooting section of the documentation.

**Comment by mikkamikka** [comment]
@qm13 We are attempting to use DEFAULT processing mode: DirectML

GPU driver is up to date: NVIDIA driver version 465.89

Logging shows that dependencies check, ONNX runtime, and tracker creation is successful:
```
New logging session started

[2021-04-12 20:21:37.199] [info] [t=14612] [K4ABT] D:\a\1\s\src\TrackerHost\TrackerHost.cpp (465): VerifyDependencies(). Verifying Dependencies!
[2021-04-12 20:21:37.306] [info] [t=14612] [K4ABT] D:\a\1\s\src\TrackerHost\TrackerHost.cpp (146): Create(). Initializing CUDA and ONNX Runtime... 
[2021-04-12 20:21:54.711] [info] [t=14612] [K4ABT] D:\a\1\s\src\TrackerHost\TrackerHost.cpp (168): Create(). Done.
```

I've noticed that the k4a.dll you deliver with the Body Tracking SDK v1.1.0 example (on the left) differs in size from the one delivered with the Kinect SDK v1.4.1 (on the right), while the file version is the same:
![k4a_compare](https://user-images.githubusercontent.com/2395086/114607853-b24f2400-9ca5-11eb-9c79-b391bab20f5b.PNG)

Maybe this is the reason for the problem?

**Comment by scotthsu98052** [comment]
@vladalx please check with fractalfantasy about the directML issue.

**Comment by fractalfantasy** [comment]
Perhaps we're installing it wrong? 

With NuGet now broken on the latest update, it's difficult to understand how to update the Body Tracking SDK on the **k4abt_simple_3d_viewer** sample. We're simply replacing files within BT SDK 1.0.1 package folder - I admit this is a hacky solution, curious how you envisioned us to use this BT release without NuGet?

Here's the steps we're taking:

### 1) install the NuGet packages, and build solution (vs2019)
![image](https://user-images.githubusercontent.com/12879320/115785863-0b961200-a38e-11eb-9868-8d5a4b185bf2.png)

### 2) replace these files with the ones from the new BT SDK 1.1.0
![image](https://user-images.githubusercontent.com/12879320/115785971-31231b80-a38e-11eb-8ee2-6360837a8c4b.png)
![image](https://user-images.githubusercontent.com/12879320/115786401-c4f4e780-a38e-11eb-8dfe-93d46546e6d1.png)
![image](https://user-images.githubusercontent.com/12879320/115786434-cf16e600-a38e-11eb-9985-b3df981934f5.png)

### 3) copy these DLL's into the bin/release folder
![image](https://user-images.githubusercontent.com/12879320/115786526-f2419580-a38e-11eb-9032-69e6bb1883ab.png)

Thanks for looking into this!

**Comment by vladalx** [comment]
Hello

pls clarify the steps you are taking to get to this error, and let me know :

1. if you run k4abt_simple_3d_viewer from the Program Files/azure kinect bodytracking sdk/tools folder, is it working ?
2. are you using the simple_3d_viewer sample source code from git ?

Thank you

**Comment by fractalfantasy** [comment]
Thanks @vladalx 

1. Yes  k4abt_simple_3d_viewer.exe from Program Files works
2. Yes we are using the sample code from git

--

We actually got the sample running by replacing .dlls in the v1.0.1 NuGet but there were stability issues (it was a hacky solution). 

Decided to take another route using a third party node, everything seems installed fine but getting this error when trying to initiate the tracker. 

Does this error tell you anything?  Perhaps it's not calling upon the right onnx dll?

```
Exception during initialization: C:\source\ort-restore\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1487)\onnxruntime.dll!00007FFCD2E8F2AC: (caller: 00007FFCD2EDEE66) Exception(3) tid(366c) 80070057 The parameter is incorrect.

[2021-04-29 14:36:13.814] [error] [t=13932] [K4ABT] ..\src\TrackerHost\TrackerHost.cpp (185): Create(). Exception during initialization: C:\source\ort-restore\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1487)\onnxruntime.dll!00007FFCD2E8F2AC: (caller: 00007FFCD2EDEE66) Exception(3) tid(366c) 80070057 The parameter is incorrect.

[2021-04-29 14:36:13.815] [error] [t=13932] [K4ABT] ..\src\sdk\k4abt.cpp (38): tracker->Create(sensor_calibration, config) returned failure in k4abt_tracker_create()
```

**Comment by qm13** [comment]
@fractalfantasy can you verify you are attempting to execute with DirectML? If so what is the version of Windows you are using.

**Comment by fractalfantasy** [comment]
> @fractalfantasy can you verify you are attempting to execute with DirectML? If so what is the version of Windows you are using.

yes trying to initiate the DirectML model
Windows 10 (v.1909)

--

Fyi this is the thread where we are trying to figure it out:
https://github.com/wouterverweirder/kinect-azure/issues/40

**Comment by qm13** [comment]
@fractalfantasy looking over this thread is it correct that you can get k4abt_simple_3d_viewer.exe running with DirectML but cannot get your project running?
If that is the case can you please verify you have the correct DLLs in place for your project.

**Comment by fractalfantasy** [comment]
Yes k4abt_simple_3d_viewer.exe runs with DirectML fine.

Not sure if you saw the thread I linked, we’ve been trying to update the kinect-azure node but lack of NuGet is making things difficult, still figuring out how to get the .dll referenced properly.

Are you planning on adding NuGet in the future or is it not possible with this architecture?

**Comment by kfzyqin** [comment]
I believe I am facing the same problem. What is your GPU?

**Comment by qm13** [comment]
All, we are working in a new NuGet package which will be released soon. This package will NOT include any of the NVIDIA required DLLs. It will also include only the normal model. NuGet packages are limited to 250MB in size and many of the NVIDIA DLLs have ballooned to far exceed this limit.

**Comment by fractalfantasy** [comment]
This has been super confusing, but we figured out it has something to do with windows library search order - the problem is that it loads the system directml.dll instead of the custom dll (likely because the system's directml.dll it's already running / loaded into memory).
https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

I think we'll get to the bottom of it this week, will let you know when/if we come up with a solution.
