### ISSUE TITLE
Unity 3D apps are freezing while trying to close them (Body Tracking SDK 1.1.0)

### ISSUE THREAD

**Issue by cavisions** [microsoft/Azure-Kinect-Sensor-SDK#1563]
The new Body Tracking SDK (1.1.0) seems keeping (for the Unity 3D applications) the SDK libraries in use preventing the application from shutting down. The Kinect Sensor is turned off, but the application is still running. Any help would be appreciated. We have been using the older SDK without such complications.

### Setup

- Microsoft Windows [Version 10.0.19042.870]
- VS2019 Community v16.9.3 building 64-bit
- Sensor SDK 1.4.1
- Body Track SDK 1.1.0
- App of your choice; I used the https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/sample_unity_bodytracking updated to Body Tracking SDK 1.1.0 (I can share the upgraded sample if needed)
- Intel i7 with 32GB ram and RTX2060

**To Reproduce in Unity**

1. Start application that uses Kinect Azure
2. Stop the application in Unity
3. Try to close Unity
4. Unity is not responding

**To Reproduce in build**

1. Start application that uses Kinect Azure
2. Try to close the application
3. Application is not responding

**Comment by cavisions** [comment]
Have you reproduced this issue? Is there any workaround for this? I'd appreciate some info, because I need to decide whether revert my project to the older SDK or is it worth waiting. Thank you in advance!

**Comment by anantley** [comment]
Hi @cavisions,  
I got it to repro, looking into the crash now
 Angus

**Comment by muadiber** [comment]
I have the same problem

**Comment by cavisions** [comment]
@anantley Are there any news here? Thanks in advance!

**Comment by anantley** [comment]
@cavisions, there is a fix now for the threading problem, with an updated readme and batch file.
https://github.com/microsoft/Azure-Kinect-Samples/pull/61

**Comment by seph14** [comment]
still crash on quit of standalone build.

tested unity 2019.1.2f1 / 2020.3.0 / 2020.3.1, windows10 personal / enterprise.

**Comment by anantley** [comment]
@seph14  I just did a fresh git and followed the directions from the readme and could not repro the bug.
Unity 2019.1.2  

I did have some trouble getting the stand alone to run, but here are the dlls in the exe folder that worked for me
![image](https://user-images.githubusercontent.com/60194205/120261662-35740b80-c24d-11eb-9d2a-a992b9556cfe.png)

I had to close explorer and reopen it to get the dlls to register.  But it had no problem closing the app while the body tracking was running.

Do you have a crash log?  Or any more config details.  ie visual studio version?

**Comment by seph14** [comment]
@anantley that are the dlls I have. Just tested and still crashing. 

Nothing meaningful in the log, only related to this might be the following lines:
```
Setting up 3 worker threads for Enlighten.
  Thread -> id: 3db4 -> priority: 1 
  Thread -> id: 380c -> priority: 1 
  Thread -> id: 26b0 -> priority: 1 
```
These are the last lines in the log.

I changed process mode in SkeletalTrackingProvider to
`ProcessingMode = TrackerProcessingMode.Cuda`
But TrackerProcessingMode.GPU crashes for me too.

Other configs:
VS2017 (15.9.16) (which I think it's irrelevant because Unity build is using their own compiler no?)
script backend:  Mono
API level:            .net standard 2.0
incremental GC: yes
