### ISSUE TITLE
Hand Tracking in Unity using Azure Kinect DK ?

### ISSUE THREAD

**Issue by UnityQueriesAsk** [microsoft/Azure-Kinect-Sensor-SDK#1574]
Hello All, 

This is not an issue. I need some help.
I have implemented the Azure Kinect DK Unity basic integration. My actual problem is I have to control the player using hand tracking.

Please check the following link once I want this type of control in Unity using Azure Kinect DK.

https://youtu.be/-msUHAhwru8

Can you please explain how can I implement this type of control ?

Thank you.

**Comment by qm13** [comment]
Are you looking for wrist tracking or full articulated (fingers) tracking?

**Comment by Thaina** [comment]
> Are you looking for wrist tracking or full articulated (fingers) tracking?

I came here trying to find finger solution
