### ISSUE TITLE
Enable easy distribution of Firmware

### ISSUE THREAD

**Issue by MsDerekMa** [microsoft/Azure-Kinect-Sensor-SDK#158]
Currently we only have the firmware blob in the MSI. This means if you want to try out a firmware you must install the new SDK. Or if you want to roll back after installing a new SDK and firmware, that you need to install the old SDK somewhere.

Ideally, we should have a way to directly get at an arbitrary firmware version.

**Comment by Brent-A** [comment]
We need a design for how to handle this. We don't have a good place to host these at the moment:
* GitHub is not appropriate since these are binaries and are licensed separately from the SDK
* The MSI is only usable on Windows

We probably want to use one of the packaging systems for this.

**Comment by wes-b** [comment]
Firmware is currently in MSI and NuGet packages going forward. We still need to release initial firmware so users can go back to factory release version of firmware for early SDK versions.

**Comment by wes-b** [comment]
We can address if this is ever needed
