### ISSUE TITLE
How can I get the depth value of a specific point in the image from the live stream of Azure Kinect

### ISSUE THREAD

**Issue by lavender-mkl** [microsoft/Azure-Kinect-Sensor-SDK#1581]
I'm working on a project. This project involves a person reaching into the box to take the parts, and then assemble the parts. I want to know the depth value of this person's hand when he caught the box, so that I can judge whether this person has grasped the box or not, how can I get the depth value?

**Comment by diablodale** [comment]
I recommend you read the SDK documentation and then review the example code.

The SDK documentation has tutorials for how to get body tracking information for joints including the hand. https://docs.microsoft.com/en-us/azure/kinect-dk/build-first-body-app
You can easily get the x,y,z real world coordinate. If you want a depth value you can transform the x,y,z coordinate into a depthmap coordinate with the coordinate transform functions https://docs.microsoft.com/en-us/azure/kinect-dk/use-calibration-functions

The examples is git repo has many examples https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples
