### ISSUE TITLE
Camera calibration and transformation

### ISSUE THREAD

**Issue by ipa-vsp** [microsoft/Azure-Kinect-Sensor-SDK#1585]
Hello,

I am trying to calculate the dimension of a box placed on the table using Depth data. Therefore, the Azure Kinect camera is placed above around 70 cm above the table and facing the top surface of the box. During the calculation, on the Y axis, I have calculated a 6.08 degree of tilt, which is expected because of the [depth sensor tilt.](https://docs.microsoft.com/de-de/azure/kinect-dk/coordinate-systems#depth-and-color-camera) 

I have two questions,
1. How to calibrate the camera to remove the 6-degree sensor tilt? Are there any right steps that I have to perform to eliminate the tilt?
2. Are there any API support to obtain coordinate transformation (position and orientation) between the colour camera and depth frame. 

Thank you.

**Comment by diablodale** [comment]
HI. The Kinect documentation discusses all of this and the sdk provides functions. I recommend you read all the Kinect docs starting with all of the HOWTO guides at https://docs.microsoft.com/en-us/azure/kinect-dk/about-sensor-sdk
