### ISSUE TITLE
how can I Azure Kinect in opencv(c++)  show the depth image

### ISSUE THREAD

**Issue by lavender-mkl** [microsoft/Azure-Kinect-Sensor-SDK#1587]
I want to use opencv to show real-time depth images, how can I program it?

**Comment by diablodale** [comment]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1209
https://github.com/microsoft/Azure-Kinect-Samples/tree/master/opencv-kinfu-samples
