### ISSUE TITLE
Question about the maximum skeletons the kinect tracks

### ISSUE THREAD

**Issue by tctoki** [microsoft/Azure-Kinect-Sensor-SDK#1594]
Hi, I have a question about the maximum number of the skeletons tracking.

Since the maximum number of the skeletons Kinect can detect is six, if I have more than 6 people in front of the Kinect, will it get the closet six skeletons, or will it get the first six skeletons that it detects no matter what distances from the Kinect, or it depends on the skeleton confidence?

Another question is for the player index image, is the maximum also six though I am not getting the skeleton data?

Thanks in advance! :P

**Comment by qm13** [comment]
There is no programmatic limit on the number of skeletons Azure Kinect BT can track. The number of skeletons you can track will depend on available compute and desired frame rate.
