### ISSUE TITLE
How to run csharp_3d_viewer Azure-Kinect-Samples with Azure Kinect Body Tracking SDK version 1.1.0

### ISSUE THREAD

**Issue by madhawap** [microsoft/Azure-Kinect-Sensor-SDK#1595]
**Problem description:**

I am trying to run the Azure Kinect C# sample project (csharp_3d_viewer) listed [here](https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/csharp_3d_viewer) in Azure-Kinect-Samples GitHub repo on GeForce 30 series GPU (NVIDIA GeForce RTX 3070). When I run the project on Visual Studio (2019) with ```TrackerProcessingMode.Gpu```, the window form pops up but displays nothing and the cursor keeps spinning. On the Azure Kinect device, I can see the red light is on.  However, when I set the ```TrackerProcessingMode.Cpu``` the program runs but it is noticeably laggy. The program runs successfully on GeForce 20 series GPU (NVIDIA GeForce RTX 2070) with Azure Kinect Body Tracking SDK version 1.0.1.

I realized that Microsft has released Azure Kinect Body Tracking SDK version 1.1.0 which supports GeForce 30 series GPUs. Since the new SDK version doesn't have NuGet install, I tried adding the required DLLs in SDK version 1.1.0 to the project which did not work. 

I would like to know how could I install Azure Kinect Body Tracking SDK version 1.1.0 to run csharp_3d_viewer sample? Does the new version has a  C# wrapper as in previous SDKs?

**To Reproduce:**
1. Download Azure-Kinect-Samples from [here](https://github.com/microsoft/Azure-Kinect-Samples) and open charp_3d_viewer project on Visual Studio 2019
2. Connect Azure Kinect to the PC
3. Run the project
4. Project runs without any errors on the Console but the pop-up window displays nothing.
5. Change the  ```TrackerProcessingMode.Gpu``` to  ```TrackerProcessingMode.Cpu``` on Program.cs file and re run the project.
6. Project runs without any errors on the consoles and the can see the video and skeleton on the pop-up window

**Screenshots:**

with ```TrackerProcessingMode.Gpu```
![image](https://user-images.githubusercontent.com/12988860/117687615-4f48a280-b1fb-11eb-8f8b-28d426828efb.png)

with ```TrackerProcessingMode.Cpu```
![image](https://user-images.githubusercontent.com/12988860/117687420-20323100-b1fb-11eb-814d-d683437b9481.png)

**Desktop:**
 - Windows 10 Build 19041
 - SDK Version: 1.1.0
 - GPU - GeForce RTX 3070

**Comment by qm13** [comment]
@madhawap please see #1562. There currently is no NuGet package for v1.1.0. Follow the instructions in this issue to move the necessary files into place.
