### ISSUE TITLE
[KinectV2] Microsoft.Kinect nuget package to support Net5

### ISSUE THREAD

**Issue by vpenades** [microsoft/Azure-Kinect-Sensor-SDK#1596]
First of all, I am fully aware this is not the right place to request something related to the now outdated KinectV2 sensor, but I don't know any other place to ask, other than the old KinectSDK forums, which now seem to be dead. My hope is that someone here might point me in the right direction, or know who should I contact.

**Is your feature request related to a problem? Please describe.**

Our product currently supports a variety of sensors, including the Kinect2, as it happens, we have a very important client that's been using our product with Kinect2 for some years now, and they refuse to change to newer sensors for a variety of reasons, so we're forced to keep offering support for this client.

But also we keep moving forward with our software, and we planned to move to net5.0 in the following months. We've just discovered that [Microsoft.Kinect](https://www.nuget.org/packages/Microsoft.Kinect/) nuget package is exclusive of Net4.5 , which is unable to run under Net5.0.

So this is a show stopper for us: we either drop Net5, or the Kinect2, and this client along with it, which is not really an option, so we'll keep our product on NetFramework.

**Describe the solution you'd like**

We would like [Microsoft.Kinect](https://www.nuget.org/packages/Microsoft.Kinect/) to be updated to support net5.0 ... no new features, just net5 support.

Or a way to contact someone to who we could put our case.

**Describe alternatives you've considered**

I tried to decompile the assembly to see if it could be recompiled to newer framework, without success.

**Additional context**

I would be very happy to leave the Kinect2 behind and move to newer sensors, but when you have a client with 200 kinects and a huge investment, it's not that easy.  We can progressively move that client to use newer sensors progressively over one or two years from now, but not in one shot.

**Comment by qm13** [comment]
Kinect for Windows v2 was discontinued in 2017. There are no plans to update the software.
