### ISSUE TITLE
Point cloud compensate in empty area

### ISSUE THREAD

**Issue by fi6** [microsoft/Azure-Kinect-Sensor-SDK#1599]
**Describe the bug**
Points are filled in the empty area which is a disturbance in some high-accuracy applications.

**To Reproduce**

**Expected behavior**
Add a 'high accuracy' parameter or related ways to turn off the compensate feature.

**Logs**

**Screenshots**
![Screenshot from 2021-05-17 16-48-08](https://user-images.githubusercontent.com/45503345/118556098-750d0480-b731-11eb-982a-2d737d41962c.png)
![rviz_screenshot_2021_05_17-16_41_18](https://user-images.githubusercontent.com/45503345/118556157-89e99800-b731-11eb-8a69-570604eeb8be.png)

In the situation up, the points between the arm should not exist

![Screenshot from 2021-05-17 17-09-26](https://user-images.githubusercontent.com/45503345/118557568-5c055300-b733-11eb-82f2-0436dbac8b7b.png)
![Screenshot from 2021-05-17 17-09-17](https://user-images.githubusercontent.com/45503345/118557577-5dcf1680-b733-11eb-9f8a-95d072d09165.png)

Also in this situation, the left side of box is empty but filled with points by sdk

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04
 - SDK Version:  1.4.1
 - Firmware version: rgb: 1.6.102, depth: 1.6.75

**Additional context**

**Comment by fi6** [comment]
Hi @qm13,

Why the issue is closed? Is there any comments/solution for this?

**Comment by v-wewei** [comment]
@fi6 Does the issue solved?
