### ISSUE TITLE
k4abt_sensor_orientation_t not working anymore

### ISSUE THREAD

**Issue by Moovency** [microsoft/Azure-Kinect-Sensor-SDK#1606]
Hello,

The sensor_orientation parameter seems to not be taken in account anymore.
No matter the value we set, bodies are only detected with the camera beeing on its normal position.

Could you check if you have the same issue please ?

Thank you.

**Comment by Moovency** [comment]
Hello,

Any update on the subject ?

Thank you.

**Comment by scotthsu98052** [comment]
Please provide more info:
  BT SDK version
  OS version
  GPU model
  tracker_config.processing_mode
  Do you use default model file or you use other model files?

**Comment by Moovency** [comment]
BT SDK: 1.1.0
OS version: Windows 10.0.19042
GPU model : Nvidia Geforce GTX 1050
tracker_config.processing_mode : K4ABT_TRACKER_PROCESSING_MODE_GPU
For model file we use dnn_model_2_0_lite_op11.onnx and dnn_model_2_0_op11.onnx
The error appears with both of them.

**Comment by PierrePlantard** [comment]
Dear @qm13, is this issue is corrected ? If so, when do you plan to release the new version.
Regard,
Pierre

**Comment by fkavache** [comment]
@Moovency 
Could you please provide more detailed information on how exactly are you reproducing this issue?
Also, it's interesting whether bodies are detected only partly, sometimes or they are not detected at all.

**Comment by Moovency** [comment]
Hi @fkavache 
To reproduce this issue : 
- call **k4abt_tracker_create** with **k4abt_tracker_configuration_t config** and set **sensor_orientation** with **K4ABT_SENSOR_ORIENTATION_FLIP180**  (this is reproducible also with the other options https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/1.1.x/group__btenums_ga8e5fb3391addee8fadaa809c601e223e.html ).
- Flip the Kinect Camera 180°
- Try to track the skeleton

-> In our case, the body is not tracked at all when using 180° (rotation is not taken in account)

Let me know if you need more details.

**Comment by fkavache** [comment]
Hi @Moovency

In my case body tracking is working fine. 
In the worst scenario (flipped camera without any orientation parameter) at least there should be partial body recognition. 
Can you try to:
1. record flipped .mkv video using k4arecorder tool and use it as an input? 
(you can use the PlayFile function from [simple_3d_viewer)](https://github.com/microsoft/Azure-Kinect-Samples/blob/master/body-tracking-samples/simple_3d_viewer/main.cpp sample as reference)
2. flip camera 180° without any orientation parameter.

**Comment by Moovency** [comment]
Hi @fkavache 

You can check in attachment the scenarios we have tested : 

- Pic01 : k4abt_sensor_orientation_t set to K4ABT_SENSOR_ORIENTATION_DEFAULT , camera in place -> body tracking ok
- Pic02 : k4abt_sensor_orientation_t set to K4ABT_SENSOR_ORIENTATION_FLIP180, camera in place -> body tracking ok
- Pic03 : k4abt_sensor_orientation_t set to K4ABT_SENSOR_ORIENTATION_FLIP180, upside down camera -> body tracking ko

Thanks !

![Pic01](https://user-images.githubusercontent.com/74403053/152500134-2c0872e7-7db2-4d5a-924e-8f2382d3a2a2.jpg)

![Pic02](https://user-images.githubusercontent.com/74403053/152500161-a1d2f7a1-3a08-4adb-9eb1-67d5fa270974.jpg)

![Pic03](https://user-images.githubusercontent.com/74403053/152500184-e5711708-2303-45f0-9dc1-4f3e73e38529.jpg)

**Comment by fkavache** [comment]
Hi @Moovency

I rechecked just in case, I can confirm that BT **works correctly** with FLIP180 option and camera upside down.
Could you please try simple_3d_viewer which comes with the BT SDK? **C:\...\Azure Kinect Body Tracking SDK\tools\k4abt_simple_3d_viewer.exe**

**screenshot**
![image](https://user-images.githubusercontent.com/29062515/154741107-2c8e8680-2c6c-451a-8bb7-317dbfda48a0.png)
