### ISSUE TITLE
there are warnings   when body track v1.1.0 with cuda 

### ISSUE THREAD

**Issue by senshin998** [microsoft/Azure-Kinect-Sensor-SDK#1612]
Can anyone tell me what this is？Does it  need to care about？

![QQ图片20210529170441](https://user-images.githubusercontent.com/17866598/120065009-c73f1580-c0a1-11eb-9ade-b989e0583679.png)

**Comment by diablodale** [comment]
duplicate of https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1555

**Comment by senshin998** [comment]
thanks
