### ISSUE TITLE
Unity and Azure Kinect DK gestures implementation references ?

### ISSUE THREAD

**Issue by UnityQueriesAsk** [microsoft/Azure-Kinect-Sensor-SDK#1622]
Hi All,

I am developing a Unity game using Azure Kinect DK. I need some references related to the below gestures.

Running - For player run
Jump - For player jump.

Can anyone share a few references related to this gestures or share an idea how can I implement these gestures.

Thanks in advance.

**Comment by qm13** [comment]
Please look at https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples.

**Comment by UnityQueriesAsk** [comment]
Hi, Thank you so much for your response.

For Azure Kinect DK floor detection can you please share a few Unity and C# references?

Thank you.
