### ISSUE TITLE
Is it possible to body tracking from other device?

### ISSUE THREAD

**Issue by gdosu** [microsoft/Azure-Kinect-Sensor-SDK#1631]
Hello.

I wonder if I can process body tracking from mkv which recorded by common camera(not azure kinect) or pre-made ply(point cloud).

Thank you for reading.

**Comment by diablodale** [comment]
I suspect you will have challenges

- The depth data will need to be somehow transformed from your other camera into a format that is the same as Kinect Azure: pixels, pov, focal length, etc. The neural net and supporting code was trained for specific hardware.
- There might also be licensing issues. I recommend you read your license for the Body Tracking SDK.

If it is legally allowed, sounds like a good project for you to try. Code it and tell us your experience.
