### ISSUE TITLE
Distorted objects in camera

### ISSUE THREAD

**Issue by Marselias** [microsoft/Azure-Kinect-Sensor-SDK#1633]
Hi, we have a problem when trying to use kinect for estimating shape and position of an object due to distortion in PointCloud data.

![box](https://user-images.githubusercontent.com/57571372/124133900-92e4bd80-da82-11eb-9175-65263e0181ed.png)

at the image above u can see plastic box of size 10x10x10 cm but in pointcloud there is a distortion of one of the sides.

another example contains same plastic box and a cardboard box, distortion is very similar:

![cardboard_and_plastic](https://user-images.githubusercontent.com/57571372/124134045-b7409a00-da82-11eb-8798-a400c9b53879.png)

what is the source of this issue?

**Comment by qm13** [comment]
Please provide some RGB images of the setup you are imaging.
