### ISSUE TITLE
How can i get the information about Focus with a kinect DK?

### ISSUE THREAD

**Issue by Applied-Energetic** [microsoft/Azure-Kinect-Sensor-SDK#1640]
I am doing some work about Multi-focus Image Fusion.And I try to get some train dataset by Kinect dk which can provide me RGB and Depth data. SO I want to know if Kinect dk can Adjust the focus of kinect dk . if not , how can I calculate the focus ?

**Comment by diablodale** [comment]
It is my understanding that the Kinect Azure RGB camera is a fixed focus camera.
You can get the camera calibration matrix which contains the focal point and other intrinsic/extrinsic values using https://docs.microsoft.com/en-us/azure/kinect-dk/use-calibration-functions#retrieve-calibration-data

**Comment by Applied-Energetic** [comment]
Very thank you for response，and i do get the matrix and focal point .Just like these picture.
![image](https://user-images.githubusercontent.com/56194237/125251874-5a6a9c80-e32a-11eb-9a77-717104700dca.png)
![image](https://user-images.githubusercontent.com/56194237/125251890-5fc7e700-e32a-11eb-8bd5-d8e71b242787.png)
SO I want to know is the matrix Unchangeable？If I can change it , how should I do?
It is very important for my work , if it is possible I can get the Multi-focus image as my train data.
Thanks again.

**Comment by diablodale** [comment]
The calibration matrices (intrin, extrin) are unchangable for a given mode (wide pov, narrow pov, etc.). There is no variable lens focus.

**Comment by Applied-Energetic** [comment]
Thank you very much.

**Comment by Applied-Energetic** [comment]
problem solved
