### ISSUE TITLE
Dependencies table for ONNX Runtime is wrong

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#1644]
**Describe the bug**

Is the dependencies table for ONNX Runtime in [this document](https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#required-dlls-for-onnx-runtime-execution-environments) correct?
I think that's not correct, at least not when it comes to DirectML. (directml.dll is missing.)
It is also strange that CUDA DLLs are included in the dependencies of CPU and TensorRT.
https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#required-dlls-for-onnx-runtime-execution-environments

**Screenshots**

![2021-07-19_13h15_13](https://user-images.githubusercontent.com/816705/126101963-65a93d3a-2d7f-4eef-9db2-4f07071d98e6.png)

**Additional context**

**Comment by diablodale** [comment]
related to https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1541

**Comment by qm13** [comment]
Fixed
