### ISSUE TITLE
Kinect dependencies not available for download - long-term support again failing

### ISSUE THREAD

**Issue by diablodale** [microsoft/Azure-Kinect-Sensor-SDK#1649]
Dependencies for the Kinect v1 and v2 SDKs have disappeared from the official download locations at Microsoft Downloads. The links throughout various Microsoft websites and Microsoft download server lists don't work.

https://developer.microsoft.com/en-us/windows/kinect/
scroll down and click on `Microsoft Speech Platform SDK 11`
It will report `We're sorry, this download is no longer available.`

https://www.microsoft.com/en-us/download/search.aspx?q=speech+recognition&first=1
click on any of the Speech Platform v11 downloads. All will report `We're sorry, this download is no longer available.`

https://docs.microsoft.com/en-us/previous-versions/office/developer/speech-technologies/jj127858(v=msdn.10)?redirectedfrom=MSDN
click on any of the Speech Platform v11 downloads. All will report `We're sorry, this download is no longer available.`

Even this https://docs.microsoft.com/en-us/windows/apps/speech
In the main `Win32 platform section` click `Microsoft Speech Platform - Software Development Kit (SDK) (Version 11)`
will report `We're sorry, this download is no longer available.`

Both the Microsoft Speech Platform SDK v11 and Microsoft Speech Platform Runtime v11 are needed for full development and usage of Kinect v1 and v2 SDKs.

This is another example of https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1083

**Comment by qm13** [comment]
The Azure Kinect team does not own the previous Kinect products. I have passed the issue to the team that owns these products which are now end of life products.

**Comment by diablodale** [comment]
With what process or person "to the team" can I associate? I ask so to track progress and close loops on success or failure.

**Comment by qm13** [comment]
@diablodale if you have not already done so you should file a bug via Windows Feedback Hub at
https://microsoft.sharepoint.com/sites/mywork/SitePages/Windows10/Feedback-Support.aspx

**Comment by diablodale** [comment]
Hi, is that a site generally available to customers? For 2 days I've tried to get to it and it always reports

```
That didn't work
We're sorry, but dale@hidale.com can't be found in the microsoft.sharepoint.com directory. Please try again later, while we try to automatically fix this for you.

If that doesn't help, contact your support team and include these technical details:
Correlation ID: 76bde69f-303b-0000-d93b-30d89d694314
Date and Time: 8/18/2021 7:29:14 AM
URL: https://microsoft.sharepoint.com/sites/mywork/SitePages/Windows10/Feedback-Support.aspx
User: dale@hidale.com
Issue Type: User not in directory.
```
