### ISSUE TITLE
sample freezes on k4abt_tracker_create... any ideas why?

### ISSUE THREAD

**Issue by skywalkerwin** [microsoft/Azure-Kinect-Sensor-SDK#1651]
Hello I am trying to run a body tracking sample and it seems like somethings getting stuck here:

![image](https://user-images.githubusercontent.com/47264358/127728480-210e6140-0265-4f1c-96b8-1c6ec5262dc1.png)

Kinect Sample can be found here: https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download

Any ideas why the sdk would freeze trying to create a tracker?

Thanks you!!

**Comment by qm13** [comment]
Can you run the pre-compiled k4abt_simple_3D_viewer on your system?

**Comment by skywalkerwin** [comment]
> Can you run the pre-compiled k4abt_simple_3D_viewer on your system?

I can

**Comment by peterkennard** [comment]
same issue here windows 10 Pro installed and the latest stable kinect SDK and body tracker SDKs  as of 12/3/2021

I built the simple_3d_viewer from master with VisualStudio 2019 , I updated nuget packages, built both debug and release versions,  No build issues.

Tried to run both Debug 64 bit and Release 64 bit versions, and it hangs in k4abt_tracker_create no error messages, just hangs.
I am running it in the CPU mode, and do not have a kinect (HW) installed on the machine.

The binary supplied with the SDK runs fine in GPU mode.

The program I built will run with the test.mkv file just very slowly.  It will not run in GPU mode.

The machines has a RTX 3060 Laptop GPU on it and is set ro use that for the desktop.  Other GPU programs work fine.

**Comment by submorphic** [comment]
Having similar problem.  simple viewer shipped with SDK runs fine on three different laptops.  When I build a simple viewer kit and run it is fine on two laptops, but hangs without error on k4abt_tracker_create() on the third laptop. I'm capturing trace info and will update post.

As expected...no trace output...log file empty confirming hang on the tracker_create call

**Comment by peterkennard** [comment]
Thanks would be great to solve this 😊

**Comment by harryspiercy** [comment]
Hi all, I encountered the same issue while running the latest SDK from my laptop with a RTX 3060.

I haven't found a proper solution but have found changing the trackers config processing mode to CPU stops the hanging when hitting the create tracker method.

`trackerConfig.processing_mode = K4ABT_TRACKER_PROCESSING_MODE_CPU;`

Would be great to get a solution for running with the GPU of course but thought this may help someone get going!

**Comment by thisisfangsheng** [comment]
Hello, I run into the same problem. Looking forward to the solution. Thanks.
