### ISSUE TITLE
How to capture and access color images with Azure Kinect DK using Unity?

### ISSUE THREAD

**Issue by UnityQueriesAsk** [microsoft/Azure-Kinect-Sensor-SDK#1652]
Hi All,

Can anyone share a few references of how to capture and access color images with Azure Kinect DK using Unity?

Thank you.

**Comment by qm13** [comment]
Have you looked at the Unity sample https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/sample_unity_bodytracking

**Comment by UnityQueriesAsk** [comment]
> Have you looked at the Unity sample https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/sample_unity_bodytracking

Hi, Thanks for your response.

I have checked the Unity sample.

My scenario is I need to capture a color image with Azure Kinect DK and that image has to be downloaded in my pc using Unity.

Can you please share a few references for this scenario.

Thank you.

**Comment by qm13** [comment]
Duplicate of #1656 which has a better explanation of what the developer is trying to do.
