### ISSUE TITLE
ANY CODE PACKAGE AVAILABLE FOR ARSANDBOX IN AZURE KINECT CAMERA?

### ISSUE THREAD

**Issue by Kanish2002** [microsoft/Azure-Kinect-Sensor-SDK#1659]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kanish2002** [comment]
I just need the code as same as ucdavis arsandbox project in for new Azure Kinect Camera.

**Comment by qm13** [comment]
AR Sandbox would need to add the support.

**Comment by Kanish2002** [comment]
> AR Sandbox would need to add the support.

But I just need to know how to give color coding for particular depth and also to cover a particular area using azure kinect.

How to focus a particular area and show it on screen?
Also need to know how to compute and work with depth of the camera.
