### ISSUE TITLE
IR laser stays on causing the camera to get hot

### ISSUE THREAD

**Issue by nicobeek** [microsoft/Azure-Kinect-Sensor-SDK#1663]
**Describe the bug**
On window close I call device.StopCameras() and device.Dispose() which ends everything correctly. However, if my program terminates abnormally the IR laser stays on, causing the camera to get hot after a while. The streaming led on the front of the camera does turn off, so I guess the device knows that it is no longer being used.

**To Reproduce**
Start the program from within Visual Studio. When the camera is started (with depth camera enabled) the white streaming led turns on and the IR laser can be seen faintly. Pressing 'stop debugging (shift + F5)' will end the program and the white streaming led will turn off, but the IR laser will stay on. 

*UPDATE*
This was with firmware version:
RGB camera firmware:      1.6.102
Depth camera firmware:    1.6.75
Depth config file:        6109.7
Audio firmware:           1.6.14

I have just updated the firmware to the latest available. Still the same issue, but the white streaming led now stays on as well. I can still use the camera in other programs (like the camera app included in Windows) after exiting the camera app the streaming led still remains on. The only way to turn it off is to rerun my Kinect program and end it normally, causing device.StopCameras() and device.Dispose() to be called.

**Desktop (please complete the following information):**
 - OS with Version: Microsoft Windows 10 Pro   Version	10.0.19042 Build 19042
 - SDK Version:  1.4.1
 - Firmware version:  
  RGB camera firmware:      1.6.110
  Depth camera firmware:    1.6.79
  Depth config file:        6109.7
  Audio firmware:           1.6.14
  Build Config:             Production
  Certificate Type:         Microsoft

**Comment by qm13** [comment]
This is by design. We cannot reliably determine this state. There is no problem with the laser to remain on.
