### ISSUE TITLE
Azure Kinect DK cameras failed to open in the Azure Kinect Viewer?

### ISSUE THREAD

**Issue by UnityQueriesAsk** [microsoft/Azure-Kinect-Sensor-SDK#1666]
Hi All,

I have been using the Azure Kinect DK for a long time but today all the cameras failed to open in the Azure Kinect Viewer.

I am getting the following messages pop up when connecting:

IMU failed: timed out!
IMU Data: data source failed!
Camera failed : timed out!

The Log view shows the below error :

[error] : usb_cmd_libusb_cb(). LibUSB transfer status of 00000002 unexpected

I am using the Azure Kinect SDK v1.4.1 and the firmware version (1.6.110079014). I have tried different USB ports on my pc but still, I am getting the above errors.

Can anyone please provide a solution for these errors?

Thanks in advance.

**Comment by qm13** [comment]
Please verify if the issue persists when connected to another PC. If it does then it is likely hardware failure.

**Comment by qm13** [comment]
Also if you have a 2nd AKDK please does it exhibit the same problems on the PC?

**Comment by jonahpearl** [comment]
I get this problem on a home-built machine when the USB controllers aren't correct, as discussed here: https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#usb3-host-controller-compatibility. I don't really understand why some USB ports work and others don't, but it's definitely a reproducible problem. Fixed just by using a different USB port on the motherboard.

**Comment by TuttiChi** [comment]
> I get this problem on a home-built machine when the USB controllers aren't correct, as discussed here: https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#usb3-host-controller-compatibility. I don't really understand why some USB ports work and others don't, but it's definitely a reproducible problem. Fixed just by using a different USB port on the motherboard.

A ctually right. My clevo NH50 cant use this camera, but Thinkpad x390 yoga can use use it without error
