### ISSUE TITLE
IR image save problem

### ISSUE THREAD

**Issue by kimtaehyeong** [microsoft/Azure-Kinect-Sensor-SDK#1670]
Save IR img problem

Hello, we have the purpose of acquiring IR images on a single PC.

[Environment]
By connecting kinect DK one by one to a single PC, you are using 3 kinects using a total of 3 computers.
We are currently acquiring IR images with my python code reference: https://github.com/etiennedub/pyk4a.
The size of the image stores 1024 1024 size.

[Situation]
The person was photographed at a distance of about 50cm from the camera, and IR, RGB, and Depth are stored at once.

To save the original IR image, do not use convert and save the original image as 16bit (0~65536).
For visualization of the saved image, convert the image with the following code to proceed with the visualization.

```
def gray_rescale_2d(gray, minval, maxval):
     gray = (gray - minval) / (maxval-minval) * 255
     gray[gray < 0] = 0
     gray[gray > 255] = 255
     return gray
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11425786/131241201-ee97d4c6-62eb-44e4-ab38-213246c8095e.png)

**Problem**
There are two problems as shown in the image above.
1. How can I reduce the saturation around the eyes? I wonder if it depends on the characteristics of the human eye. -> Because there are people who can see well and people who can't see well.
2. In the picture attached above, there are cases where the pupils of the right and left eyes cannot be seen. How can I get a clear image when shooting?

thank you.

**Comment by qm13** [comment]
It sounds like you are using the active IR image that is generated by the depth engine as an offshoot of calculating depth. This is a fixed exposure and fixed illumination image. If the person is too close to the camera the IR image will be overexposed (similarly if they are too far from the camera it will be underexposed). If you want a controlled IR image then I suggest you use the passive IR image with external IR illumination (an admittedly expensive application for Azure Kinect).
