### ISSUE TITLE
K4ABT_SENSOR_ORIENTATION_FLIP180 is not taken into account in k4abt_tracker_create 

### ISSUE THREAD

**Issue by Moovency** [microsoft/Azure-Kinect-Sensor-SDK#1673]
Hi,

We are facing a bug in the body tracker when we are flipping the camera : 
We have set the sensor_orientation property with K4ABT_SENSOR_ORIENTATION_FLIP180 value but it does not enable body tracking when the camera is 180° flipped.
We are running 1.1.0 version.

I did not find but is there already an opened issue for that ?

Thanks.

**Comment by qm13** [comment]
Also https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1606
