### ISSUE TITLE
Azure Kinect Discontinuation/Release date? 

### ISSUE THREAD

**Issue by hayeonp95** [microsoft/Azure-Kinect-Sensor-SDK#1674]
Hi Everyone, 

Do you have any idea of release date for Azure Kinect Camera? 

I have been waiting for few months to be restocked, so was wondering if it would be ever restocked any time soon? 

Thank you!

**Comment by qm13** [comment]
You need to call the phone number listed on the purchase page.

**Comment by dimitrijevic** [comment]
Now the store listing's gone, or is just me? New prices incoming, 3rd-party models, or...?  
https://www.microsoft.com/en-US/d/azure-kinect-dk/8pp5vxmd9nhq

**Comment by qm13** [comment]
We are investigating this issue. No, it is not new pricing or 3rd party models.
