### ISSUE TITLE
Version 1.2.0 not able to download msi package

### ISSUE THREAD

**Issue by Zulex** [microsoft/Azure-Kinect-Sensor-SDK#1680]
As the title suggest, the download link of v1.2.0 of the sdk is not working anymore. Could this be updated, thanks in advance!

**Comment by qm13** [comment]
The .msi files pre v1.4 have been pulled due to a security issue with the signing process of those files (not restricted to Azure Kinect). There are no plans to resign and reissue.

The documentation will be updated shortly.
