### ISSUE TITLE
Azure Kinect Camera not detected in Viewer - Windows 11

### ISSUE THREAD

**Issue by darthcodar** [microsoft/Azure-Kinect-Sensor-SDK#1699]
Device is connected via USB 3.0 and LED on back is solid white. 
Azure Kinect Viewer fails to detect the device.

Desktop:

    Display Drivers: latest nVidia GeForce
    OS with Version: Windows 11 Pro, version 21H2
    SDK Version: 1.4.1
    Firmware version: (unable to connect)

Additional context
Unable to Find device in Azure Kinect Viewer app, tried refresh devices, reboot.
Unable to see device serial number
USB cable directly plugged into rear port of computer, USB3, no hub used

I can run the Kinect as a webcam/camera through Windows Camera app. 
Usual Webcam has been disconnected
Tried on work laptop, same issue - is this a Windows 11 incompatibility?

Azure Kinect 4K Camera is detected in the Device Manager under cameras
Azure Kinect 4K Camera and Azure Kinect Depth Camera are detected in the Device Manager under USB devices

Solution found - updated to latest firmware and worked straight away.
Can close

Just a FYI, command used in case anyone else needs:

.\AzureKinectFirmwareTool.exe -u firmware\AzureKinectDK_Fw_1.6.110079014.bin

**Comment by pswot** [comment]
Have this bug been solved?

**Comment by darthcodar** [comment]
Solved with update to newest firmware. Thanks a lot
