### ISSUE TITLE
Latest firmware versioning issue on SDK v1.4.1? 

### ISSUE THREAD

**Issue by kalisina** [microsoft/Azure-Kinect-Sensor-SDK#1700]
Hi Guys, 

I'm using 6 Azure Kinects. 
I've done a factory reset for all of them (manually pushing the button), and what I've noticed is that the factory firmware is higher than the firmware provided by the latest sdk v1.4.1, is that just a versioning typo issue? Or should I leave the factory firmware and not use the one from the SDK.

You'll notice that the `Depth camera firmware` is downgrading after the update
    
![firmware-comp](https://user-images.githubusercontent.com/1659350/139595939-5e4227d1-301e-40b8-9d78-df5660bf7348.png)

**Desktop (please complete the following information):**
 - OS with Version:  Windows 10 Pro
 - SDK Version: v1.4.1v
 - Firmware version:  AzureKinectDK_Fw_1.6.110079014

Thank you for your help

**Comment by qm13** [comment]
@arkader the factory has started loading the latest firmware. The v1.5 SDK which carries the new firmware is delayed. You can also find the firmware here https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/firmware

**Comment by kalisina** [comment]
Thank you for this information @qm13 
I'll upgrade all the sensors to this latest version then:
AzureKinectDK_Fw_1.6.110080014.bin
