### ISSUE TITLE
How does the official example "sample_unity_bodytracking" convert the joint coordinate to the Unity?

### ISSUE THREAD

**Issue by Chang-Che-Kuei** [microsoft/Azure-Kinect-Sensor-SDK#1705]
In the example [sample_unity_bodytracking](https://github.com/microsoft/Azure-Kinect-Samples/blob/master/body-tracking-samples/sample_unity_bodytracking/Assets/Scripts/TrackerHandler.cs), the program converts each joint coordinate to the coordinate in Unity.  
I know that the official [document](https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints) has described a bit about the joint coordinate. I believed it is unclear for someone who wants to convert the joint coordinate into other 3D software like Maya and blender. For example,
`Quaternion leftHipBasis = Quaternion.LookRotation(xpositive, -zpositive);`  
Why `xpositive` and `-zpositive` are put into the left hip joint coversion?  
In the code file [TrackerHandler.cs](https://github.com/microsoft/Azure-Kinect-Samples/blob/master/body-tracking-samples/sample_unity_bodytracking/Assets/Scripts/TrackerHandler.cs), it did the conversion. Could you provide some hints or reference on how you do the conversion?
<img src="https://user-images.githubusercontent.com/24307350/140714136-839d4c1b-5f67-4820-bb36-702604fa5699.png " height="300"><img src="https://user-images.githubusercontent.com/24307350/140714521-adda9599-d8f3-4640-a630-5e2df5da9b38.png " height="300">

**Comment by fkavache** [comment]
Hi @Chang-Che-Kuei

LookRotation takes two arguments: forward and upward vectors.
In our case forward is xpositive (right) and upward is -zpositive (backward)

Quaternion leftHipBasis = Quaternion.LookRotation(xpositive, -zpositive);

_‘Z axis will be aligned with **forward**, X axis aligned with cross product between **forward** and **upwards**, and Y axis aligned with cross product between Z and X.’ [Quaternion.LookRotation](https://docs.unity3d.com/ScriptReference/Quaternion.LookRotation.html)_

So, after conversion, the Z axis will face right, X will face upward (product of right and backward) and Y will face forward, which is exactly what the documentation picture depicts.

![image](https://user-images.githubusercontent.com/29062515/163434024-5f501899-c15f-4026-af02-1977345f5f48.png)
![image](https://user-images.githubusercontent.com/29062515/163434068-5c7cb1ed-6c32-47a3-b941-70392020f2ab.png)

**Comment by amantley** [comment]
Hi I hope this doesn't make things more confusing but I annotated the code that converts from right hand to left handed systems in order to use the Kinect rotation output with Unity.   In order to convert to Maya you don't need to convert to a left handed system so you could leave that part out.  You would need to remember that the rotations we get below need to be changed in Maya to account for pre rotations that are on rig joints.
```
for (int jointNum = 0; jointNum < (int)JointId.Count; jointNum++)
        {
            /// For translation the coordinate system of the Azure Connect is positive z-forward in the direction the camera is pointing, positive y-down where the screw mount is  
            /// and positive x-right towards the RGB camera.  https://docs.microsoft.com/en-us/azure/kinect-dk/coordinate-systems
            /// this is a standard right handed coordinate system rotated 180 about the z axis.
            /// For the purposes of this sample app in Unity we have a game object representing the Azure Kinect Device that has the 
            /// standard y-axis pointing up, x axis pointing right and the z axis point forward.
            /// In Unity they use a left handed coordinate system so it is necessary to convert from right to left handed coords.
            /// The easiest thing to do here was to just negate the y value coming from the Azure Kinect Skeleton Data
            /// Then Translation values will be consistent with a left handed system with 0,0,0 at the camera origin and pos z in the direction of the camera
            /// pos y in the up direction and positive x to the right.
            Vector3 jointPos = new Vector3(skeleton.JointPositions3D[jointNum].X, -skeleton.JointPositions3D[jointNum].Y, skeleton.JointPositions3D[jointNum].Z);

            /// to go from camera relative coordinates to a camera offset in Unity world coordinates 
            /// we multiply by the world rotation of the camera game object 
            /// which in this case is our local transform.
            Vector3 offsetPosition = transform.rotation * jointPos;
            
            /// then add the camera world position to get the joint world position
            Vector3 positionInTrackerRootSpace = transform.position + offsetPosition;

            /// now we need to convert the rotation from right handed coordinate sytem coming from the Azure Kinect skeleton data
            /// to the left handed system needed by Unity.
            /// Here I do that by rotating the kinect rotation by 180 degrees about the y axis.  You could also do this by negating the z and x coordinates of
            /// the Kinect joint rotation.  Either way is fine.  
            /// 
            /// 
            /// the quaternion coming from the kinect device for each joint is created below as
            /// new Quaternion(skeleton.JointRotations[jointNum].X, skeleton.JointRotations[jointNum].Y, skeleton.JointRotations[jointNum].Z, skeleton.JointRotations[jointNum].W)
            /// it can be seen as composed of A*B where A is the pre rotation that puts the joint into T-Pose in the Kinect Skeleton 
            /// and B is then the offset that represents the current delta of that rotation that has been read by the tracker.
            /// From Linear Algebra we know that A*B*Ainverse => gives the rotation C which is B represented in the standard basis.  
            /// This means we have a delta joint rotation relative to the standard right handed system that the Kinect is based on 
            /// in the code below this rotation is mutiplied by the Y_180_FLIP to convert to the Unity Left handed system. 
            /// 
            /// If we create a intermediate rig where all joints have the identity rotation to be in T-pose, then the A*B*Ainverse rotation above will put each
            /// joint into the pose that the tracker is reading.  For each joint A*B*Ainverse is a rotation relative to the root of the rig, they are not relative
            /// to a parent joint 
            /// 
            /// 
            /// here A is the basis rotation we initialized above and B is some unknown offset
            Quaternion AB = new Quaternion(skeleton.JointRotations[jointNum].X, skeleton.JointRotations[jointNum].Y, skeleton.JointRotations[jointNum].Z, skeleton.JointRotations[jointNum].W);

            Quaternion ABAinverse = AB * Quaternion.Inverse(basisJointMap[(JointId)jointNum]);

            /// here we convert from right to left handed coordinates to match Unity's expectation
            Quaternion jointRot = Y_180_FLIP * ABAinverse; 
        }
```
