### ISSUE TITLE
recording at the same time RGB, depth and Skeleton videos 

### ISSUE THREAD

**Issue by Ahmed-KASAPBASI** [microsoft/Azure-Kinect-Sensor-SDK#1710]
Hello...

I need to record videos (RGB, depth and skeleton) with voice at the same time (synchronously) from 3 different Azure Kinect which are connected to one PC.

The recorded videos will be saved as separated files.

How I can do that?
which programs or software I should use?
If that is possible, what are the possible formats of the recorded videos ?
Please, I need detailed information.

**Comment by asergaz** [comment]
Similar question in Q&A: https://docs.microsoft.com/en-us/answers/questions/634903/index.html
