### ISSUE TITLE
I want to use the previous version (Azure Kinect SDK 1.0.2)

### ISSUE THREAD

**Issue by Avita0207** [microsoft/Azure-Kinect-Sensor-SDK#1716]
It may be difficult to understand in English from the translation, but I'm sorry.
I want to use the previous package Azure Kinect SDK 1.0.2, but when I tried to use MSI, I couldn't download it because the file was missing as "404 --File or directory not found.".
So, if you would like a package that is not available, I asked you to submit a problem, so I posted it here.
Thank you.

**Comment by qm13** [comment]
These are no longer available.
