### ISSUE TITLE
Kinect DK Body Tracking 1.1.0 isn't working on Intel Iris Xe GPU

### ISSUE THREAD

**Issue by Alessandro-Minerba** [microsoft/Azure-Kinect-Sensor-SDK#1736]
Hi, I've updated the Body Tracking SDK to the 1.1.0 version on my project, because the official documentation said that this update would exend the compatibility to the Intel GPUs (https://docs.microsoft.com/it-it/azure/kinect-dk/body-sdk-download). I'm using a PC with an Iris XE Graphics GPU, but even changing the TrackerProcessingMode in the bodyTracker creation it doesn't work, exept for the CPU mode, which is obviously slow. Does anyone have a solution? 
@qm13 I dare to tag you because I see You are really active in this field.
Thanks for your help!

**Comment by fkavache** [comment]
Hi @Alessandro-Minerba

Are you on windows? if so which EP are you using.
