### ISSUE TITLE
Fail to record using Azure Kinect DK recorder

### ISSUE THREAD

**Issue by pythonsql21** [microsoft/Azure-Kinect-Sensor-SDK#1739]
I am new to Azure Kinect. After installing the MSI package of azure Kinect SDK (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md), I tried to record data stream using Azure Kinect DK recorder but got an error like below.
![Screenshot (78)](https://user-images.githubusercontent.com/86695336/152498131-acca49c3-c7b2-4a55-8579-ea56a8c83c2a.png)

I used Firmware Versions as below.
  OS: Windows 10
  RGB camera firmware:      1.6.110
  Depth camera firmware:    1.6.80
  Depth config file:        6109.7
  Audio firmware:           1.6.14
I could use Azure Kinect viewer v1.4.1 without any problem but failed to record the data stream.

Thx.

**Comment by shinjich** [comment]
Try opening the command prompt as administrator or changing the current directory.

**Comment by qm13** [comment]
This error is occurs because you are writing into the tools directory under Program Files. In general it is a bad practice to write to  Program Files and Windows now prevents none administrative users from writing to any systems directory. Instead include a path with the filename to an appropriate user directory.

**Comment by pythonsql21** [comment]
Thank you for your responses. It worked after I changed the directory.

**Comment by haotian21** [comment]
> Thank you for your responses. It worked after I changed the directory.

Hi, can you please illustrate how I can change the directory where the recordings are saved? I am encounting the same problem right now. Thank you very much.
