### ISSUE TITLE
missing k4a_export.h

### ISSUE THREAD

**Issue by MadeByOzzy** [microsoft/Azure-Kinect-Sensor-SDK#1740]
Hello!  I am trying to build this project from scratch using the supplied CMakeLists.txt file.

The file "k4a.h" references two other headers: "k4aversion.h" and "k4a_export.h".

k4aversion.h.in exists in "./include/k4a", but there is no configure_file() in the supplied CMakeLists.txt to turn the ".h.in" file in to a regular ".h" file.  Adding a configure_file() command to my upper level CMakeLists.txt file seems to have fixed that issue.

However there is still the issue of a missing k4a_export.h.  There is not a ".h.in" either, no where in the repo.

I do not know where the k4a_export.h file might be...

I found this related issue from a few years ago:

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/852

The resolution on that thread is to clone the repo and build with cmake, but that is what I am doing and it does not auto-generate k4a_export.h.

**Comment by MadeByOzzy** [comment]
Resolved this issue.  I had to open the kinect cmake project itself, build that, that created some stuff in "./out/build/..." including the k4a_export.h and k4aversion.h files.

I had to add:

"out/build/windows-default/src/sdk/include" to my main CMakeLists.txt target_include_directories(), and that solved it

**Comment by Jayden9912** [comment]
Hi @MadeByOzzy . Could you guide me on your solution? I am facing the same issue but couldn't figure out how to do it. Thanks in advance.
