### ISSUE TITLE
Cant run install-opencv .ps1 on Windows 10 Powershell

### ISSUE THREAD

**Issue by jiany-ctrl** [microsoft/Azure-Kinect-Sensor-SDK#1742]
Cant run install-opencv .ps1 on Windows 10 Powershell and the error message is shown below:

An exception was thrown: A parameter cannot be found that matches parameter name 'MaximumRetryCount'.
Processing downloaded file: error_Download-ToTemp_did_not_return_a_file

![image](https://user-images.githubusercontent.com/72469440/153293400-0abe77f5-3edf-47df-86d0-30ca67ecd73f.png)

**Comment by fkavache** [comment]
Hi @jiany-ctrl

is this related to Kinect?

**Comment by jiany-ctrl** [comment]
> 

Is it in this repo?

**Comment by qiaoxu123** [comment]
Hi, i meet the same problem recently and solved it successfully. It should results from the low PowerShell version.

You can type `$host` to see the current version, maybe it's lower than 7.0(like the default 5.1). The parameters like `MaximumRetryCount` added in the new version 7.0 maybe. It can be checked in this [link](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.2&viewFallbackFrom=powershell-6)

The update command in Powershell
```
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
```
