### ISSUE TITLE
LATENCY - LOW REFRESH - SDK BODYTRACKING 1.1 

### ISSUE THREAD

**Issue by SamuelGaudemer** [microsoft/Azure-Kinect-Sensor-SDK#1759]
Hello everyone ! 

The Azure Kinect shows latency on Unity 9.4 with the Bodytracking SDK 1.1.
There is a low refresh rate and a latency between the motion performed and the motion transcribed. 

I have a GTX 970 and an i7. 
I do not understand where this bug can come from. Do you have the same ?

Thank you.

**Comment by qm13** [comment]
Do you see the latency without Unity?
Are you using BT SDK v1.1.1?
