### ISSUE TITLE
Body Tracking Viewer of Azure Kinect Body Tracking SDK v1.1.1 does not launch correctly

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#1763]
**Describe the bug**

k4abt_simple_3d_viewer.exe of Azure Kinect Body Tracking SDK v1.1.1 does not launch correctly.

**To Reproduce**

1. Install Azure Kinect Body Tracking SDK v1.1.1 by msi installer.
2. Run tools/k4abAt_simple_3d_viewer.exe.
3. Show white window with console window.
4. App exits with an error code (3221226505). 

**Expected behavior**

**Logs**

**Screenshots**

![2022-04-06_16h13_54](https://user-images.githubusercontent.com/816705/161916920-a4af55d8-96f0-4d9e-80d5-33327232afbf.png)
![2022-04-06_16h10_51](https://user-images.githubusercontent.com/816705/161916382-602ad616-3389-4242-9bc2-1fcbe501d27f.png)

**Desktop (please complete the following information):**
 - OS with Version: Windows 11 Pro x64 21H2 (22000.556) 
 - SDK Version: Azure Kinect Sensor SDK v1.4.1 and Azure Kinect Body Tracking SDK v1.1.1 
 - Firmware version: AzureKinectDK_Fw_1.6.110079014.bin (Azure Kinect Sensor SDK v1.4.1) 
 - GPU and Driver: NVIDIA GeForce GTX 1080 Ti / NVIDIA Driver 512.15 (Game Ready)

**Windows Error Reporting**
[Report.wer](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/8424760/Report.txt)

**Additional context**

Azure Kinect Body Tracking Viewer (Azure Kinect Body Tracking SDK) was working on the same PC with Windows 10 and Azure Kinect Body Tracking SDK v1.1.0. It is not working after updating the OS, GPU Driver and Body Tracking SDK. But, Azure Kinect Viewer (Azure Kinect Sensor SDK) is still working correctly after updating the OS and GPU Driver.

**Related Issues**
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1762
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1761

**Comment by fkavache** [comment]
Hi, we are working on that issue, 

Before official release could you please try if this prebuilt **k4abt_simple_3d_viewer.exe** works for you? 
just replace existing **..\Azure Kinect Body Tracking SDK\tools\k4abt_simple_3d_viewer.exe** with attached file and run body tracking with CUDA or TRT

Please use v1.1.1 BT SDK and the latest NVidia driver.

[k4abt_simple_3d_viewer.zip](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/8440756/k4abt_simple_3d_viewer.zip)

**Comment by UnaNancyOwen** [comment]
@fkavache Thanks for working on this issue! 👍 

> [k4abt_simple_3d_viewer.zip](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/8440756/k4abt_simple_3d_viewer.zip)


It works well in my environment with DirectML and CUDA processing mode!
It doese not works with TensorRT processing mode. (I'm not sure if that was the intended behavior.)

![2022-04-07_17h09_44](https://user-images.githubusercontent.com/816705/162152152-67ab57a4-9a21-4926-8842-1b7437030e76.png)
![2022-04-07_17h14_29](https://user-images.githubusercontent.com/816705/162152796-7af6a7cf-94d9-45d1-8205-09c734060997.png)

If you need more experiment and confirm before official release, I will be glad to help you.

**Comment by fkavache** [comment]
@UnaNancyOwen

Glad to hear that, TRT just needs some time to build local cache.

**Comment by UnaNancyOwen** [comment]
@fkavache After a few minnits wait, it works well with TensorRT processing mode. All processing modes works correctory! Thanks!

**Comment by UnaNancyOwen** [comment]
> After a few minnits wait, it works well with TensorRT processing mode.

However, the cache seems to be generated each time of started
![2022-04-07_18h03_27](https://user-images.githubusercontent.com/816705/162163062-521ac910-417e-421c-a6a6-37c815ef2fc9.png)
.

**Comment by fkavache** [comment]
It's a normal behavior, you just need to enable caching 

https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#configurations

ORT_TENSORRT_CACHE_PATH=/path/to/calibration/table
ORT_TENSORRT_ENGINE_CACHE_ENABLE=1

**Comment by UnaNancyOwen** [comment]
> ORT_TENSORRT_CACHE_PATH=/path/to/calibration/table
> ORT_TENSORRT_ENGINE_CACHE_ENABLE=1

Oh! It is good! 👍  I had missed the documentation.

**Comment by leventalpsal** [comment]
> Hi, we are working on that issue,
> 
> Before official release could you please try if this prebuilt **k4abt_simple_3d_viewer.exe** works for you? just replace existing **..\Azure Kinect Body Tracking SDK\tools\k4abt_simple_3d_viewer.exe** with attached file and run body tracking with CUDA or TRT
> 
> Please use v1.1.1 BT SDK and the latest NVidia driver.
> 
> [k4abt_simple_3d_viewer.zip](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/8440756/k4abt_simple_3d_viewer.zip)

I had the same issue, Azure Kinect Viewer working, k4abt_simple_3d_viewer.exe (2133KB) crashing on startup. The prebuilt k4abt_simple_3d_viewer.exe (2134KB) works fine.

Environment details:
Azure Kinect SDK 1.4.1
Azure Kinect Body Tracking SDK 1.1.1
Ryzen 9 5900 HX
Nvidia RTX 3070 laptop GPU
Nvidia Game Ready driver 511.79
Windows 11 22000.593

**Comment by fkavache** [comment]
@leventalpsal

Sounds good!

**Comment by gradientLord** [comment]
> It's a normal behavior, you just need to enable caching
> 
> https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#configurations
> 
> ORT_TENSORRT_CACHE_PATH=/path/to/calibration/table ORT_TENSORRT_ENGINE_CACHE_ENABLE=1

how exactly do you enable TENSORRT caching on your system? I tried these commands in elevated command prompt and it didnt work.

**Comment by fkavache** [comment]
Hi, @gradientLord

Those are environment variables, try:
**$env:ORT_TENSORRT_ENGINE_CACHE_ENABLE = 1
$env:ORT_TENSORRT_CACHE_PATH="C:\Users\\...\Desktop\cache"** from powershell.

**Comment by UnaNancyOwen** [comment]
> TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_10554548234644750994_1_0.engine

If set up correctly, it will generate a cache file like this one in first run time! And the next time, the viewer application will be launched quickly. 👍

**Comment by Aquariusquintini** [comment]
> Hi, we are working on that issue,
> 
> Before official release could you please try if this prebuilt **k4abt_simple_3d_viewer.exe** works for you? just replace existing **..\Azure Kinect Body Tracking SDK\tools\k4abt_simple_3d_viewer.exe** with attached file and run body tracking with CUDA or TRT
> 
> Please use v1.1.1 BT SDK and the latest NVidia driver.
> 
> [k4abt_simple_3d_viewer.zip](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/8440756/k4abt_simple_3d_viewer.zip)

I can confirm that the attached zip-file works.

Environment details:
Azure Kinect SDK 1.4.1
Azure Kinect Body Tracking SDK 1.1.1
Intel Core i9-10980XE
Nvidia CUDA 11.6
Nvidia RTX 3080 GPU
Nvidia driver 512.15
Windows 10 21H1 (Build 19043.1526)

**Comment by pschaub** [comment]
> Hi, we are working on that issue,
> 
> Before official release could you please try if this prebuilt **k4abt_simple_3d_viewer.exe** works for you? just replace existing **..\Azure Kinect Body Tracking SDK\tools\k4abt_simple_3d_viewer.exe** with attached file and run body tracking with CUDA or TRT
> 
> Please use v1.1.1 BT SDK and the latest NVidia driver.
> 
> [k4abt_simple_3d_viewer.zip](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/8440756/k4abt_simple_3d_viewer.zip)

works, tested on RTX 3090, nvidia driver 512.15

**Comment by qm13** [comment]
Fixed in v1.1.2

**Comment by anggawahyuw** [comment]
> 
It doesn't work for my laptop, RTX 3070 TI. I am confused how to run body tracking with CUDA or TRT?

**Comment by anggawahyuw** [comment]
it works, RTX 3070 Ti, windows 11 pro, thank you
