### ISSUE TITLE
Failure execute sample_unity_bodytracking Build with BT1.1.1

### ISSUE THREAD

**Issue by naonaoue** [microsoft/Azure-Kinect-Sensor-SDK#1767]
I'm trying BT1.1.1 with Unity.
'sample_unity_bodytracking' works perfectly with UnityEditor2020.3 (LTS) if you follow these documents.

'Change log v1.1.1','Microsoft Visual C ++ Redistributable latest supported downloads', and'Azure-Kinect-Samples / body-tracking-samples / sample_unity_bodytracking / ReadMe.'

However, in the build of'PC, Mac & Linux Standalone-> windows-> x86_64', even if you insert Dll as instructed after the build is successful, when you execute it,'K4A_WAIT_RESULT_FAILED' wait the thread of BT.

Finally if you Build a Standalone Executable
 Then you will need to put these files in the same directory with the .exe:
onnxruntime.dll
onnxruntime_providers_cuda.dll
onnxruntime_providers_shared.dll
onnxruntime_providers_tensorrt.dll
dnn_model_2_0_op11.onnx
dnn_model_2_0_lite_op11.onnx
cudnn64_8.dll
cudnn_cnn_infer64_8.dll
cudnn_ops_infer64_8.dll
cudart64_110.dll
cublas64_11.dll
cublasLt64_11.dll
cufft64_10.dll
directml.dll

why is that?

**Comment by fkavache** [comment]
Hi @naonaoue

What is the question exactly? Why does a standalone executable need library files to be copied by yourself in order to work?

**Comment by naonaoue** [comment]
Hi@[fkavache](https://github.com/fkavache)
Excuse me. It seems that I didn't have enough vocabulary.
I know I need a copy as it is written in the ReadMe.
If you follow the ReaMe instructions in'sample_unity_bodytracking'to copy the dll, but the exe built by Unity will not work.
The error 'K4A_WAIT_RESULT_FAILED' on starting BodyTracking thread.
Is there a mistake in the ReadMe description?

**Comment by fkavache** [comment]
@naonaoue 

Could you please share how to reproduce exactly?

**Comment by naonaoue** [comment]
OK. @fkavache
1)My Local is reactor2019.
![スクリーンショット 2022-04-17 202859](https://user-images.githubusercontent.com/27718076/163712436-9c78b548-ffed-4796-9896-03ed009d9819.jpg)
2)This Sample is Works fine On 'Unity Editor 2020.3.33f1'.
![スクリーンショット 2022-04-17 202805](https://user-images.githubusercontent.com/27718076/163712585-b94d0379-b5a3-4e44-b0f2-500d08ead959.jpg)
3)Build
![スクリーンショット 2022-04-17 203547](https://user-images.githubusercontent.com/27718076/163712654-39ab4584-abc3-4c6b-ba35-342f6019bda5.jpg)
![スクリーンショット 2022-04-17 204659](https://user-images.githubusercontent.com/27718076/163713046-a92bb19c-5072-42f8-8ca0-9a4e4024de07.jpg)
4)copy dll files in the same directory with the .exe
![スクリーンショット 2022-04-17 202337](https://user-images.githubusercontent.com/27718076/163712722-613d95bc-13d4-4920-9058-86877f24c14c.jpg)
5)not work.
![image](https://user-images.githubusercontent.com/27718076/163712795-905b6196-1f19-457d-95b0-e3dd0bfc0efb.png)

6)k4a.log
New logging session started

[2022-04-17 20:38:51.798] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (225): ******************** Device Info ********************
[2022-04-17 20:38:51.798] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (226): K4A SDK version:     1.4.1
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (232): Serial Number:       000405502712
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (236): RGB Sensor Version:  1.6.110
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (239): Depth Sensor Version:1.6.80
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (242): Mic Array Version:   1.6.14
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (245): Sensor Config:       6109.7
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (248): Build type:          Release
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (253): Signature type:      MSFT
[2022-04-17 20:38:51.823] [critical] [t=16204] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\depth\depth.c (259): ****************************************************

**Comment by fkavache** [comment]
@naonaoue

It works in my case, from where are you copying the library files?

![image](https://user-images.githubusercontent.com/29062515/163717335-c2e9c709-8213-4e65-8423-5db9924b3c3e.png)

**Comment by naonaoue** [comment]
@fkavache
Oh, really?
Very thanks for your try!

I copying from ,
1st)C:\Program Files\Azure Kinect Body Tracking SDK\tools
2nd)body-tracking-samples\csharp_3d_viewer\bin\x64\Debug\net48\win-x64
In my case, neither was good.

I want you to tell me the correct place.

**Comment by fkavache** [comment]
@naonaoue

First run **MoveLibraryFiles.bat** it will do the job for you and copy the library files from 
**...\Azure-Kinect-Samples\body-tracking-samples\sample_unity_bodytracking**

**Comment by naonaoue** [comment]
@fkavache
Yes, I did that too and it works in Unity Editor.
However, I think that there are not enough files.

'MoveLibraryFiles.bat'
if not exist Assets\Plugins mkdir Assets\Plugins
set BODY_TRACKING_SDK_PATH=C:\Program Files\Azure Kinect Body Tracking SDK\
set BODY_TRACKING_TOOLS_PATH="%BODY_TRACKING_SDK_PATH%tools\"
set BODY_TRACKING_LIB_PATH="%BODY_TRACKING_SDK_PATH%sdk\netstandard2.0\release\"
copy %BODY_TRACKING_LIB_PATH%Microsoft.Azure.Kinect.BodyTracking.dll Assets\Plugins
copy %BODY_TRACKING_LIB_PATH%Microsoft.Azure.Kinect.BodyTracking.pdb Assets\Plugins
copy %BODY_TRACKING_LIB_PATH%Microsoft.Azure.Kinect.BodyTracking.deps.json Assets\Plugins
copy %BODY_TRACKING_LIB_PATH%Microsoft.Azure.Kinect.BodyTracking.xml Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\netstandard2.0\Microsoft.Azure.Kinect.Sensor.dll Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\netstandard2.0\Microsoft.Azure.Kinect.Sensor.pdb Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\netstandard2.0\Microsoft.Azure.Kinect.Sensor.deps.json Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\netstandard2.0\Microsoft.Azure.Kinect.Sensor.xml Assets\Plugins
copy %BODY_TRACKING_TOOLS_PATH%cublas64_11.dll Assets\Plugins
copy %BODY_TRACKING_TOOLS_PATH%cublasLt64_11.dll Assets\Plugins
copy %BODY_TRACKING_TOOLS_PATH%cudart64_110.dll Assets\Plugins
copy packages\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll Assets\Plugins
copy packages\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll Assets\Plugins
copy packages\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll Assets\Plugins
copy packages\System.Reflection.Emit.Lightweight.4.6.0\lib\netstandard2.0\System.Reflection.Emit.Lightweight.dll Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\native\amd64\release\depthengine_2_0.dll Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\native\amd64\release\k4a.dll Assets\Plugins
copy packages\Microsoft.Azure.Kinect.Sensor.1.4.1\lib\native\amd64\release\k4arecord.dll Assets\Plugins
copy %BODY_TRACKING_TOOLS_PATH%onnxruntime.dll Assets\Plugins
copy %BODY_TRACKING_TOOLS_PATH%k4abt.dll Assets\Plugins
copy %BODY_TRACKING_TOOLS_PATH%cudnn64_8.dll .\
copy %BODY_TRACKING_TOOLS_PATH%cudnn_cnn_infer64_8.dll .\
copy %BODY_TRACKING_TOOLS_PATH%cudnn_ops_infer64_8.dll .\
copy %BODY_TRACKING_TOOLS_PATH%onnxruntime.dll .\
copy %BODY_TRACKING_TOOLS_PATH%dnn_model_2_0_op11.onnx .\
copy %BODY_TRACKING_TOOLS_PATH%cublas64_11.dll .\
copy %BODY_TRACKING_TOOLS_PATH%cublasLt64_11.dll .\
copy %BODY_TRACKING_TOOLS_PATH%cudart64_110.dll .\
copy %BODY_TRACKING_TOOLS_PATH%cufft64_10.dll .\

'README.md'
### Finally if you Build a Standalone Executable 
####Then you will need to put these files in the same directory with the .exe:
- onnxruntime.dll
- onnxruntime_providers_cuda.dll
- onnxruntime_providers_shared.dll
- onnxruntime_providers_tensorrt.dll
- dnn_model_2_0_op11.onnx
- dnn_model_2_0_lite_op11.onnx
- cudnn64_8.dll
- cudnn_cnn_infer64_8.dll
- cudnn_ops_infer64_8.dll
- cudart64_110.dll
- cublas64_11.dll
- cublasLt64_11.dll
- cufft64_10.dll
- directml.dll

**Comment by fkavache** [comment]
@naonaoue

What's happening when you open the UnityCSharp.exe?

**Comment by fkavache** [comment]
@naonaoue

Try File -> Build Settings -> Build.

In my case there is no scene selected.

![image](https://user-images.githubusercontent.com/29062515/163721672-6b7da567-c8a8-4c6c-a343-ad8383b3e5f7.png)

**Comment by naonaoue** [comment]
@fkavache 
I tried "No scene selected" but unfortunately it was the same.

Using your screenshot as a reference, I put in 9 files from the root of 'sample_unity_bodytracking' and 'Assets/Plugins'.
But it didn't work.
It feels like the BT is out

FYI) GPU:RTX3070 / 472.84-desktop-win10-win11-64bit-international-nsd-whql.exe

https://user-images.githubusercontent.com/27718076/163721774-dd451f6f-6171-45a7-9589-5d2d8da14c0d.mp4

.

**Comment by naonaoue** [comment]
@scotthsu98052 @fkavache
Hi,
I may have found another bug.
Does "k4abt.dll" recognize the path of double-byte characters?
BT did not start when I used Japanese double-byte characters in the path of the executable application, built by Unity Editor.
"K4a.dll" seems to be compatible, and Kinect ID etc. were picked up.

**Comment by qm13** [comment]
@naonaoue that is a know issue. See #1540.

**Comment by naonaoue** [comment]
@qm13 Oh really! Will it be fixed in BT1.1.2?

**Comment by qm13** [comment]
There are currently no plans to fix it.

**Comment by KikeVilla** [comment]
Somebody found some fix for this issue?. I got the same problem.
