### ISSUE TITLE
Body Tracking v1.1.1 and 1.1.2 installer errantly deletes v1.1.0

### ISSUE THREAD

**Issue by diablodale** [microsoft/Azure-Kinect-Sensor-SDK#1782]
The MSI installer for Body Tracking v1.1.1 and v1.1.2 both errantly deletes v1.1.0 with no notice, prompt, warning, or choice.

This is an impossible scenario for production-quality software development that needs to support a range of SDK, libraries, versions.
Please reference all Linux projects, or Windows projects like oneAPI, Visual Studio, WinSDK, CUDA.
BT must allow install of its headers,bins,libraries at any location desired by the dev and without deleting other libraries (like itself prior version).

### Setup

* Microsoft Windows [Version 10.0.19044.1706]
* Body Tracking v1.1.0 already installed at `C:\Program Files\Azure Kinect Body Tracking SDK`

### Repro

1. Double-click on `Azure Kinect Body Tracking SDK 1.1.1.msi` or `Azure Kinect Body Tracking SDK 1.1.2.msi`
2. Follow wizard until location inquiry
3. Type `C:\Program Files\Azure Kinect Body Tracking SDK 1.1.1` or similar for 1.1.2
4. Continue wizard

### Result

The installer deletes the existing 1.1.0 folder `C:\Program Files\Azure Kinect Body Tracking SDK`

### Expected

The installer does nothing to `C:\Program Files\Azure Kinect Body Tracking SDK` folder

**Comment by fkavache** [comment]
@diablodale

This issue appears in older versions too.

One way to maintain another version is to **rename after installation**.

Also, we are not planning to fix this issue in the near future.

**Comment by diablodale** [comment]
Is this fixed (completed)? If so, in what version is it fixed?

Or is this closed "wont-fix"? This is a distinct state and therefore has no completion or version.
