### ISSUE TITLE
Only "Azure Kinect 4K Camera" showing in "Device Manager > Camera"

### ISSUE THREAD

**Issue by ratuspro** [microsoft/Azure-Kinect-Sensor-SDK#1792]
Hello, 

I'm trying to use the feed from all Azure Kinect cameras in other apps (e.g. iMotions, OBS) but only the 4K Camera shows up in these apps.
Unfortunately, there is only one camera available on the device manager, under "Camera > Azure Kinect 4K Camera" while the other cameras appear under "Universal Serial Bus devices".
I would expect to see them all under "Camera". Can you please provide further details on how to solve this problem.

Also, note that:
 - I can see all the cameras in the Azure Kinect Viewer but cannot use the feed in other apps.
 - The firmware is the latest one.
 - A factory reset did not solve the issue.
 - I'm using a usb 3.0 port

Thanks in advance

**Comment by AshokPeddakotla-MSFT** [comment]
Adding related Q&A issue : https://docs.microsoft.com/en-us/answers/questions/899174/index.html
