### ISSUE TITLE
How to run the azure kinect sdk example in Visual Studio / Ubuntu

### ISSUE THREAD

**Issue by CNCKNAM** [microsoft/Azure-Kinect-Sensor-SDK#1802]
I want to try `transformation_example` to output `.ply` from `.mkv`  file.

SDK Link: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/transformation

Reference to build the SDK: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md

I have already downloaded the Azure Kinect Viewer and it can run
<hr>

In **Ubuntu**, I clone the SDK folder in /Downloads folder, then using cmake to build 
`mkdir build && cd build`
`cmake .. -GNinja`
`cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug`
`ninja`

But I got the problem that some library not found
  
![image](https://user-images.githubusercontent.com/56154801/179210367-67bec83c-13b8-46aa-b84d-bf4f5f37ab92.png)

<hr>

In **Windows**, Visual Studio 2017 support  `cmake` directly build all. I build all in the root of SDK folder. It builds success but can't run `transformation_example` in cmd

![螢幕擷取畫面 (3)](https://user-images.githubusercontent.com/56154801/179213037-0780c037-a6ed-49db-b9d2-4a131015138e.png)

**Error in Cmd**
It said `not recognized as an internal or external command`
![image](https://user-images.githubusercontent.com/56154801/179213525-0f24a4f9-8f5e-425b-bf78-a633b6c6c753.png)

**<h3>SETUP:</h3>**
<hr>

**Ubuntu**
<ul>
<li>Ubuntu 18.04</li>
<li>SDK Version: 1.4.1</li>
</ul>

<hr>

**Windows Visual Studio**
<ul>
<li>Visual Studio 2017</li>
<li>SDK Version: 1.4.1</li>
</ul>

**Comment by GuardKing** [comment]
Hello, could you please tell me how to solve the problem? I open the folder using VisualStudio, and it run the CmakeLists.txt automaticly, but i still don't konw how to run the example.
![image](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/assets/104762946/1c027365-7c26-4dd5-9746-963229eca72f)
