### ISSUE TITLE
AzureKinectViewer displays No available devices

### ISSUE THREAD

**Issue by CN-PotatoChips** [microsoft/Azure-Kinect-Sensor-SDK#1808]
The 4K camera and depth camera are displayed in Windows Device Manager.The indicator on the back of the device is steady white.I can start the camera using live streaming software but it shows No available devices in AzureKinectViewer .

Log:
[ trace    ] : k4a_device_t_create(). Created   k4a_device_t 000001EEA0117AF0
[ trace    ] : depthmcu_t_create(). Created   depthmcu_t 000001EEA011B590
[ trace    ] : usbcmd_t_create(). Created   usbcmd_t 000001EE9A94D4E0
[ info     ] : find_libusb_device(). Container ID found: {dd2d0228-33d7-4ee8-e1b7-975c9b8cb89e} 
[ info     ] : populate_serialnumber(). Serial Number found 000094102912
[ trace    ] : usb_cmd_io(). XFR: Cmd=00000115, PayloadSize=255
[ trace    ] : colormcu_t_create(). Created   colormcu_t 000001EEA012F990
[ trace    ] : usbcmd_t_create(). Created   usbcmd_t 000001EE9A94EC80
[ info     ] : find_libusb_device(). Container ID found: {dd2d0228-33d7-4ee8-e1b7-975c9b8cb89e} 
[ info     ] : populate_serialnumber(). Serial Number found 000094102912
[ trace    ] : calibration_t_create(). Created   calibration_t 000001EEA0107810
[ trace    ] : usb_cmd_io(). XFR: Cmd=00000111, PayloadSize=10240
[ trace    ] : capturesync_t_create(). Created   capturesync_t 000001EEA009B310
[ trace    ] : queue_t_create(). Created   queue_t 000001EEA028D960
[ trace    ] : queue_t_create(). Created   queue_t 000001EEA028DF50
[ trace    ] : queue_t_create(). Created   queue_t 000001EEA028D8C0
[ trace    ] : depth_t_create(). Created   depth_t 000001EEA010E710
[ trace    ] : usb_cmd_io(). XFR: Cmd=00000201, PayloadSize=18
[ trace    ] : usb_cmd_io(). XFR: Cmd=00000201, PayloadSize=18
[ info     ] : ******************** Device Info ********************
[ info     ] : K4A SDK version:     1.4.1
[ trace    ] : usb_cmd_io(). XFR: Cmd=00000115, PayloadSize=255
[ info     ] : Serial Number:       000094102912
[ info     ] : RGB Sensor Version:  1.6.110
[ info     ] : Depth Sensor Version:1.6.79
[ info     ] : Mic Array Version:   1.6.14
[ info     ] : Sensor Config:       6109.7
[ info     ] : Build type:          Release
[ info     ] : Signature type:      MSFT
[ info     ] : ****************************************************
[ trace    ] : dewrapper_t_create(). Created   dewrapper_t 000001EEA00F50E0
[ trace    ] : queue_t_create(). Created   queue_t 000001EEA028D3C0
[ trace    ] : usb_cmd_io(). XFR: Cmd=000000f2, PayloadSize=0
[ trace    ] : usb_cmd_io(). XFR: Cmd=0000000a, PayloadSize=0
[ trace    ] : color_t_create(). Created   color_t 000001EEA00FADA0
[ error    ] : RuntimeClassInitialize(). Failed to activate source in open camera: 0x80070003
[ error    ] : SUCCEEDED( Microsoft::WRL::MakeAndInitialize<CMFCameraReader>(&color->m_spCameraReader, (GUID *)container_id)) returned failure in color_create()
[ trace    ] : color_t_destroy(). Destroyed color_t 000001EEA00FADA0
[ error    ] : color_create( device->tick_handle, container_id, serial_number, color_capture_ready, handle, &device->color) returned failure in k4a_device_open()
[ trace    ] : queue_t_destroy(). Destroyed queue_t 000001EEA028D3C0
[ trace    ] : dewrapper_t_destroy(). Destroyed dewrapper_t 000001EEA00F50E0
[ trace    ] : depth_t_destroy(). Destroyed depth_t 000001EEA010E710
[ trace    ] : queue_t_destroy(). Destroyed queue_t 000001EEA028D960
[ trace    ] : queue_t_destroy(). Destroyed queue_t 000001EEA028DF50
[ trace    ] : queue_t_destroy(). Destroyed queue_t 000001EEA028D8C0
[ trace    ] : capturesync_t_destroy(). Destroyed capturesync_t 000001EEA009B310
[ trace    ] : calibration_t_destroy(). Destroyed calibration_t 000001EEA0107810
[ trace    ] : usbcmd_t_destroy(). Destroyed usbcmd_t 000001EE9A94D4E0
[ trace    ] : depthmcu_t_destroy(). Destroyed depthmcu_t 000001EEA011B590
[ trace    ] : usbcmd_t_destroy(). Destroyed usbcmd_t 000001EE9A94EC80
[ trace    ] : colormcu_t_destroy(). Destroyed colormcu_t 000001EEA012F990
[ trace    ] : k4a_device_t_destroy(). Destroyed k4a_device_t 000001EEA0117AF0

[ error    ] : RuntimeClassInitialize(). Failed to activate source in open camera: 0x80070003
What does this mean?

**Comment by wangcc123-dave** [comment]
I meet the same probelm.RuntimeClassInitialize(). Failed to activate source in open cemera: 0x80070003.Have you solved it?
