### ISSUE TITLE
Synchronising azure with mocap system to avoid interference 

### ISSUE THREAD

**Issue by bs97** [microsoft/Azure-Kinect-Sensor-SDK#1822]
It has been mentioned in previous issues that synchronisation between azure Kinect and other marker-based IR mocap systems (such as vicon or optitrack) is possible, it just requires custom hardware/software to sync and trigger IR pulses. 

There are a few setups that I can currently imagine:

1) A trigger switch that delays the start of recording between azure and the mocap system - this would require consistent IR pulses in both systems, which would require the same timing for IR pulses throughout the capture. I'm not sure if this is the case.

2)  To avoid relying on the consistency of IR pulses. A IR sensor that acts as a trigger telling azure to start when no IR pulse is received, then using the azure's exposure time as the IR pulse rest time for the mocap system. This method would depend on the reliability of the depth exposure time. Again, I'm unsure how reliable this is. 
 
I am wondering if anyone has any experience with this and could provide a basic outline of what this setup would look like and what additional hardware would be involved? Any help with this matter or nudges in the correct direction would be greatly appreciated.

**Comment by qm13** [comment]
Please see https://docs.microsoft.com/en-us/azure/kinect-dk/multi-camera-sync. You will need a way to electrically connect the mocap system with the AKDK device(s) sync input. Use the mocap system as the master to the AKDK subordinates such that the AKDK device(s) take images when the mocap system is not emitting IR light.

**Comment by bs97** [comment]
Thank you for your response qm13! Does the signal coming from the mocap system act as a start trigger (that is only sent once) or is there continuous input from the mocap to the kinect (everytime there is no IR light emitted)?

**Comment by bs97** [comment]
Thank you for your help qm13!
