### ISSUE TITLE
Azure Kinect device detected by windows but not found in the viewer and the other K4a apps

### ISSUE THREAD

**Issue by frenchtouchXR** [microsoft/Azure-Kinect-Sensor-SDK#1841]
I had my devices working fine on my laptop untill today. They are no more usable by the K4a apps and libraries. I get the error : 
[ error    ] : usb_cmd_get_device_count(). No devices found in the azure viewer. The cameras work fine on my other computer. I changed the cables, double checked the alimentation (it's solid white), switched the usb 3.0 plugs, restarted 20 time the computer, reinstalled the Azure Kinect DK 14.0 and 141. The camera is still not found.
 
![Capture d’écran (89)](https://user-images.githubusercontent.com/40068776/192514294-c2b03a1f-c754-4829-a826-3b4faf286409.png)
![Capture d’écran (90)](https://user-images.githubusercontent.com/40068776/192514297-e4f4b6c5-6b0a-43c9-be92-0889a72d0d3b.png)

**Comment by dasparli** [comment]
Did anything on your laptop change between the last time it worked and today?

Have you tried running another USB device on the same connectors that your Kinect was connected to?

**Comment by frenchtouchXR** [comment]
Hi, Maybe a windows update. I noticed my laptop's bisoncam isn't found anymore by the device manager. I don't know if it has something to do. I tried with another kinect camera on every usb 3 plug. 

Here is the full log error : [ error    ] ( D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\usbcommand\usbcommand.c:1037 ) : usb_cmd_get_device_count(). No devices found

**Comment by frenchtouchXR** [comment]
In the device manager of windows 10 I deactivated/reactivated the webcam : Azure Kinect 4K camera. It then was found again by the kinect viewer. I can't explain what happened.
