### ISSUE TITLE
Performance and quality recommendations regarding body tracking processing model

### ISSUE THREAD

**Issue by MoritzSkowronski** [microsoft/Azure-Kinect-Sensor-SDK#1851]
Hi there,

are there any general recommendations on whether to use CUDA, TensorRT or DirectML for body tracking with the Azure Kinect?

**Comment by l1ndaB** [comment]
We recently wrote a paper about differences in body tracking which might be interesting: [https://www.mdpi.com/1424-8220/23/2/878](https://www.mdpi.com/1424-8220/23/2/878)

**Comment by MoritzSkowronski** [comment]
Thanks, that is super interesting!
