### ISSUE TITLE
k4a_calibration_2d_to_3d related

### ISSUE THREAD

**Issue by myalos** [microsoft/Azure-Kinect-Sensor-SDK#1863]
Hello.
In fastpointcloud example, why are not all points(512x512) valid? Is it because there are places in the image sensor that can not receive light?
`
k4a_calibration_2d_to_3d(
                calibration, &p, 1.f, K4A_CALIBRATION_TYPE_DEPTH, K4A_CALIBRATION_TYPE_DEPTH, &ray, &valid);

            if (valid)
            {
                table_data[idx].xy.x = ray.xyz.x;
                table_data[idx].xy.y = ray.xyz.y;
            }
            else
            {
                table_data[idx].xy.x = nanf("");
                table_data[idx].xy.y = nanf("");
            }
`

**Comment by dasparli** [comment]
I can confirm that a point can be invalid because the field of view of the sensor is limited and so there is a check to ensure that the unprojected point is not outside the field of view.

**Comment by myalos** [comment]
Hi, happy to see you again!  The confirm is what i need,  thank you !  ^ v ^
