### ISSUE TITLE
Can anybody help explain undistort example in SDK

### ISSUE THREAD

**Issue by myalos** [microsoft/Azure-Kinect-Sensor-SDK#1864]
in function compute_xy_range, compute x_min and x_max in 1-mm plane that can project in image sensor
in function create_pinhole_from_xy_range
why fx = 1.f / (x_max_min), ? in my knowledge database, fx = f * \alpha \alpha is the ratio of length in mm to pixel.
why px is -x_min * fx  rather x_min * fx
![image](https://user-images.githubusercontent.com/77491386/204181264-f9ec13e3-9548-4471-839a-bfecf7c2f8d4.png)
i can't figure out how this model works
`ray.xyz.y = ((float)y - pinhole->py) / pinhole->fy;
ray.xyz.x = ((float)x - pinhole->px) / pinhole->fx;
k4a_calibration_3d_to_2d(calibration, &ray, camera, camera, &distorted, &valid);
`
Thanks in advance.

**Comment by dasparli** [comment]
![image](https://user-images.githubusercontent.com/102560310/205363545-f2182ec5-4895-4751-badd-729eedaa09f7.png)

**Comment by myalos** [comment]
Very clear explanation, Thank you ! ^v^
