### ISSUE TITLE
Hello, I would like to ask if you have solved this problem and how to save the original data with code?

### ISSUE THREAD

**Issue by jamajim** [microsoft/Azure-Kinect-Sensor-SDK#1931]
Hello, I would like to ask if you have solved this problem and how to save the original data with code?

_Originally posted by @ZHUI999 in https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1897#issuecomment-1577793848_

**Comment by ZHUI999** [comment]
Good afternoon, the problem has not been solved yet. We hope you will reply to solve the problem as soon as possible.

**Comment by jamajim** [comment]
- > jsmls ks ['s``](

- [ ] ksmus 

- [ ] 

- [ ] 74653e

)
