### ISSUE TITLE
K4AViewer doesn't have a clear error when Depth Engine is missing

### ISSUE THREAD

**Issue by MsDerekMa** [microsoft/Azure-Kinect-Sensor-SDK#197]
If the Depth Engine DLL is missing and you try to start streaming, the error message is a generic "Failed to start device!" error. Ideally K4AViewer would let you know that the Depth Engine DLL is missing. This would require adding a function call to check for the Depth Engine or adding error codes to indicate such a thing.

**Comment by Brent-A** [comment]
Since this is mitigated by the trace messages, I'm closing the issue.

**Comment by wangniancai** [comment]
latest version can't open device , trace just like above , 0.8 worked

**Comment by wes-b** [comment]
@wangniancai the Windows MSI for 1.1.0 is working as expected. Feel free to open a new issue that captures details about your specific issue, and we will work through it.

**Comment by williampMSFT** [comment]
@wangniancai if you're seeing the same trace as above, it means the depth engine wasn't found.  Please ensure depthengine_1_0.dll is present and adjacent to k4aviewer.exe.  You can get the depth engine for Windows from the public Windows MSI.
