### ISSUE TITLE
Document Depth auto power down

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#227]
Depth camera will power down to preserve device life if it detects frames have not been read from the device for more than 60s. 

This is note worthy in the case of being a subordinate device, if the master takes more than 60s, then depth will not start.

**Comment by tesych** [comment]
it is documented in our [Azure Kinect documentation](https://docs.microsoft.com/en-us/azure/Kinect-dk/troubleshooting#depth-camera-auto-powers-down).
