### ISSUE TITLE
Linux build does not support SSE 4.1

### ISSUE THREAD

**Issue by mbleyer** [microsoft/Azure-Kinect-Sensor-SDK#230]
k4a_depth_to_xyz() uses SSE 4.1. Currently, the SSE optimization is only enabled for the Windows build, as the Linux compiler is not configured to use SSE 4.1. Also the #ifdef in \Azure-Kinect-Sensor-SDK\src\transformation\rgbz.c needs to be changed from #ifdef _M_X64 to a macro that is also present in the Linux environment.

**Comment by schultetwin1** [comment]
This was fixed by PR #317
