### ISSUE TITLE
Add documentation on acceptable RGB camera manual exposure values

### ISSUE THREAD

**Issue by mffigueroa** [microsoft/Azure-Kinect-Sensor-SDK#240]
When looking at either the [Kinect hardware specs](https://review.docs.microsoft.com/en-us/azurekinect/azure-kinect-devkit?branch=master) or the [k4a_color_control_command_t documentation](https://review.docs.microsoft.com/en-us/azurekinect/api/k4a-color-control-command-t?branch=master), it is not clear what the acceptable values are for the RGB camera exposure time setting. As a user, the experience then involves trying different values randomly just to see what works.

**Comment by DrMaxP** [comment]
Any ideas on when the hardware specs and this documentation will be accessible to external users?

**Comment by joylital** [comment]
We have some specs here: aka.ms/kinectdocs. Take a look and let us know what additional information is needed to help us improve that.

**Comment by DrMaxP** [comment]
Ok. So general hardware capabilities I haven't seen addressed are:

**Comment by Brent-A** [comment]
Thanks for your interest @DrMaxP! We started a new FAQ list which I hope answers your questions in issue #338.

**Comment by wes-b** [comment]
#362 is related, waiting to hear back from the factory on HW capabilities.

**Comment by tesych** [comment]
the table is not added to [hardware spec](https://docs.microsoft.com/azure/Kinect-dk/hardware-specification#rgb-camera-exposure-time-values)
