### ISSUE TITLE
lib/cmake folder does not have a k4arecordConfig.cmake file

### ISSUE THREAD

**Issue by skalldri** [microsoft/Azure-Kinect-Sensor-SDK#257]
The Azure Kinect SDK can be included in projects by simply pointing cmake to the SDK lib/cmake folder, and then calling:

find_package(k4a 1.0.0 REQUIRED)

This will locate the k4aConfig.cmake file and include the libaries / headers needed to use the SDK.

There is no equivalent file for locating the k4arecord files (k4arecord.dll and .lib). We should have a separate k4arecordConfig.cmake file to make it easier to link against the recording binaries.

**Comment by ichlubna** [comment]
Please can someone tell me what I'm doing wrong? I can't find the config file after building the SDK. I only have the bin folder with the library but can't make it work with a different CMake project using the find_package cause the folder doesn't have config file.

**Comment by pajama** [comment]
There is no "lib/cmake" folder.
