### ISSUE TITLE
Support mapping image other than the depth map from depth space to color space

### ISSUE THREAD

**Issue by yijiew** [microsoft/Azure-Kinect-Sensor-SDK#260]
The instance map in the K4ABT SDK is a map in depth space. But currently there is no way for them to map the instance map from the depth space to color space. It would be useful to have an API to help map the image other than the depth map from depth space to color space.

**Comment by Brent-A** [comment]
Wes will follow up with @yijiew to work out a set of requirements.

**Comment by yijiew** [comment]
It is some custom format. Basically it will be a 8-bit image covers the same resolution as the depth/IR image. 

The fast point cloud example is a very good way to generate point cloud in 3d. But projecting the point cloud in 3d back to other camera space is not that trivial by the following reasons: 
1. the naïve method won't handle the occlusion
2. the 3d point cloud is not dense enough to cover every pixels in the new camera view. 

Our transformation algorithm handles both cases by creating mesh out of the point cloud to fill in the missing pixels. I guess it will be hard for our users to implement this algorithm by themselves. I will further chat with Wes about this then. Thanks!

**Comment by dimitrijevic** [comment]
I'm sorry to crash in, but is this Kinect Fusion-like API, or producing mesh from a depth map? If so when please, will this come? Open sourced, or...? TIA

**Comment by yijiew** [comment]
It is not related to produce mesh from a depth map. We create a simple mesh internally for us to transform between coordinates in GPU. But I don't think we will ever expose that mesh out. Please feel free to create this separate issue if you think the mesh data is important.
