### ISSUE TITLE
bootstrap-ubuntu.sh failures do not block build

### ISSUE THREAD

**Issue by Brent-A** [microsoft/Azure-Kinect-Sensor-SDK#285]
See this build:

https://dev.azure.com/aipmr/azure-kinect-sensor-sdk-CI/_build/results?buildId=1330

Transient network outages can result in bootstrap-ubuntu.sh failing to install proper packages. Later build steps fail due to running in an unexpected environment.

We should ensure that errors in this setup step block further steps from running.

**Comment by joylital** [comment]
Let's have a proposal for how we will address this before we take a change.

**Comment by Brent-A** [comment]
We can re-open if we see more problems. This should also be mitigated by #460 if we do that.
