### ISSUE TITLE
LibUsb prints out error messages when multiple devices are in use.

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#302]
LibUSB should not generate error messages when opening two Azure Kinects at the same time.

**Comment by somacoder** [comment]
See https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/485 for a more specific description to this error.

**Comment by somacoder** [comment]
See #485 for a more specific description of this error.
