### ISSUE TITLE
Basic support for Kinect-v2 sensors

### ISSUE THREAD

**Issue by rfilkov** [microsoft/Azure-Kinect-Sensor-SDK#337]
**Is your feature request related to a problem? Please describe.**

There is no way to do real tests of K4A SDK, before you actually ship the Azure Kinect DK.

**Describe the solution you'd like**

If not too much extra work, it would be nice, if this SDK provides at least basic support for the Kinect-v2 sensors, as well. This way it would be much easier more people to test the SDK, in means of reliability, usability and performance.

**Describe alternatives you've considered**

**Additional context**

**Comment by Brent-A** [comment]
Thanks. Unfortunately this isn't something that can be accomplished very easily and is outside of the scope of the Azure Kinect Sensor SDK design.

We are looking to publish some pre-recorded sample data (#339) to help people get started without hardware.
