### ISSUE TITLE
Azure Kinect FAQs

### ISSUE THREAD

**Issue by Brent-A** [microsoft/Azure-Kinect-Sensor-SDK#338]
We are planning to publishing an updated list of FAQs at [https://azure.com/kinect](https://azure.com/kinect). 

Here is a current list of FAQs that we are gathering before updating the site. Please comment on this issue if you have suggestions for additional FAQs.

### What are the hardware specifications?

Hardware specifications are available at [https://aka.ms/kinectdocs](https://aka.ms/kinectdocs).

### Can I find the relative position of two Azure Kinect devices?

This won't be part of the SDK, but we hope to provide examples on some techniques to do this.

### What are the limits on how many devices can be synchronized?

It is recommended that you connect a maximum of 9 subordinate devices in daisychain configuration, or 3 subordinates in a star configuration. 

### How many devices can be connected to a single PC?

The CPU and GPU requirements are variable depending on the framerate and resolution of the device. The minimum spec for a PC ensures that one device running at its maximum framerate will function well. If devices are connected to separate USB root ports, and you have sufficient resources, you should be able to connect any number devices.

### Can you control the master to subordinate device capture offset?

Yes. This can be used to reduce interference between cameras or create effectively higher framerates.

### Can the Azure Kinect DK be used outdoors?

The device should only be used in the [operating environment conditions](https://azure.com/kinect). The Azure Kinect DK is not weather proof.

### What are the details of specific modes?

Details are available here [https://aka.ms/kinectdocs](https://aka.ms/kinectdocs).

### When will the device be available in my area?

Watch [https://azure.com/kinect](https://azure.com/kinect) for updates on this topic.

### Where can I ask more questions or provide feedback?

For questions and issues pertaining to the SDK, please check our [GitHub issues](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues) and create a new ones if you have more questions.

To voice your support for new features, capabilities, or scenarios for the Azure Kinect SDK or the Azure Kinect DK device, please tell us on our [Customer Voice page](https://feedback.azure.com/forums/920053).

### Can the directional microphone array pinpoint the spatial location of an audio source in 3 dimensions?

@joylital?

**Comment by DrMaxP** [comment]
Many thanks for this.
