### ISSUE TITLE
spdlog verssion you are using is about a year old and causing issues on Linux

### ISSUE THREAD

**Issue by bjelovar** [microsoft/Azure-Kinect-Sensor-SDK#343]
As I was building solution with SDK, I encountered issue where my code is using spdlog and your code is using it as well. However, SDK is using about year old version and it caused some strange memory allocation issue. I stopped further investigation since version difference might be an issue here.
Please update spdlog to latest version 1.3.1.

**Comment by wes-b** [comment]
Hi @bjelovar, thanks for the feedback. Moving to new versions of SpdLog is something we would like to often as it allows up to pickup the latest features of that project. However the internal process for doing so is more complicated. So we will be taking updates only when needed.

As for the SPDLOG issue, I can not reproduce the problem. So I am closing this for now.
