### ISSUE TITLE
On Linux the device doesn't enumerate if the power is connected second

### ISSUE THREAD

**Issue by MsDerekMa** [microsoft/Azure-Kinect-Sensor-SDK#375]
**Describe the bug**
If the power is connected second, a Linux system won't recognize the attached device.

**To Reproduce**
1. Connect a USB-A to C cable to the computer and plug it into the device.
2. Connect the power cable to the device.
3. Use the AzureKinectFirmwareTool to list the device.
4. The tool says no devices are connected.

**Expected behavior**
The order of the USB vs Power shouldn't matter and the device will enumerate if both cables are connected.

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04.2 LTS
 - SDK Version:  1.1.0-beta.0
 - Firmware version: 1.6.987014

**Comment by MsDerekMa** [comment]
This appears to only affect one of my computers. The other computer everything works as expected. One other side effect is that instead of giving an error about not being able to open the device when running without the power connection, it just doesn't show up. In addition after the Firmware Update step where the device is rebooted, the device never enumerates.

**Comment by MsDerekMa** [comment]
This is a computer with an Asus P8Z77-V PRO/THUNDERBOLT motherboard. The USB ports are from the Intel Z77 Chipset and are USB 3.1 Gen 1. The ASMedia host controller does not appear to work at all.

**Comment by MsDerekMa** [comment]
USB View when the Kinect is working:
![Kinect in Good State](https://user-images.githubusercontent.com/13106742/58519215-69e8f480-8167-11e9-804d-e3b07eb70705.png)

USB View when the Kinect is not working:
![Kinect in bad state](https://user-images.githubusercontent.com/13106742/58519217-6c4b4e80-8167-11e9-9dc3-72b32d5e58f8.png)

It looks like the USB hub in the device is enumerating, but that the devices downstream of that are not.

**Comment by wes-b** [comment]
I can't repro this. Lets treat this as a one off issue until we get a signal this is happening on more than 1 PC.

**Comment by lianghongzhuo** [comment]
I also have this problem. When Azure Kinect died (it died quite ofen), I have to unplug the power and USB, and first plug in the power adapter, second plug in the USB to the pc. The other way around will lead to unable to start the camera.
The USB cable is a custom 3-meter usb-c to USB-A cable. (I'm using ubuntu 18.04 with ros)

**Comment by michael-createc** [comment]
Over 2 years later and this exact issue is still very much present on Jetson Nanos running Ubuntu 18.04
