### ISSUE TITLE
Document external capture stablization

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#396]
**Describe the bug**
Multi device capture with manual exposure can take 8 capture to stabilize.

**Additional context**
Auto exposure in multi device is strongly discouraged because time synchronization will always be fluctuating due to the moving exposure time.

**Comment by tesych** [comment]
This is documented in [Azure Kinect documentation](https://docs.microsoft.com/azure/Kinect-dk/troubleshooting#multi-device-synchronization)

**Comment by wes-b** [comment]
We might want to move topic from the above location to just after here: https://docs.microsoft.com/en-us/azure/Kinect-dk/retrieve-images#configure-and-start-the-device. As stabilization requirements seem to align better with getting samples for the first time rather than trouble shooting.

**Comment by wes-b** [comment]
Feel free to close if you disagree

**Comment by tesych** [comment]
updated the documentation
