### ISSUE TITLE
sync does not work in depth only camera modes

### ISSUE THREAD

**Issue by DavidRobb** [microsoft/Azure-Kinect-Sensor-SDK#401]
We have an application that requires only depth frames but these need to be syncronised.

sync does not work with the following configuration:
    m_config.depth_mode = K4A_DEPTH_MODE_WFOV_2X2BINNED;
    m_config.camera_fps = K4A_FRAMES_PER_SECOND_30;
    //  m_config.color_format = K4A_IMAGE_FORMAT_COLOR_MJPG;
    //  m_config.color_resolution = K4A_COLOR_RESOLUTION_720P;

Uncommenting the color camera options provides a 5v sync pulse and sync appears to work as expected.

To reduce unnecessary bandwidth we would like the sync to be available in depth only modes.

**Comment by wes-b** [comment]
Good find! The workaround is to run the color camera on the master only, subordinates do not need the color camera running.
