### ISSUE TITLE
xorg-dev and libsoundio-dev dependencies missing in linux build docs

### ISSUE THREAD

**Issue by 37** [microsoft/Azure-Kinect-Sensor-SDK#405]
Quick / simple one. 

When following the instructions to build from source on linux I found xorg-dev is a dependency not listed alongside the others. 

See: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md#linux-dependencies

My system information: 
Ubuntu 18.04 running i3 with x. 

Command entered:
Step2. 

`    cmake .. -GNinja
`

Errors: 

```
CMake Error at extern/glfw/src/CMakeLists.txt:222 (message):
  The RandR library and headers were not found
-- Configuring incomplete, errors occurred!
```

Attempted installing just libxrandr-dev (sudo apt install libxrandr-dev), which progressed the install to another error: 

```
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Using X11 for window creation
CMake Error at extern/glfw/src/CMakeLists.txt:231 (message):
  The Xinerama library and headers were not found
```

So I just installed the full xorg-dev:
sudo apt install xorg-dev

and cmake runs successfully. 

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/noom/Code/kinect/Azure-Kinect-Sensor-SDK/build
```

Edit: after cmake, when running 'ninja' another dependency presented itself: 

    $ ninja

`ninja: error: 'LIBSOUNDIO_LIB-NOTFOUND', needed by 'bin/k4aviewer', missing and no known rule to make it`

Resolved by installing libsoundio-dev

```
sudo apt install libsoundio-dev
cmake .. -GNinja
ninja
```

Then the SDK built successfuly.

## Suggested action: 
add xorg-dev, libsoundio-dev to list of build deps.

**Comment by MsDerekMa** [comment]
The "building.md" documentation references a list of dependencies and references a script that will install all dependencies.  The list of dependencies in the documentation is what is out of date, the script should install everything appropriately. We should consider just referencing the script itself as the source of truth for the list of dependencies.

**Comment by schultetwin1** [comment]
Thank you for reporting! I'm on it

**Comment by schultetwin1** [comment]
I've change the documentation to just point towards the installation script. That script is run in CI and so should be kept up to date.
