### ISSUE TITLE
Add instructions for installing linux binaries and k4a-tools in SDKv1.1

### ISSUE THREAD

**Issue by 37** [microsoft/Azure-Kinect-Sensor-SDK#406]
After building the SDK for linux it becomes apparent you need the linux binaries / depthengine.so.1.0 file for the SDK to work properly, as per [/docs/depthengine.md](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/depthengine.md). 

For example, running /build/bin/viewer_opengl: 

```
Started opening K4A device...
[2019-06-11 15:12:18.898] [error] [t=17739] ../src/dynlib/dynlib_linux.c (86): dynlib_create(). Failed to load shared object libdepthengine.so.1.0 with error: libdepthengine.so.1.0: cannot open shared object file: No such file or directory
...
[2019-06-11 15:12:18.908] [error] [t=17732] ../src/sdk/k4a.c (741): depth_start(device->depth, config) returned failure in k4a_device_start_cameras()
Failed to start cameras!
Press [enter] to exit.
```

According to the docs the binaries are not yet available for Linux, though should be around for SDKv1.1, which I've just built. 

I did some digging and found [#290](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/290) discussing binary naming and versioning conventions and the mention of binaries being available for linux at http://packages.microsoft.com/

> This is all done. Debian packages are available on packages.microsoft.com. Instructions on how to add packages.microsoft.com are [here](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
> 
> I'm working on getting them updated to include more recent versions of Ubuntu

Looking further into it I managed to get the binaries set up on my system (Ubuntu 18.04). 

## Setting up binaries on Linux: 

For setup instructions for other distros see https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software.

#### Ubuntu 18.04 instructions

```
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install k4a-tools
```

Success! I could now run the SDK examples. 

![screenshot-2019-06-11-16:24:34](https://user-images.githubusercontent.com/10803121/59248779-c1f32100-8c66-11e9-880d-90a31d51e9f9.png)
![screenshot-2019-06-11-15:58:33](https://user-images.githubusercontent.com/10803121/59248787-c61f3e80-8c66-11e9-9c87-e19313a4752e.png)

## Suggested actions:
Add instructions for setting up linux repositories and installing the k4a-tools .debs to /docs/depthengine.md

**Comment by wes-b** [comment]
#293

**Comment by wes-b** [comment]
#7 Is the original issue about this.

**Comment by schultetwin1** [comment]
@37 thank you for the awesome write-up and nice investigative skills. I have added instructions for how to install debian packages to docs/usage.md.

Here is the PR for that change  #412
