### ISSUE TITLE
Hololens unity3d support

### ISSUE THREAD

**Issue by sabariprasad** [microsoft/Azure-Kinect-Sensor-SDK#407]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wes-b** [comment]
Hi @sabariprasad, I see that you opened this [feedback item](https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/37877938-hololens-unity3d-support) on Azure Kinect DK Feedback. That is the best place to track the enhancement, so I am going to close this one.
