### ISSUE TITLE
K4AViewer does not play back IR track on recordings in PASSIVE_IR mode

### ISSUE THREAD

**Issue by xthexder** [microsoft/Azure-Kinect-Sensor-SDK#424]
**Describe the bug**
When opening recording files created in PASSIVE_IR mode, K4AViewer will only display the Color track.
The Depth mode shows as "(None)".

**To Reproduce**
1. Create a test recording with `k4arecorderer -l 10 -d PASSIVE_IR test.mkv`
2. Open the recording in k4aviewer

**Expected behavior**
The IR track should be displayed, and the Depth mode should be K4A_DEPTH_MODE_PASSIVE_IR

**Desktop (please complete the following information):**
 - OS with Version: Windows
 - SDK Version:  1.1.0
 - Firmware version:  N/A

**Comment by wes-b** [comment]
Assigned to @williampMSFT, but he is busy for the next month or so, Help Wanted set.
