### ISSUE TITLE
Getting the floor plane

### ISSUE THREAD

**Issue by vpenades** [microsoft/Azure-Kinect-Sensor-SDK#441]
**Is your feature request related to a problem? Please describe.**

I've looked throught the code of Kinect Azure DK and body tracking SDK and I've noticed there's no way to retrieve the floor plane anywhere.

**Describe the solution you'd like**

Typically, floor plane has been available along with tracked skeleton bodies, but I consider it as a core feature, not something that belongs to an extended SDK, so to me, I woud like this feature to be available in the core SDK.

**Describe alternatives you've considered**

If not in the core SDK, at least it should be available in the body tracking SDK...

**Additional context**

Floor plane is important to transform any detected feature from camera space to world space.

It's typically used on tracked skeleton bodies, But it's not the only use case.

Even for plain image manipulation, being able to transform points from depth camera space to world space allows many interesting artistic effects.

**Comment by cdedmonds** [comment]
This feature request for body tracking has been moved to user voice. 

https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/38188435-ground-plane-support

**Comment by Thaina** [comment]
@cdedmonds Did UserVoice site is already closed ?
