### ISSUE TITLE
Build on clean Ubuntu 18.04 succeeds;device enumerates; however cannot `start`.

### ISSUE THREAD

**Issue by eric-schleicher** [microsoft/Azure-Kinect-Sensor-SDK#454]
**Describe the bug**

Example applications can enumerate, but not start kinect device after successful setup &  build on fresh installation of Ubuntu 18.04 (x64)

Appears to be permission related on the USB port.  *Is possible this is just an Udev rule?*

*update: I lifted an example rules file from kinect2; modified it for the device IDs that the K4A uses.  this resolved the insufficient permissions when attempting to enumerate devices....  

But the core issue still remains; which is that the device cannot be "started"

Rules file I created is [here](https://gist.github.com/eric-schleicher/6c7e9bbf32be9996b5c47b516955fad1)

**To Reproduce**
1. On vanilla Ubuntu 18.04 LTS (desktop) Host
2. Clone and setup build environment per official [instructions page](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md)
   used the `scripts/bootstrap_ubuntu.sh` shell file to prepare the environment
3. Build examples as instructed on ^ instructions page
4. Run (from `build/bin`) `./k4aviewer`;  note that no usb devices are enumerate and console show permission warning
  ```
rosuser@vega:~/Downloads/Azure-Kinect-Sensor-SDK/build/bin$  ./k4aviewer 
libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/002/008: Permission denied
libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
[2019-07-02 14:57:52.405] [error] [t=12861] ../src/usbcommand/usbcommand.c (305): find_libusb_device(). Unable to open LIBUSB at index 0 
[2019-07-02 14:57:52.405] [error] [t=12861] ../src/depth_mcu/depth_mcu.c (68): usb_cmd_create(USB_DEVICE_DEPTH_PROCESSOR, device_index, NULL, &depthmcu->usb_cmd) returned failure in depthmcu_create()
[2019-07-02 14:57:52.405] [error] [t=12861] ../src/sdk/k4a.c (129): depthmcu_create(index, &device->depthmcu) returned failure in k4a_device_open()

  ```

#### Run with elevated permissions
1. In a console enter: `sudo ./k4aviewer`
2. Select the device from available dropdown list, Click 'open device'
6. Select green 'Start' button
7. :(
![image](https://user-images.githubusercontent.com/8261783/60549276-3acf2100-9cd9-11e9-9cef-89ea9f5631cd.png)

**Expected behavior**
Expecting device to open device and stream!

**Screenshots**

when attempting to run  sample applications; they are not able to open the device, following dmesg output occurs

![image](https://user-images.githubusercontent.com/8261783/60548554-33a71380-9cd7-11e9-8693-963c924442bc.png)

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04 LTS 
  `Linux vega 4.19.8-041908-generic #201812080831 SMP Sat Dec 8 13:34:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - SDK Version:  
   git commit `7153c3c0a66219a884feeb1c18c1d04b61cc6493`
 - Firmware version:  
  ![image](https://user-images.githubusercontent.com/8261783/60549180-f5125880-9cd8-11e9-8cad-920f49af8baf.png)

**Additional context**
dmesg output starting from plug in.
```
[ 6180.353040] usb 2-2.1: new SuperSpeed Gen 1 USB device number 10 using xhci_hcd
[ 6180.376160] usb 2-2.1: New USB device found, idVendor=045e, idProduct=097a, bcdDevice= 1.27
[ 6180.376164] usb 2-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6180.376167] usb 2-2.1: Product: 4-Port USB 3.0 Hub
[ 6180.376169] usb 2-2.1: Manufacturer: Generic
[ 6180.376171] usb 2-2.1: SerialNumber: 000254392112
[ 6180.398215] hub 2-2.1:1.0: USB hub found
[ 6180.398446] hub 2-2.1:1.0: 2 ports detected
[ 6180.452885] usb 1-2.1: new high-speed USB device number 18 using xhci_hcd
[ 6180.557603] usb 1-2.1: New USB device found, idVendor=045e, idProduct=097b, bcdDevice= 1.27
[ 6180.557607] usb 1-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6180.557609] usb 1-2.1: Product: 4-Port USB 2.0 Hub
[ 6180.557611] usb 1-2.1: Manufacturer: Generic
[ 6180.557613] usb 1-2.1: SerialNumber: 000254392112
[ 6180.605718] hub 1-2.1:1.0: USB hub found
[ 6180.606037] hub 1-2.1:1.0: 4 ports detected
[ 6180.957014] usb 2-2.1.2: new SuperSpeed Gen 1 USB device number 11 using xhci_hcd
[ 6180.981720] usb 2-2.1.2: New USB device found, idVendor=045e, idProduct=097c, bcdDevice= 1.00
[ 6180.981724] usb 2-2.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6180.981727] usb 2-2.1.2: Product: Azure Kinect Depth Camera
[ 6180.981729] usb 2-2.1.2: Manufacturer: Microsoft
[ 6180.981730] usb 2-2.1.2: SerialNumber: 000254392112
[ 6181.060863] usb 1-2.1.3: new high-speed USB device number 19 using xhci_hcd
[ 6181.164116] usb 1-2.1.3: New USB device found, idVendor=045e, idProduct=097e, bcdDevice= 1.06
[ 6181.164120] usb 1-2.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6181.164122] usb 1-2.1.3: Product: Azure Kinect Microphone Array
[ 6181.164124] usb 1-2.1.3: Manufacturer: Microsoft Corporation.
[ 6181.164126] usb 1-2.1.3: SerialNumber: 000254392112
[ 6181.245518] usb 2-2.1.1: new SuperSpeed Gen 1 USB device number 12 using xhci_hcd
[ 6181.265466] usb 2-2.1.1: Isoc endpoint with wBytesPerInterval of 1024 in config 1 interface 1 altsetting 4 ep 129: setting to 944
[ 6181.265888] usb 2-2.1.1: New USB device found, idVendor=045e, idProduct=097d, bcdDevice= 0.0c
[ 6181.265890] usb 2-2.1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6181.265893] usb 2-2.1.1: Product: Azure Kinect 4K Camera
[ 6181.265894] usb 2-2.1.1: Manufacturer: Microsoft
[ 6181.265896] usb 2-2.1.1: SerialNumber: 000254392112
[ 6181.309774] uvcvideo: Found UVC 1.00 device Azure Kinect 4K Camera (045e:097d)
[ 6181.342367] uvcvideo: Failed to set UVC probe control : -32 (exp. 26).
[ 6181.343708] hid-generic 0003:045E:097E.0017: hiddev2,hidraw4: USB HID v1.11 Device [Microsoft Corporation. Azure Kinect Microphone Array] on usb-0000:05:00.3-2.1.3/input2
[ 6181.345475] uvcvideo 2-2.1.1:1.0: Entity type for entity Extension 2 was not initialized!
[ 6181.345478] uvcvideo 2-2.1.1:1.0: Entity type for entity Extension 6 was not initialized!
[ 6181.345480] uvcvideo 2-2.1.1:1.0: Entity type for entity Extension 5 was not initialized!
[ 6181.345482] uvcvideo 2-2.1.1:1.0: Entity type for entity Processing 3 was not initialized!
[ 6181.345484] uvcvideo 2-2.1.1:1.0: Entity type for entity Camera 1 was not initialized!
[ 6181.345583] input: Azure Kinect 4K Camera as /devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb2/2-2/2-2.1/2-2.1.1/2-2.1.1:1.0/input/input35
[ 6245.485654] usb 2-2.1.1: usbfs: process 14656 (k4aviewer) did not claim interface 0 before use

```

**Comment by wes-b** [comment]
This does sound like a udev issue. But our expectation is that ```su ./k4aviewer``` is enough for the viewer to run successfully.

Also make sure you are seeing a white LED on the back of the device to ensure you are properly connected to USB 3.0 and power.

We also have a sample udev, see https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#linux-device-setup

**Comment by eric-schleicher** [comment]
Yes, I get the LED as expected.  Once you close the error dialog, I do see that audio data is flowing (graph), but no IMU or camera(s)

I'll take look at your udev file.

**Comment by wes-b** [comment]
Something else to consider is if the PC USB Host controller is compatable. We know there are issues with Container ID's on Windows and certain USB 3.X controllers. We also know that some just fail after a few seconds of operation.

If you come up with a good way to list host controllers on Linux it would be great to share as the topic below is Windows focused.
https://docs.microsoft.com/en-us/azure/Kinect-dk/troubleshooting#usb3-host-controller-compatibility

**Comment by tesych** [comment]
There's no repro for this issue. Please provide more information and we will revisit this.

**Comment by martinakos** [comment]
I have the same problem. Ubuntu 18.04 I have copied the 99-k4a.rules to /etc/udev/rules.d/ and I do get a solid white light in the back of the device. Have you found a solution for this problem?

**Comment by wes-b** [comment]
Failing to start is usually caused by the depth engine but being installed

**Comment by martinakos** [comment]
yes, if I disable the depth camera in the GUI I can see the color camera. do I need to install anything else besides k4a-tools?

**Comment by RoseFlunder** [comment]
You need the azure kinect sdk and the installation is described here:
https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download

**Comment by martinakos** [comment]
I did follow that installation guide. I had also installed sudo apt install libk4a1.1-dev 
yet I got the "failed to start device!" error.

**Comment by wes-b** [comment]
Please share your logs and open a new issue. Are you trying to call start on a machine you have remoted to?

**Comment by seva100** [comment]
@martinakos I have had exactly the same problem on Ubuntu 18.04, and updating graphics driver helped. I used the standard system dialogue (Software & Updates -> Additional Drivers) and updated from nvidia-418 to nvidia-430, then made a reboot. Afterwards, depth camera in k4aviewer started working.

**Comment by murez** [comment]
I tested on Ubuntu 20.04 with the bionic deb packages, and it works well by the command `sudo k4aviewer`.

**Comment by jacquesj1** [comment]
Hello,
![Capture d’écran de 2020-11-18 23-42-15](https://user-images.githubusercontent.com/46788587/99597075-b8432080-29f7-11eb-8e2d-a47137e8a63b.png)

I have had exactly the same problem on Ubuntu 18.04, but the rgb cam don't work.
My graphic cards is RTX2080ti (drivers 455).
The log:

[2020-11-18 23:39:51.405] [error] [t=3038] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/capturesync/capturesync.c (144): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    684400 type:Depth
[2020-11-18 23:39:51.439] [error] [t=3038] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/capturesync/capturesync.c (144): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    717733 type:Depth
[2020-11-18 23:39:51.472] [error] [t=3038] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/capturesync/capturesync.c (144): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    751066 type:Depth
[2020-11-18 23:39:51.505] [error] [t=3038] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/capturesync/capturesync.c (144): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    784400 type:Depth
[2020-11-18 23:39:51.539] [error] [t=3038] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/capturesync/capturesync.c (144): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:    817733 type:Depth
[2020-11-18 23:39:51.567] [error] [t=3042] /__w/1/s/extern/Azure-Kinect-Sensor-SDK/src/sdk/k4a.c (269): capturesync_get_capture(device->capturesync, capture_handle, timeout_in_ms) returned failure in k4a_device_get_capture()
![Capture d’écran de 2020-11-18 23-41-14](https://user-images.githubusercontent.com/46788587/99597015-9ea1d900-29f7-11eb-812b-2f268f09553c.png)
