### ISSUE TITLE
Saving individual frames to file in the streaming example

### ISSUE THREAD

**Issue by leo-step** [microsoft/Azure-Kinect-Sensor-SDK#466]
Hello, I have been testing the streaming example and it has been working successfully. However, I would like to save the individual frames to the disk. I was thinking that since the streaming example involved capturing individual frames, it could be modified to save them too. I have been trying to make this modification but unsuccessfully. Can this feature be implemented or can someone point me to a solution that already exists for this?

**Comment by tesych** [comment]
@leo-step, thank you for the suggestion, we do not have a working example at this time how to to save the individual frames to the disk. Please review [Record and Playback API documentation](https://docs.microsoft.com/en-us/azure/Kinect-dk/record-playback-api) to help you get started.
