### ISSUE TITLE
Color to Depth Timing may have an offset if setting manual exposure repeatedly.

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#471]
**Describe the bug**
Setting the exposure time will cause the timing between the depth and color camera to diverge while the device adjusts to the new exposure value. If the exposure is continuously being updated (every frame), even to the same value, then the device will appear to have a permeant offset.

- [ ] We need to update GitHub code comments to capture this issue.
- [x]  We need to update Microsoft.com documentation to capture this issue.

**Solution**
To avoid this only send an exposure setting command if the exposure needs to be changed.

**To Reproduce**
1. Use a test app like throughput_perf or the streaming example
2. Modify the app to set exposure for every frame
3. modify the app to show timestamp differences between color and IR
4. Run the app.

**Expected behavior**
In this scenario we expect that most of the time the timing will be off
**Desktop (please complete the following information):**
 - OS with Version: Windows 10
 - SDK Version:  1.1
 - Firmware version:  1.6.1027514

**Comment by tesych** [comment]
documented in [troubleshooting page](https://docs.microsoft.com/en-us/azure/Kinect-dk/troubleshooting)
