### ISSUE TITLE
turbojpeg.h file not found

### ISSUE THREAD

**Issue by frenche6** [microsoft/Azure-Kinect-Sensor-SDK#476]
**Describe the bug**
For the transformation project, issue finding the 'turbojpeg.h file.
Actual error is: "Cannot open include file: 'turbojpeg.h': No such file or directory".

When navigating to the extern folder, the libjpeg-turbo folder is empty except for the CMakeLists.txt file.

This may be an issue of me not knowing where the file is located to link it properly.

**To Reproduce**
1. Open the examples solution
2. Rebuild solution
3. See Error

**Expected behavior**

To be able to reference the file 'turbojpeg.h', and remove error.

**Screenshots**

![image](https://user-images.githubusercontent.com/10505689/60974305-d83cdd00-a2f7-11e9-99f4-835d38e667d9.png)

**Desktop (please complete the following information):**
 - OS with Version: Windows 1803
 - SDK Version:  1.1.0
 - Firmware version:  Not sure where to find

**Comment by wes-b** [comment]
I am guessing you have a fresh clone and have not yet built the SDK. So the git submodules are not populated. You need to run ```git submodule update --init --recursive``` to pulling the header down.

**Comment by frenche6** [comment]
Thank you for the suggestion, that led me in the correct direction. I downloaded the project, with submodules this time, and I am able to finally run the cmake successfully.
