### ISSUE TITLE
Change to C11 from C99

### ISSUE THREAD

**Issue by Brent-A** [microsoft/Azure-Kinect-Sensor-SDK#481]
**Is your feature request related to a problem? Please describe.**
Some functionality such as `static_assert` doesn't work with C99

**Describe the solution you'd like**
Move the C compiler from C99 to C11

**Describe alternatives you've considered**
If we leave it, we need to continue working around some nice to have features. Since we have no known hard constraint to stay on C99, this seems like the most productive path.

**Comment by wes-b** [comment]
The work for this was not straight forward, and there is no compelling reason to invest in it now, so I am closing this. Happy to bring this back when its needed.
