### ISSUE TITLE
Can Let Azure-Kinect-Sensor-SDK support Nvidia Xavier?

### ISSUE THREAD

**Issue by nonlinear1** [microsoft/Azure-Kinect-Sensor-SDK#486]
My company want to make a product based on Kinect for Azure and Nvidia Xavier. But when I 
install SDK to Nivida Xavier, I failed! So could you make SDK support Nvidia Xavier?
Or Can you give me some suggestion and I can do some work to let SDK support Nvidia Xavier!
 Thanks a lot
Guan

**Comment by wes-b** [comment]
Unfortunately we do not currently support ARM. The private depth engine binary required by the SDK means Microsoft needs to add the support for it. You can go over to https://aka.ms/azurekinectfeedback and vote for the features you want added to the SDK next.
