### ISSUE TITLE
Firmware Missing in Azure Kinect SDK 1.1.0.msi

### ISSUE THREAD

**Issue by jbrownkramer** [microsoft/Azure-Kinect-Sensor-SDK#487]
**Describe the bug**

The [firmware update instructions](https://docs.microsoft.com/en-us/azure/kinect-dk/update-device-firmware) say "In the SDK install location under (SDK install location)\tools\ you should find: ... A Firmware .bin file in the firmware folder, such as AzureKinectDK_Fw_1.5.926614.bin.".  I have installed the SDK by downloading and running the msi file from [https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download](https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download), and there is no .bin file in the \tools\ directory or anywhere else that I can see.

**Comment by wes-b** [comment]
Yes, thank you for the reminder. We need to start adding the firmware. So far there have not been any updates to release.

**Comment by jbrownkramer** [comment]
Oh, OK.  We received a camera recently with the following firmware.  I think you're telling me that this is the latest.  Is that right?

```
Current Firmware Versions:
  RGB camera firmware:      1.6.98
  Depth camera firmware:    1.6.70
  Depth config file:        6109.7
  Audio firmware:           1.6.14
  Build Config:             Production
  Certificate Type:         Microsoft
```

**Comment by wes-b** [comment]
Yes, that is correct.

**Comment by wes-b** [comment]
Yes, this is correct. 

And with a recent check-in to an internal repro, our next released NuGet and MSI installer will have the firmware. For now Linux users will have to crack one of these open to get the firmware if needed.

**Comment by vargasjona** [comment]
Hello @wes-b where Can I find last_firmware.bin for Linux??

**Comment by wes-b** [comment]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#msis
