### ISSUE TITLE
[Request] Move playback C++ wrapper to include/k4arecord

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#491]
**Is your feature request related to a problem? Please describe.**
The include/k4arecord directory doesn't contain C++ wrapper.
However, C++ wrapper for playback already exists in tools/k4aviewer/playback.hpp.
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/tools/k4aviewer/playback.hpp

**Describe the solution you'd like**
**Describe alternatives you've considered**
Move <code>playback.hpp</code> to include/k4arecord from tools/k4aviewer.

**Additional context**
If it is possible, I want to use record feature with wrapper like playback wrapper. (future work?)

**Comment by Brent-A** [comment]
Thanks @UnaNancyOwen. Since this impacts the public API surface, we're going to schedule an internal review to ensure we don't have any concerns regarding future breaking changes, and that we have adequate test coverage for the new API surface.
