### ISSUE TITLE
body tracking viewer error

### ISSUE THREAD

**Issue by chankamlam** [microsoft/Azure-Kinect-Sensor-SDK#492]
as the pic blew

![image](https://user-images.githubusercontent.com/9009522/61173567-a95c8a80-a5c7-11e9-89ba-c8e46efbac6c.png)

OS:Windows10
GPU:low than 1070
CUDA：10

**Comment by wes-b** [comment]
k4abt_simple_3d_viewer.exe

"The application cannot be started normally (Oxc0000142). Click OK to close the application."

**Comment by wes-b** [comment]
0xC0000142 = STATUS_DLL_INIT_FAILED

Check that you have all the required dependecies.

**Comment by cdedmonds** [comment]
@chankamlam can you confirm that:
1. CUDNN is installed and in your path
2. The VC++ 14 runtime is installed

We are working to create better error messages for missing dependencies in a future release.

**Comment by chankamlam** [comment]
How 2 check VC ++ 14 installed or not ,I have been install vs studio 2019, seems it must be already installed

**Comment by chankamlam** [comment]
CUDNN is it meant CUDA? I have been installed CUDA 10, but my GPU Display card is low than 1070, is it the key point of the error

**Comment by yijiew** [comment]
@chankamlam cuDNN is a separate library than CUDA. It needs to be separately installed. Please follow the instruction here for detailed installation steps: https://docs.microsoft.com/en-us/azure/Kinect-dk/body-sdk-setup. 

The body tracking SDK can run on some graphics card that is lower than 1070. We have tested to run it on GTX 1050Ti and it runs OK. May I ask what graphics card are you using?

**Comment by chankamlam** [comment]
@yijiew i have installed CUDA10 before i opened it

**Comment by chankamlam** [comment]
@yijiew i had installed CUDA10 before i opened it

**Comment by yijiew** [comment]
@chankamlam But did you install cuDNN? As I mentioned, cuDNN needs to be installed separately.

**Comment by chankamlam** [comment]
What s cuDNN? official website did not said that needs to installed the cuDNN,how 2 install that?

**Comment by cdedmonds** [comment]
@chankamlam please follow the directions here:
https://docs.microsoft.com/en-us/azure/Kinect-dk/body-sdk-setup

**Comment by venscn** [comment]
https://developer.nvidia.com/rdp/cudnn-archive

**Comment by rabbitdaxi** [comment]
@chankamlam please let us know whether you following the body tracking sdk setup process did fix your issue.

**Comment by cdedmonds** [comment]
Closing this issue since this seems to be a case of missing dependencies. @chankamlam please let reactivate if you have more details to share.

**Comment by twt6** [comment]
once you download the cudnn file, what do you do with it? Save it somewhere specific? Open it? I'm still getting error 0xc0000142

https://developer.nvidia.com/rdp/cudnn-archive

**Comment by yijiew** [comment]
@twt6 : you should copy the cudnn.dll to either the cuda folder or your project folder for it to be loaded correctly.

**Comment by twt6** [comment]
Thank you so much for the response! I'm pretty new to all of this. 

I found a file called "cudnn64_7.dll". The path was CUDA > bin > cudnn64_7.dll. Is that the correct file?

I don't know for sure what you mean by cuda folder or project folder. I found this folder and tried it there but it didn't work:
![Screenshot (1)](https://user-images.githubusercontent.com/56006903/65926229-0edf3c80-e3a9-11e9-8713-e85ea8a1f68d.png)

**Comment by twt6** [comment]
@yijiew

I tried it in this folder as well, still didn't work:

![Screenshot (2)](https://user-images.githubusercontent.com/56006903/65926635-0be54b80-e3ab-11e9-8413-ba8b5857cb1f.png)

**Comment by twt6** [comment]
@yijiew

I just tried this:

https://www.quora.com/How-do-I-register-DLL-files-in-a-Windows-10-64-bit

But it gave me this error:

![Screenshot (4)](https://user-images.githubusercontent.com/56006903/65927868-53220b00-e3b0-11e9-893b-a056f343dc21.png)

**Comment by yijiew** [comment]
@twt6 What version of the SDK are you using? If you download the latest SDK (version 0.9.3), the cudnn64_7.dll should be already included in the tools folder and everything should work out of the box.

**Comment by twt6** [comment]
I am using 0.9.3. I have uninstalled and reinstalled it, and it still is not opening. We downloaded binaries on this page:
https://www.nuget.org/packages/Microsoft.Azure.Kinect.BodyTracking/0.9.3
and put them in the Bin folder. Still not working.

**Comment by ianychoi** [comment]
Thank you for the info - I confirm that using the latest version with dependencies (I cloned some old projects which didn't include them) work very well.

@twt6 If you are using Visual Studio, you can simply remove and re-add the nuget package on *References* menu in your solution explorer. Or please check whether the firmware on the device is up-to-date or not.
