### ISSUE TITLE
libusb errors that devices is no longer connected!

### ISSUE THREAD

**Issue by wqs111000** [microsoft/Azure-Kinect-Sensor-SDK#496]
**Describe the bug**

When  a single Sensor opened, It seems to be working properly. But LibUsb always prints out error messages, as the figure below shows.
**Screenshots**

![clipboard](https://user-images.githubusercontent.com/16065087/61192067-27ae4f00-a6e4-11e9-9aa7-5970c8e8ff61.png)

**Desktop (please complete the following information):**
 - OS with Version: Win 10 
 - SDK Version:  1.1.0 
 - Firmware version: 
![clipboard](https://user-images.githubusercontent.com/16065087/61192234-8f18ce80-a6e5-11e9-8213-5529a747ee6e.png)

**Comment by wes-b** [comment]
Good issue, I have seen this too. Its a delayed message from LibUsb after a device is disconnected.

**Comment by Brent-A** [comment]
Related to #485 and #302.
