### ISSUE TITLE
Unclear documentation for k4a_calibration_2d_to_2d and k4a_calibration_2d_to_3d

### ISSUE THREAD

**Issue by this-username-is-taken** [microsoft/Azure-Kinect-Sensor-SDK#498]
Both functions require a depth argument when being called. However, when the source camera type is color, there is no depth information. The documentation doesn't specify what the depth argument should be and what the expected behavior is in such case.

**Comment by mbleyer** [comment]
We allow for the color camera to be chosen as the source camera type in order to keep these functions as general as possible. One way to derive the depth value in the color camera geometry is to use the function k4a_transformation_depth_image_to_color_camera().

**Comment by this-username-is-taken** [comment]
Thanks Michael. I followed up with Andrew earlier and got clarification on this issue. My only concern is that this is not immediately clear from the documentation. Given that there is no example code on the usage of k4a_calibration_2d_to_2d, I worry that other people may also get confused as I did.

**Comment by rabbitdaxi** [comment]
@this-username-is-taken , I think one thing we can do is update the documents in how-to section https://docs.microsoft.com/en-us/azure/Kinect-dk/use-calibration-functions, or also this function's parameter source_depth_mm's description with the additional message "one way to derive the depth value in the color camera geometry is to use the function k4a_transformation_depth_image_to_color_camera()"
