### ISSUE TITLE
Getter methods for capture and device handle

### ISSUE THREAD

**Issue by darahan** [microsoft/Azure-Kinect-Sensor-SDK#527]
I am using the C++ wrapper of the k4a SDK, but discovered there was no recording functionality in this wrapper. In order to make the C functions ``k4a_record_create" and "k4a_record_write_capture" to work, I needed the device and capture handles. However, these handles are private within the C++ wrapper. Therefore I added getter methods to their respective classes. I would suggest these getter methods are added until a C++ recording wrapper is built. I am willing to cooperate in both.

**Comment by wes-b** [comment]
We are open to this, feel free to submit a PR.

This is also partially related to #416.

**Comment by darahan** [comment]
Will do!
