### ISSUE TITLE
External sync has fixed 10,000us timestamp delay when single PC has dual-device  

### ISSUE THREAD

**Issue by YuXinFan** [microsoft/Azure-Kinect-Sensor-SDK#528]
**Describe the bug**
I installed two Kinect DK on a single PC and configure the external sync with 3.5mm audio cable. I set the configuration of cameras with correct MASTER and SUB. However, they have a fixed 10,000us delay. Only in few times, they work well. And when I give it a 1s thread sleep after starting cameras, these two devices became aligned.  

**Desktop (please complete the following information):**
 - OS with Version: Windows 1803
 - SDK Version:  1.1.0

**Comment by wes-b** [comment]
Thanks for the question, I think you might be hitting #471. Additionally there are a couple other issues impacting multi device synchronization, which are captured with #530. Let me know if you are still seeing an issue that you don't think falls into one of those buckets and we will reopen this.
