### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by imanjj** [microsoft/Azure-Kinect-Sensor-SDK#531]
**Is your feature request related to a problem? Please describe.**
I need to develop in Unity but do not have programming skills to plug Kinect into Unity.

**Describe the solution you'd like**
A starter project that I can use the camera inside the environment.

**Additional context**
We are trying to remote control a robot. Unity environment is giving us a lot of help with developing mixed-reality application. If we could plug Kinect into it as well. We could maximize our application's utility.

**Comment by cdedmonds** [comment]
Thanks for this feature request @imanjj. We are tracking interest in Unity on our user voice site here:

https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/38079964-azure-kinect-dk-unity-sdk

Please up vote so we can prioritize interest.
