### ISSUE TITLE
Post process options for "occlusion noise" and others.

### ISSUE THREAD

**Issue by barakooda** [microsoft/Azure-Kinect-Sensor-SDK#533]
either from one or multi camera data, 
if you guys can offer state of  the art 
realtime TOF "occlusion noise" post process manipulations options.
it will be great.
(currently i only delete points by distance or triangle size or edge detection )

https://www.youtube.com/watch?v=0FBY_wlY9pQ

keep up the great work

**Comment by cdedmonds** [comment]
@barakooda this may be an area that we could publish samples. Different applications will likely have slightly different filtering needs.

**Comment by mbleyer** [comment]
@barakooda, can you specify what exactly you mean by _occlusion_ noise?

**Comment by barakooda** [comment]
Well I`m not using scientific terms :-) or expert on this side.
but,as far as noticed,
there is "regular" noise when you for example point the sensor onto a wall and sees running bumps.
and 
there are different kind of noise \ artifacts behaviors on the edges...
I can understand maybe its interpolation outcome between gaps on the Z .
but it can really behave weird,maybe unpredictable in some cases... (?)
so i called it occlusion noise :-)

**Comment by cdedmonds** [comment]
Currently this is outside of the scope of the changes we are considering for the sensor SDK.
