### ISSUE TITLE
LoggingManager error when create more than one body tracker

### ISSUE THREAD

**Issue by YuXinFan** [microsoft/Azure-Kinect-Sensor-SDK#540]
**Describe the bug**
when create more than one k4abt_tracker_t using k4abt_tracker_create(), there will be an error says "Only one instance of LoggingManager created with InstanceType::Default can exist at any point in time." and the program crashes during the second "Initializing CUDA and ONNX Runtime..." section.

**To Reproduce**

1. open two devices and open both cameras
2. create first k4abt_tracker_t by k4abt_tracker_create()
3. create second k4abt_tracker_t by k4abt_tracker_create()
4. the error occurs

**Expected behavior**
the second tracker was created successfully and program not crash 

**Desktop (please complete the following information):**
 - OS with Version: Windows 1803 
 - SDK Version:  1.1.1

**Comment by cdedmonds** [comment]
Currently body tracking does not support multiple tracker instances in the same process. This is the same issue as reported in #519
