### ISSUE TITLE
Cannot create Capture in C#

### ISSUE THREAD

**Issue by rfilkov** [microsoft/Azure-Kinect-Sensor-SDK#542]
**Describe the bug**

I tried to create a Capture with my own color and depth data, like this:

`

                device.StartCameras(new DeviceConfiguration
                {
                    ColorFormat = ImageFormat.ColorBGRA32,
                    ColorResolution = ColorResolution.r1080p,
                    DepthMode = DepthMode.NFOV_Unbinned,
                    SynchronizedImagesOnly = true,
                });

                using (Capture capture = Sensor.Capture.Create())
                {
                    int colorWidth = 1920, colorHeight = 1080;  // ImageFormat.ColorBGRA32
                    Image colorImage = new Image(ImageFormat.ColorBGRA32, colorWidth, colorHeight, colorWidth * 4);

                    byte[] btColorImage = new byte[colorWidth * colorHeight * 4];
                    colorImage.CopyBytesFrom(btColorImage, 0, 0, btColorImage.Length);
                    colorImage.Timestamp = new TimeSpan(DateTime.Now.Ticks);

                    int depthWidth = 640, depthHeight = 576;  // DepthMode.NFOV_Unbinned
                    Image depthImage = new Image(ImageFormat.Depth16, depthWidth, depthHeight, depthWidth * sizeof(ushort));

                    byte[] btDepthImage = new byte[depthWidth * depthHeight * sizeof(ushort)];
                    depthImage.CopyBytesFrom(btDepthImage, 0, 0, btDepthImage.Length);
                    depthImage.Timestamp = new TimeSpan(DateTime.Now.Ticks);

                    capture.Color = colorImage;
                    capture.Depth = depthImage;

                    Debug.Print("Capture.Color: " + capture.Color);  // prints null
                    Debug.Print("Capture.Depth: " + capture.Depth);  // prints null
                }
`

Although colorImage and depthImage are valid, after the assignment capture.Color and capture.Depth are both null.

**To Reproduce**

Execute the code snipped above.

**Expected behavior**

I expected to get a valid Capture with valid images inside.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: Windows 1809
 - SDK Version:  1.1.1
 - Firmware version: factory defaults  

**Additional context**

**Comment by Brent-A** [comment]
Thanks @rfilkov, I see the problem. It looks like we aren't calling the k4a_capture_set_color API so the managed cache is getting overwritten the next time we read the image. I'll work on getting a fix in.

**Comment by rfilkov** [comment]
Thank you, @Brent-A

**Comment by t-kurtke** [comment]
Hey! How can you do              
` depthImage.CopyBytesFrom(btDepthImage, 0, 0, btDepthImage.Length);`
?? I can't find this function anywhere. Thank you!
