### ISSUE TITLE
capture error when multi-device using multi-thread to capture

### ISSUE THREAD

**Issue by YuXinFan** [microsoft/Azure-Kinect-Sensor-SDK#550]
**Describe the bug**
When installing multi-device (at the first time, 4 devices/at the second time, 6 devices), create a thread for each device to do capturing. Store captures in a short queue. And the main thread gets the capture result from the queue.  The function capturesync_get_capture() sometimes gets error.

**To Reproduce**

1. Install multi-devices, 6 devices in my problem, connect and set them as external sync.
2. Set the "synchronized_images_only" to true. 
3. Set Image Format to RGBA32, Set color resolution to 2016P, set depth resolution to NFOV_UNBINNED
4. Start all devices, Create a thread for each device to do capturing
5. Start running program to do capture. This error occurs.

**Expected behavior**

the program can get captures and runs without error.
**Logs**

[error] [t=9128] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\capturesync\capturesync.c (143): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:   2684400 type:Depth

**Screen**
![image](https://user-images.githubusercontent.com/22362306/61991919-aebada00-b089-11e9-8804-d705281dc7ac.png)

**Desktop (please complete the following information):**
 - OS with Version: Windows 1803
 - SDK Version:  1.1.1 

**Additional context**
When I use 4 cameras with 720p color resolution, NFOV_2X2BINNED depth mode, this error did not occur. But when I increase to 6 devices, 2160p, NFOV_UNBINNED, this error occurs

**Comment by YuXinFan** [comment]
**Additional information**
When I increase the number of kinect device to 6, and increase the image resolution from 720p to 2160p. An error always occurs when capturing

**Logs**
[error] [t=9128] D:\a\1\s\extern\Azure-Kinect-Sensor-SDK\src\capturesync\capturesync.c (143): replace_sample(). capturesync_drop, releasing capture early due to full queue TS:   2684400 type:Depth

**Screen**
![image](https://user-images.githubusercontent.com/22362306/61991775-c1341400-b087-11e9-9e8c-eebafa108f4c.png)

**Comment by wes-b** [comment]
You have too many devices on a single PC. USB can not keep up.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by YuXinFan** [comment]
For your information, I connect 4 PCIe  Data acquisitions to the PC. USBs are connected to data acquisitions. I think it may be ok.

**Comment by cdedmonds** [comment]
@YuXinFan it is possible you are exceeding the available PCIe bandwidth on the machine.

**Comment by wes-b** [comment]
We are happy that you had 4 devices running on a single PC.

**Comment by kalisina** [comment]
Hey @YuXinFan 
Did you manage to fix the issue? I've got the same when running 6 sensors at 1080p

**Comment by YuXinFan** [comment]
> Hey @YuXinFan Did you manage to fix the issue? I've got the same when running 6 sensors at 1080p

@arkader I forgot the detail and I have left the project, but it has been fixed. 

I remember that this error only occurs at the starting process. It has some probability of error or normally starts in my PC.  if the device runs normally, it won't cause this error in the following running. 

Maybe you can add a mechanism in your code to catch the error and mechanism restart it until normally start.
