### ISSUE TITLE
Kinect may lose some captures when do external sync with a time sleep

### ISSUE THREAD

**Issue by YuXinFan** [microsoft/Azure-Kinect-Sensor-SDK#554]
**Describe the bug**

When external sync with multiple kinects, some devices will lose a capture.   
**To Reproduce**

1. Set multiple kinects as external sync.
2. Create a thread for each device to do capturing.
2. Get capture result of each device by a for loop in the main thread.
3. After each loop round in the main thread, let main thread sleep 20ms.
4. See the timestamp of each capture in a round, sometimes they have about 33ms difference.

**Expected behavior**
Captures all have the same timestamp.

**Screenshots**

![image](https://user-images.githubusercontent.com/22362306/62044164-cf736300-b234-11e9-9790-137979e45712.png)

**Desktop (please complete the following information):**
 - OS with Version:  Windows 1803
 - SDK Version:  1.1.1

**Additional context**
When not sleep 20ms in the main thread, captures are synced.

**Comment by spschul** [comment]
While confusing, this behavior isn't exactly incorrect, although it can certainly be frustrating.

First of all, while the device does some internal queueing, if an application needs to be able to keep up with the cameras without dropping any frames, it needs to be fast enough to receive all of those captures as they come in. That's a fairly fundamental limitation.

The Azure Kinect DK will not enforce that a frame dropped on one camera will guarantee that all synced cameras drop that frame. So, simply getting the image for each device doesn't guarantee that they will stay in sync.

If your use-case requires all device captures to have a corresponding capture on all other devices that you are using, one simple solution is to keep track of a capture from each device, and, in a loop, get a new capture for the camera that currently has the oldest capture, updating it and bringing that camera's tracked capture closer to up-to-date, until all images of interest have sufficiently close timestamps.

Note that I hope to have an example of how to do this up fairly soon, but it's not quite finished yet.

Hope this helps!
