### ISSUE TITLE
k4aviewer should have a visual indicator when displaying unsynchronized color/depth frames

### ISSUE THREAD

**Issue by mffigueroa** [microsoft/Azure-Kinect-Sensor-SDK#556]
**Is your feature request related to a problem? Please describe.**
This request pertains to the situation of viewing an MKV in k4aviewer that has unsynchronized depth/color frames (i.e. the clip was recorded with k4a_device_configuration_t.synchronized_images_only set to false). When scrubbing the timeline bar back and forth, the timestamp display on the RGB view can vary for the same depth timestamp shown. This is likely because when there is no color frame corresponding to the depth frame, the last viewed color frame is displayed. This can be confusing for the user, as it is not clear initially if this is due to any corruption in the MKV file or other issues.

**Describe the solution you'd like**
Add an indicator overlaying the RGB view near the Timestamp display which indicates that the currently viewed RGB frame does not correspond to the selected timestamp position.

**Describe alternatives you've considered**
- In the Recording Settings pane in the upper left of k4aviewer shown when viewing MKV clips, add a row to display if the color and depth frames are synchronized or not.
- Blur the RGB view or have some other visual indicator on the frame that the currently viewed RGB frame does not correspond to the selected timestamp position.

**Comment by Brent-A** [comment]
I think we will fix #557 which should reduce the need for this. We'd rather not add more complication to the viewer, but if we get more feedback we'll consider this later.
