### ISSUE TITLE
Kinect for Azure averaging images 

### ISSUE THREAD

**Issue by snair61** [microsoft/Azure-Kinect-Sensor-SDK#564]
I am trying to take average of different images captured by the kinect. 
`k4a_image_t depth_image;`
Is there an operator to add images of this format?

**Comment by snair61** [comment]
Adding to above: is it possible to add multiple depth images like the opencv matrices. I want to generate the point cloud for a mean depth image.

**Comment by cdedmonds** [comment]
This is not something we would consider to be in scope for the sensor SDK. The data could be wrapped in an OpenCV image to accomplish this.
