### ISSUE TITLE
Body Tracking is inaccurate when arms moves fast and worse when the device is vertical

### ISSUE THREAD

**Issue by wqs111000** [microsoft/Azure-Kinect-Sensor-SDK#603]
**Describe the bug**

1.When the body moves arms  fast in front of the sensor, the arm joints of the body skeleton will  be separate with the arms of the depth image,as the figure below shows.
![clipboard](https://user-images.githubusercontent.com/16065087/62605769-5effcc80-b92d-11e9-9195-43553fc141c5.png)
What is the reason? How to fix it? I tried it with a more powerful graphics card and it didn’t improve. How and when does  the DNN model output its estimated skeleton? 

2. When the device is vertical (that is the cameras are vertical alignment), body Tracking is almost unusable,except for some very standard postures. 
![1111](https://user-images.githubusercontent.com/16065087/62609378-3c24e680-b934-11e9-99c3-fc4c2111661a.png)

**To Reproduce**
1. Stand in front of the sensor.
2. Move arms fast.

And 
1. Rotate the Kinect device to be vertical 
2. Open the body tracking viewer

**Comment by wqs111000** [comment]
Some issues like #514 and #521 are related to this issue.

**Comment by yijiew** [comment]
Thanks for reporting this issue. We are planning to solve these two issues you mentioned in the next release. Please stay tuned.

**Comment by yijiew** [comment]
There is another issue that is opened regarding to the vertical mounting issue #604 . And we are planning to use #514 to track the latency issue. I will close this issue for duplication.

**Comment by fractalfantasy** [comment]
I’ve created a feature request to address the latency, inaccuracy and slow speed of Azure Kinect body tracking by implementing the Kinect 2 ‘random forest’ model as an option.. pls upvote:

https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/39945454-legacy-body-tracking-like-kinect-v2

cc: @wqs111000
