### ISSUE TITLE
Can I use kinect vertically for body tracking?

### ISSUE THREAD

**Issue by isyoon0721** [microsoft/Azure-Kinect-Sensor-SDK#604]
Hi, I use Kinect vertically.

Body tracking is relatively unstable compared to when used in the horizontal direction.

Do I need to replace variables to use vertically?

**Describe the bug**

Body Tracking unusable.

**To Reproduce**

Tested in Simple_3D_Viewer sample : WFOV 2x2 binned Mode

**Expected behavior**

**Logs**

**Screenshots**

![kinect vertical](https://user-images.githubusercontent.com/53856289/62610463-b6f2ff00-b93e-11e9-974a-eeae10a743f5.jpg)
![screenshot1](https://user-images.githubusercontent.com/53856289/62610466-b6f2ff00-b93e-11e9-9768-360fe642d188.PNG)
![screenshot2](https://user-images.githubusercontent.com/53856289/62610468-b78b9580-b93e-11e9-86ec-93bfcbe95560.PNG)

**Desktop (please complete the following information):**
 - OS with Version: Win 10
 - SDK Version:  Azure Kinect Body Tracking SDK 0.9 

**Additional context**

**Comment by yijiew** [comment]
Thanks for reporting this issue. The vertical mounting is not supported in the previous version of SDK, To address this issue, we will add an option for the customer to specify the mounting direction of the sensor when creating the tracker.

**Comment by bibigone** [comment]
> To address this issue, we will add an option for the customer to specify the mounting direction of the sensor when creating the tracker.

It would be really great! Brilliant idea.

**Comment by yijiew** [comment]
The new release 0.9.2 is published! The problem is resolved. You can download this now at: [msi](https://www.microsoft.com/en-us/download/details.aspx?id=100128),  [nuget](https://www.nuget.org/packages/Microsoft.Azure.Kinect.BodyTracking/0.9.2) or apt-get on Linux.
