### ISSUE TITLE
Publish SDK 1.2.0

### ISSUE THREAD

**Issue by Brent-A** [microsoft/Azure-Kinect-Sensor-SDK#608]
1.2.0 has reached beta, and is planned for official release on the week of Aug 19th.

**MSI Link:** *TBD will be posted soon*
**Nuget Link:** [1.2.0-beta.1](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.2.0-beta.1)
**Deb package link:** *TBD will be posted soon*

**For anyone interested in trying the beta:**
Please download and try the 1.2.0 beta packages. File new issues if you encounter any problems, please clearly state the version of the SDK you encountered the problems with (e.g. 1.2.0-beta.0). If you have any other comments on the release, you can also comment on this issue.

**Firmware update:**
There is a new firmware file included in this release. Please follow the [firmware update instructions](https://docs.microsoft.com/en-us/azure/Kinect-dk/update-device-firmware) to update your firmware.

**Summary of [changes](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CHANGELOG.md) from 1.1.x:**
* C# (and other .NET language) support added. Compatible with .NET Standard 2.0.
* Depth Engine breaking changes to 2.0, SDK now relies on this new version.
* Firmware updates for better USB compatibility.
* Added new API's k4a_image_get_device_timestamp_usec(), k4a_image_get_system_timestamp_usec(), 
k4a_image_set_device_timestamp_usec(), k4a_image_set_system_timestamp_usec(), and k4a_image_set_exposure_usec().
* Deprecated API's k4a_image_get_timestamp_usec(), k4a_image_set_timestamp_usec(), and k4a_image_set_exposure_time_usec().
* Added new transformation API k4a_transformation_depth_image_to_color_camera_custom().
* Fixed color exposure get & set API's.
* The C++ API for playback was made public.
* Depth engine is now searched for in the same path as k4a.dll

See full list of issues in this [milestone](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/milestone/3?closed=1).

**Comment by initialneil** [comment]
@Brent-A Thanks for the update! With the new API, when using multiple cameras wire-synced, which timestamp should use to decide the same frame? `k4a_image_get_device_timestamp_usec` or `k4a_image_get_system_timestamp_usec`?

**Comment by wes-b** [comment]
> With the new API, when using multiple cameras wire-synced, which timestamp should use to decide the same frame? k4a_image_get_device_timestamp_usec or k4a_image_get_system_timestamp_usec?

```k4a_image_get_device_timestamp_usec``` is the API returning the hardware timestamp used for device synchronization.

**Comment by ichlubna** [comment]
Thanks, any way to get `libdepthengine.so.2.0` for Linux?

**Comment by rfilkov** [comment]
> With the new API, when using multiple cameras wire-synced, which timestamp should use to decide the same frame? k4a_image_get_device_timestamp_usec or k4a_image_get_system_timestamp_usec?
> 
> k4a_image_get_device_timestamp_usec is the API returning the hardware timestamp used for device synchronization.

@wes_b, what is the idea behind the two timestamps? What is the use case, when should we use k4a_image_get_system_timestamp_usec then?

**Comment by rfilkov** [comment]
@Brent-A Is there msi of 1.2.0b0 available already?

**Comment by tesych** [comment]
@rfilkov, the msi is not available for 1.2 beta.

**Comment by jrterven** [comment]
How to install the nuget package in Ubuntu 18.04?
I already installed mono-devel and nuget on linux as described here: https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools
What's next?

**Comment by venscn** [comment]
If I has many custom image, Can the parameter transformed_depth_image of this function k4a_transformation_depth_image_to_color_camera_custom be null?

**Comment by wes-b** [comment]
> @wes_b What is the idea behind the two timestamps? What is the use case, when should we use k4a_image_get_system_timestamp_usec then?

@rfilkov, k4a_image_get_system_time_nsec() is a time measured by the host system using QueryPerformanceCounter / clock_gettime(CLOCK_MONOTONIC) to capture the host system time when the image arrived. k4a_image_get_device_time_usec is the device's time stamp (that can be synchronized across multiple devices) and has to mapping to host system time.

**Comment by venscn** [comment]
@wes-b
This will waste a lot of memory and time to handle many custom image.

**Comment by christianmakela** [comment]
@venscn 
The depth output buffer is needed for checking occlusions. If client passed in a null pointer then the SDK would have to allocate a temporary buffer for storing the output depth.

The client can reuse the same depth output buffer for all calls to k4a_transformation_depth_image_to_color_camera_custom() which means no memory is wasted vs. calling k4a_transformation_depth_image_to_color_camera_custom() just once.

**Comment by jbrownkramer** [comment]
We've tried out the beta.  It drops in just fine to our system.  Do you know when it is likely to come out of beta?

**Comment by venscn** [comment]
@christianmakela Thank u

**Comment by wes-b** [comment]
MSI and NuGet have been published. The Debian is delayed until next week unfortunately.

http://download.microsoft.com/download/1/9/8/198048e8-63f2-45c6-8f96-1fd541d1b4bc/Azure%20Kinect%20SDK%201.2.0.msi

**Comment by fishcu** [comment]
> How to install the nuget package in Ubuntu 18.04?
> I already installed mono-devel and nuget on linux as described here: https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools
> What's next?

Run `mono nuget.exe install Microsoft.Azure.Kinect.Sensor` in the folder where you want to download the package(s). You will find `libdepthengine.so.2.0` in the `Microsoft.Azure.Kinect.Sensor.1.2.0/linux/lib/native/x64/release/` subfolder.

**Comment by simplecosmas** [comment]
I cannot install this Nuget Link: 1.2.0, on my visual studio for windows get this error "Azure kinect only supports the x86/x64 platform" and my computer is a x64 bit platform.

**Comment by wes-b** [comment]
> I cannot install this Nuget Link: 1.2.0, on my visual studio for windows get this error "Azure kinect only supports the x86/x64 platform" and my computer is a x64 bit platform.

If you are still hitting this, then please open a new issue, and use the bug template share more info.  Your Windows and VS versions would be super helpful.
