### ISSUE TITLE
How to correct the depth image distortion of WFOV mode？

### ISSUE THREAD

**Issue by carlhuang070** [microsoft/Azure-Kinect-Sensor-SDK#610]
Hi,i get the depth frame  by set WFOV mode.
but i found the depth frame is distortion in WFOV mode.
and How to correct the depth image distortion of WFOV mode?

**Comment by rabbitdaxi** [comment]
@carlhuang070 Hope these example code helps: 
- Simple undistort with nearest neighbor interpolation: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/examples/undistort/main.cpp
- Undistort with opencv or custom bilinear interpolation: https://github.com/microsoft/Azure-Kinect-Samples/blob/master/opencv-kinfu-samples/main.cpp

**Comment by rabbitdaxi** [comment]
We will update the undistort example with more details.
