### ISSUE TITLE
C# wrapper missing Custom transformation API

### ISSUE THREAD

**Issue by Brent-A** [microsoft/Azure-Kinect-Sensor-SDK#617]
**Describe the bug**
The new custom transformation APIs were added to C and C++, but not yet to C#.

**Comment by rabbitdaxi** [comment]
Other than k4a_transformation_depth_image_to_color_camera_custom(), there is another newly added one k4a_calibration_color_2d_to_depth_2d(), they both in C\C++, not in C#

**Comment by UnaNancyOwen** [comment]
I think this is required function. Body index map image can't be transformed using C# wrapper.
When will it be implemented? (Do you need to set milestone to [Release 1.4.0](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/milestone/10)?)
Thanks,

**Comment by UnaNancyOwen** [comment]
@Brent-A @rabbitdaxi I have sent a pull request to fix this issue. Please review it! Thanks,
