### ISSUE TITLE
Whether microsoft Body Tracking can support whole top down scenerio?

### ISSUE THREAD

**Issue by carlhuang070** [microsoft/Azure-Kinect-Sensor-SDK#621]
Whether microsoft Body Tracking can support whole top down scenerio?

Such as attachment.

**Comment by carlhuang070** [comment]
![image](https://user-images.githubusercontent.com/24726317/62760475-a9608500-bab6-11e9-98bc-cf2e498c12a3.png)

**Comment by cdedmonds** [comment]
@carlhuang070 this is not currently a supported configuration. If you are interested in this for future releases please make a feature request on the user voice site here: 

https://feedback.azure.com/forums/920053-azure-kinect-dk

@qm13 FYI
