### ISSUE TITLE
Debian package for Ubuntu 16.04

### ISSUE THREAD

**Issue by kiran1228** [microsoft/Azure-Kinect-Sensor-SDK#624]
We need to run the Kinect sensor on a Ubuntu 16.04 system. Is there a prebuilt distribution of this or can we build the SDK and get the Depth Engine binary to run the cameras with this system.

**Comment by wes-b** [comment]
Right now we only have a Debian for 18.04: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#debian-package. But you can build the SDK yourself and get the depth engine from NuGet package: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/608.
