### ISSUE TITLE
Support for Windows 7

### ISSUE THREAD

**Issue by KaiGuo-Vision** [microsoft/Azure-Kinect-Sensor-SDK#630]
Hello, Mr./Ms.

This SDK of Kinect DK supports only Windows 10 and Ubuntu 18.04.  As you know, there are also so many Win 7 users, may I ask your help to update this SDK to support the Windows 7?

Best regards,

**Comment by tesych** [comment]
@KaiGuo-Vision , thank you for this question! I would suggest to post this feature request on [User Voice](https://feedback.azure.com/forums/920053) and if we see a lot of votes for it, we would consider it for implementation.
