### ISSUE TITLE
libk4a.so and libk4arecord.so exporting dependencies symbols

### ISSUE THREAD

**Issue by schultetwin1** [microsoft/Azure-Kinect-Sensor-SDK#650]
**Describe the bug**
libk4a and libk4arecord are exporting symbols from libusb, libuvc, spdlog, and other dependencies.

**To Reproduce**
1. Build this repo on Linux
2. Run `nm -D bin/libk4a.so` to view exported symbols
3. Notice that there are exported symbols that we do not want to export.

**Expected behavior**
The default behavior of GCC (due to legacy reasons) if to make all functions not declared as static visible in the shared object. We do not want this. Instead, we want only functions decorated as K4A_EXPORT to be exported from the shared object.

**Desktop (please complete the following information):**
 - OS with Version: Linux
 - SDK Version:  1.2.0-beta.1 and below

**Comment by johnny761127** [comment]
I have relative issue,
Could you help me to check
Thanks

**Describe the bug**
libk4a.so.1.4.0 dependencies issue on Ubuntu 18.04.6

mkdir build
cd build
cmake .. -GNinja
ninja
FAILED: bin/transformation_example
: && /usr/bin/c++ -g -pie -Wl,--as-needed -Wl,--build-id examples/transformation/CMakeFiles/transformation_example.dir/main.cpp.o examples/transformation/CMakeFiles/transformation_example.dir/transformation_helpers.cpp.o -o bin/transformation_example -Wl,-rpath,"\$ORIGIN:/home/smartall/Azure-Kinect-Sensor-SDK/build/bin" bin/libk4arecord.so.1.4.0 extern/libjpeg-turbo/src/libturbojpeg.a bin/libk4a.so.1.4.0 && :
//usr/local/lib/libpthread.so.0：对‘__libc_fcntl64@GLIBC_PRIVATE’未定义的引用 //usr/local/lib/libpthread.so.0：对‘__open64_nocancel@GLIBC_PRIVATE’未定义的引用
//usr/local/lib/libpthread.so.0：对‘__nanosleep_nocancel@GLIBC_PRIVATE’未定义的引用 //usr/local/lib/libpthread.so.0：对‘__write_nocancel@GLIBC_PRIVATE’未定义的引用
//usr/local/lib/libpthread.so.0：对‘__pause_nocancel@GLIBC_PRIVATE’未定义的引用
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**To Reproduce**
mkdir build
cd build
cmake .. -GNinja
ninja


**Desktop (please complete the following information)**
OS Version: Ubuntu 18.04.6(Using Kinect Azure)), but with another win11 OS(Not using for Kinect Azure)
SDK Version: 1.40
Firmware Version: 1.6.110
