### ISSUE TITLE
Missing VersionInfo.cs files in C# build

### ISSUE THREAD

**Issue by ckcampbell248** [microsoft/Azure-Kinect-Sensor-SDK#661]
When I try to build the C# examples, I get the error "VersionInfo.cs could not be found"

Specifically: 

> Source file 'C:\Users\chrcam\git\kinect\csharp\SDK\..\VersionInfo.cs' could not be found.	
> Source file 'C:\Users\chrcam\git\kinect\csharp\Extensions\WinForms\..\..\VersionInfo.cs' could not be found.
> Source file 'C:\Users\chrcam\git\kinect\csharp\Examples\WinForms\..\..\VersionInfo.cs' could not be found.

I noticed that the string "/VersionInfo.cs" was in the .gitignore file for the repo. 

Are these files missing or am I missing something required to create them?

**To Reproduce**
1. Open k4a.sln in Visual Studio
2. Build solution

**Expected behavior**
Successful build

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS with Version: Windows 10 18950
 - SDK Version:  latest
 - Firmware version:  1.6.98?

**Comment by RoseFlunder** [comment]
Hi,

did you read all instructions for building the project from source?
[https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md)

I could build the C# wrapper without any problems.
Maybe you forgot this part?

> The C# build depends on files generated by the CMake and Ninja build systems. Therefore the CMake configuration steps generates files that will be consumed by the C# Build and Test systems to find the needed components. Therefore, you need to run the CMake configuration and build before loading the C# solution.
