### ISSUE TITLE
Basic Types Need a seprated project targeting "AnyCPU" 

### ISSUE THREAD

**Issue by waynebaby** [microsoft/Azure-Kinect-Sensor-SDK#697]
**Is your feature request related to a problem? Please describe.**

I am Referencing Azure Kinect datatype to other .NET standard Project running in iOS .  Currently the date types are closely coupled with main features, which is blocking build to iOS cos iOS is neither a x86 nor a x64 planform

**Describe the solution you'd like**

an separate nuget project called "AKDK.Primitives"  

**Describe alternatives you've considered**

**Additional context**

**Comment by wes-b** [comment]
Dup of #648?

**Comment by waynebaby** [comment]
@wes-b yes! thanks for referencing
