### ISSUE TITLE
Add images in green screen example

### ISSUE THREAD

**Issue by spschul** [microsoft/Azure-Kinect-Sensor-SDK#706]
**Is your feature request related to a problem? Please describe.**

The green screen example would be better-explained with some pictures.

**Describe the solution you'd like**

I didn't have time to create some visual aids, but if we could either have a short video (probably using windows-G) of the demo working or even a few screen caps of what it looks like when an object is partially obscured, that'd be fantastic!

**Comment by tesych** [comment]
images are added.
