### ISSUE TITLE
Function "k4a_capture_get_depth_image" returns null image

### ISSUE THREAD

**Issue by fyang064** [microsoft/Azure-Kinect-Sensor-SDK#710]
When I called the function to get depth image from capture frame, it gave back nothing at all.
![WeChat Screenshot_20190903004333](https://user-images.githubusercontent.com/44177668/64144762-ff89c500-cde3-11e9-8706-6bfba6d3086a.png)

**Comment by wes-b** [comment]
Sometimes a color or depth image is dropped, especially at startup. If you want to SDK to only provide captures that it has recieved both color and depth images, then set synchronized_images_only to true in k4a_device_configuration_t when starting the cameras.
