### ISSUE TITLE
Version number in the folder name of K4A SDK

### ISSUE THREAD

**Issue by rfilkov** [microsoft/Azure-Kinect-Sensor-SDK#711]
**Describe the bug**

Currently, when the Azure Kinect SDK is installed by MSI installer, the by-default path is 'C:\Program Files\Azure Kinect SDK vX.Y.Z'.

**To Reproduce**

It would be better the path to be without the version number, like 'C:\Program Files\Azure Kinect SDK'. This will make it simpler to keep the environment variables pointing to the latest installed K4A SDK. It will also prevent keeping old folders of the uninstalled SDKs that contain log-files.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: Windows 1809
 - SDK Version:  1.2.0
 - Firmware version:  

**Additional context**

**Comment by wes-b** [comment]
Thanks for the suggestion. One of our goals is to support multiple versions installed side by side. Side by side allows an Alpha/Beta build to be installed next to an official release. This allows developers to point at which ever version they want. So it might be bit more convenient to remove the version in one case, we think it will be more helpful to a larger group to allow multiple versions to install different versions.
