### ISSUE TITLE
Image stride in k4aviewer "too large"?

### ISSUE THREAD

**Issue by fishcu** [microsoft/Azure-Kinect-Sensor-SDK#712]
Minor thing... Just came across this line in `tools/k4aviewer/k4apointcloudvisualizer.cpp`, lines 140ff:

```
m_pointCloudColorization = k4a::image::create(K4A_IMAGE_FORMAT_COLOR_BGRA32,
                                                      m_calibrationData.depth_camera_calibration.resolution_width,
                                                      m_calibrationData.depth_camera_calibration.resolution_height,
                                                      m_calibrationData.depth_camera_calibration.resolution_width * 3 *
                                                          static_cast<int>(sizeof(int16_t)));
```

It seems like it should be something like `sizeof(BgraPixel)` instead (dropping the 3 times multiplier)? Possibly a bug without any resulting issues?

**Comment by wes-b** [comment]
@rabbitdaxi should this be K4A_IMAGE_FORMAT_CUSTOM instead of BGRA?

**Comment by rabbitdaxi** [comment]
@fishcu good catch, by looking at the code, `sizeof(BgraPixel)` definitely makes more sense
