### ISSUE TITLE
C# Examples do not compile.  Missing depthengine_2_0.dll

### ISSUE THREAD

**Issue by WheezardX** [microsoft/Azure-Kinect-Sensor-SDK#713]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4551,5): error MSB3030: Could not copy the file "D:\External\Azure-Kinect\build\Win-x64-Debug-Ninja\bin\depthengine_2_0.dll" because it was not found.

The most recent installer for the SDK is 1.2.0, so I'm not sure how I'm suppose to get 2.0?

Load the K4a.sln under src/csharp/ and try and build the WinForms example.

#c#

**Comment by RoseFlunder** [comment]
depthengine_2_0.dll is shipped with the sensor sdk 1.2.0
