### ISSUE TITLE
Request for depth engine release on debian stretch

### ISSUE THREAD

**Issue by ratman** [microsoft/Azure-Kinect-Sensor-SDK#739]
Hi Everyone,
as the title tells, I would like to request Debian packages for genuine debian distros as well, preferably for stretch, but also for buster. Is there hope for that in the near future?

BR.

**Comment by wes-b** [comment]
Please head over to  https://aka.ms/azurekinectfeedback to ask for this feature.

**Comment by ratman** [comment]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#debian-package

### "We currently have debian packages available for Ubuntu 18.04. If you have need for a different debian distribution, please file an issue."

Guess where the hyperlink leads:

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/new?assignees=&labels=Enhancement&template=feature-request--enhancement-.md&title=

**Comment by wes-b** [comment]
Ahh, thank you for pointing that out. I will update the link
