### ISSUE TITLE
Creating a 3D 360 degree volumetric capture video

### ISSUE THREAD

**Issue by JayaSaiSontineni** [microsoft/Azure-Kinect-Sensor-SDK#742]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tesych** [comment]
closing this issue, but if you have more questions, please let us know.

**Comment by Elenaegr** [comment]
Hello @tesych , I would be interested in knowing if there is any way to merge the 3D models created from different synched kinects into just one. If so, I would like to know the way to do so or any tips to begin with. Thanks!

**Comment by wes-b** [comment]
Check out our green screen sample. It demonstrates how to transform depth data from 1 camera coordinate system to another cameras. It also uses OpenCv to calculate the transformation necessary to convert images between the two cameras.

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/green_screen

**Comment by Elenaegr** [comment]
Hello @wes-b, 
I tried the green_screen example with the following parameters for both configurations (one camera and two synched cameras) and the result seems to be exactly the same one. See the following screenshots:

Result when running it for two cameras **>green_screen.exe 2 9 6 22**
<img width="682" alt="2 kinects" src="https://user-images.githubusercontent.com/40830719/74737074-6137d180-5254-11ea-90c6-6439edb54282.png">

Result when running for it one camera **>green_screen.exe 1 9 6 22**
<img width="510" alt="1 kinect" src="https://user-images.githubusercontent.com/40830719/74737211-a8be5d80-5254-11ea-8cd5-55d195e49894.png">

Which are the differences I should see? I was expecting to get better resolution for the 2 cameras configuration but it doesn't seem to be any. Any help would be appreciated.

**Comment by wes-b** [comment]
The demo works best when the camera's are only a few inches apart and the color (master) is between the two depth camera's.

See this: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/green_screen
