### ISSUE TITLE
Need documentation on merging multiple videos recorded using external synchronization having each sensor connected to it's own host PC

### ISSUE THREAD

**Issue by JayaSaiSontineni** [microsoft/Azure-Kinect-Sensor-SDK#744]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by JayaSaiSontineni** [comment]
I have connected two sensors to different Host PC's. recorded 10 seconds video and have received 2 .mkv files. 

How can I merge them as a single video?

**Comment by tesych** [comment]
@JayaSaiSontineni, you can definitely merge them as a single video. Please check out [green screen sample](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/green_screen) for guidence.

**Comment by JayaSaiSontineni** [comment]
Hello @tesych , Can you please provide more examples if available for better understanding of the concept on how to acheive it.

**Comment by tesych** [comment]
@JayaSaiSontineni , unfortunately we do not have more examples at the moment. Please check again soon.

**Comment by madelinegannon** [comment]
@tesych is there a reference or diagram for how to composite live data streaming from multiple host pcs? The [docs](https://docs.microsoft.com/en-us/azure/kinect-dk/multi-camera-sync#host-computers) suggest it's doable, but I've only seen references to single PC with multiple USB Controllers in practice (like #971).
