### ISSUE TITLE
Can Azure Kinect SDK interact with a web framework? (React, Vue)

### ISSUE THREAD

**Issue by Jeremy410** [microsoft/Azure-Kinect-Sensor-SDK#746]
I need some of the Azure Kinect functionalities, but what if i want to use the camera on the web instead of a desktop application? Will it be possible?

**Comment by troy-virtusense** [comment]
The web browser would have to have support for it, I assume.

**Comment by wes-b** [comment]
No, not natively. You would need to write some kind of service to make it available.
