### ISSUE TITLE
Transform color image to depth camera / Awareness for unknown color

### ISSUE THREAD

**Issue by christiandreher** [microsoft/Azure-Kinect-Sensor-SDK#762]
I have the problem that when transforming a color image to the depth camera, there are large patches of re-used texture in the fringe areas where there should be no color information available.

Here is a picture of the result of this operation, in this case with a hole puncher:

![aligned_image](https://user-images.githubusercontent.com/40353855/64786891-cc77cc00-d56f-11e9-84e3-ca3be7ee5d68.png)

Note the left edge area, where large portions of the texture are re-used. I would expect these patches to be of undefined color, i.e.:

![aligned_image_exp](https://user-images.githubusercontent.com/40353855/64788027-f500c580-d571-11e9-8157-5fb37555088e.png)

It's even visible in the [official documentation](https://docs.microsoft.com/en-us/azure/kinect-dk/use-image-transformation) (right lower picture).

Is it possible to transform the color image to the depth camera and just assign for example an alpha of 0 to those pixels which are occluded, similar to how it is handled when transforming a depth image to the color camera?

My problem is that I do not need a point cloud with such a high resolution, and I don't want to waste so much computation effort to transform the depth image to the color camera, just to downsample it afterwards. Using a lower RGB resolution is not an option, because I need the RGB image for other purposes.

**System:**
 - OS with Version: Ubuntu bionic
 - SDK Version: v1.2.0

(Might be a duplicate of #761, not sure)

**Comment by christiandreher** [comment]
Thank you for your response.

The problem is that I also have to do processing with the pointcloud. I do not need a huge pointcloud, so I'd have to downscale it again. This means, to get a pointcloud which suits my needs I need to:

1. Transform the depth image to the color camera, resulting in a giant pointcloud (takes more time than necessary, because I don't need it at that resolution)
2. Process the whole giant pointcloud to downsample it (is superfluous because I don't need that pointcloud resultion in first place)
3. Process the pointcloud I actually need

This means that a lot of processing power is wasted. It would help a lot if we could downscale the RGB image to map the depth image to that downscaled RGB image.

**Comment by rabbitdaxi** [comment]
@christiandreher Thanks for the feedback. Yes, your idea make sense to me. In fact, you can do that already, you can downsample the RGB image to some resolution that you like. And you can update the k4a_calibration_t color camera intrinisics with the corresponding scale with your downsampled image (focal length/principle point and also the resolution), then you can use the updated calibration object to pass into the transformation create function and use the transform depth to color as it is.

**Comment by christiandreher** [comment]
Thank you very much for your help and support.

This suggestion was really helpful. I was indeed able to achieve what I want by following the steps exactly as you described.

**Comment by RoseFlunder** [comment]
@christiandreher
I would be interested in using this too because I don't need a point cloud with a higher resolution than the depth image.
Could you elaborate about it more in detail what I exactly need to set in the SDK to get a color image with the same resolution as for example the NFOV_UNBINNED depth image?
Then I can switch to this method instead of using the color_to_depth function.

**Comment by rabbitdaxi** [comment]
@RoseFlunder , I provided some simple sample code that you can mimic to help reduce the depth_to_color transform compute with downscale the color image before transform (and how do you fake such a calibration object for transformation initialization). This process assume the downscaling having the color image aspect ratio unchanged.

**Comment by RoseFlunder** [comment]
@rabbitdaxi Thank you very much. That is very helpful.
