### ISSUE TITLE
How to test c# application (unit/integration, mock, pre-recorded playback)

### ISSUE THREAD

**Issue by StummeJ** [microsoft/Azure-Kinect-Sensor-SDK#774]
We're trying to mock (Moq) out the Kinect device, but have noticed that it's written in such a way to not allow this.  The end goal is to test that our application sets up the device correctly and processes an image capture correctly.

Is there any guidance on how to test a C# application that uses the Sensor SDK?

Cheers

**Comment by MsDerekMa** [comment]
Thanks for the feedback. I don't have much familiarity with Moq. Do you have a sample of something you can share where you were trying to mock and were having issues with?

**Comment by StummeJ** [comment]
I don't have a sample but we were looking to test configuration, and capturing a frame to convert to a depth point cloud.  Really any guidance on how to test with the Kinect not in the loop would be amazing.

**Comment by tesych** [comment]
@StummeJ , we are working on C# record and playback and hopefully it will help to resolve the issue.
