### ISSUE TITLE
Update API Reference for Azure Kinect Body Tracking SDK

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#779]
**Describe the bug**

The [API reference](https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/0.9.x/index.html) for Azure Kinect Body Tracking SDK seems old. It is still v0.9.1.
Please update API reference for Azure Kinect Body Tracking SDK.

**To Reproduce**

1. Access to https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/0.9.x/index.html

**Expected behavior**

Update API reference to Azure Kinect Body Tracking SDK v0.9.3.

**Comment by qm13** [comment]
Thanks for pointing this out. Fixed.
