### ISSUE TITLE
Azure kincet view can't start Depth Camera

### ISSUE THREAD

**Issue by ThangUnity** [microsoft/Azure-Kinect-Sensor-SDK#783]
I install https://download.microsoft.com/download/1/9/8/198048e8-63f2-45c6-8f96-1fd541d1b4bc/Azure%20Kinect%20SDK%201.2.0.msi

![2](https://user-images.githubusercontent.com/29943808/65399989-dad4ac00-dde9-11e9-821d-a5da95516ff7.PNG)
![Capture](https://user-images.githubusercontent.com/29943808/65399990-dad4ac00-dde9-11e9-9153-cc32006a570e.PNG)
Please help me

**Comment by wes-b** [comment]
I think you have a bad device. There is no reason you should be getting a TransactionId of 0x5555555. Do you have a 2nd Azure Kinect?

**Comment by ThangUnity** [comment]
I have only a brand new Azure Kinect. why bad device? . What can I do?

**Comment by wes-b** [comment]
Use the k4aviewer and see if you can start just the color camera. Your log indicates reading the depth calibration is returning an invalid transaction ID, and there is no reason for that except the device or firmware are broken.

You can also try a factory reset, and then restore firmware to the version you have above.
https://support.microsoft.com/en-us/help/4494277/reset-azure-kinect-dk
