### ISSUE TITLE
k4a_image_get_exposure_usec() doesn't match value set by k4a_device_set_color_control()

### ISSUE THREAD

**Issue by msamples** [microsoft/Azure-Kinect-Sensor-SDK#784]
Tested on K4A 1.2, Ubuntu 18.04

Problem reproduces with the demo app "k4afastcapture_streaming", but also when lower-level APIs are used.

Ultimately k4afastcapture_streaming makes use of uvc_set_exposure_abs in uvc_camerareader.cpp

By putting different values into the manual exposure control, I can make the camera return images with exposures = {500us, 2500us, 66670us}, but nothing else.

I would expect to have finer granularity in the control of the camera exposure.

This may be an issue with the FW on the device.

**Comment by wes-b** [comment]
Thanks @msamples, please see issue #647 for a definition of how exposure works, and please see #448 for an issue that impacts the actual setting.

**Comment by wes-b** [comment]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/792
