### ISSUE TITLE
Body Tracking in CSharp Samples

### ISSUE THREAD

**Issue by JpEncausse** [microsoft/Azure-Kinect-Sensor-SDK#786]
**Is your feature request related to a problem? Please describe.**

I can only understand and build "quickly" samples in Azure-Kinect-Samples/build2019 
Can you provie a simple sample using Body Tracking in C# ?
(It would be great if the implementation do not require GeForce SDK)

**Describe the solution you'd like**

A CSharp Sample for BodyTracking in Azure-Kinect-Samples/build2019/5 - Body Tracking

**Comment by qm13** [comment]
Body tracking does not currently have a C# wrapper. Please create feedback at https://feedback.azure.com/forums/920053-azure-kinect-dk?filter=top&page=1 for C# wrapper and associated samples.
