### ISSUE TITLE
Missing ReadMe in Body Tracking Samples

### ISSUE THREAD

**Issue by Greta-A** [microsoft/Azure-Kinect-Sensor-SDK#817]
Where is the read me for the body tracking samples? I cannot find it.

**Comment by yijiew** [comment]
@Greta-A : it is not in the sensor sdk repo. You can find all our body tracking samples here: https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples. And the readmes are in each folder.
