### ISSUE TITLE
How can I record the body tracking or at least the joints positions?

### ISSUE THREAD

**Issue by monajalal** [microsoft/Azure-Kinect-Sensor-SDK#831]
There is no save button. I am not sure how to save the body tracking results either into an mkv/video file or as a txt/json file that has joint information.

![image](https://user-images.githubusercontent.com/1892917/66580940-32df1280-eb4d-11e9-9efd-a1a8629ce016.png)

**Comment by RoseFlunder** [comment]
You have to implement something yourself but there are some examples on how to use the body tracking sdk provided in this repository:
https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples

**Comment by JpEncausse** [comment]
Hello @monajalal sincethe last answer from @RoseFlunder , did you implement something you could share to store skeleton data in a raw file for each frame ? Thanks

**Comment by Azzedine-Touazi** [comment]
Hello all
To extract joints and orientations from .mkv file you can use the code from the following link (very interesting)
Azure-Kinect-Samples/body-tracking-samples/offline_processor/

**Comment by aanexplus** [comment]
> Hello all
> To extract joints and orientations from .mkv file you can use the code from the following link (very interesting)
> Azure-Kinect-Samples/body-tracking-samples/offline_processor/

Thanks for your comment. Do you know how to add the bodytrackinghelpers and utilities header file?

**Comment by Azzedine-Touazi** [comment]
Sorry for the delay. Maybe now you have the solution but I still prefer to answer...
I see that you want to build the application on Linux. In this case you can just copy BodyTrackingHelpers.h and Utilities.h in a specific directory and then add the directory path to g++ with -I option (or gcc). **g ++ main.cpp -I / path to specific directory...**   Thanks.

**Comment by aanexplus** [comment]
Thanks! That works. I built a small app to batch process my mkv files with the offline processor. Do you or anybody know how to record or convert the data to bvh format?

**Comment by Azzedine-Touazi** [comment]
I propose to use the Json file generated by offline_processor.exe. For example, you can use the python bvhtoolbox to convert from .csv to .bvh (of course after extracting and saving the Json 3D-joints into csv format…). Br.

**Comment by aanexplus** [comment]
Thanks! I have the JSON file converted to CSV. I will explore the python toolbox to see if it can do what I want.

**Comment by aanexplus** [comment]
> 
> 
> I propose to use the Json file generated by offline_processor.exe. For example, you can use the python bvhtoolbox to convert from .csv to .bvh (of course after extracting and saving the Json 3D-joints into csv format…). Br.

I have been able to convert my Quaternions into Euler but how did you build the hierarchy file? We can also talk via email (aanex2005@gmail.com)

**Comment by Alessandro-Minerba** [comment]
Hi everybody, does anyone solved this issue (saving body tracking results) using C#? I'm quite new to the language and kinect DK device and C# documentation is really poor. Thanks!

**Comment by yudhiardiyanto** [comment]
> Thanks! I have the JSON file converted to CSV. I will explore the python toolbox to see if it can do what I want.

can you share your project please send to yudhi.ardiyanto@gmail.com
