### ISSUE TITLE
"SAVE" button doesn't work in Azure Kinect Viewer

### ISSUE THREAD

**Issue by monajalal** [microsoft/Azure-Kinect-Sensor-SDK#832]
Save button doesn't work before or after clicking on start or stop buttons. Essentially you should be able to save the capture after you click on stop button.

![image](https://user-images.githubusercontent.com/1892917/66581167-a123d500-eb4d-11e9-92a3-8c0658699121.png)

**Comment by wes-b** [comment]
#842
