### ISSUE TITLE
Offline processor body tracking example doesn't run out of the box

### ISSUE THREAD

**Issue by shreyapandit** [microsoft/Azure-Kinect-Sensor-SDK#835]
**Describe the bug**

Trying to run the offline_processor example as mentioned in https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/808

I built the offline processor exe successfully and now trying to feed it an mkv file to convert.
It fails with an error cc @yijiew 

**To Reproduce**

The output json file should have been created.

**Logs**

**Screenshots**

![error_after_cuda](https://user-images.githubusercontent.com/836757/66695149-e8b07b00-ec8b-11e9-8d24-1439afa06149.png)

**Desktop (please complete the following information):**
 - OS with Version: Windows 10
 - SDK Version:  1.0.3

**Additional context**

**Comment by yijiew** [comment]
@shreyapandit Thanks for reporting this! This change should have fixed the issue you reported: https://github.com/microsoft/Azure-Kinect-Samples/pull/32.

**Comment by shreyapandit** [comment]
Glad I could help @yijiew! :)

**Comment by aanexplus** [comment]
> Glad I could help @yijiew! :)

Hey Shreyapandit. How did you record the body tracking as an MKV file?
