### ISSUE TITLE
The camera isn't being recognized in Ubuntu

### ISSUE THREAD

**Issue by rajk97** [microsoft/Azure-Kinect-Sensor-SDK#841]
Hi all! I'm trying to use Azure Kinect SDK on Ubuntu. I have done the installation part right and am able to view the k4aviewer as well. However, I see no device recognized in the window. I'm using dual boot. In windows, I can see the device being recognized there but not in Ubuntu. Can you please help me with this issue? Thanks.

**Comment by wes-b** [comment]
You do this https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#linux-device-setup?

**Comment by rajk97** [comment]
Thanks
