### ISSUE TITLE
3d object tracking example +Unity

### ISSUE THREAD

**Issue by remi0s** [microsoft/Azure-Kinect-Sensor-SDK#844]
**Is your feature request related to a problem? Please describe.**
Currently i have not found any examples of tracking an 3d object using the current SDK. I believe it would vastly beneficial to inlcude such examples since it would be helpfull for projects like VR/AR and much more.

**Describe the solution you'd like**
My main goal is to keep track of a gun's replica (G3A3) in order to use it inside a unity game. I have allready managed to use the body tracking inside the unity using a c# wrapper from [this project](https://github.com/bibigone/k4a.net) and i'm using the replica attached to the right wrist joint for the tracking task. Also for the rotation of the replica i'm currently using an IMU attached inside the replica.
This method is not optimal as the replica might get infront of the line of site of the hands while also i believe it is more computational expensive than tracking the replica alone.
So i would like a to know if its possible to track the replica itself.

**Describe alternatives you've considered**
If tracking the 3d object itself (i guess using some sort of point cloud tracking) is not a viable solution maybe then some alternatives would be:
- Color tracking distinctive colors painted on the replica.
- Infrared led tracking possitioned on the replica.

Thank your for your time.

**Comment by tesych** [comment]
Hello @remi0s , thank you for your suggestion! At this moment there's no plan to develop the sample you are asking, but we will keep it in mind in the future.
