### ISSUE TITLE
Color camera not working

### ISSUE THREAD

**Issue by arpit15** [microsoft/Azure-Kinect-Sensor-SDK#845]
**Description**
The color camera doesn't show up and leads to timeout.

**To Reproduce**
1. Compile SDK on ubuntu 18.04 using default instructions
2. Run executable `./bin/k4aviewer`

**Expected behavior**
The expectation is that the color image will show up in the window of the viewer. 

**Logs**
I compiled the SDK in debug mode which gave [this](https://gist.github.com/arpit15/d9022bf5c2104690e1fe7a7cdc609442) log on the command line. 

**Video**
[google drive link](https://drive.google.com/file/d/1ekaF-Hk6OcXZJHB1LTEJC6IAS-Bm4ln4/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04 kernel 5.0.0-31-generic
 - SDK Version:  master, v1.3.x
 - Firmware version:  
RGB camera firmware:      1.6.102
  Depth camera firmware:    1.6.75
  Depth config file:        6109.7
  Audio firmware:           1.6.14

**Comment by wes-b** [comment]
Hi arpit15, can you collect "info" level logs while reproducing the issue? https://docs.microsoft.com/en-us/azure/Kinect-dk/troubleshooting#collecting-logs

The log you provided above is from LibUvc and doesn't have any errors.

**Comment by arpit15** [comment]
The info level log is [here](https://gist.github.com/arpit15/825ea9855794060ed5cecaeb63af6ae5)

**Comment by wes-b** [comment]
Thanks for the log, that is a critical level log unfortunately. Along with the ENV variable you created you also need `set K4A_LOG_LEVEL=i`

**Comment by arpit15** [comment]
After setting `set K4A_LOG_LEVEL=i`, I get [this](https://gist.github.com/arpit15/a8e535f6ffda8731ec55ecd7109868f2).

**Comment by wes-b** [comment]
Bummer, there is no sign of an error in the log.

Your repro steps are to start the viewer and press start? Are you changing any of the options? 

Any idea what USB Host controller you PC is using?

**Comment by wes-b** [comment]
> I have AMD 3.0 Host controller. I checked it using lspci -v | grep USB

Please see our topic about USB controllers: https://docs.microsoft.com/en-us/azure/kinect-dk/troubleshooting#usb3-host-controller-compatibility

**Comment by arpit15** [comment]
For linux, the document doesn't list the set of host controller which are supported. I am able to get depth image, imu and microphone data. Is there a resource or code you can point me to figure out how to get camera data?
I have [MSI X399 SLI](https://www.msi.com/Motherboard/X399-SLI-PLUS/Specification) plus motherboard. I am unsure if the `lspci -v  | grep USB` is the correct method to check USB host controller type.

**Comment by wes-b** [comment]
We have not tested with that particular USB controller, so I don't know if it should work. 

Can you build the SDK for [debug](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md#building) and capture the LibUvc debug output generated in the console window?

**Comment by wes-b** [comment]
@arpit15 any update on this?

**Comment by fnuabhimanyu** [comment]
@wes-b @arpit15 I am facing a very similar issue. Did you find any solution to this?
