### ISSUE TITLE
Missing k4a.pyd file

### ISSUE THREAD

**Issue by cbg88** [microsoft/Azure-Kinect-Sensor-SDK#847]
**Describe the bug**
 Getting linker errors, missing k4a.pyd file even after downloading the newest version (1.3). File cannot be open as it does not exist in the SDK.

**To Reproduce**

Should be a valid file path (if this file exists, however it does not within our machine). 
File should open. 

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by wes-b** [comment]
Sorry I can't tell what you are compiling. The SDK itself does not include Python.

**Comment by lpasselin** [comment]
It is a typo  from the python sdk you are using.
.pyd files are not required btw. The instructions are wrong.

Try using this python sdk instead: https://github.com/etiennedub/pyk4a
Windows install instruction are provided.
