### ISSUE TITLE
How should I pass the output.mkv which contains RGB+Depth to k4abt_simple_3d_viewer.exe ?

### ISSUE THREAD

**Issue by monajalal** [microsoft/Azure-Kinect-Sensor-SDK#848]
How should I pass the output.mkv which contains RGB+Depth to k4abt_simple_3d_viewer.exe to see the result of body tracking on an already captured depth video?

```
C:\Program Files\Azure Kinect Body Tracking SDK\tools>k4abt_simple_3d_viewer.exe -d WFOV_UNBINNED C:\Users\ivcla\workspace\kinectoutput\shreya_oct17.mkv

USAGE: (k4abt_)simple_3d_viewer.exe Mode[NFOV_UNBINNED, WFOV_BINNED]
    NFOV_UNBINNED (default) - Narraw Field of View Unbinned Mode [Resolution: 640x576; FOI: 75 degree x 65 degree]
    WFOV_BINNED             - Wide Field of View Binned Mode [Resolution: 512x512; FOI: 120 degree x 120 degree]
e.g.   (k4abt_)simple_3d_viewer.exe WFOV_BINNED

```

**Comment by RoseFlunder** [comment]
This is not a feature of the simple 3d viewer.
You would have to integerate it yourself.
The source code for the simple 3d viewer is available in the samples:
https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/simple_3d_viewer

**Comment by monajalal** [comment]
well, I am requesting it as a feature then from Azure Kinect DK team

**Comment by yijiew** [comment]
@monajalal : thanks for putting this request. Since it is not a bug, I will remove the "Bug" tag. 

As @RoseFlunder mentioned, the viewer is open-sourced. Please feel free to modify the code by yourself. We recently posted another sample that demonstrates how you playback a mkv clip and run through the body tracking SDK here: https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/offline_processor. You can try to merge these two samples together.

**Comment by RoseFlunder** [comment]
@yijiew
One question regarding the samples projects:
All projects are Visual Studio projects which is fine for Windows but would it be possible to provide CMake files or sth for Linux as well?

**Comment by yijiew** [comment]
@RoseFlunder : we currently don't have the plan to do so. But it should be straightforward to create your own CMake files for Linux build. Since the sample project is open-sourced, if you create some CMake files that is working, we welcome you to send us a pull request :)

**Comment by billpottle** [comment]
@monajalal - You can now use offline mode in simple_3d_viewer to view pre-recorded files.

**Comment by qm13** [comment]
Fixed
