### ISSUE TITLE
k4a_export.h file missing

### ISSUE THREAD

**Issue by joshy91** [microsoft/Azure-Kinect-Sensor-SDK#852]
Couldn't find any prior documentation online

**Describe the bug**
in order to run c scripts 
the file   includes/k4a subfolder/k4a.h    has the line 
#include <k4a/k4a_export.h> 
But k4a_export.h does not exist within the entire Azure-Kinetic-Sensor-SDK repo
Removing that line generates a series of errors which suggest the file is necessary and contains necessary code

**Desired Resolution**
Please add the appropriate k4a_export.h file within the repo

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04
 - SDK Version:  1.4.0

**Comment by wes-b** [comment]
You need to clone the repo and build with CMake. The header file will be auto generated.
