### ISSUE TITLE
k4a_calibration_2d_to_3d

### ISSUE THREAD

**Issue by yuliangxiao** [microsoft/Azure-Kinect-Sensor-SDK#863]
Why there is no Z coordinate?thanks
![1117](https://user-images.githubusercontent.com/36064756/67839159-f724e080-fb2d-11e9-95a4-dc1396c9effe.jpg)

**Comment by wes-b** [comment]
I don't understand your question. Please elaborate more.

**Comment by yuliangxiao** [comment]
Parameter is "1.f",I don't know the Z coordinate has always been 1.000000,The document says target_point3d_mm unit is mm,Why is the parameter value is -0.1388,Instead of 1388,Where can I find such documents?thanks

**Comment by venscn** [comment]
In the last step of function k4a_calibration_2d_to_3d, x = target.x * source_depth_mm,y = target.y * source_depth_mm, z = source_depth_mm.

**Comment by yuliangxiao** [comment]
I know that,But I want to know why XY is -0.1388,Unit is also mm?thanks

**Comment by rabbitdaxi** [comment]
@yuliangxiao please read through this page first: https://docs.microsoft.com/en-us/azure/Kinect-dk/use-calibration-functions, and please also read the function doc remarks and parameter descriptions. Make sure when you using this function, you need to check the function return valid result. Let us know whether you still have questions after you read the link above. It might be helpful if you describe what exactly trying to do, you can paste sample code if you want us to help you spot your issue

**Comment by yuliangxiao** [comment]
thanks
