### ISSUE TITLE
Depth measure problem and a weird point cloud

### ISSUE THREAD

**Issue by lihk11** [microsoft/Azure-Kinect-Sensor-SDK#873]
I am not sure it is a bug or not, but it really confused me.
I am using the Azure Kinect DK to get point cloud for some parts, but the point clouds I get are weird, please take a look at the following picutre, 
![image](https://user-images.githubusercontent.com/4299373/68014980-f45ff200-fccb-11e9-8084-f1eda8073b22.png)

 The middle one is correct, but the parts in both sides seem to have a dirtortion, because the middle stick of the part is not at the middle...
 
the middle part(expected result):
![image](https://user-images.githubusercontent.com/4299373/68015441-232a9800-fccd-11e9-97ba-ff002204948e.png)

the left one (the middle stick is more left than expected):
![image](https://user-images.githubusercontent.com/4299373/68015477-3473a480-fccd-11e9-9b77-27f6c4627d60.png)
the left one at a different view angle:
![image](https://user-images.githubusercontent.com/4299373/68015484-376e9500-fccd-11e9-9428-4910dcf0b086.png)

Could someone point out what the problem is?

**Comment by rabbitdaxi** [comment]
@lihk11 Thank you for the feedback. It is a little bit challenging to see what is the exactly issue by looking at this point cloud rendering without looking at the real object/environment or setup... Would it be possible for you to make a mkv recording by using the k4arecorder from the SDK when you can repro this issue and share to us? If you feel not comfortable share the recording, then we can  using this issue channel to discuss more by guessing what might be causing it.

**Comment by jesd23** [comment]
Not and check zillow. _vneo,a k popsicleface, james e smith also confused by communication to bring new color.


On Nov 4, 2019, at 11:20 AM, "Andrew Duan" <notifications@github.com<mailto:notifications@github.com>> wrote:


@lihk11<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flihk11&data=02%7C01%7C%7C78f1369ea2304bc7b07008d7615c15f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637084920434911592&sdata=MCfqrECrTSdgHkamJh2Gh%2BzpBytvAcTfjembVJeUjvg%3D&reserved=0> Thank you for the feedback. It is a little bit challenging to see what is the exactly issue by looking at this point cloud rendering without looking at the real object/environment or setup... Would it be possible for you to make a mkv recording by using the k4arecorder from the SDK when you can repro this issue and share to us? If you feel not comfortable share the recording, then we can using this issue channel to discuss more by guessing what might be causing it.

**Comment by rabbitdaxi** [comment]
@lihk11 please let us know whether you have information that can help clarify the issue here. See previous post. For issues more than 7 days old without response, we will close them.

**Comment by jesd23** [comment]
********PRIVATE Confidential Information *******.
