### ISSUE TITLE
How to extract IMU data from mkv output? 

### ISSUE THREAD

**Issue by Dennis2Choi** [microsoft/Azure-Kinect-Sensor-SDK#877]
Hi ~ Folks

I'm just starting to understand what is IMU data from Azure Kinect...
But I cound not find how to get IMU data from Kinect. 
Cause I'm working on the SDK now. 

For now, I just used to use k4arecoder and k4aviewer 
But How can I extract IMU data from MKV file. 
I just learned how to extract RGB image and Depth image from MKV
But there is no description about extracting IMU Data...

Is there any explanation for that? 
Is there any one to help me? 

Thank you

Regards

Dennis

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RoseFlunder** [comment]
You can retrieve them from a recording using this method:
C API: [k4a_playback_get_next_imu_sample](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___functions_ga95ebfacc8f175e1cd8a4ed425b4e5582.html#ga95ebfacc8f175e1cd8a4ed425b4e5582)
There is also a similiar method in the C++ wrapper that you can invoke on the playback object.
