### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by rajk97** [microsoft/Azure-Kinect-Sensor-SDK#879]
Hi all! I'm trying to install k4atools. When I run

`sudo apt install k4a-tools`

I get the following error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 k4a-tools : Depends: libsoundio1 (>= 1.0.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Please help me out. I'm a beginner to this. I'm using Ubuntu 18.04. Thanks.

**Comment by Brent-A** [comment]
(Edited original post for formatting)

**Comment by schultetwin1** [comment]
`k4a-tools` includes a binary called `k4a_viewer` that takes a dependency on libsoundio. The `(>= 1.0.1)` part means we need a version of libsoundio that is greater than 1.0.1.

There are many tutorials out there for installing packages after hitting this error. The first suggestion on all of them is using `-f` in the apt-get install command. I'd search around and see if you can find a way around this.

**Comment by rajk97** [comment]
Thank you for your response. I'll look into it.

*Raj *Kolamuri
Graduate Student
Mechanical Engg.
Carnegie Mellon University
Ph: +412 897 8877
EMail: rkolamur@andrew.cmu.edu

ᐧ

**Comment by remmel** [comment]
If you are using Ubuntu 22.04; libsoudio1 is not available there anymore, it must be install using Ubuntu 20.04 repo :
```
sudo apt-add-repository -y -n 'deb http://archive.ubuntu.com/ubuntu focal main'
sudo apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu focal universe'
sudo apt-get install -y libsoundio1
sudo apt-add-repository -r -y -n 'deb http://archive.ubuntu.com/ubuntu focal universe'
sudo apt-add-repository -r -y 'deb http://archive.ubuntu.com/ubuntu focal main'
```

Thanks https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1790#issuecomment-1531626651
