### ISSUE TITLE
Block man sample?

### ISSUE THREAD

**Issue by knat** [microsoft/Azure-Kinect-Sensor-SDK#880]
**Is your feature request related to a problem? Please describe.**

Can't find the way to use the joint orientation values to motion the avatar. I find the joint orientation values in azure kinect is totally different than in kinect v2.

**Describe the solution you'd like**

In kinect v2, there is a block man sample which use joint orientation values to rotate the blocks. Could you please provide the azure kinect block man sample?

Kinect v2 block man sample:
![a](https://user-images.githubusercontent.com/10220052/68081017-e207c480-fe41-11e9-9828-e237192de711.png)
[KinectEvolution-XAML.zip](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/files/3801279/KinectEvolution-XAML.zip)

**Describe alternatives you've considered**

**Additional context**

**Comment by wes-b** [comment]
Sorry, we are not currently planning to do a sample like this. If you'd like, you can create a new request for it at https://aka.ms/azurekinectfeedback.  This site is where we use community feedback to help determine priorities for the project.
