### ISSUE TITLE
Azure-Kinect-Sensor-SDK/examples/viewer

### ISSUE THREAD

**Issue by yuliangxiao** [microsoft/Azure-Kinect-Sensor-SDK#881]
Azure-Kinect-Sensor-SDK/examples/viewer/ Can I create a demo under Windows?

**Comment by wes-b** [comment]
Thanks for the question. Are you asking to create a windows sample next to our OpenGL sample?

**Comment by yuliangxiao** [comment]
Yes, I want to show point cloud on windows, thank you。
