### ISSUE TITLE
Link broken in building.md

### ISSUE THREAD

**Issue by jasjuang** [microsoft/Azure-Kinect-Sensor-SDK#885]
**Describe the bug**

The link for [using the depth engine](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/docs/usage.md#debian-package) in the Linux Dependencies section is broken in https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md. When I click it it shows 404 error. 

**Expected behavior**
I expect some valid webpage to pop up.

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04
 - SDK Version:  Latest

**Comment by wes-b** [comment]
Thanks, its updated now.
