### ISSUE TITLE
Supports external GPU?

### ISSUE THREAD

**Issue by meitros** [microsoft/Azure-Kinect-Sensor-SDK#886]
Hi! I was wondering whether you knew if the kinect body tracking sdk would work with an external gpu. I have a laptop (macbook) with windows via bootcamp - so can use the sensor sdk but not the body tracking sdk - and was worried about spending the money on an external gpu without knowing whether or not it would work.

**Comment by yijiew** [comment]
This question might be related to issue #882 

Currently the body tracking SDK will use the GPU device 0 to run the algorithm. I would suspect it will always use your laptop GPU for the current version. But we are planning to ship a version that allows the customer to choose which GPU to use, then I think it will allow you to use an external GPU.
