### ISSUE TITLE
K4A_DEPTH_MODE_WFOV_UNBINNED

### ISSUE THREAD

**Issue by yuliangxiao** [microsoft/Azure-Kinect-Sensor-SDK#887]
In fastpointcloud example,Why can't I set K4A_DEPTH_MODE_WFOV_UNBINNED,No problem with the rest of the settings,for example K4A_DEPTH_MODE_WFOV_2X2BINNED,thanks

**Comment by wes-b** [comment]
Due to raw image data size this is the one mode we don't support at 30 FPS.

https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification#depth-camera-supported-operating-modes
