### ISSUE TITLE
Why does use only one core of CPU in the cpu_mode of Azure Kinect Body Tracking SDK?

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#888]
**Describe the bug**

The cpu_mode of Azure Kinect Body Tracking SDK seems to use only one core of CPU.
Is this a bug? or is it the intended behavior?

**To Reproduce**

Set k4abt_tracker_configuration_t::cpu_mode to true.
Start body tracking using CPU.

**Expected behavior**

I want to process of body tracking a little more faster on the CPU.
Perhaps, it get a little faster if use multicore.

benchmark (for your reference):

| CPU                       | FPS                 |
|:--------------------:|:---------------:|
| Intel Core i9 9900K | about 1.5 fps |

**Screenshots**

![2019-11-06_00h17_20](https://user-images.githubusercontent.com/816705/68220509-3326dc80-002b-11ea-820f-edd9c322d712.png)

**Desktop (please complete the following information):**
 
 
 - Body Tracking SDK Version: 0.9.4 

**Additional context**

**Comment by qm13** [comment]
Fixed in v0.9.5.
