### ISSUE TITLE
Box dimension sample project

### ISSUE THREAD

**Issue by Jalroka** [microsoft/Azure-Kinect-Sensor-SDK#899]
I'm trying to locate the sample project mentioned here under the Sensor SDK that measures box dimension.

https://azure.microsoft.com/en-us/services/kinect-dk/

Thanks

**Comment by tesych** [comment]
this sample contains internal libraries that cannot be shared at the this time.

**Comment by josecache** [comment]
When do you plan to share it?

**Comment by abbott1234** [comment]
Also asked for this sample. 
Or any samples for  world coordinate transform with depth values?
