### ISSUE TITLE
There is a sort of a typo at...

### ISSUE THREAD

**Issue by hanseuljun** [microsoft/Azure-Kinect-Sensor-SDK#906]
Here: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/cca87fc36acab7ed9a484aaa978ab6bcd7b54d34/src/transformation/intrinsic_transformation.c#L312

(xx + 3.f * xx) should be (xx + 3.f * yy)

**Comment by wes-b** [comment]
Thanks for spotting this!
