### ISSUE TITLE
Problem of" if you unlugged the device,you must close and reopen the device"

### ISSUE THREAD

**Issue by 1216704928** [microsoft/Azure-Kinect-Sensor-SDK#908]
**Describe the bug**

I am making changes to the SDK, i have built my own copy of the SDK from source,and fellow the instruction in building for how to build from source.After compiling, run the generated k4aviewer. exe. Although the interface window is opened, it cannot "start".
**To Reproduce**

![7.png](http://ww1.sinaimg.cn/large/005Zn2sIgy1g8yov7tdexj30oa02bq2u.jpg)
![8.png](http://ww1.sinaimg.cn/large/005Zn2sIgy1g8yoy90mz3j30pe0b3dg9.jpg)
![6.png](http://ww1.sinaimg.cn/large/005Zn2sIgy1g8yozqxy9mj313u0oygmp.jpg)
http://ww1.sinaimg.cn/large/005Zn2sIgy1g8yoyqc9bdj30oa02bq2u.jpg
http://ww1.sinaimg.cn/large/005Zn2sIgy1g8yoy90mz3j30pe0b3dg9.jpg
http://ww1.sinaimg.cn/large/005Zn2sIgy1g8yozqxy9mj313u0oygmp.jpg
**Expected behavior**

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by wes-b** [comment]
The viewer has the option of collecting logs, can you share them?

**Comment by denkywu** [comment]
I have the same problem.

![2019-11-26 15-50-43屏幕截图](https://user-images.githubusercontent.com/44558925/69609497-a0df8a80-1064-11ea-806b-261951d7bfde.png)

**Comment by denkywu** [comment]
> I have the same problem.
> 
> ![2019-11-26 15-50-43屏幕截图](https://user-images.githubusercontent.com/44558925/69609497-a0df8a80-1064-11ea-806b-261951d7bfde.png)

My problem solved by updating my graphics drivers (NVIDIA) instead of integrated graphics.
