### ISSUE TITLE
Link broken in building.md

### ISSUE THREAD

**Issue by scimad** [microsoft/Azure-Kinect-Sensor-SDK#909]
The link for `docker container` in the `Building using Visual Studio` section is broken in https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md. Shows 404 error when clicked.

**Comment by wes-b** [comment]
Thank you, that was a dead comment and I have removed it in develop

**Comment by wes-b** [comment]
Commit: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/commit/2916978939b9bdbebced340d381ebcc035b53d98
