### ISSUE TITLE
29.97hz Framerate

### ISSUE THREAD

**Issue by TomHVR** [microsoft/Azure-Kinect-Sensor-SDK#910]
**Is your feature request related to a problem? Please describe.**

Mode to run the depth and RGB cameras at a 29.97 fps mode. Almost all prosumer camera systems support only 23.976fps, 24fps, 29.97fps, 59.94fps in NTSC countries, and 25fps & 50fps in PAL countries. It makes frame accurate synchronization with external non machine vision cameras impossible.

**Describe the solution you'd like**

An option to run the depth & RGB sensors at 29.97fps mode and 25fps mode for PAL regions.

**Describe alternatives you've considered**

Retiming the 29.97hz footage to 30fps using frame duplication, which produces a shuttering image.

**Additional context**

**Comment by wes-b** [comment]
Thanks @TomHVR, I have moved this over to customer voice. Please upvote the feature request.

https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/39062128-support-additional-framerates
