### ISSUE TITLE
Where can I get firmware 1.6.104075014 bin file

### ISSUE THREAD

**Issue by jimzou** [microsoft/Azure-Kinect-Sensor-SDK#915]
Where can I get firmware 1.6.104075014 bin file？There is no such file in the result of source code compilation.

**Comment by wirthual** [comment]
Hi,
you can find the fimware file in this [Nuget package](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.0-alpha.0). Version 1.4.0-alpha.0.

Just extract it, and you can find the neded file in the firmware folder.
