### ISSUE TITLE
Problems when build the Azure Kinect Body Tracking Offline Processor

### ISSUE THREAD

**Issue by YingzheLiu** [microsoft/Azure-Kinect-Sensor-SDK#920]
When I tried to build the Offline Processor, it showed that there is no member name pull/pull_back, and I am using Windows x64 Visual Studio 2019.
![image](https://user-images.githubusercontent.com/53392222/69074046-79911980-09e3-11ea-88fe-8eeee97b71f7.png)
![image](https://user-images.githubusercontent.com/53392222/69074101-93caf780-09e3-11ea-9b13-e823321b0d64.png)

**Comment by yijiew** [comment]
@YingzheLiu Thanks for reporting this issue. We have spotted the similar issue in Visual Studio 2019. The error list seems to be false positive information. If you go to the "Output" tag, you will find that the project actually is built successfully. 
![image](https://user-images.githubusercontent.com/4919062/69190311-fd76fe80-0ad4-11ea-9f62-f8c521c64e35.png)
![image](https://user-images.githubusercontent.com/4919062/69190339-0b2c8400-0ad5-11ea-87cd-27e40c23f228.png)

You can run or debug the executable without any problems. So I suspect there is a Visual Studio bug in the ErrorList generation.
