### ISSUE TITLE
Vulkan Back-End Processing For Body-Tracking

### ISSUE THREAD

**Issue by kklouzal** [microsoft/Azure-Kinect-Sensor-SDK#923]
I had feedback posted here https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/39038287-vulkan-body-tracking-back-end-processing and it was unfortunately merged with another feedback.

Hardware requirements for body tracking are steep especially when using multiple sensors. Using a Low-Overhead-API such as Vulkan would help alleviate most of the hardware constraints imposed by the current implementation. **Vulkan would ensure a vendor-neutral cross-platform solution** for high-performance processing using compute shaders.

Body tracking is a highly sought after feature and getting it right is paramount to the success of this device in many scenarios.

Most, if not all, machines have dedicated graphics processing hardware along with an integrated graphics processor on the CPU itself. In most cases the IGPU is sitting there idle while the DGPU is handling all the work. Giving developers the option to use Vulkan to provide skeletal tracking on the idle IGPU would be the best course of action in providing a stable and successful body tracking API.

Vulkan also provides the ability to use multiple GPUs to process a given task which would open the door for a single, more powerful machine, to handle dozens of sensors at the same time.

**Comment by qm13** [comment]
Thank you for your suggestion. We have looked into this option but do not believe it is a viable path for our product at this time.
