### ISSUE TITLE
Calibration seems weired

### ISSUE THREAD

**Issue by TxT1212** [microsoft/Azure-Kinect-Sensor-SDK#925]
**Describe the bug**

Hi, although the device is already calibrated, but I still got a rgb image with quite strong distortion. 
**To Reproduce**

Follow the instruction to view the calibration result:
1. run $ ROS_NAMESPACE=rgb rosrun image_proc image_proc
2. run $ rosrun image_view image_view image:=rgb/image_rect_color
2. run $ rosrun image_view image_view image:=rgb/image_raw
3. face camera to tehe edge of a desk.
**Screenshots**

![Screenshot from 2019-11-18 04-44-15](https://user-images.githubusercontent.com/32816417/69210642-670b1180-0b96-11ea-8e36-798b56947d0e.png)
left one is image_rect_color, the desk edge suppose to be straight.
**Desktop (please complete the following information):**
 - OS with Version: ubuntu 18.04
 - SDK Version:  1.2.0
 - Firmware version:  
  RGB camera firmware:      1.6.102
  Depth camera firmware:    1.6.75
  Depth config file:        6109.7
  Audio firmware:           1.6.14
  Build Config:             Production
  Certificate Type:         Microsoft

**Additional context**

**Comment by TxT1212** [comment]
BTW, what is the use of k4 k5 k6? It seems OpenCV calibration result only has k1 k2 k3. 
I found some related code in k4a.h 
`K4A_EXPORT k4a_result_t k4a_calibration_color_2d_to_depth_2d(const k4a_calibration_t *calibration,
                                                             const k4a_float2_t *source_point2d,
                                                             const k4a_image_t depth_image,
                                                             k4a_float2_t *target_point2d,
                                                             int *valid);`
but I couldn't find how they are used.

**Comment by amonnphillip** [comment]
@TxT1212  Opencv 3+ supports all 8 distortion parameters used by the Azure Kinect dk camera.

What version of Opencv are you using?

**Comment by TxT1212** [comment]
> @TxT1212 Opencv 3+ supports all 8 distortion parameters used by the Azure Kinect dk camera.
> 
> What version of Opencv are you using?


well, I asked my computer  `pkg-config --modversion opencv
`
and my computer told me I am using 3.2.0. Because I installed multi versions of opencv, so I'm not sure which version ros used. ros version is malena.

**Comment by jasjuang** [comment]
Not familiar with ros but you can test it out simply with just opencv. You have to use all 8 distortion parameters and put them in the order of k1 k2 p1 p2 k3 k4 k5 k6 and then pass it to `cv::undistort`.

**Comment by TxT1212** [comment]
> Not familiar with ros but you can test it out simply with just opencv. You have to use all 8 distortion parameters and put them in the order of k1 k2 p1 p2 k3 k4 k5 k6 and then pass it to `cv::undistort`.

thank you for your reply, I found the function. I calibrate the kinect myself, the result seems much better.
