### ISSUE TITLE
Can the recorder be changed to record MKV video (including audio)？

### ISSUE THREAD

**Issue by 1216704928** [microsoft/Azure-Kinect-Sensor-SDK#927]
**Is your feature request related to a problem? Please describe.**

Can the recorder be changed to record MKV video (including audio)？
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tesych** [comment]
@1216704928 , k4arecorder doesn't record sound. You can use Speech SDK to do so. You can find more documentation as part of our [Azure Kinect documentation](https://docs.microsoft.com/en-us/azure/Kinect-dk/access-mics). Currently there's no plan to include the audio. If this feature is important for you, please add this to the [Customer voice](https://feedback.azure.com/forums/920053) so it can be upvoted.

**Comment by 1216704928** [comment]
Can I capture the audio from the k4aviewer?

**Comment by wes-b** [comment]
> Can I capture the audio from the k4aviewer?

Sorry, no you can't

**Comment by TristanWYL** [comment]
Check [this](https://github.com/TristanWYL/Azure-Kinect-Recorder) out, I believe you could find what you need.
