### ISSUE TITLE
k4arecorder iostream stream error, unable to record file

### ISSUE THREAD

**Issue by neurojaym** [microsoft/Azure-Kinect-Sensor-SDK#928]
**Describe the bug**
I recently set up the Kinect SDK, and in attempting to use the command line k4arecorder got some errors. In the documentation (https://docs.microsoft.com/en-us/azure/kinect-dk/record-sensor-streams-file) the suggested line to use works fine ('Create Recording, Step 2), but if I change the output filename to any different path, I get an <iostream stream error> (see attached image). Is there a pre-requisite file structure that must be in place before beginning recording? Are there any specific requirements for the filename entered to the k4arecordere.exe command?
Otherwise it seems "Unable to create recording file".

I'm probably missing something very simple here, but can't quite figure out what it is! Thanks for the help. 

**To Reproduce**
<Steps to reproduce the behavior:
1. enter the tools folder under the Azure Kinect SDZ v 1.3.0
2. run k4arecorder.exe with filenames that are different from the suggested `%TEMP%\output.mkv`
Any filepath that begins with %temp% works as expected, but how can I direct my saved recordings to a specified directory?
>
**Expected behavior**
<I expected that the prompt would have given me the classic
Device Serial number:...
Device Version:.....
Device started

--the typical outputs during a successful recording. Instead, please see the attached screenshot of some sample errors. 
>
**Logs**

**Screenshots**

![IMG_3234](https://user-images.githubusercontent.com/19783128/69269854-e6e9a980-0b9f-11ea-9d51-f233f41a0522.JPG)

**Desktop (please complete the following information):**
 - OS with Version: < Windows 10 Pro >
 - SDK Version:  <  1.3.0 >
 - Firmware version:  <RBG=1.6.102, Depth=1.6.75 >

**Additional context**

**Comment by rfilkov** [comment]
There is no Desktop-subfolder of 'C:\Program Files\Azure Kinect SDK v1.3.0\tools'. This causes the error when the recorder tries to create the output file. You probably mean 'C:\Users\{your-user-name}\Desktop'
