### ISSUE TITLE
kinect azure rgb flow 

### ISSUE THREAD

**Issue by barakooda** [microsoft/Azure-Kinect-Sensor-SDK#931]
can you please elaborate on the kinect azure rgb flow ?

I guess its goes this way :
after debayer and ISP --> RGB ( native ) -> FPGA ( YUV\MJPEG) or leave it as RGB > thru USB 3.0 -> system.

**Comment by wes-b** [comment]
Image format is captured natively in YUY2, NV12, or MJPG by the sensor. It is transferred to the PC via USB3.0. On Windows Media Foundation is used to ready the UVC end point, on Linux LibUvc is used.

**Comment by barakooda** [comment]
When you say "sensor" you mean the whole kinect ?
cause the RGB sensor in the kinect capture rgb 10bit "regular" (bayered) rgb matrix.
it must be hardware that convert the RGB (after debayer) to YUV and Mjpeg....

what i`m missing ?

**Comment by wes-b** [comment]
We have not documented these details. If you are blocked then please let us know what is blocking you.

**Comment by barakooda** [comment]
I`m just confused.
the kinect azure viewer enable you 4 color modes with different resolutions#fps etc...
in the hardware spec docs it shows very strict table with MJPEG ruling most of it.

if the kinect viewer is just sdk ui interface - why the table does not reflect this options too ?

anyway, 
I`m just make sure I can get RGB, MJPEG and NV12 color modes for my use.

**Comment by wes-b** [comment]
The K4aViewer is showing the same combination of resolution, format, and frame rates that are documented here: https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification#color-camera-supported-operating-modes. These are the native resolution and formats supported by the rgb sensor.

Additionally the SDK (and viewer) add a BGRA formats, which the SDK does the conversion.

**Comment by barakooda** [comment]
Thank you very much for your quick replies .
