### ISSUE TITLE
Azure Kinect SDK does not have k4aConfig.cmake , k4arecordConfig.cmake

### ISSUE THREAD

**Issue by hci-mkim** [microsoft/Azure-Kinect-Sensor-SDK#934]
as I cloned this repo and trying to build cmake in order to get data from kinect keypoint sources. however, cmake returned errors and it doesnt have k4aConfig.cmake , k4arecordConfig.cmake 

where can i get those cmake files????
thank you.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: Windows 10 x64
 - SDK Version:  v.1.3.0
 - Firmware version:  

**Additional context**

**Comment by wes-b** [comment]
Sorry we can't help much without more detail, please review our build instructions and share how to repro your issue.

https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md#building-and-dependencies
