### ISSUE TITLE
serious noise

### ISSUE THREAD

**Issue by yuliangxiao** [microsoft/Azure-Kinect-Sensor-SDK#939]
How to deal with the serious noise?I can't see the object now.The light is too strong?
![111](https://user-images.githubusercontent.com/36064756/69507774-a0fd5e80-0f6e-11ea-9935-7755b05ebe55.jpg)

**Comment by tesych** [comment]
@yuliangxiao can you please follow our bug template and provide the rest of the information regarding this issue?
