### ISSUE TITLE
SDK dropping depth frames

### ISSUE THREAD

**Issue by t-walker-21** [microsoft/Azure-Kinect-Sensor-SDK#941]
**Describe the bug**

When using the azure, I am constantly getting warnings from both ROS and the k4aviewer. The warning arises from the depth_engine_thread, and it states that the processing of the depth image is too slow @ 1000ms. I have encountered this issue on multiple machines even when running the camera at 5 fps. The sdk recommends a firmware update, how can I acquire the binary that needs to be passed into the firmware tool?

**To Reproduce**

1. Open k4aviewer
2. Open your device and choose the 3072p @ 15 frames. The format should be BGRA, and the depth mode should be WFOV binned.
3. Press start to commence the streaming from both color and depth cameras

**Expected behavior**
In the log terminal, you should get the warning:
_[warning] : depth engine thread. Depth image processing is too slow at 1000ms._

**Logs**
The log reads:

_[ info ] : drop sample(). capturesync_drop, Dropping sample TS: X type Depth_

where X is an ever increasing integer

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04.3 LTS
 - SDK Version:  ? Not sure how to acquire this info
 - Firmware version: RGB - 1.6.98 Depth - 1.6.70

**Comment by wes-b** [comment]
There are a couple issues here:
- There is a bug in the reporting of 1000ms that we need to fix.
- You ask about the binary needed for the firmware tool.
  - The binary is in the [Installer](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/usage.md#msis) and in the [NuGet](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.3.0) packages.
  - If you have more questions about this, then lets open a new issue.
- dropped frames are typically related to PC performance. Perhaps you can enable logging at an informational level and we can help confirm that version another issue.

**Comment by wes-b** [comment]
https://github.com/Azure/azure-c-shared-utility/pull/423
