### ISSUE TITLE
Is there any open source code for 3D human skeleton tracking

### ISSUE THREAD

**Issue by 1216704928** [microsoft/Azure-Kinect-Sensor-SDK#944]
**Describe the bug**

Is there any open source code for 3D human skeleton tracking
**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by qm13** [comment]
I am not aware of any open source 3D skeleton tracking.
