### ISSUE TITLE
Kinect for Windows v2 (K4W2) support

### ISSUE THREAD

**Issue by rafael2k** [microsoft/Azure-Kinect-Sensor-SDK#952]
Hi,

Right now I don't have budget to buy a new Kinect, but as my Kinect v2 still works fine and does the job and I'd like to know if there are any plans for support the Kinect v2 (K4W2) through this wonderful SDK?

ps: My OS is Linux, and right now I'm using libfreenect2.

**Comment by wes-b** [comment]
Sorry, we don't have any plans for this. Feel to make a formal request for this over at https://aka.ms/azurekinectfeedback.
