### ISSUE TITLE
More than 10 devices

### ISSUE THREAD

**Issue by initialneil** [microsoft/Azure-Kinect-Sensor-SDK#954]
In the [depth_mcu.c](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/abccbce97ef6c086f02bf8b5a22af8f01e3e630d/src/depth_mcu/depth_mcu.c#L60), there's a hard-coded limit of the number devices to be 10.

> RETURN_VALUE_IF_ARG(K4A_RESULT_FAILED, device_index >= 10);

Can this be removed? I've tested 10 devices and it works fine. Now trying to have more.

Many thanks!

**Comment by wes-b** [comment]
Yes everything should work fine. If your depth camera's have any overlap, then you need to be aware of depth laser interfierance and how to avoid it, [which is covered here]( https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/868#issuecomment-552621616).
