### ISSUE TITLE
Azure Kinect Body Tracking SDK v0.9.5 installer doesn't include C# wrapper

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/Azure-Kinect-Sensor-SDK#961]
**Describe the bug**

Azure Kinect Body Tracking SDK v0.9.5 installer doesn't include C# wrapper (<code>Microsoft.Azure.Kinect.BodyTracking.dll</code>). It is only include in nuget package.

**Expected behavior**

Please include C# wrapper in the Azure Kinect Body Tracking SDK installer.
Azure Kinect Sensor SDK installer already include C# wrapper.

**Comment by qm13** [comment]
This will be fixed in the v1 release

**Comment by cavisions** [comment]
> This will be fixed in the v1 release

When can we expect the v1 to be released?

**Comment by qm13** [comment]
Fixed in v1.0.0
