### ISSUE TITLE
Undistort example fails to create look up table with v1.3.0

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/Azure-Kinect-Sensor-SDK#963]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/17b644560ce7b4ee7dd921dfff0ae811aa54ede6/examples/undistort/main.cpp#L394

The above line in the undistort example fails to create the lookup table k4a image on my pc. Calls to create other image types (for example, the undistorted image) succeed. The pinhole values seem to be valid, both the width and height are 512. I am using a download of the v1.3.0 Azure Kinect SDK.

**Comment by wes-b** [comment]
Can you share logs generated by the SDK for the failure?

**Comment by chrisfromwork** [comment]
yes, are there instructions for how to obtain these logs?

**Comment by chrisfromwork** [comment]
i was able to get source to resolve with pdbs, It turned out i was building against one version of the sdk but was calling into a different version at runtime. This caused image types to get out of sync causing image creation failures.
