### ISSUE TITLE
 How to get the raw phase image 

### ISSUE THREAD

**Issue by TxT1212** [microsoft/Azure-Kinect-Sensor-SDK#980]
**Is your feature request related to a problem? Please describe.**
I found Kinect v2 can return phase images. [https://github.com/OpenKinect/libfreenect2/issues/821](url)
 is it possible for Azure Kinect?

**Comment by wes-b** [comment]
Sorry we don't currently have any plans to do this. Feel free to ask for this feature over at https://aka.ms/azurekinectfeedback. We will consider adding support if it gets enough feedback from the community.

**Comment by tanjasper** [comment]
Is it still the case that one cannot get the raw phase image? Or has there been any change/update to this?
