### ISSUE TITLE
How to get stride length using kinect?

### ISSUE THREAD

**Issue by devLupin** [microsoft/Azure-Kinect-Sensor-SDK#994]
**In an environment with multiple kinect installations**
Q. Is there a way to measure stride length when a person walks in kinect range?

![simul_picture](https://user-images.githubusercontent.com/33558083/71146220-b319a680-2267-11ea-9cc5-93528005ab7d.png)
↑ refer to simulation picture

**Comment by rabbitdaxi** [comment]
Just throw some ideas: 
- you can leverage body tracking SDK, and access the joints that can help you identify stride https://docs.microsoft.com/en-us/azure/Kinect-dk/body-joints (e.g. foot/ankle), then you can leverage the joints [position ](https://microsoft.github.io/Azure-Kinect-Body-Tracking/release/0.9.x/structk4abt__joint__t.html) to find the stride length
- or, you can use your own detection algorithm to find the foot in color image, and then leverage sensor sdk to get the 3d point for those interesting points and measure the distance from the 3d point of them to identify stride

hope it helps
