### ISSUE TITLE
Version 0.9.5, small head turn and inaccurate eye, nose and ear positions

### ISSUE THREAD

**Issue by venscn** [microsoft/Azure-Kinect-Sensor-SDK#997]
**Describe the bug**
In 0.9.5, the head recognition is very inaccurate, hope to fix it in the next version

**Screenshots**
![v0 9 4](https://user-images.githubusercontent.com/11350982/71231544-61d1eb80-2329-11ea-8239-3c3d27c8c0d2.png)
 - OS with Version: Windows 10
 - SDK Version:  0.9.4
 - Description: It's normal.

![v0 9 5](https://user-images.githubusercontent.com/11350982/71231562-7b733300-2329-11ea-8779-8bde39d1316c.png)
 - OS with Version: Windows 10
 - SDK Version:  0.9.5
 - Description: It's inaccurate.

**Comment by prjova37** [comment]
Thank you for reporting this. We are investigating this issue.

**Comment by Zumra** [comment]
@venscn Thank you for reporting the issue. We have addressed it, and the fix will be available in the next release. Looking forward to hearing your feedback

**Comment by qm13** [comment]
Fixed in v1.0.0
