### ISSUE TITLE
Color Camera doesn't work

### ISSUE THREAD

**Issue by yeongwoonIm** [microsoft/Azure-Kinect-Sensor-SDK#998]
I launch the Azure Viewer only Color Camera.
but it doesn't work;;;(Depth Camera is fine. it works very well)

PC
OS : windows 10 enterprise 2016 LTSB 64bit
CPU : intel i7-7700K cpu @ 3.60GHz
RAM : 8 GB
GPU : Intel HD630

SDK : 1.3.0

USB 3.0 plug of PC has just one.

Viewer shows this.
![image](https://user-images.githubusercontent.com/12051241/71235512-bf713280-233f-11ea-8f64-c66bfc163cd4.png)

full logs
------------------------------------------------------------------------------------------------
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample
[ warning  ] : CFrameContext(). No metadata attached to the sample

------------------------------------------------------------------------------------------------

I searched issues. and I think this is similar problem.
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/839
I checked Device Manager. it look like fine..
![image](https://user-images.githubusercontent.com/12051241/71235718-50480e00-2340-11ea-9881-a74a2633ec46.png)

I checked Win Event Viewer. There is not any error logs.

I did uninstall & install SDK and plug-in & plug-out USB cable several times. but it doesn't work..

what I have to do next??

**Comment by wes-b** [comment]
You have something installed on your PC interfiering with your camera pipeline. Is anything in this https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/459#issuecomment-541994957 helpful?

**Comment by tesych** [comment]
No response. Closing this issue. Please let us know if the problem continues.

**Comment by yeongwoonIm** [comment]
> You have something installed on your PC interfiering with your camera pipeline. Is anything in this [#459 (comment)](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/459#issuecomment-541994957) helpful?

There is no interfiering with my camera. it has only 1 kinectDK connected.
